### ISSUE TITLE
API to set SRTP ciphers and negotiate GCM

### ISSUE THREAD

**Issue by fippo** [aiortc/aiortc#1012]
While looking at #956 and the code for it I noticed that the SRTP cipher suites are [hardcoded as well](https://github.com/aiortc/aiortc/blob/main/src/aiortc/rtcdtlstransport.py#L156):
```
ctx.set_tlsext_use_srtp(b"SRTP_AES128_CM_SHA1_80")
```
In general we've seen some quite nice CPU improvements with GCM-based ciphers, see the Chrome bug.
There is a trade-off since they add overhead so this can't be enabled by default but a lot of servers do tweaking here in order to get Chrome to prefer GCM. See https://bugs.chromium.org/p/chromium/issues/detail?id=713701#c21 et al.

This is as easy as passing
```
ctx.set_tlsext_use_srtp(b"SRTP_AEAD_AES_256_GCM:SRTP_AEAD_AES_128_GCM:SRTP_AES128_CM_SHA1_80")
```
(i.e. concatenating the different suites with `:`) but requires plumbing. In the past there were build issues with the GCM cipher suites but I *think* these are gone nowadays.

**Comment by jlaine** [comment]
Hi @fippo ! I updated `pylibsrtp` a while back to add support for GCM ciphers:

https://github.com/aiortc/pylibsrtp/commit/d1f6eb32c0422ec5fd6968fe1965a5870fc9141a

I'd have to look at how the SRTP cipher is negociated though to wire it up in aiortc.

**Comment by jlaine** [comment]
I had a look at this and it looks like we are going to need to submit PRs to `cryptography` and `pyOpenSSL` because we are missing a wrapper for `SSL_get_selected_srtp_profile`. Without this we cannot determine which SRTP profile was negotiated.

**Comment by jlaine** [comment]
Another hurdle for GCM: currently `pylibsrtp` binary wheels do not have support for GCM, because that would mean compiling against OpenSSL (or NSS, or mbed). Yay.
