### ISSUE TITLE
Received video frame pts jumps over 4 billion forward

### ISSUE THREAD

**Issue by thedogrex** [aiortc/aiortc#1041]
Hello, am using aiortc audio and video tracking with MediaRecorder. 

Am printing received frame count durung the last second:

```
    async def recv(self):
        frame = await self.track.recv()

        if self.count_timestamp is not None:
            self.frame_count += 1

            if time.time() - self.count_timestamp > 1.0:
                self.count_timestamp = time.time()
                print(f'video frames: {self.frame_count} time_base:{frame.time_base} start_pts: {self._last_frame_pts} end pts: {frame.pts}', flush=True)
                self.frame_count = 0
                self._last_frame_pts = frame.pts
        else:
            self.count_timestamp = time.time()

        return frame
```

The problem is when we have low FPS < 14 seconds the next received frame pts will jump over 4 billion forward. Because of that MediaRecorder creates a video file over 35 hours long for 15 minute session.

logs:
```
video frames: 30 time_base:1/90000 start_pts: 20148300 end pts: 20239020
video frames: 31 time_base:1/90000 start_pts: 20239020 end pts: 20331180
video frames: 26 time_base:1/90000 start_pts: 20331180 end pts: 20409030
video frames: 24 time_base:1/90000 start_pts: 20409030 end pts: 20481030
video frames: 33 time_base:1/90000 start_pts: 20481030 end pts: 20583180
video frames: 24 time_base:1/90000 start_pts: 20583180 end pts: 20653830
video frames: 43 time_base:1/90000 start_pts: 20653830 end pts: 20783340
video frames: 32 time_base:1/90000 start_pts: 20783340 end pts: 20878470
video frames: 12 time_base:1/90000 start_pts: 20878470 end pts: 22596300
video frames: 38 time_base:1/90000 start_pts: 22596300 end pts: 4317621196
video frames: 32 time_base:1/90000 start_pts: 4317621196 end pts: 4317743596
video frames: 22 time_base:1/90000 start_pts: 4317743596 end pts: 4317809926
video frames: 38 time_base:1/90000 start_pts: 4317809926 end pts: 4317923686
video frames: 33 time_base:1/90000 start_pts: 4317923686 end pts: 4318021516
```

Also I can confirm that it was a small connection problem, so some packets were lost there, because image was not updated.
So the video frames count is lower because we have not received recv call with a video frame.
Please help! How to make these pts correct.

**Comment by jlaine** [comment]
Could you please elaborate on how to reproduce this? Are you using one of the examples provided with aiortc?

**Comment by thedogrex** [comment]
> Could you please elaborate on how to reproduce this? Are you using one of the examples provided with aiortc?

No. Its our custom solution, but we are using standart aiortc library.
Finally we have solved an issue, we are saving pts, and if it jumps a lot forward - we just ignore it and writing next frames according to difference between frames. Not ideal, but it works on our side. Have spend more than 2 months for debuggong and solving it - and the solution is a few lines of code.

class VideoTransformPTS_Track(MediaStreamTrack):
    """
    A video stream track that transforms frames (normalize pts)
    """

    kind = "video"

    def __init__(self, track):
        super().__init__()
        self.track = track

        self._prev_frame_pts = 0
        self._diff_pts = 0
        self._show_pts = 0

    async def recv(self):
        frame = await self.track.recv()
        if self._prev_frame_pts == 0:
            self._prev_frame_pts = frame.pts
            self._show_pts = frame.pts
        else:
            self._diff_pts = frame.pts - self._prev_frame_pts
            if self._diff_pts > VIDEO_CLOCK_RATE * 2:               # skip frame (AIORTC bug hack)
                self._show_pts = self._prev_frame_pts
                self._prev_frame_pts = frame.pts
                return None
            else:
                self._prev_frame_pts = frame.pts
                frame.pts = self._show_pts + self._diff_pts
                self._show_pts = frame.pts

        return frame
