### ISSUE TITLE
Connection fails if both devices are on seperate networks

### ISSUE THREAD

**Issue by witehound** [aiortc/aiortc#1119]
So i have made several stable connections if both the python app and the client are on the same network, anytime i try to use them on separate networks if fails with a message like this.
<img width="580" alt="Screenshot 2024-06-18 at 5 20 14 PM" src="https://github.com/aiortc/aiortc/assets/26417477/4a44118e-3854-42cb-9596-90e8c7e6099b">

here is the code for the offer in the python app.py
```async def offer(request):
    params = await request.json()
    offer = RTCSessionDescription(sdp=params["sdp"], type=params["type"])

    pc = RTCPeerConnection()
    pcs.add(pc)

    @pc.on("datachannel")
    def on_datachannel(channel):
        @channel.on("message")
        def on_message(message):
            print(message)

    @pc.on("connectionstatechange")
    async def on_connectionstatechange():
        print("Connection state is %s" % pc.connectionState)
        if pc.connectionState == "failed":
            await pc.close()
            pcs.discard(pc)

    # open media source
    audio, video = create_local_tracks(
        args.play_from, decode=not args.play_without_decoding
    )

    if audio:
        audio_sender = pc.addTrack(audio)
        if args.audio_codec:
            force_codec(pc, audio_sender, args.audio_codec)
        elif args.play_without_decoding:
            raise Exception("You must specify the audio codec using --audio-codec")

    if video:
        video_sender = pc.addTrack(video)
        if args.video_codec:
            force_codec(pc, video_sender, args.video_codec)
        elif args.play_without_decoding:
            raise Exception("You must specify the video codec using --video-codec")

    await pc.setRemoteDescription(offer)

    answer = await pc.createAnswer()
    await pc.setLocalDescription(answer)

    return web.Response(
        content_type="application/json",
        text=json.dumps(
            {"sdp": pc.localDescription.sdp, "type": pc.localDescription.type}
        ),
    )
```

here is the code for the offer in client.js
```
function start() {
    var config = {
        sdpSemantics: 'unified-plan'
    };

    if (document.getElementById('use-stun').checked) {
        config.iceServers = [{ urls: ['stun:stun.l.google.com:19302'] }];
    }

    pc = new RTCPeerConnection(config);

    // connect audio / video
    pc.addEventListener('track', (evt) => {
        if (evt.track.kind == 'video') {
            document.getElementById('video').srcObject = evt.streams[0];
        } else {
            document.getElementById('audio').srcObject = evt.streams[0];
        }
    });

    document.getElementById('start').style.display = 'none';
    negotiate();
    document.getElementById('stop').style.display = 'inline-block';
}

function negotiate() {
    pc.addTransceiver('video', { direction: 'recvonly' });
    pc.addTransceiver('audio', { direction: 'recvonly' });
    return pc.createOffer().then((offer) => {
        return pc.setLocalDescription(offer);
    }).then(() => {
        // wait for ICE gathering to complete
        return new Promise((resolve) => {
            if (pc.iceGatheringState === 'complete') {
                resolve();
            } else {
                const checkState = () => {
                    if (pc.iceGatheringState === 'complete') {
                        pc.removeEventListener('icegatheringstatechange', checkState);
                        resolve();
                    }
                };
                pc.addEventListener('icegatheringstatechange', checkState);
            }
        });
    }).then(() => {
        var offer = pc.localDescription;
        return fetch('/offer', {
            body: JSON.stringify({
                sdp: offer.sdp,
                type: offer.type,
            }),
            headers: {
                'Content-Type': 'application/json'
            },
            method: 'POST'
        });
    }).then((response) => {
        return response.json();
    }).then((answer) => {
        return pc.setRemoteDescription(answer);
    }).catch((e) => {
        alert(e);
    });
}
```

aiortc version 1.8.0
ngrok is used to expose the python app

I am not familiar with how webrtc works so please do help me know if there are extra steps i have missed or done wrong.

**Comment by kuchlous** [comment]
I have the same problem. I am also using a TURN server assuming that the peers are behind symmetric NATs. As I debug this, I find that the connection does not work even on local network if I use "relay" only ice candidates. One side I have aiortc and the other I have a JS client running in the browser. I have attached the dump from the browser webrtc internals.
[WebRTC Internals Dump (1).txt](https://github.com/user-attachments/files/15898290/WebRTC.Internals.Dump.1.txt)

The debug log from the aiortc is also attached.
[server.log](https://github.com/user-attachments/files/15898298/server.log)

This is running with a co-turn server that I am running on AWS. I have the same issue running with the twilio TURN server.

Please let me know what other information would help.

**Comment by kuchlous** [comment]
@witehound , your problem may be because you are not using a TURN server. When the peers are on different networks, one of them may be behind a symmetric NAT and you may need to use a TURN server as your ICE server.

**Comment by kuchlous** [comment]
@witehound , I have been unable to get it to work either so do not want to dispense advice that may not help. Requesting more experienced people to help please.

**Comment by kuchlous** [comment]
Congrats. Did you install your own turn server? If yes, please share the settings. Would you be willing to share your code?

**Comment by kuchlous** [comment]
I finally have it working. Strangely, flipping the offer/answer from python (offer) / js (answer) to js(offer) / python (answer) made it work. Have no idea why that should be the case. @witehound , your code gave me that idea. Thanks.
