### ISSUE TITLE
how to disable stun

### ISSUE THREAD

**Issue by pvlking** [aiortc/aiortc#1128]
I don't want to use STUN  Server. SO I created RTCPeerConnection :
`config = RTCConfiguration(iceServers=[])
    pc = RTCPeerConnection(configuration=config)`
but stun also runed, how can don't use STUN Server?

**Comment by el07694** [comment]
Few words i know.

If both server (python user) and client (html5 user) are on a lan network there is no need of stun or turn server.

If you want to disable stun you may use turn instead.
