### ISSUE TITLE
Using    sender.track.stop(); doesn't actually stop the recording or trigger the         @track.on("ended") code

### ISSUE THREAD

**Issue by Nniol** [aiortc/aiortc#1129]
I am using the example server code and want to keep the data connection open after I have finished recording. 
So I added a new button which appears after start is clicked upon, the function of this button is to call stop_recording() as shown below.

```
function stop_recording() {
    document.getElementById('stop_recording').style.display = 'none';
    document.getElementById('stop_session').style.display = 'inline-block';
    // close local audio / video
    pc.getSenders().forEach((sender) => {
        console.log ("sender",sender)
        sender.track.stop();
        console.log ("sender",sender)
    });
}

```

However when these are sent nothing happens in the server. The recording stops and no new data is sent, but the following code is not triggered

```
        @track.on("ended")
        async def on_ended():
            log_info("Track %s ended", track.kind)
            await recorder.stop()
```

When I click then click on Stop and trigger the stop() function then the recording stops, but so do the data connections which means I can't send anything back
```
function stop() {
    document.getElementById('stop_session').style.display = 'none';

    // close data channel
    if (dc) {
        dc.close();
    }
    // close transceivers
    if (pc.getTransceivers) {
        pc.getTransceivers().forEach((transceiver) => {
            if (transceiver.stop) {
                transceiver.stop();
            }
        });
    }

    // close peer connection
    setTimeout(() => {
        pc.close();
    }, 500);
}
```

**Comment by Nniol** [comment]
I am assuming it is this bit of code in mediastreams.py that is the issue

```
class MediaStreamTrack(AsyncIOEventEmitter, metaclass=ABCMeta):
   
    ...
    ...
   
   
    def stop(self) -> None:
        if not self.__ended:
            self.__ended = True
            self.emit("ended")

            # no more events will be emitted, so remove all event listeners
            # to facilitate garbage collection.
            self.remove_all_listeners()
```

**Comment by Nniol** [comment]
Ok, looking at an older issue I also now stop the transceivers and I am to stop recording, this removes the recording button from my web client, but still doesn't trigger the ended event in the server

```
function stop_recording() {
    // document.getElementById('stop_recording').style.display = 'none';
    // document.getElementById('stop_session').style.display = 'inline-block';
    // close local audio / video
    pc.getSenders().forEach((sender) => {
        console.log ("sender",sender)
        sender.track.stop();
        console.log ("sender",sender)
    });
    // close transceivers
    if (pc.getTransceivers) {
        pc.getTransceivers().forEach((transceiver) => {
            if (transceiver.stop) {
                transceiver.stop();
            }
        });
    }
}
```

**Comment by fippo** [comment]
after stopping the transceiver you need to renegotiate the SDP at minimum.

**Comment by Nniol** [comment]
> Quote reply

So, what you are saying in essence is that to stop the audio I do need to sot the recorder and the transceiver.

Then do I need to send a new HTTP call to offer  or is there a renegotiate at SDP call available? So this renegotiation would only include the current data channel and would not recreate that channel?
