### ISSUE TITLE
aiortc with aiohttp works but not fastapi

### ISSUE THREAD

**Issue by pushkarprasad007** [aiortc/aiortc#1132]
I have a sample application (https://github.com/pushkarprasad007/llm-aiortc) which uses aiortc, where User is supposed to send the audio and then its recorded on python server on backend, and then python server is supposed to respond with 3 different audio back to back (mimicing LLM behavior where token by token are returned in streaming fashion). This project is intended to serve as a reference to lot of people who might be trying to achieve the conversational app using LLM.

There are two files to run

 1. server_aiohttp.py 
 2. server_fastapi.py

When I use python3.12, and I run the aiohttp code, it works fine. However, with fastapi, it gets stuck some place. Since a lot of development these days is in fastapi, it would be of great help if this project works with fastapi as well. I've spent enough time to debug, before deciding to come on this forum.

Any directions or better still, if someone can help figure, would be helpful not just for me but a whole lot of community who spent countless hours trying to make this work. I hope my earnest attempt to achieve this goes to a logical conclusion.

Steps:
```
python3.12 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python server_<aiohttp|fastapi>.py

Go to localhost:8080
Click on green power button
After some time Webrtc status shows 'connected'
Click on audio button and speak, and then click on stop.
```

**Comment by qwert1887** [comment]
i guess the way you startup fastapi app is stuck on uvicorn.you can try change the way startup uvicorn. you can refer to this [https://github.com/tiangolo/fastapi/issues/5782](https://github.com/tiangolo/fastapi/issues/5782).i am not sure.Hope helpfull for you.

**Comment by pushkarprasad007** [comment]
> i guess the way you startup fastapi app is stuck on uvicorn.you can try change the way startup uvicorn. you can refer to this [tiangolo/fastapi#5782](https://github.com/tiangolo/fastapi/issues/5782).i am not sure.Hope helpfull for you.

Many thanks!
