### ISSUE TITLE
three ISSUES: one is only support addtrack,but not support removetrack.

### ISSUE THREAD

**Issue by watermonth** [aiortc/aiortc#1145]
one issues as the title.
two: stable connection can't send offer. when I am writing a SFU,need send offer to renegotiate clients。
there: MediaRelay track,a SFU relay one track from client to others,NOT NEED to create a new trackid,just NEED to reuse or copy client's track Id.

thanks

**Comment by RyantheKing** [comment]
I was wondering if there has been an update on this? I also am curious if there are plans to implement a removeTrack method for RTCPeerConnection.
