### ISSUE TITLE
Using `examples/webcam` to play the video, the quality is very poor at first

### ISSUE THREAD

**Issue by LogWell** [aiortc/aiortc#1163]
I replaced the function in the [example](https://github.com/aiortc/aiortc/blob/main/examples/webcam/webcam.py#L21-L41) so that I can play a downloaded video. 

1. video resolution is 1920x1080
2. MacBook Air M1

```
def create_local_tracks(play_from, decode):
    player = MediaPlayer('...')
    return player.audio, player.video
```

The quality is very poor at first, and it will get better after a while.
The audio was a little abnormal during the process, but the picture looked more intuitive.

<img width="774" alt="image" src="https://github.com/user-attachments/assets/263e48a5-0fe5-444b-8a3c-ffeead32b654">
<img width="734" alt="image" src="https://github.com/user-attachments/assets/26e3b0b3-a688-4c73-b646-2dc76ce3a66b">

**Comment by Anandesh-Sharma** [comment]
similar thing happens with me. +1

**Comment by LogWell** [comment]
May be the sacrifice of image quality to ensure real-time
