### ISSUE TITLE
WebRTC URL format

### ISSUE THREAD

**Issue by kandeng** [aiortc/aiortc#1184]
Just wonder how to add more information to the URL of webrtc connection?

Ideally, we want webrtc URL like this,  webrtc://127.0.0.1:8080/app_one/?user=myname&password=mypassword

Is that possible? If yes, how to implement it?

Many thanks!

**Comment by R0NAM1** [comment]
WebRTC is initiated via exchanging SDP between two or more peers and having them auto connect in the background, it is VERY abstracted.
 
All you need to do is define a remote peer and exchange an offer and answer with them. You can wrap this in authorization by noting the IP address you are communicating with and implementing a separate auth endpoint.

For instance what I do is request a session with my server and it generates a PIN that I then have to submit then it whitelists my IP address and accepts SDP offers from me.

Plenty of tutorials and such online for how to implement it, just look at the examples provided:
https://github.com/aiortc/aiortc/tree/main/examples/webcam

**Comment by kandeng** [comment]
Crystal clear, many thanks.   @R0NAM1 

Especially, the webcam.py gives a very detailed example.  

Another question, my scenario is like this, 

1. There are some static webcams, installed at fixed spots. In addition, there are some mobile webcams, installed on vehicles and robots. 

2. All the webcam video streams will be sent to a stream server, say Simple Realtime Server (SRS), via either WebRTC or RTMP, or less likely RTSP. 

3. Quite some human viewers, view the webcam video in their browsers, say Chrome, via WebRTC. 

Now, our question is, in step 2, either protocol is the best choice, to upload the video stream from webcam to the stream server?

**Comment by kandeng** [comment]
Now, our question is, in step 2, **which** protocol is the best choice, to upload the video stream from webcam to the stream server?

Typo : (

**Comment by R0NAM1** [comment]
Typically you go with the source codec/type, if it's a PoE camera it's usually RTSP.
For USB cameras that would be WebRTC and likely grabbing device /dev/video0 or something equivalent.
If you needed WebRTC and had only RTSP for example since both use RTP you can actually set an RTSP source in pyav and it works, I've done it.

**Comment by kandeng** [comment]
More details about our scenario, 

1. We use USB camera, and use openCV to capture `device /dev/video0` video stream. 

2. Before sending the video stream to remote servers, we need to use openCV to do some image processing. 

3. After image processing, we use ffmpeg to convert the `codec='rawvideo'` to `vcodec='libx264'`, then send the stream to the remote server. 

In this scenario, WebRTC, RTSP, or RTMP, which one shall we use? 

A lot of thanks!

**Comment by R0NAM1** [comment]
I think the best way to put it is no matter what you use WebRTC from Python -> Web Browser.
Your WebRTC source can be RTMP, RTSP or any other input (In this case /dev/video0)

**Comment by kandeng** [comment]
To make sure my understanding is correct, let me repeat your suggestion in these steps.   @R0NAM1 

1. From device, it doesn't matter too much which protocol that our python script uses to push the webcam video stream up to the remote stream server, 

   either RTMP, or RTSP, but not WebRTC. 

2. From the remote stream server, say SRS (Simple Realtime Server), to viewers' browsers,  our Javascript running on browser, should use WebRTC to pull the video stream from the SRS to the browsers.  

   in the JS pulling procedure, we should use WebRTC, but not RTSP or RTMP. 
   
  Is my understanding correct?

**Comment by R0NAM1** [comment]
Web Browsers don't support RTSP or RTMP and that's why you need to use WebRTC. However you don't 'pull' WebRTC like an RTSP stream, you connect with another peer and can two way exchange audio, video & data
https://medium.com/dvt-engineering/introduction-to-webrtc-cad0c6900b8e
https://webrtc.org/

**Comment by kandeng** [comment]
O, yes, yes, WebRTC dosn't `pull`.   @R0NAM1 

The javascript running in the browser, uses WebRTC to connect to the SRS stream server, and get the webcam stream from the SRS server. 

All issues are solved. 

Now, I close this issue, to make it convenient to maintain this forum. 

Of course, in case we have more sub issues to follow up, we can re-open this issue. 

A lot of thanks!
