### ISSUE TITLE
Create a logo for aiortc

### ISSUE THREAD

**Issue by jlaine** [aiortc/aiortc#137]
It would be great to have a logo for `aiortc`, ideally something which reflects its Python roots (snakes and/or blue-yellow is welcome). My graphics skills are limited so if someone wants to contribute a logo it would be greatly appreciated!

**Comment by justingolden21** [comment]
I just made a pull request [here](https://github.com/jlaine/aiortc/pull/138) that added a new logo. Let me know what you think.

**Comment by jlaine** [comment]
Hi @justingolden21 ! Thanks for taking a stab at this, it's highly appreciated.

I'm a little worried that the logo isn't distinctive enough, especially when you shrink it: it's almost identical to Python's logo. Also, I think we need to request permission from the Python Software Foundation if we want to create a derived work.

It was suggested to me to maybe play with letters (for instance "RTC" or "rtc") to make them look somewhat like the Python snakes. As there are three letters and only two snakes, maybe turn the "r" and "c" into blue / yellow snakes and leave the "t" in "normal"?

**Comment by jlaine** [comment]
For now I'm going to settle on a variant of the logos pasted above, it's visible at:

https://aiortc.readthedocs.io/en/latest/
