### ISSUE TITLE
Janus Example Question

### ISSUE THREAD

**Issue by oreanidai** [aiortc/aiortc#139]
Hi.

I run the example of janus.py and modify the video source from local file to IP Camera via RTSP (rtsp://ip_addr).

```
    # create media source
    options = {'video_size': '640x480'}
    if args.play_from:
        player = MediaPlayer('rtsp://ip_addr', format='rtsp', options=options)
    else:
        player = None

```

And it show the error:

```
max delay reached. need to consume packet
RTP: missed 1 packets
error while decoding MB 19 22, bytestream -5
Exchanging media
deprecated pixel format used, make sure you did set range correctly
error while decoding MB 19 22, bytestream -5
max delay reached. need to consume packet
RTP: missed 145 packets
error while decoding MB 26 12, bytestream -31
max delay reached. need to consume packet
RTP: missed 43 packets
```

Janus log output:

```
[WARN] Incoming RTCP SR SSRC (4208385020) does not match the expected one (0) video=1
[WARN] [3607692468606077] Dropping RTCP packet with unknown SSRC (0)
```

I use webrtc-streamer rtsp url list randomly.
https://github.com/mpromonet/webrtc-streamer/blob/master/config.json

This is rtsp_url `rtsp://46.105.54.176:80/64connections/Pariscam3.stream` I used.

if rtsp_url is `rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov` , no problem.

Do you know something?

Thanks!

Best,
oreanidai

**Comment by jlaine** [comment]
You seem to be mixing various things in this issue:

- you shouldn't need to modify the source of the example to use rtsp, why not pass `--play-from some_url`?

- the ffmpeg errors: have you tried the same URL using ffmpeg on the command line? I'm not an FFmpeg developer so unless you can show me the problem is specific to aiortc I won't be of much help

- the SSRC error: this looks interesting but unrelated to using rtsp. Do you get the same error when sending a simple mp4 file?

**Comment by jlaine** [comment]
OK, I'll try to circle back to this / reproduce this myself after FOSDEM

**Comment by jlaine** [comment]
I tried running `ffplay` on `rtsp://46.105.54.176:80/64connections/Pariscam3.stream` and I don't get any video for ~15s so I'm not surprised things are not working smoothly: the call to `av.open()` is completely blocking the event loop.

I also get the same errors about a deprecated pixel format:

```
[rtsp @ 0x7f45a8000b80] UDP timeout, retrying with TCP   0B f=0/0   
Input #0, rtsp, from 'rtsp://46.105.54.176:80/64connections/Pariscam3.stream':
  Metadata:
    title           : Pariscam3.stream
  Duration: N/A, start: 4.160000, bitrate: N/A
    Stream #0:0: Video: h264 (Baseline), yuvj420p(pc, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 180k tbc
[swscaler @ 0x7f459c177e00] deprecated pixel format used, make sure you did set range correctly
```

However what **really** messes things up is that the first frame has no presentation timestamp. I don't really want to start inventing timestamps, so I think the easiest fix would be for `MediaPlayer` to drop any such frames.

**Comment by oreanidai** [comment]
Thanks for the reproduction and information.
I understood that I am a movie stream problem.

> so I think the easiest fix would be for MediaPlayer to drop any such frames. My problem is now how to add a unit test for this case, as I don't want CI to depend on an RTSP source.

OK! 

I am very grateful.

Thanks!!

**Comment by jlaine** [comment]
OK the latest code now skips the problematic first frame. I was unable to reproduce the SSRC error.
