### ISSUE TITLE
Janus example. Memory leak

### ISSUE THREAD

**Issue by laim-user** [aiortc/aiortc#141]
Hello! I tried to use your example for janus and encountered a big memory leak. On a video of 2 minutes takes about 3.5-3.7 GB. The level grows linearly until the end of the video playback.

Mac OS X 10.14.1 Mojave. Python 3.6.2. Use the latest version of your library.

**Comment by jlaine** [comment]
Hi! Without access to the specific video it might be a bit tricky to debug, but here are some things you can try:

- try not specifying a video file, in which case the example will just send green video frames and no audio, and let it run for a long time. Is the memory usage stable?

- could you provide the output of `ffprobe` on your video file? It might be that it has multiple audio / video tracks, in which case `MediaPlayer` may not be doing the right thing.

**Comment by laim-user** [comment]
Thanks for the quick response! Actually you are right. I tried the green frames - no memory leaks. Then I tried to download another example (“Big Buck Bunny”, like in your twitter account :), also without any serious leaks. Keeps at the level of 200-300mb.

I attach the ffprobe output on the video file with which I am having problems:
`ffprobe version 4.1 Copyright (c) 2007-2018 the FFmpeg developers
  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1_3 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gpl --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librtmp --enable-libspeex --enable-videotoolbox
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2016-08-13T04:33:44.000000Z
  Duration: 00:02:17.69, start: 0.000000, bitrate: 1388 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x714 [SAR 1:1 DAR 640:357], 1259 kb/s, 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2016-08-13T04:33:44.000000Z
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      creation_time   : 2016-08-13T04:33:44.000000Z
      handler_name    : ISO Media file produced by Google Inc.`

Could you tell me how to handle videos with multiple audio tracks, etc.? Need to filter a file before transferring it to a program?

**Comment by jlaine** [comment]
This is odd, the ffprobe output for this file only shows one audio track and one video track, which should be fine. Would it be possible to share this file so that I can investigate?

**Comment by laim-user** [comment]
> This is odd, the ffprobe output for this file only shows one audio track and one video track, which should be fine. Would it be possible to share this file so that I can investigate?

sure
https://drive.google.com/open?id=1wIS1dhydDOVAxXt9b25yjfQ_bSiFmxGJ

**Comment by jlaine** [comment]
I tried out the file you provided and the memory usage (RSS) on Linux is nowhere near the numbers you mentioned. I'm wondering whether maybe encoding is falling behind on your machine, in which case you might be accumulating frames in memory?

**Comment by jlaine** [comment]
Closing, no response from submitter.
