### ISSUE TITLE
How can i integrate aiortc in django?

### ISSUE THREAD

**Issue by faizankarim** [aiortc/aiortc#142]
Need help i want to integrate aiortc in django.. Is it possible? Like i want to use same server example with django app...

**Comment by jlaine** [comment]
This is a duplicate of #56

**Comment by jlaine** [comment]
"Integration with Django" isn't very descriptive, it entirely depends on what you want to do. One note though: Django is not natively designed to work with asyncio, so I'm not convinced you'll want them to live in the same process.

**Comment by faizankarim** [comment]
ok, so i am trying to attach front end in another application and backend in another application can i do that??? something like api i can call from django or any other we framework???

**Comment by faizankarim** [comment]
done there was error of cors , aiohttp_cors lib helped me.

**Comment by ghosthapper** [comment]
Hi, I am working on the Django project actually I got structed while integrating aiortc server into a Django project. 
Is it possible to integrate with Django? So, can u suggest any ideas regrading to this.
