### ISSUE TITLE
Applying sendonly on server example

### ISSUE THREAD

**Issue by seosmeal** [aiortc/aiortc#143]
I've been going through the examples and playing around with them. I've noticed that if I set the JavaScript client in the `server` example to send video only, the server doesn't receive the stream. 

Here's the code change I've made to the client:
```
function negotiate() {
    var offerOptions = {
        offerToReceiveAudio: false,
        offerToReceiveVideo: false
    }
    return pc.createOffer(offerOptions).then(function(offer) {
        return pc.setLocalDescription(offer);
    ...
```
Here's the code change I've made to the server to print a log when it receives a frame:
```
class VideoTransformTrack(VideoStreamTrack):
    def __init__(self, track, transform):
        super().__init__()  # don't forget this!
        self.counter = 0
        self.track = track
        self.transform = transform

    async def recv(self):
        frame = await self.track.recv()
        print('Frame received.')
        self.counter += 1
        ...
```
Shouldn't it still receive the frame with these modifications?

**Comment by jlaine** [comment]
First of all `offerToReceiveAudio` and `offerToReceiveVideo` are obsolete options, they no longer exist in the standard, use `addTransceiver`.

Secondly, think about what you are doing here. `VideoTransformTrack` is a special kind of track which is used to *send* back the received video with a transform applied. If you have specified the client doesn't want to receive video, it's never going to be read so its `recv` method is never called.

On the server side, try instead connecting the received track to a `MediaRecorder` and you should see you are correctly receiving the video.
