### ISSUE TITLE
Help required in broadcasting the frames

### ISSUE THREAD

**Issue by najeeb-tyson** [aiortc/aiortc#144]
Can you help me in broadcasting the frames after processing them to browser where one endpoint is the python application with captures frame from camera. 
Or you can recommend me any server which can broadcast the frames it receives from our application.
Thanks

**Comment by jlaine** [comment]
You can use the `janus` example to achieve what you want: it allows you to send a video stream to a [Janus](https://janus.conf.meetecho.com/) video room.
