### ISSUE TITLE
I can't install aiortc via pip

### ISSUE THREAD

**Issue by liehu** [aiortc/aiortc#146]
creating build/lib.linux-x86_64-3.6/av/subtitles
    copying av/subtitles/__init__.py -> build/lib.linux-x86_64-3.6/av/subtitles
    creating build/lib.linux-x86_64-3.6/av/video
    copying av/video/__init__.py -> build/lib.linux-x86_64-3.6/av/video
    running build_ext
    running config
    pkg-config returned flags we don't understand: -pthread -pthread

**Comment by jlaine** [comment]
Please report this where it belongs: https://github.com/mikeboers/PyAV
