### ISSUE TITLE
Example videostream-cli failed on macOS

### ISSUE THREAD

**Issue by wydwww** [aiortc/aiortc#148]
Try to run example `aiortc/examples/videostream-cli` with command 
```
python cli.py offer
```
I tried with python 3.7 and 3.6, on the latest macOS.
Error message is 
```
(above is normal)
-- Please send this message to the remote party --
{"type": "bye"}

Traceback (most recent call last):
  File "cli.py", line 98, in <module>
    signaling=signaling))
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "cli.py", line 50, in run
    await signaling.send(pc.localDescription)
  File "/Users/username/stream/lib/python3.7/site-packages/aiortc/contrib/signaling.py", line 67, in send
    self._write_pipe.write(object_to_string(descr) + '\n')
BlockingIOError: [Errno 35] write could not complete without blocking
```
Seems like a macOS-related issue.

**Comment by jlaine** [comment]
This is probably indeed specific to OS X I seem to recall standard in/out
is handled differently.

Can you try one of the other signaling methods (add -h to see available
options)?

**Comment by jlaine** [comment]
Also, I just re-read your message and it looks as though the example did not actually "fail", but doesn't shut down cleanly?

**Comment by CatsNipYummy** [comment]
I didn't quite understand the fix for this issue. I am facing the same error.

`python cli.py answer` seems to run fine. It blocks with `-- Please enter a message from remote party --` But `python cli.py` offer gives me the above error.

**Comment by jlaine** [comment]
aiortc's demos provide several ways of exchanging SDP between the two parties, copy and paste is just one of them. Since copy-and-paste seems to have issues on OS X my suggestion is to use a different method.

**Comment by prashanthi-r** [comment]
`python3 cli.py offer --signaling tcp-socket` - specifying the signaling protocol works for me!
