### ISSUE TITLE
video frozen - timestamp issue?

### ISSUE THREAD

**Issue by jhnbyrn** [aiortc/aiortc#149]
I've been trying to get the webcam.py example to work on a raspberry pi 3. The issue is that the video is frozen on one frame most of the time. Roughly every 5-10 seconds, it plays smoothly and in perfect real-time for around 1-3 seconds, then freezes again. 

I don't think the problem is fundamentally a CPU power issue, because I've tried 32x32 resolution and the performance wasn't any better. Currently I'm using 240x120 and it's not even maxing out 1 cpu core. 

I did some debugging and noticed that the packet timestamps were sometimes getting stuck. Here's an example of what I mean:

```
DEBUG:rtp:sender(video) > RtpPacket(seq=57329, ts=830271968, marker=1, payload=120, 1237 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=57330, ts=830274967, marker=1, payload=120, 1230 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=57331, ts=830277967, marker=1, payload=120, 1221 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=57332, ts=1416195148, marker=1, payload=120, 1219 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=57333, ts=1416195148, marker=0, payload=120, 1300 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=57334, ts=1416195148, marker=1, payload=120, 29 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=57335, ts=1416195148, marker=1, payload=120, 1252 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=57336, ts=1416195148, marker=1, payload=120, 1286 bytes)
...
...
```

The ts values then stay frozen on 1416195148 for a while. 

The immediate cause of this ts issue is that the frames coming from the **MediaPlayer** usually have **frame.pts = 0**. Sometimes they have a real value, and that seems to correspond to when the video works for a few seconds. 

I added some debugging statements to the **player_worker** function in **media.py**, just before **video_first_pts** is subtracted from **frame.pts**, and here's what I'm seeing:

```
DEBUG:rtp:sender(video) > RtpPacket(seq=47430, ts=835290032, marker=0, payload=120, 1300 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=47431, ts=835290032, marker=1, payload=120, 141 bytes)
frame.pts: 0
video_first_pts: 89077492395
DEBUG:rtp:sender(video) > RtpPacket(seq=47432, ts=835290032, marker=0, payload=120, 1300 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=47433, ts=835290032, marker=1, payload=120, 364 bytes)
frame.pts: 0
video_first_pts: 89077492395
DEBUG:rtp:sender(video) > RtpPacket(seq=47434, ts=835290032, marker=0, payload=120, 1300 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=47435, ts=835290032, marker=1, payload=120, 238 bytes)
frame.pts: 0
video_first_pts: 89077492395
```

...with occasional intermittent bursts of things like this, which seem right to me:

```
DEBUG:rtp:sender(video) > RtpPacket(seq=47396, ts=835290032, marker=0, payload=120, 1300 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=47397, ts=835290032, marker=1, payload=120, 292 bytes)
frame.pts: 89092122860
video_first_pts: 89077492395
```

(In this log output^ the packet ts is still frozen but I presume that's just due to the asynchronous nature of the code.)

Am I on the right track in debugging this? I don't know much about video stuff so I'm kind of winging it here, but this looks to me like that frame.pts = 0 should not be happening, and would cause the packets to be discarded by the browser. 

**Versions**:
**aiortc** 0.0.19
**pyav** 6.1.2
**ffmpeg** 3.2.12-1-deb9u1+rpt1 (seems to be the latest available package).

I have run the webcam.py example on my laptop and it works perfectly. There, I have ffmpeg 4.1.1. 

Could ffmpeg be the issue here? Is it worth building from the latest source for the pi?

Thanks!

**Comment by jlaine** [comment]
It's definitely weird that the pts is "stuck", it feels like a bug in the ffmpeg / v4l2 driver. Maybe you could try experimenting with ffmpeg on the command line to see whether you reproduce this "stuck" pts?

As you have probably figured out yourself, aiortc propagates the timestamps received from ffmpeg so as to respect the timing information.

**Comment by jhnbyrn** [comment]
Thanks. I'll try experimenting with ffmpeg, and possibly building the latest version (I think I have to set up a cross-compiler to do that). 

I've turned up logging for the v4l2 driver (bcm2835-v4l2) and it's logging what look like good timestamps to me - no zeros.

**Comment by jhnbyrn** [comment]
I have not been able to reproduce it with ffmpeg, but I can reproduce it consistently with a simply python script using pyav, so we can definitely rule out aiortc. I'll follow up with the pyav project when I know more. Thanks.
