### ISSUE TITLE
Data channel with negotiated = True and custom id

### ISSUE THREAD

**Issue by davidskuza** [aiortc/aiortc#150]
Hi, 

am I right that we can't use option _negotiated_ and set our custom _id_ (https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createDataChannel#RTCDataChannelInit_dictionary) on data channel? I see I could pass id to _RTCDataChannel_ instead of calling _createDataChannel_ on _RTCPeerConnection_ but then I'm "not able" to ___createSctpTransport()_. Anyways setting id alone probably doesn't give me much. I need this for already created web "client" which uses this options.

**Comment by jlaine** [comment]
You are right, at the moment negotiated data channels are not supported. I shouldn't be too hard to implement though, and I would certainly review a PR adding this (don't forget to add unit tests).

**Comment by jlaine** [comment]
Closed thanks to David's great work!
