### ISSUE TITLE
Help required sending frames from client to server and back to client

### ISSUE THREAD

**Issue by maurogsp** [aiortc/aiortc#152]
Im working on a django project, i have implemented on my server side some functions that uses opencv mat objects and process them to recognize faces. What I need to do is to send the video frames from the browser to the server side, process them with opencv and send them back to the client side with the recognized faces. I would need to know how to achieve this using some method from aiortc library.
I hope i made my point, thank you!

**Comment by jlaine** [comment]
The "server" example does exactly that : receive frames from the browser, transform them with opencv and send them back.

NOTE: this is going to be a distinct process from your Django gunicorn / wsgi processes, as those processes do not use asyncio.

**Comment by raghavendrajain** [comment]
@jlaine Hi. I have a question. Do we need to install something on the client side?
I understand that on server we do need to have following installation
`
$ pip install aiohttp aiortc opencv-python`

**Comment by wy353208214** [comment]
Hi jiaine,
As the same as server example, in Django request receive the offer, and create answer to client，but can not receive video/audio data on track. I think the does't connected.
1. use Django log:
 

> INFO:pc:PeerConnection(1d3f1720-32a2-445b-ad67-151e813fc82d) Created for 192.168.88.52
INFO:pc:PeerConnection(1d3f1720-32a2-445b-ad67-151e813fc82d) Track video received
[pid: 84372|app: 0|req: 1/1] 192.168.88.52 () {60 vars in 1074 bytes} [Thu Jun  1 10:28:09 2023] POST /faceauth/offer => generated 1814 bytes in 7369 msecs (HTTP/1.1 200) 10 headers in 379 bytes (1 switches on core 0)

2. use example server log:
> INFO:pc:PeerConnection(5978c785-1370-4180-a13d-5d72bc5deb21) Created for 192.168.88.52
INFO:pc:PeerConnection(5978c785-1370-4180-a13d-5d72bc5deb21) Track video received
INFO:pc:PeerConnection(5978c785-1370-4180-a13d-5d72bc5deb21) Connection state is connecting
INFO:aioice.ice:Connection(0) Discovered peer reflexive candidate Candidate(ULwlquJZNi 1 udp 1853824767 192.168.88.52 58651 typ prflx)
INFO:aioice.ice:Connection(0) Check CandidatePair(('192.168.88.188', 52301) -> ('192.168.88.52', 58651)) State.WAITING -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('192.168.88.188', 52301) -> ('192.168.88.52', 58651)) State.IN_PROGRESS -> State.SUCCEEDED
INFO:aioice.ice:Connection(0) ICE completed
INFO:pc:PeerConnection(5978c785-1370-4180-a13d-5d72bc5deb21) Connection state is connected
INFO:aioice.ice:Connection(0) Discovered peer reflexive candidate Candidate(cuT5wH8Nuj 1 udp 1853759231 192.168.99.101 6465 typ prflx)
INFO:aioice.ice:Connection(0) Check CandidatePair(('192.168.88.188', 52301) -> ('192.168.99.101', 6465)) State.WAITING -> State.IN_PROGRESS
