### ISSUE TITLE
Failed to set SSL role for the channel

### ISSUE THREAD

**Issue by ggsato** [aiortc/aiortc#153]
Hi,

Thanks for this great python module.
I have tried all the examples, and they worked fine.

Then, tried my test between a Chromium browser on a Raspberry pi and an aiortc app running on a dedicated conda env on my Mac. Both are placed behind NAT, and connected to the Internet via their fiber connection respectively.

After a successful ice completion with a signaling over websockets, my data channel failed to open due to the following error.

> Uncaught (in promise) DOMException: Failed to set remote answer sdp: Failed to push down transport description for data: Failed to set SSL role for the channel.

Chromium ---> offer SUCCESS ---> aiortc
Chromium <--- answer SUCCESS <--- aiortc
Chromium ---> datachannel open FAILED ---> aiortc

I would really appreciate if you suggest where to look into or a way to debug on a browser.

Thanks!

**Comment by jlaine** [comment]
I'm sorry but I have nothing to go on in this report, so my knee-jerk reaction would be "Chromium on pi isn't behaving properly." What happens if you use Chromium on another desktop instead of the pi?

**Comment by ggsato** [comment]
OK, here's one answer immediately available to your third question. I will prepare the others. 

> Can you share the SDP being exchanged between the two parties?

**Chromium ---> offer SUCCESS ---> aiortc**

`{"type":"offer","sdp":"v=0\r\no=- 1094086840190438438 5 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE data\r\na=msid-semantic: WMS\r\nm=application 50996 DTLS/SCTP 5000\r\nc=IN IP4 192.168.1.104\r\na=candidate:1019731727 1 udp 2113937151 192.168.1.104 50996 typ host generation 0 network-cost 50\r\na=candidate:3182836534 1 udp 2113939711 2408:211:618b:9900:d94:51f7:addc:2085 60293 typ host generation 0 network-cost 50\r\na=ice-ufrag:Jd+n\r\na=ice-pwd:rtQ51WpKFAH0gZTtFYGMwggY\r\na=ice-options:trickle\r\na=fingerprint:sha-256 A9:11:25:7D:97:AB:36:CE:B2:48:AA:5D:ED:B2:85:DA:FE:C5:F1:F6:F9:7A:5A:2E:CA:91:11:E3:07:71:92:B5\r\na=setup:actpass\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n"}`

**Chromium <--- answer SUCCESS <--- aiortc**

`{"sdp": "v=0\r\no=- 3761878504 3761878504 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=group:BUNDLE data\r\na=msid-semantic:WMS *\r\nm=application 51785 DTLS/SCTP 5000\r\nc=IN IP4 192.168.10.155\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 65535\r\na=max-message-size:65536\r\na=candidate:a81637f2b94ffb117bd1648cd1a14b03 1 udp 2130706431 192.168.10.155 51785 typ host\r\na=candidate:0bb28849bcd420e4176adf7e172c73d0 1 udp 2130706431 2408:211:618b:9500:45e:5639:1427:8323 51786 typ host\r\na=candidate:fc599b1010a082ca771e53f080384060 1 udp 2130706431 2408:211:618b:9500:6dd8:b764:f412:a977 51787 typ host\r\na=candidate:c846ef4de3955c1224b9c528c823c070 1 udp 1694498815 122.222.71.213 51785 typ srflx raddr 192.168.10.155 rport 51785\r\na=candidate:336424b59cdf3a3d0e4bf42be45aca5c 1 udp 16777215 172.26.10.243 54382 typ relay raddr 192.168.10.155 rport 53661\r\na=end-of-candidates\r\na=ice-ufrag:x2pp\r\na=ice-pwd:kqWZXJPZmA11jkKDVoJzgN\r\na=fingerprint:sha-256 61:5C:99:EF:69:24:0F:83:AC:CC:20:9C:4D:EE:4F:84:71:AF:32:ED:41:70:2D:12:66:1E:73:6D:CB:97:05:DE\r\na=setup:active\r\n", "type": "answer"}`

**Comment by ggsato** [comment]
> What happens if you use Chromium on another desktop instead of the pi?

The desktop I was able to quickly make a test was Ubuntu 16.04 + Firefox, on which Chromium can not be installed now due to dependencies.

The result was successful by the following exchanges!!

**Firefox ---> offer SUCCESS ---> aiortc**

`{"type":"offer","sdp":"v=0\r\no=mozilla...THIS_IS_SDPARTA-65.0 6387448096828668265 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=fingerprint:sha-256 E3:91:C9:8F:EC:E9:2F:FF:75:8C:52:57:D6:F1:E3:E6:64:2B:54:99:7D:F6:A0:80:E4:CF:1F:B5:70:CE:60:6D\r\na=group:BUNDLE 0\r\na=ice-options:trickle\r\na=msid-semantic:WMS *\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=sendrecv\r\na=ice-pwd:20dabd34dc1365e89d33dd13aa9d6058\r\na=ice-ufrag:f83ae266\r\na=mid:0\r\na=setup:actpass\r\na=sctp-port:5000\r\na=max-message-size:1073741823\r\n"}`

**Firefox <--- answer SUCCESS <--- aiortc**

`{"sdp": "v=0\r\no=- 3761890903 3761890903 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic:WMS *\r\nm=application 53777 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 192.168.10.155\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:65536\r\na=candidate:a81637f2b94ffb117bd1648cd1a14b03 1 udp 2130706431 192.168.10.155 53777 typ host\r\na=candidate:0bb28849bcd420e4176adf7e172c73d0 1 udp 2130706431 2408:211:618b:9500:45e:5639:1427:8323 53778 typ host\r\na=candidate:fc599b1010a082ca771e53f080384060 1 udp 2130706431 2408:211:618b:9500:6dd8:b764:f412:a977 53779 typ host\r\na=candidate:c846ef4de3955c1224b9c528c823c070 1 udp 1694498815 122.222.71.213 53777 typ srflx raddr 192.168.10.155 rport 53777\r\na=candidate:336424b59cdf3a3d0e4bf42be45aca5c 1 udp 16777215 172.26.10.243 61288 typ relay raddr 192.168.10.155 rport 64201\r\na=end-of-candidates\r\na=ice-ufrag:jRq1\r\na=ice-pwd:4zJvyFvVgTdwHyoqgxysRV\r\na=fingerprint:sha-256 C5:07:E1:5E:47:72:D9:66:A4:E7:BF:E5:17:0D:1D:A2:51:AB:97:15:69:55:8F:95:6F:F6:A8:60:72:22:AE:2D\r\na=setup:active\r\n", "type": "answer"}`

And then, the aiortc app successfully received some candidates to establish the connection.

`{'type': 'candidate', 'sdpMid': '0', 'sdpMLineIndex': 0, 'candidate': 'candidate:0 1 UDP 2122187007 192.168.1.106 42566 typ host'}`

I will prepare a test case with Chromium to reproduce this issue.

**Comment by ggsato** [comment]
> I will prepare a test case with Chromium to reproduce this issue.

I tried an Ubuntu 16.04 box with the latest Chromium via aptitude(version 73), and which worked fine as below.

**Chromium ---> offer SUCCESS ---> aiortc**

`{"type":"offer","sdp":"v=0\r\no=- 5691310405058907564 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:CA9g\r\na=ice-pwd:oKJLm129wkloey+XguSERrcb\r\na=ice-options:trickle\r\na=fingerprint:sha-256 22:04:AC:8D:9F:9E:A0:43:F8:08:91:FD:08:30:1E:A0:A3:E5:33:9B:3D:13:79:53:76:A0:FF:AF:12:C0:8F:AE\r\na=setup:actpass\r\na=mid:0\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n"}`

**Chromium <--- answer SUCCESS <--- aiortc**

`{"sdp": "v=0\r\no=- 3761923986 3761923986 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic:WMS *\r\nm=application 61964 DTLS/SCTP 5000\r\nc=IN IP4 192.168.10.155\r\na=mid:0\r\na=sctpmap:5000 webrtc-datachannel 65535\r\na=max-message-size:65536\r\na=candidate:a81637f2b94ffb117bd1648cd1a14b03 1 udp 2130706431 192.168.10.155 61964 typ host\r\na=candidate:0bb28849bcd420e4176adf7e172c73d0 1 udp 2130706431 2408:211:618b:9500:45e:5639:1427:8323 54815 typ host\r\na=candidate:fc599b1010a082ca771e53f080384060 1 udp 2130706431 2408:211:618b:9500:6dd8:b764:f412:a977 54816 typ host\r\na=candidate:eb99b0393e319b844652c1d5d59d576c 1 udp 2130706431 192.168.113.1 57506 typ host\r\na=candidate:4385b11cfa8bd0f69330cd5dad74f323 1 udp 2130706431 192.168.240.1 59484 typ host\r\na=candidate:c846ef4de3955c1224b9c528c823c070 1 udp 1694498815 122.222.71.213 61964 typ srflx raddr 192.168.10.155 rport 61964\r\na=candidate:e421bd7019ff9fb4e37a573a72dd85b1 1 udp 16777215 172.26.15.73 60422 typ relay raddr 192.168.10.155 rport 62836\r\na=end-of-candidates\r\na=ice-ufrag:cfNY\r\na=ice-pwd:PIfFfkX00KZzXUQdGQtFkz\r\na=fingerprint:sha-256 C2:C6:47:3A:52:AC:97:AD:21:63:3D:43:45:B7:C5:67:DD:76:8F:44:B4:A9:46:03:3D:90:C3:12:7F:72:CF:EA\r\na=setup:active\r\n", "type": "answer"}`

So far, your knee-jerk reaction sounds the right answer. Also, I noticed the version on the pi is older, version 65.

**Comment by ggsato** [comment]
> Also, I noticed the version on the pi is older, version 65.

I have confirmed it works fine after I reinstalled the OS(the version of Chromium is the same). I am not sure what made the difference, but here're SDPs exchanged.

**Chromium ---> offer SUCCESS ---> aiortc**

`{"type":"offer","sdp":"v=0\r\no=- 2769551386572726693 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE data\r\na=msid-semantic: WMS\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:hXQ+\r\na=ice-pwd:mesrhPizT84G4BEeaILMvcKS\r\na=ice-options:trickle\r\na=fingerprint:sha-256 56:AC:85:D8:85:33:5D:2A:2E:75:E7:DD:CF:80:7B:5F:F4:AF:F5:EC:9D:22:25:B5:55:FB:70:6F:2D:55:0D:DC\r\na=setup:actpass\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n"}`

**Chromium <--- answer SUCCESS <--- aiortc**

`{"sdp": "v=0\r\no=- 3761932399 3761932399 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=group:BUNDLE data\r\na=msid-semantic:WMS *\r\nm=application 56381 DTLS/SCTP 5000\r\nc=IN IP4 192.168.10.155\r\na=mid:data\r\na=sctpmap:5000 webrtc-datachannel 65535\r\na=max-message-size:65536\r\na=candidate:a81637f2b94ffb117bd1648cd1a14b03 1 udp 2130706431 192.168.10.155 56381 typ host\r\na=candidate:0bb28849bcd420e4176adf7e172c73d0 1 udp 2130706431 2408:211:618b:9500:45e:5639:1427:8323 56382 typ host\r\na=candidate:fc599b1010a082ca771e53f080384060 1 udp 2130706431 2408:211:618b:9500:6dd8:b764:f412:a977 56383 typ host\r\na=candidate:b7ec9dd944952d3d77ff71826c742655 1 udp 2130706431 2408:211:618b:9500:11c:5619:19c3:fe87 56384 typ host\r\na=candidate:eb99b0393e319b844652c1d5d59d576c 1 udp 2130706431 192.168.113.1 61387 typ host\r\na=candidate:4385b11cfa8bd0f69330cd5dad74f323 1 udp 2130706431 192.168.240.1 54456 typ host\r\na=candidate:c846ef4de3955c1224b9c528c823c070 1 udp 1694498815 122.222.71.213 56381 typ srflx raddr 192.168.10.155 rport 56381\r\na=candidate:e421bd7019ff9fb4e37a573a72dd85b1 1 udp 16777215 172.26.15.73 55306 typ relay raddr 192.168.10.155 rport 58537\r\na=end-of-candidates\r\na=ice-ufrag:sYPv\r\na=ice-pwd:r5rxLAU8qfHxMsFuQEyJLz\r\na=fingerprint:sha-256 BE:6D:9E:1D:94:BA:53:B4:FA:5A:86:01:E8:13:28:AE:09:F0:70:F2:1D:1A:50:67:25:43:05:09:74:FC:22:3C\r\na=setup:active\r\n", "type": "answer"}`

From the above exchanges so far, the offer of the 1st failure case includes candidate. So it might have been my test environment got messed up as you suggested from the googling.

Let me close this issue since now this doesn't seem like anything wrong with aiortc.
