### ISSUE TITLE
Add a Websocket-based signaling method for examples

### ISSUE THREAD

**Issue by ryogrid** [aiortc/aiortc#154]
aiortc datachannel-filexfer example is very very nice example for developers interested in WebRTC and needs reliable p2p direct communication with udp hole punching (data channel is over SCTP and reliable transport) !!!.
But it can not run on Windows platform due to asyncio restriction of pipe.
So I implemented datachannel-filexfer example using websocket signaling server.
(signaling server is copy of code on aioice example )

https://github.com/ryogrid/aiortc_filexfer_sample_for_win32/commit/e69c055abe21c3abf9f5913ab0dca609c9e23a5b

if it has problem for pull request, please comment me :-)
(if this kind post to issues is bad action, sorry...)

**Comment by ryogrid** [comment]
sorry. required for trying is not inough.

[Tested environment]
Python 3.7.1
https://www.python.org/downloads/windows/
Windows x86-64 executable installer

Windows10 Home 64bit version 1803

[aiortc installation]
- for install to windows platform, not normal procedure is required.
- commads below is executed on command prompt

$ git clone https://github.com/ryogrid/aiortc_filexfer_sample_for_win32.git
$ cd aiortc_filexfer_sample_for_win32
$ python setup.py install
$ pip install websockets

**Comment by ryogrid** [comment]
for windows environment installation and running, some modifications are needed...
I forgot these...

https://github.com/ryogrid/aiortc_filexfer_sample_for_win32/compare/e69c05...ee8355

**Comment by ryogrid** [comment]
with mature deliberation, I understand that my modification can not be merge to aiortc.
so I decided create fork of aiortc as library for p2p direct sctp communication.

https://github.com/ryogrid/punch_sctp

sorry for bothering you.

**Comment by jlaine** [comment]
I don't quite understand what happened here, why do you need to fork aiortc at all?

a/ I'm open to providing a websocket-based signaling for the examples

b/ even if I wasn't there is no need to actually fork aiortc to use your own signaling method

**Comment by ryogrid** [comment]
I need functionality of establish p2p ditect data channel only and I want offer it to windows users.
but it cant be realized current aiortc code base (code around media device and codec cant be work on windows platform and making these runnable is not easy. and current pip package could not be installed windows platform due to build error of native bindings...)
so, i decided fork and remove codes not need for data channel and codes not runnable on windows...

i am sorry for code use of aiortc as part of different name library orz

**Comment by lgrahl** [comment]
Can't comment on issues regarding Windows but what you want is #78 then. @jlaine made it clear that he is open for PRs in that regard, so no fork required. :slightly_smiling_face:

**Comment by lgrahl** [comment]
Btw, IANAL, but I'm somewhat certain you cannot simply remove @jlaine from the copyright notice of a BSD-3 licensed project. I would be very careful with these kinds of changes to not get into any legal trouble.

https://github.com/ryogrid/punch_sctp/blob/933ed9c3d75e40d935f0b618627b489e9a8ea293/LICENSE

**Comment by ryogrid** [comment]
@lgrahl
thank you  for comment.
In fact, I want contribute to aiortc and functionality of my forked repository should be implemented as a part of aiortc.
but, I think it is difficult due to reason which i wrote above.
Is there any nice solution? if exists, please notice me :-)
if so, I apply my modification to code tree of aiortc.

>Btw, IANAL, but I'm somewhat certain you cannot simply remove @jlaine from the copyright notice of a BSD-3 licensed project. I would be very careful with these kinds of changes to not get into any legal trouble.

Yes. when place LICENSE file, I worry about that author? of codes should be who.
And I decide that place my name because when some problem occur with using my repository code, blames should not hurt @jlaine.  
instead,  I emphasised that codes of my repository is almost composed with codes of aiortc and wrote by contributors of it.

But, if there is appropriate description, i want modify to it.
please comment me :-)

**Comment by ryogrid** [comment]
Changing my repository,  and library name to 'aiortc-datachannel' is better?

**Comment by jlaine** [comment]
I suggest you start by explaining what exactly you want to do and work on your communication skills. You opened an issue and closed it less than 24h later declaring that the only way forward was to fork aiortc. How about we start again?

**Comment by ryogrid** [comment]
ok.

- i want p2p ditect communicaton library which is simple and not need complecated setup like preparering stun and signaling server, and many dependent platform specific package (via yum, apt, brew).  
i think above is not concept of aiortc, so i sould need making other library using aiortc. therefore, i need add modification which make aiortc usable like above.
- i want to make my library usable on windows platform also. because i want at least offer over nat file transfer tool to windows users (i use WebRTC on my job(company) now. but i am interested at overlay? network (freenet, skype, winny, tor, Chord ... etc) and over nat communication,  since around 2008. so i surpriced aiortc filetransfer example )
- though this maybe out focus of this explanation, i want develop simple share usable signaling server and host it at my server for my library and tool (this need mechanism for sharing)

that's all :-)

**Comment by jlaine** [comment]
Concerning the signaling method:

- if it's self-contained and can be used as a drop-in replacement for aiortc's examples, feel free to submit a PR.

- otherwise, you're free to use your own signaling in your code base without needing to fork aiortc: the signaling methods are *only* used in the examples, nowhere else.

The rest of the goals of the library seem out of scope for aiortc's core, but it sounds as if it can all be implemented *on top* of aiortc as opposed to requiring a fork

**Comment by ryogrid** [comment]
@jlaine 
thanks for reply.

> The rest of the goals of the library seem out of scope for aiortc's core, but it sounds as if it can all be implemented on top of aiortc as opposed to requiring a fork.

I think that "rest of the goals" needs not small modification like below.

https://github.com/aiortc/aiortc/issues/154#issuecomment-478356222
>I find out select package functinality like...
>　pip install aiortc[XXX]
>through #78.
>switching code with specified functionality need modification to setup.py and library code tree (import 
 code also should be switch) is not easy but may be worth trying :-)

Is this is acceptable?

**Comment by ryogrid** [comment]
I think continue deveoping [punch_sctp](https://github.com/ryogrid/punch_sctp) (my fork of aiortc) repo until I get answer and it is "acceptable".
And I reveted @jlaine name to LICENSE file due to pointing out here.
I'm sorry for wronged copyright description.

Regards.

**Comment by ryogrid** [comment]
I created PR for this issue.

https://github.com/aiortc/aiortc/pull/169

regards.

**Comment by jlaine** [comment]
Can you remind we what specific problem Windows has with copy-and-paste signaling?

**Comment by ryogrid** [comment]
Hi @jlaine
　
>Can you remind we what specific problem Windows has with copy-and-paste signaling?
OK.

1.  aiortc pip package can't install windows platform...
2.  uvloop does not support windows platform.
3. asyncio implementation on Windows Platform does not support pipe perfectly (some kind of pipe may work but stdin could not be handled when I tested).
https://docs.python.org/3/library/asyncio-platforms.html
https://gyazo.com/5a0bc658f99856a6bec6e802b387a0e7
I tried use of ProactorEventloop on copy-and-paste signaling.   
But it didn't work too (Python version is 3.7).

**Comment by jlaine** [comment]
1. It does, but requires a bit more work : https://github.com/aiortc/aiortc/issues/50#issuecomment-487478284

2. That's true, I'll modify the example to not fail if uvloop cannot be imported, it's not a hard requirement.

3. OK, thanks for the information. Did you try the other signaling method such as tcp-socket?

**Comment by ryogrid** [comment]
Hi jlaine.

> OK, thanks for the information. Did you try the other signaling method such as tcp-socket?
No. because I didn't know the method.
And after know I didn't also because the method can't work over NAT needed situation (this situation is my main concern).

**Comment by ryogrid** [comment]
@jlaine 
For my purpose, adding of websocket signaling to filexfer example is not important because that code can be wrote on my application or library which use aiortc internally. 
#172 

So if you think that  modification like #171 is not acceptable and modification like that wont merged aiortc, I has to fork aiortc and keep it my special version of aiortc...

https://github.com/aiortc/aiortc/issues/50#issuecomment-487478284 is very nice information. but it is hard procedure for developer.

If dll builed by Visual Studio and needed dll is bundled with aiortc package when specify --platform option to pip, It is best soluction than my modification.
But I think it may be difficult...

**Comment by ryogrid** [comment]
@jlaine 
I decided until aiortc package offers data channel only installation which can run on Windows also,    
I maintain special version of aiortc (aiortc-dc) repository and offer pip package from the repo.

https://github.com/ryogrid/aiortc-dc
https://pypi.org/project/aiortc-dc/
 
I hope you will understand.

regards.

**Comment by ryogrid** [comment]
@jlaine 
I think that available design for offering data channel only feature is extracting data channel feature codes and make sub-package like aioice from the codes.
And the solution is best for aiortc and developers who need data channel feature which is very very convinient.

Sorry for saying selfishness...

regards.

**Comment by jlaine** [comment]
`aiortc` examples have shipped with support for appr.tc signaling for a while, I'm going to close this.
