### ISSUE TITLE
Looking for a low latency HD video streaming solution

### ISSUE THREAD

**Issue by spectralcodec** [aiortc/aiortc#156]
I am using WebRTC to control a robot over a wireless LAN and have been using Chrome to stream HD (1280x720, 30fps w/ stereo sound) video for a few years now.  Unfortunately after Chrome 44 something changed in the way it buffers and I can not rely on newer version producing a consistent low latency audio/video stream (<250 ms).  I have tried experimenting with adjusting some values in Chrome's jitter buffer code and recompiling but have not had very good results with that.  I have also created a Python program to stream MJPEG with very low latency but then bandwidth becomes the issue. 
My question is: does aiortc allow control over the way receive buffering is handled?  I don't mind if frames are dropped with varying network conditions,  I am mainly concerned with keeping latency as low as possible. 
I would love to be able to get away from using an ancient version of Chrome to stream low latency HD video!
Thanks,
 Chris

**Comment by jlaine** [comment]
I have limited time, and don't plan to support legacy Chrome versions, too much has changed in the way they handle SDP. If older Chrome versions are a must, I'm afraid you're on your own.
