### ISSUE TITLE
transport not supported for stun based ice server

### ISSUE THREAD

**Issue by mayfield** [aiortc/aiortc#157]
For a stun ICE server such as `stun:global.stun.twilio.com:3478?transport=udp`  The regex in `rtcicetransport.py` is not relaxed enough..

```
[2019-03-20 13:06:35,713] [relay.eventing] [ERROR] Event Listener Exception [message]:
Traceback (most recent call last)
10. File "/home/mayfield/project/librelay-python/relay/eventing.py", line 45, in dispatchEvent
      await r
9.  File "/home/mayfield/project/relay-calling-sfu/relay_calling_sfu/main.py", line 115, in onMessage
      await self.controlHandlers[control](exchange)
8.  File "/home/mayfield/project/relay-calling-sfu/relay_calling_sfu/main.py", line 154, in onCallOffer
      await call.addPeerOffer(exchange)
7.  File "/home/mayfield/project/relay-calling-sfu/relay_calling_sfu/call.py", line 191, in addPeerOffer
      await pc.setRemoteDescription(offer)
6.  File "/usr/local/lib64/python3.6/site-packages/aiortc/rtcpeerconnection.py", line 660, in setRemoteDescription
      transceiver = self.__createTransceiver(direction='recvonly', kind=media.kind)
5.  File "/usr/local/lib64/python3.6/site-packages/aiortc/rtcpeerconnection.py", line 834, in __createTransceiver
      dtlsTransport = self.__createDtlsTransport()
4.  File "/usr/local/lib64/python3.6/site-packages/aiortc/rtcpeerconnection.py", line 812, in __createDtlsTransport
      iceGatherer = RTCIceGatherer(iceServers=self.__configuration.iceServers)
3.  File "/usr/local/lib64/python3.6/site-packages/aiortc/rtcicetransport.py", line 147, in __init__
      ice_kwargs = connection_kwargs(iceServers)
2.  File "/usr/local/lib64/python3.6/site-packages/aiortc/rtcicetransport.py", line 73, in connection_kwargs
      parsed = parse_stun_turn_uri(uri)
1.  File "/usr/local/lib64/python3.6/site-packages/aiortc/rtcicetransport.py", line 115, in parse_stun_turn_uri
      raise ValueError('malformed uri')
ValueError: malformed uri
```

The regex for TURN servers includes support for the transport query arg, but stun does not.

**Comment by dsvictor94** [comment]
Based on RFC 7064 (https://tools.ietf.org/html/rfc7064#section-3.1) "stun" and "stuns" URIs does not support transport parameter

**Comment by jlaine** [comment]
I think I agree with Victor, how come you have these "protocol" parameters in a STUN URI?

**Comment by lgrahl** [comment]
I'm quite sure they are supported but I would have to look it up. They definitely work in browsers.

**Comment by lgrahl** [comment]
I think you're right when it comes to the spec. Very interesting: Firefox does use TCP if requested with `stun.example.org?transport=tcp` but Chrome does not and uses UDP. I guess it's proprietary then and raising an exception is appropriate.

**Comment by mayfield** [comment]
These come straight from twilios API for stun turn servers.

**Comment by lgrahl** [comment]
Doesn't mean that it's correct.

**Comment by jlaine** [comment]
We're not the only ones who have come to the conclusion that Twilio's URL are not RFC-conformant:

https://github.com/onsip/SIP.js/issues/117

I don't plan to add hacks for such URLs in `aiortc` so your best option is to drop the query string from the STUN/STUNS uris you receive from Twilio. If you're a Twilio customer I also suggest you open an issue with them so they can fix it.

**Comment by mayfield** [comment]
I already added a workaround and I understand the position being taken.
But keep in mind you're on a short list of webrtc implementations that
don't tolerate this;  iOS, Android, Safari, Firefox and Chromium
accept/ignore the extrainious query args.

It's unlikely twilio will change, so aiortc is the one that suffers.

**Comment by lgrahl** [comment]
That way of thinking is a bit twisted. aiortc doesn't suffer from following standards. Twilio does from not following them. There's absolutely no guarantee that Firefox, or the whole swath of webrtc.org based implementations, keep support for this proprietary extension. I wouldn't even count on a PSA for that, so it could break for them any day.
