### ISSUE TITLE
Strange latency that is fixed after a while ?

### ISSUE THREAD

**Issue by metal3d** [aiortc/aiortc#160]
Hi,

Very impressed by aiortc, I'm currently writing an article to use it.

I'm currently building a simple "visio-conference" (without sound) to explain how it works, and I have a strange (yes, really weird) problem.

I created a little interface with 2 videos element. The first one is the sender view (this is not the video coming from the server, but the direct webcam view)
The second element is a receiver.

Sender creates the RTC connection and creates an offer with a "nickname". 
The "receiver" type the nickname and calls the server.

At this time, it works. 

But at first, I've got a latency that is approximately 14s (actually, I guess it's the time passed between the instant I send the video, and the instant I ask to stream if back)

After a while, something happens - stream is freezing, then get back and... no latency !

I tried to open a second "viewer" (in another browser), to stop all the viewers, then reopen viewers interface => no latency

So, what happens for the first minutes when I see a big latency ?

Note: at this time, the server is local

**Comment by metal3d** [comment]
OK, after several tests I now understand what happens.

If I make the "sender" to read the stream back in a video element, there is no latency anymore for "receivers".

If I don't read the stream, it's like it is cached for a while. Receivers receive past frames. Then the memory (on server side) begins to be filled and after a while the memory releases the cache.

VideoStreamTrack seems to keeps frames until a reader begins to get them...

So, to avoid the problem, I make the sender "reading" is own stream... Even if it's not what I want...

Is there a way to make VideoStreamTrack to not cache frames if there is no readers ?

Thanks !

**Comment by jlaine** [comment]
Hi Patrice,

You're going to have to show me some code for me to help, the base `VideoStreamTrack` does nothing so we're almost certainly talking about a subclass.

Also if your example is self-contained, would you consider submitting it for inclusion in `aiortc`'s examples, it sounds like a nice demo?

Jeremy

**Comment by metal3d** [comment]
Yes right, I didn't have the time to propose the demo but I will do it.

Let me a few days to find some time.

Thanks
