### ISSUE TITLE
No video feed when using pytorch inference

### ISSUE THREAD

**Issue by lws803** [aiortc/aiortc#163]
There's an issue with no video display although packets are being received in the server.py script provided as an example. I suspect it is due to the incoming frames overwhelming the message queue, disallowing the video frames from being inferred by the deep learning model.

I have modified server.py included in the examples to utilise my inference module

**Comment by jlaine** [comment]
That's nice. As I don't have a crystal ball to guess what changes you've made, I'm going to say "go fix your code".
