### ISSUE TITLE
webcam example not working on OS X

### ISSUE THREAD

**Issue by Borjis131** [aiortc/aiortc#164]
Hi! I just followed the guide to install aiortc and the packages needed and tried the server example and works fine, but with the webcam example i am getting this errors:

 

- The webpage is showing this modal when start is pressed: 

> SyntaxError: Unexpected token I in JSON at position 4

-  While the output in the terminal is: 

> Selected framerate (29.970030) is not supported by the device
> Supported modes:
> 1280x720@[1.000000 30.000000]fps
> 1280x720@[1.000000 30.000000]fps
>  (repeated 2 more times)
> 640x480@[1.000000 30.000000]fps
> 640x480@[1.000000 30.000000]fps
>  (repeated 2 more times)
> 320x240@[1.000000 30.000000]fps
> Error handling request
> Traceback (most recent call last):
>   File "/.../workspace/aio-env/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
>     resp = await task
>   File "/.../workspace/aio-env/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
>     resp = await handler(request)
>   File "webcam.py", line 46, in offer
>     player = MediaPlayer('default:none', format='avfoundation', options=options)
>   File "/.../workspace/aio-env/lib/python3.6/site-packages/aiortc/contrib/media.py", line 215, in __init__
>     self.__container = av.open(file=file, format=format, mode='r', options=options)
>   File "av/container/core.pyx", line 275, in av.container.core.open
>   File "av/container/core.pyx", line 227, in av.container.core.Container.__cinit__
>   File "av/container/core.pyx", line 129, in av.container.core.ContainerProxy.__init__
>   File "av/container/core.pyx", line 195, in av.container.core.ContainerProxy.err_check
>   File "av/utils.pyx", line 105, in av.utils.err_check
> av.AVError: [Errno 5] Input/output error: 'default:none' (16: avfoundation)

Im very interested in this example because i wanted to use the MediaPlayer to get the stream from the webcam in the computer. Im using macOS Mojave and python 3.6.0.

Thanks, Borja

**Comment by jlaine** [comment]
Could you please run the following:

`ffmpeg -f avfoundation -list_devices true -i ""`

**Comment by Borjis131** [comment]
Wow! thanks for your prompt reply!
Here is the output:

> ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
>   built with Apple LLVM version 10.0.1 (clang-1001.0.46.3)
>   configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1.3 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/openjdk-12.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/openjdk-12.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr
>   libavutil      56. 22.100 / 56. 22.100
>   libavcodec     58. 35.100 / 58. 35.100
>   libavformat    58. 20.100 / 58. 20.100
>   libavdevice    58.  5.100 / 58.  5.100
>   libavfilter     7. 40.101 /  7. 40.101
>   libavresample   4.  0.  0 /  4.  0.  0
>   libswscale      5.  3.100 /  5.  3.100
>   libswresample   3.  3.100 /  3.  3.100
>   libpostproc    55.  3.100 / 55.  3.100
> [AVFoundation input device @ 0x7fddb071d6c0] AVFoundation video devices:
> [AVFoundation input device @ 0x7fddb071d6c0] [0] FaceTime HD Camera
> [AVFoundation input device @ 0x7fddb071d6c0] [1] Capture screen 0
> [AVFoundation input device @ 0x7fddb071d6c0] AVFoundation audio devices:
> [AVFoundation input device @ 0x7fddb071d6c0] [0] Built-in Microphone
> : Input/output error

Seems ok except the last line

**Comment by jlaine** [comment]
That last line looks suspiciously like the error you encountered, no?

**Comment by Borjis131** [comment]
Yep, it says the same. Let me do a little research and I'll come back with answers or questions.

**Comment by Borjis131** [comment]
Ok, so I started searching the error of the ffmpeg list devices command and [this](https://lists.ffmpeg.org/pipermail/ffmpeg-user/2015-June/027193.html) is the only thing I could found, in the [next message](https://lists.ffmpeg.org/pipermail/ffmpeg-user/2015-June/027202.html) the question about the error is ignored. So I thought the problem may be the 'default:none' parameter passed as the file, I tried with other things supported by ffmpeg and it doesn't work.

Seeing the Avpy package I saw that it seems to only work with: 
> python2 (v2.6 and v2.7), python3 (from v3.2 to v3.5) 

Am I wrong?

I installed the python 3.5.4 version and tried to run it, but it gives me the same error. 
Do you know if its normal the Input/output error given when running this command? 
`ffmpeg -f avfoundation -list_devices true -i ""`

**Comment by jlaine** [comment]
You can forget about the `avpy` lead, we don't use it, we use `PyAV` which is a binding straight onto the ffmpeg libraries. Of course it works with Python 3, as aiortc is Python 3 - only :)

Back to your initial backtrace I see there is an error about the selected framerate, does it help if you change the options like:

`options = {'framerate': 30, 'video_size': '640x480'}`

**Comment by Borjis131** [comment]
I was about to ask you how do i put the framerate to 30fps, because I looked it up right [here](https://stackoverflow.com/questions/37960828/webcam-streaming-from-mac-using-ffmpeg).

I just tried your command and now it works fine, thanks for all the replys and for the awesome work with aiortc! 👍
