### ISSUE TITLE
How to make examples work?

### ISSUE THREAD

**Issue by maksutovaynur** [aiortc/aiortc#165]
Thank you for aiortc!
I've installed aiortc and dependencies on kubuntu 18.04 (amd64) and raspbian stretch (armv7).

I've tested connections: (1) kubuntu<->kubuntu; (2) kubuntu<->raspbian.

Though `datachannel-cli` example works fine for all the configurations, `videostream-cli` only works inside localhost (means only while running inside the same kubuntu) or in one local network. No exceptions, just "hanging" after copy-paste manipulations of sdp-offer and answer strings. What could be a reason?

And there is also another problem with `webcam` example: on raspbian it shows "No JPEG data found in image" and stream doesn't start. Do you have any suggestions for that situation?

**Comment by jlaine** [comment]
Can you try running the "videostream-cli" example in verbose mode (using `-v`) to see if we can gain some insights into what is going on?

**Comment by jlaine** [comment]
Closing, no reply from submitter.
