### ISSUE TITLE
Webcam example problems

### ISSUE THREAD

**Issue by llc1123** [aiortc/aiortc#166]
1. the webcam example does not support multiple clients. The server will throw an exception of device busy when the second client tries to connect.
2. when a client disconnects, the webcam will stop. If another client tries to connect after the first disconnects, the client will receive a empty MediaStreamTrack.

**Comment by jlaine** [comment]
1. Absolutely, it's not a broadcast

2. I'll check but it might be a bug in PyAV

**Comment by llc1123** [comment]
btw is it possible to connect the media player to ffmpeg by myself because I want to use custom configs and input source.

**Comment by jlaine** [comment]
`MediaPlayer` is a thin wrapper around PyAV (which is itself a binding onto ffmpeg's libraries), you should be able to pass any options you like:

https://github.com/aiortc/aiortc/blob/110e0459cbb45106a605e80fd568dd06719fee11/aiortc/contrib/media.py#L215

**Comment by jlaine** [comment]
Stopping the `MediaPlayer` should now cause the webcam to be closed. With the current PyAV version closing the webcam will occur after the GC kicks in, but this PR should ensure it gets closed immediately: https://github.com/mikeboers/PyAV/pull/513

**Comment by jlaine** [comment]
With the latest code (which requires PyAV >= 6.2.0) the webcam gets closed as soon as the connection closes.
