### ISSUE TITLE
How to send RTMP stream in the server.py example?

### ISSUE THREAD

**Issue by sergzach** [aiortc/aiortc#167]
Hi there!

I want to adjust [this code](https://github.com/aiortc/aiortc/blob/master/examples/server/server.py) to send incoming video data to nginx-rtmp-module (so, creating RTMP stream). And I can't figure out how to do that.

If I understand correctly `MediaPlayer` and `MediaRecorder` classes can not help me. They are for changing WebRTC media data (video or audio).

Probably I need some code in `on_track` (the nested function) but I can't figure out what exactly code. I have access to, say, video frames via `VideoStreamTrack`. Also I have access to whole connection via `RTCPeerConnection`. But how to get stream and just resend it via `RTMP`? Can `pyav` library help me there?

I'm a newbie to this soft (aiortc/pyav), so, I'm sorry.

**Comment by jlaine** [comment]
`MediaRecorder` is mostly what you want : it is a sink for media meaning it consumes media and passes them to the ffmpeg libraries for processing. I have no personal experience with RTMP but you probably want something like:

`MediaRecorder('rtmp:///live/myStream.sdp', format='flv')`

**Comment by sergzach** [comment]
@jlaine Do I need to install `ffmpeg` program to my docker ubuntu where `aiortc` installs or aiortc can do this without this additional installation, e.g. via libraries which are installed with `aiortc` together?

**Comment by jlaine** [comment]
PyAV, which aiortc makes use of, is a binding directly onto the ffmpeg
libraries (libav*). These libraries indeed need to be installed (see the
README.md file), but you do not need the ffmpeg program itself.

**Comment by jlaine** [comment]
Did this solve your issue?

**Comment by sergzach** [comment]
Thank you very much Jeremy! Yes, now it does record the video.

**Comment by jlaine** [comment]
Cool, thanks for letting me know!

**Comment by sergzach** [comment]
Thank you Jeremy!

In my case it works if code starts as:

`broadcast_recorder = MediaRecorder('rtmp://localhost:1935/live/myStream.sdp', format='flv'`)

May be your example without an explicit domain works too, I did not checked, I am sorry.

**Comment by AlexanderKozhevin** [comment]
@sergzach 
So we can just use any rtmp endpoint ?
Like 
```
recorder = MediaRecorder("rtmp://push.youstreamer.com/in/2112?704249fd9f8b852c6f2d5df3eac355dc",  format='flv')

```

**Comment by sergzach** [comment]
@AlexanderKozhevin 

And how do you know that stream is pushing incorrectly? Errors or no errors (e.g. swallowing)?

**Comment by AlexanderKozhevin** [comment]
@sergzach 
Inside video platform I see online status for some time, and then it's gone. 
The question remains - can I push to external server at all?

**Comment by sergzach** [comment]
Have you tried to do it with ffmpeg? For instance, like mentioned here: [https://stackoverflow.com/questions/43586435/ffmpeg-to-youtube-live](https://stackoverflow.com/questions/43586435/ffmpeg-to-youtube-live).

**Comment by mqgmaster** [comment]
@jlaine works great but the stream is being transcoded by MediaRecorder. Why? Its possible for aiortc keep the media intouched and push via RTMP? 

FFmpeg does that retransmission by using the flag "-c copy", but the option is ignored by MediaRecorder or pyAV.

Any idea for help on this?

**Comment by cagrisungur** [comment]
Can i manipulate multiple webrtc connection before calling `MediaRecorder` ?. I want to merge two stream before using `MediaRecorder` . I can successfully send using `MediaRecorder('rtmp//server.com', format=flv)` , but for two or more stream how can i do it ? @jlaine
