### ISSUE TITLE
How does aiortc behaves when some incoming UDP pakets from audio stream have been lost?

### ISSUE THREAD

**Issue by 124bit** [aiortc/aiortc#168]
My experiments with PyAv have shown that AudioFrames during write need to have pts exactly where the previous Frame finished or no pts at all, thus frames can't be dropped. 

What happens with pts of the next AudioFrame in case if previous was lost? 
Am I right that if I write all received frames to file, then after some time file will be shorter than actual time past because some UDP messages were lost?

Thanks

**Comment by jlaine** [comment]
The pts of the received AudioFrame are directly derived from the corresponding RTP packets, so if there is a gap in the received RTP packets, there will also be a gap in the AudioFrame pts:

https://github.com/aiortc/aiortc/blob/110e0459cbb45106a605e80fd568dd06719fee11/aiortc/rtcrtpreceiver.py#L434

**Comment by 124bit** [comment]
Thanks. Now it is much clearer.

In my script, I'll put empty AudioFrames before processing in a place of the lost packages because PyAv Resampler doesn't like nonconsecutive pts.
https://github.com/mikeboers/PyAV/blob/8db307bf683e97402904ac5d9ca43b7371c5f141/av/audio/resampler.pyx#L117-L122

However, for me, it looks like MediaRecorder should fail at AudioFrame encoding phase in case of a lost packet because it doesn't track pts (maybe I'm wrong, I never faced it).
https://github.com/aiortc/aiortc/blob/110e0459cbb45106a605e80fd568dd06719fee11/aiortc/contrib/media.py#L360

Thanks

**Comment by jlaine** [comment]
The PyAV resampler is indeed unhappy if the pts are not consecutive.

However to the best of my knowledge the resampler is not used by output
streams so output should work even if there are missing packets.

**Comment by 124bit** [comment]
Maybe I'm missing something, however, from my understanding links above show that AudioCodecContext uses AudioResampler in encode function. And also I received this error about wrong pts during writing to stream that is in the container opened to write to file.

**Comment by jlaine** [comment]
The AudioResampler code in PyAV has been overhauled to use FFmpeg's filter graph, so I think this is no longer an issue.
