### ISSUE TITLE
Stream stops streaming opening new MediaPlayer

### ISSUE THREAD

**Issue by JackD83** [aiortc/aiortc#173]
I came across an issue serving a video to clients using the webcam example. 
I change the example to stream a public low fps webcam trough WebRTC.

`player = MediaPlayer('http://212.170.100.189/axis-cgi/mjpg/video.cgi?resolution=640x480&dummy=1515501186711')`

Its working fine for the first client but if a second client opens the page and presses start, the video on the first client stops until the second clients MediaPlayer is ready.  This happens to every new client. All old clients just stop. 

Is there a way to fix this?

**Comment by JackD83** [comment]
Problem is caused by av.open which blocks the main event loop. I tried to handle it in a new thread without success so far

**Comment by jlaine** [comment]
Hm. Assuming we do manage to alleviate the problem with threading I wonder how to reflect this in the MediaPlayer API. This would mean moving the call to `open` out of the constructor, and probably replacing the track accessors with an async method?

**Comment by JackD83** [comment]
I'm new to all the async python calls. What I tried was to completely call the constructor of the MediaPlayer in a new thread with its own event loop and wait for it. This should allow the main loop to serve data to all clients while the MediaPlayer is initialized. Unfortunately, the MediaPlayer that was created this way did not send any data to clients. I suspect that the custom event loop of the thread is the problem and the main event loop has to be set somewhere on the MediaPlayer

**Comment by JackD83** [comment]
Moving the open call out of the constructor was the right call. 

`def __init__(self, file, format=None, options={}):       
        self.__file = file
        self.__format = format
        self.__options = options
       
 async def initialize(self):
        loop = asyncio.get_event_loop()
        self.__container = await loop.run_in_executor(None, self.avOpen, self.__file, self.__format, self.__options)
        self.__thread = None
        self.__thread_quit = None

        # examine streams
        self.__started = set()
        self.__streams = []
        self.__audio = None
        self.__video = None
        for stream in self.__container.streams:
            if stream.type == 'audio' and not self.__audio:
                self.__audio = PlayerStreamTrack(self, kind='audio')
                self.__streams.append(stream)
            elif stream.type == 'video' and not self.__video:
                self.__video = PlayerStreamTrack(self, kind='video')
                self.__streams.append(stream)

        # check whether we need to throttle playback
        container_format = set(self.__container.format.name.split(','))
        self._throttle_playback = not container_format.intersection(REAL_TIME_FORMATS)

    def avOpen(self, file, format, options):
        return av.open(file=file, format=format, mode='r', options=options)`

You have to call 
`await player.initialize()`

**Comment by jlaine** [comment]
Thanks for the feedback!

This confirms we need to alter the MediaPlayer API in a breaking fashion, I'm going to try and come up with a better API. There is another point I'm not 100% satisfied about: currently there is no way to use only a subset of the tracks contained in the file.

**Comment by hugobordigoni** [comment]
Not sure It's the best place to ask it, but shouldn't you use only one media player if it's the same media, and add the same track to multiple peer connections?

Then you have to deal with other issues: when one peer close the connection, you should not stop the track.

**Comment by caboteria** [comment]
I messed around with some code to keep the player running through connects and disconnects: https://github.com/caboteria/aiortc/tree/persistent-webcam in the examples/persistentwebcam directory.  It's based heavily on the existing webcam example but starts the MediaPlayer when the app starts and sends frames from the worker thread to each Track that has been started.

Comments welcome!

**Comment by Mohit-Ak** [comment]
Hi,
Is this problem fixed? I was also wondering if it is common to see feed degradation(latency) in the second client when compared to the first client.

I am using a Raspberry Pi4(4GB) RAM with Ubuntu 18.04 IoT 64bit pulling mjpeg feed from an IP camera and serving it to chrome on another PC via LAN. 

Are there any parameters we can tune to make the stutter or latency better when multiple clients are join?
