### ISSUE TITLE
Setting libvpx codec of cfg.rc_target_bitrate

### ISSUE THREAD

**Issue by jaykim305** [aiortc/aiortc#174]
When REMB packet is received, the target bitrate is unpacked and set as vpx codec's configuration, just like below.

https://github.com/aiortc/aiortc/blob/0310cd8486b38d8d8f295650253224247c43ed42/aiortc/codecs/vpx.py#L324-L326
https://github.com/aiortc/aiortc/blob/0310cd8486b38d8d8f295650253224247c43ed42/aiortc/codecs/vpx.py#L262-L264
(p.s  I made sure `__update_config()` is called every time, fixing `self.__update_config_needed` to be always `True`  )

I wanted to see if the vpx codec actually reflects the new `cfg.rc_taget_bitrate`, thus I saved the image and re-encoded to video to see the result.

However, the quality of the image/video is always same regardless of `cfg.rc_target_bitrate` change.
I even tried setting all `cfg.rc_target_bitrate` as just 1kbps (just like below),  expecting very low quality video, 

`DEFAULT_BITRATE = 1000  # 1 kbps`  
`MIN_BITRATE = 1000      # 1 kbps ` 
`MAX_BITRATE = 1000     # 1 kbps`  

but the result quality of image/video is always same. 
Can I get any help? 
How can I make sure vpx changes the bitrate according to its `cfg.rc_target_bitrate` ?

**Comment by jlaine** [comment]
What is the framerate of your video stream? If it's anything other than 30fps be aware that rate calculations will be wrong.

As for "how can I make sure vpx changes the bitrate", I'd suggest reading the code / docs of libvpx to confirm I'm doing things right. The WebRTC.org codebase is also an interesting source of information but the code is pretty complex due to the handling of multiple simultaneous encodings..

**Comment by jaykim305** [comment]
Frame rate is 30fps, thus it's the other problem.

As you mentioned, I am looking in to libvpx code base. 
I want check if all the cfg parameters are actually set to the codec after calling, 

`vpx_assert(lib.vpx_codec_enc_init(self.codec, self.cx, self.cfg, 0))`
`_vpx_assert(lib.vpx_codec_enc_config_set(self.codec, self.cfg))`.

But since this is called from .so library file by ffi interface, it is hard to debug.
For example, I want to access the address referred by the c pointer in self.codec structure, but I have no idea how to do it.
I think you might have some experience doing things like this.

Do you have any tips for debugging using ffi or .so files in python ?
and what libvpx code example did you refer to implementing encoding part ?

**Comment by jlaine** [comment]
Interfacing C libraries from Python is pretty straightforward, I recommend taking a look at the CFFI documentation.

It's unusual to need the address of a pointer, if you need to reach into the `vpx_codec_ctx_t` you can add the definitions for the members you need in:

https://github.com/aiortc/aiortc/blob/5e5b41bff1b7b28d5552369bb723a3c7a7c2837f/src/build_vpx.py#L133

**Comment by pkarimib** [comment]
I have a similar issue. No matter what I put for `cfg.rc_target_bitrate` the encoding result is the same.

**Comment by Tjoppen** [comment]
I can also confirm this. Setting self.cfg.rc_max_quantizer to a lower value like 10 increases bitrate but setting self.cfg.rc_target_bitrate to any value does nothing. This makes me suspect cfg isn't being used properly.

**Comment by DerGenaue** [comment]
Can confirm this.
We have an example test that adds bitrate configuration to the aiortc server example and bitrate configuration works fine for `h264` but doesn't work for `vpx`:
https://github.com/Roboy/webrtc-tests/tree/main/aiortc-test
