### ISSUE TITLE
A problem with audio from a user microphone in examples/server/

### ISSUE THREAD

**Issue by sergzach** [aiortc/aiortc#175]
Hello!

Thank you for your help! I'm close to finish my issue about mpeg-dash broadcast with `aiortc` and `nginx-rtmp-module`.

The problem I have: there is no audio in the mentioned example from a user microphone.

Yes, I can hear woman voice with the help of the next code chunks:
```
player = MediaPlayer(os.path.join(ROOT, 'demo-instruct.wav'))
...
if track.kind == 'audio':
            pc.addTrack(player.audio)
            recorder.addTrack(track)
...
```
Where `recorder.addTrack(track)` passes. Probably it means successful receiving a user audio track and adding it to a stream which is returning to a browser. But there is no audio at demo page (index.html). Woman voice is listening, yes, but no audio from a user microphone.

If I try to switch off woman voice by commenting pc.addTrack(player.audio) then there is silence.

Well, then I try to do:
```
pc.addTrack(track)
```
as in case of adding the player with the woman voice. And I hear sound from my microphone but for some reason there is noticeable sound distortion. 

Am I doing correct and is it a way to fix this distortion?

I am sorry, I've just figured out: the distortion is only when there is also the line:
```
recorder.addTrack(track)
```
When we drop the recorder line leaving only
```
pc.addTrack(track)
```
it sounds OK. 

Is it issue to fix? If not please close it.

**Comment by jlaine** [comment]
I don't understand this issue: the only audio you are supposed to hear on the browser side is the "demo-instruct.wav" file.

**Comment by sergzach** [comment]
Yes, but what if I want to change the example to hear my microphone but not the file?

Now it is not a problem I wait to be fixed, if the problem is not significant you can close it.

**Comment by jlaine** [comment]
If you want to just send your audio back to the browser you can use:

```patch
diff --git a/examples/server/server.py b/examples/server/server.py
index 53e5bb0..95fbe9f 100644
--- a/examples/server/server.py
+++ b/examples/server/server.py
@@ -132,8 +132,7 @@ async def offer(request):
         log_info("Track %s received", track.kind)
 
         if track.kind == "audio":
-            pc.addTrack(player.audio)
-            recorder.addTrack(track)
+            pc.addTrack(track)
         elif track.kind == "video":
             local_video = VideoTransformTrack(
                 track, transform=params["video_transform"]
```
