### ISSUE TITLE
Server example not working on Safari 12, iOS 12

### ISSUE THREAD

**Issue by ortegatron** [aiortc/aiortc#178]
Hi,
I'm trying the server example in many devices, so far has worked very good ,thanks for that.
But when I try on Iphone, Safari 12, the only thing i get back from video stream is a black screen. Audio stream works fine.
Server doesn't show any error, and in fact seems to be receving correctly each frame, I'm saving them to disk to check and they are fine. No errors shown on client console neither.
Do you have any idea what this compatibility issue may be?

**Comment by ortegatron** [comment]
SPD data:
Offer:
v=0
o=- 7793204826810525586 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video data
a=msid-semantic: WMS 6937f626-e28c-45c3-a69e-f8100c790455
m=audio 53171 UDP/TLS/RTP/SAVPF 111 103 9 102 0 8 105 13 110 113 126
c=IN IP4 192.168.1.5
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:211156821 1 udp 2113937151 192.168.1.5 53171 typ host generation 0 network-cost 50
a=candidate:2075991921 1 udp 2113939711 2800:a4:169b:e800:8dfe:b3e3:dca7:8d44 53172 typ host generation 0 network-cost 50
a=ice-ufrag:5wyY
a=ice-pwd:ajvC1o4yPqwdsrKdnUtbdfgI
a=ice-options:trickle
a=fingerprint:sha-256 83:EF:D6:95:00:B3:15:07:9B:27:BE:55:B1:F1:52:0C:73:7B:CD:51:1C:FD:1C:B9:94:6A:A6:AC:B5:DF:F2:F5
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:1557912193 cname:KcyXxv6oIOJJo/ZR
a=ssrc:1557912193 msid:6937f626-e28c-45c3-a69e-f8100c790455 a61c22a6-4a01-49e8-aca5-6002440a5ac8
a=ssrc:1557912193 mslabel:6937f626-e28c-45c3-a69e-f8100c790455
a=ssrc:1557912193 label:a61c22a6-4a01-49e8-aca5-6002440a5ac8
m=video 59029 UDP/TLS/RTP/SAVPF 96 97 98 99 100
c=IN IP4 192.168.1.5
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:211156821 1 udp 2113937151 192.168.1.5 59029 typ host generation 0 network-cost 50
a=candidate:2075991921 1 udp 2113939711 2800:a4:169b:e800:8dfe:b3e3:dca7:8d44 59030 typ host generation 0 network-cost 50
a=ice-ufrag:5wyY
a=ice-pwd:ajvC1o4yPqwdsrKdnUtbdfgI
a=ice-options:trickle
a=fingerprint:sha-256 83:EF:D6:95:00:B3:15:07:9B:27:BE:55:B1:F1:52:0C:73:7B:CD:51:1C:FD:1C:B9:94:6A:A6:AC:B5:DF:F2:F5
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 red/90000
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 ulpfec/90000
a=ssrc-group:FID 462875617 1586430414
a=ssrc:462875617 cname:KcyXxv6oIOJJo/ZR
a=ssrc:462875617 msid:6937f626-e28c-45c3-a69e-f8100c790455 24f71b38-32d6-48ff-89ea-349f7049f9a1
a=ssrc:462875617 mslabel:6937f626-e28c-45c3-a69e-f8100c790455
a=ssrc:462875617 label:24f71b38-32d6-48ff-89ea-349f7049f9a1
a=ssrc:1586430414 cname:KcyXxv6oIOJJo/ZR
a=ssrc:1586430414 msid:6937f626-e28c-45c3-a69e-f8100c790455 24f71b38-32d6-48ff-89ea-349f7049f9a1
a=ssrc:1586430414 mslabel:6937f626-e28c-45c3-a69e-f8100c790455
a=ssrc:1586430414 label:24f71b38-32d6-48ff-89ea-349f7049f9a1
m=application 61701 DTLS/SCTP 5000
c=IN IP4 192.168.1.5
a=candidate:211156821 1 udp 2113937151 192.168.1.5 61701 typ host generation 0 network-cost 50
a=candidate:2075991921 1 udp 2113939711 2800:a4:169b:e800:8dfe:b3e3:dca7:8d44 61702 typ host generation 0 network-cost 50
a=ice-ufrag:5wyY
a=ice-pwd:ajvC1o4yPqwdsrKdnUtbdfgI
a=ice-options:trickle
a=fingerprint:sha-256 83:EF:D6:95:00:B3:15:07:9B:27:BE:55:B1:F1:52:0C:73:7B:CD:51:1C:FD:1C:B9:94:6A:A6:AC:B5:DF:F2:F5
a=setup:actpass
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024

Answer:
v=0
o=- 3768268359 3768268359 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE audio video data
a=msid-semantic:WMS *
m=audio 40938 UDP/TLS/RTP/SAVPF 111 0 8
c=IN IP4 172.31.19.127
a=sendrecv
a=mid:audio
a=msid:fd220322-2a91-4805-8fc4-a6bd510c4073 ac4302fe-98a2-4218-b623-c412a0f9dce9
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc:2247724871 cname:{fea5c10c-e8fb-4efa-ba61-2663ab898ace}
a=rtpmap:111 opus/48000/2
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=candidate:e0c714b22d01149377f5787386ec7c2c 1 udp 2130706431 172.31.19.127 40938 typ host
a=candidate:580b5f32035da7f14a30ea7a8d826c67 1 udp 2130706431 172.17.0.1 49735 typ host
a=candidate:0ad8db753210ce9554cf251a9e51e792 1 udp 1694498815 52.39.84.238 49735 typ srflx raddr 172.17.0.1 rport 49735
a=candidate:945bd0bf4d3d8589437b9cc43f41ff52 1 udp 1694498815 52.39.84.238 40938 typ srflx raddr 172.31.19.127 rport 40938
a=end-of-candidates
a=ice-ufrag:yJfG
a=ice-pwd:ZRdCrLae4aDnzUxTrPvgke
a=fingerprint:sha-256 80:2A:C6:DB:9D:08:8D:71:9B:4E:CF:47:CF:71:B1:C0:64:38:C5:92:F8:56:4D:44:8E:40:6B:A1:91:26:3F:DD
a=setup:active
m=video 40938 UDP/TLS/RTP/SAVPF 96 97
c=IN IP4 172.31.19.127
a=sendrecv
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=mid:video
a=msid:fd220322-2a91-4805-8fc4-a6bd510c4073 cc27a099-8f76-451e-9f6f-e48407e873d6
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc-group:FID 1089079279 1856709933
a=ssrc:1089079279 cname:{fea5c10c-e8fb-4efa-ba61-2663ab898ace}
a=ssrc:1856709933 cname:{fea5c10c-e8fb-4efa-ba61-2663ab898ace}
a=rtpmap:96 H264/90000
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=fmtp:96 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42e01f
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=candidate:e0c714b22d01149377f5787386ec7c2c 1 udp 2130706431 172.31.19.127 40938 typ host
a=candidate:580b5f32035da7f14a30ea7a8d826c67 1 udp 2130706431 172.17.0.1 49735 typ host
a=candidate:0ad8db753210ce9554cf251a9e51e792 1 udp 1694498815 52.39.84.238 49735 typ srflx raddr 172.17.0.1 rport 49735
a=candidate:945bd0bf4d3d8589437b9cc43f41ff52 1 udp 1694498815 52.39.84.238 40938 typ srflx raddr 172.31.19.127 rport 40938
a=end-of-candidates
a=ice-ufrag:yJfG
a=ice-pwd:ZRdCrLae4aDnzUxTrPvgke
a=fingerprint:sha-256 80:2A:C6:DB:9D:08:8D:71:9B:4E:CF:47:CF:71:B1:C0:64:38:C5:92:F8:56:4D:44:8E:40:6B:A1:91:26:3F:DD
a=setup:active
m=application 40938 DTLS/SCTP 5000
c=IN IP4 172.31.19.127
a=mid:data
a=sctpmap:5000 webrtc-datachannel 65535
a=max-message-size:65536
a=candidate:e0c714b22d01149377f5787386ec7c2c 1 udp 2130706431 172.31.19.127 40938 typ host
a=candidate:580b5f32035da7f14a30ea7a8d826c67 1 udp 2130706431 172.17.0.1 49735 typ host
a=candidate:0ad8db753210ce9554cf251a9e51e792 1 udp 1694498815 52.39.84.238 49735 typ srflx raddr 172.17.0.1 rport 49735
a=candidate:945bd0bf4d3d8589437b9cc43f41ff52 1 udp 1694498815 52.39.84.238 40938 typ srflx raddr 172.31.19.127 rport 40938
a=end-of-candidates
a=ice-ufrag:yJfG
a=ice-pwd:ZRdCrLae4aDnzUxTrPvgke
a=fingerprint:sha-256 80:2A:C6:DB:9D:08:8D:71:9B:4E:CF:47:CF:71:B1:C0:64:38:C5:92:F8:56:4D:44:8E:40:6B:A1:91:26:3F:DD
a=setup:active

**Comment by ortegatron** [comment]
Solved. 
Add playsinline and controls to html video element.

https://stackoverflow.com/questions/48459539/webrtc-peerconnection-showing-black-screen-on-safari-11-mac-os-x-10-13

**Comment by jlaine** [comment]
Could you please submit a PR which adds this so others don't encounter the same problem?

**Comment by ortegatron** [comment]
Done :)

**Comment by jesseorg** [comment]
Safari in iOS 12.4 iPhone & Safari 13.0.4 OSX 10.15.2 does not show the video window. Apparently the addition of **playsinline** and **controls** to the video tag does not help. Perhaps there is something else to be done?
