### ISSUE TITLE
Bind to event when ice connection is lost

### ISSUE THREAD

**Issue by langep** [aiortc/aiortc#186]
I have set up a simple example server using only a data channel at the moment. I want to be able to stop the RTCPeerConnection on the server when the ice connection to the client is lost (e.g. when the client refreshes the web page or closes the tab). This shows up in the logs on the server as 

`INFO:ice:Connection(0) Consent to send expired
DEBUG:ice:Connection(0) protocol(0) connection_lost(None)`

How can I listen to these events? I am wondering if this is possible with build in methods or if I need to implement my own heartbeat.

**Comment by jlaine** [comment]
I suggest you look at the provided code examples, for instance:

https://github.com/aiortc/aiortc/blob/cbfeb8940c1eaa94895a0f7a3c7adf1dc0dc3fb7/examples/server/server.py#L123

**Comment by langep** [comment]
@jlaine I tried to follow the example as close as possible but `@pc.on('iceconnectionstatechange')` does not get called when the client closed or reloads the tab i.e. the state remains 'completed'.

**Comment by nakai-omer** [comment]
We are also having this issue and `iceconnectionstatechange` is not being raised
