### ISSUE TITLE
ValueError: 'a64e1aa4-8c7e-4671-ab02-e6a3483b1cd9.local' does not appear to be an IPv4 or IPv6 address

### ISSUE THREAD

**Issue by AlexanderKozhevin** [aiortc/aiortc#187]
Started examples/webcam on OSX Mojave. 
Keep getting this error. No matter which endpoint do I use
* localhost:8080
* 0.0.0.0:8080
* 127.0.0.1:8080
```
ValueError: 'a64e1aa4-8c7e-4671-ab02-e6a3483b1cd9.local' does not appear to be an IPv4 or IPv6 address```

---
And I'm struggling with another error on remote Ubuntu 18.04 with the same code example. 
---

av.AVError: [Errno 2] No such file or directory: '/dev/video0' (16: video4linux2,v4l2)

**Comment by jlaine** [comment]
The first error: this is a new browser behaviour, in addition to IP addresses they can offer MDNS entries. aioice/aiortc will need to be updated to support this, or at least filter out such entries. I'm not sure how I can test this though as I think Safari is the first to implement this feature and I don't use OS X.

The second error looks unrelated, just change /dev/video0 to whatever your webcam is.

**Comment by AlexanderKozhevin** [comment]
@jlaine 
About second question. But what should I change it to, if my server is remote?

**Comment by jlaine** [comment]
Regarding your first issue, I've updated aioice to not bomb on mDNS candidates:

https://github.com/aiortc/aioice/commit/96775217052ed9ac7eb045123605b20a35b67db7

aioice 0.6.15 should be hitting pypi within a few minutes with this fix. aioice doesn't however support mDNS candidates yet so I'm going to keep this issue open until it does.

Let's keep the webcam issues in a separate ticket please, I'll let you open one.
