### ISSUE TITLE
av.AVError: [Errno 2] No such file or directory: '/dev/video0' (16: video4linux2,v4l2)

### ISSUE THREAD

**Issue by AlexanderKozhevin** [aiortc/aiortc#189]
Which camera should I specify if I run the code on remote server. 
And use camera on other machine ?

**Comment by jlaine** [comment]
I'm assuming we are talking about the "webcam" example as it's the only one which uses the camera. This example is designed to illustrate:

- a server (using aiortc) which reads a video from a webcam and sends it to the client
- a client (using a browser) which only receives the video, it does not use a webcam or mic

On the server side, replace /dev/video0 by whatever the webcam is on the server side.

If there is no webcam on the server side, I suggest looking at other examples which may be closer to what you want.

**Comment by AlexanderKozhevin** [comment]
@jlaine Yeap, so I wanted to send video from the client to the server. Not vice versa.

**Comment by jlaine** [comment]
Ok, look at the "server" example then
