### ISSUE TITLE
Not able to transfer video from one peer to another

### ISSUE THREAD

**Issue by Nishanth009** [aiortc/aiortc#193]
HI,

I am trying to send a video feed(animated flag) from aiortc peer to a javascript peer and display that at javascript (html) end. I used the "Webcam.py" example from aiortc examples and changed server based logic to websocket logic.The video feed is not getting transferred to the JavaScript peer. But i can see RTCTrackEvent and MediaStream is getting generated at js end.
I have noticed  " async def on_iceconnectionstatechange():
                          print("ICE connection state is %s" % pc.iceConnectionState)"
is also not called/pc.iceConnectionState is not getting printed
i am attaching my codes for peers as well as event received at js end. Not sure why video transfer is not happening.

**both peers are at same network

Thanks

RTCTrackEvent 
-------------------------
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: RTCPeerConnection
connectionState: "connecting"
currentLocalDescription: RTCSessionDescription {type: "offer", sdp: "v=0
↵o=- 4812816766640867557 2 IN IP4 127.0.0.1
↵s…-event/16000
↵a=rtpmap:126 telephone-event/8000
↵"}
currentRemoteDescription: RTCSessionDescription {type: "answer", sdp: "v=0
↵o=- 3772269318 3772269318 IN IP4 127.0.0.1
↵s…45 cname:{e0a38b54-788d-4d41-874a-5587c7a606d8}
↵"}
iceConnectionState: "failed"
iceGatheringState: "complete"
localDescription: RTCSessionDescription {type: "offer", sdp: "v=0
↵o=- 4812816766640867557 2 IN IP4 127.0.0.1
↵s…-event/16000
↵a=rtpmap:126 telephone-event/8000
↵"}
onaddstream: null
onconnectionstatechange: null
ondatachannel: null
onicecandidate: null
oniceconnectionstatechange: null
onicegatheringstatechange: null
onnegotiationneeded: null
onremovestream: null
onsignalingstatechange: null
ontrack: null
pendingLocalDescription: null
pendingRemoteDescription: null
remoteDescription: RTCSessionDescription {type: "answer", sdp: "v=0
↵o=- 3772269318 3772269318 IN IP4 127.0.0.1
↵s…45 cname:{e0a38b54-788d-4d41-874a-5587c7a606d8}
↵"}
signalingState: "stable"
__proto__: RTCPeerConnection
defaultPrevented: false
eventPhase: 0
isTrusted: true
path: []
receiver: RTCRtpReceiver {track: MediaStreamTrack}
returnValue: true
srcElement: RTCPeerConnection {localDescription: RTCSessionDescription, currentLocalDescription: RTCSessionDescription, pendingLocalDescription: null, remoteDescription: RTCSessionDescription, currentRemoteDescription: RTCSessionDescription, …}
streams: [MediaStream]
target: RTCPeerConnection {localDescription: RTCSessionDescription, currentLocalDescription: RTCSessionDescription, pendingLocalDescription: null, remoteDescription: RTCSessionDescription, currentRemoteDescription: RTCSessionDescription, …}
timeStamp: 1696.6149999971094
track: MediaStreamTrack {kind: "video", id: "a1d19902-8636-479f-9825-f7c1888dafcf", label: "a1d19902-8636-479f-9825-f7c1888dafcf", enabled: true, muted: true, …}
transceiver: RTCRtpTransceiver {mid: "0", sender: RTCRtpSender, receiver: RTCRtpReceiver, stopped: false, direction: "recvonly", …}
type: "track"

MediaStream
----------------------------
active: true
id: "ba01271e-3cc1-4449-9d4c-4ce34202c855"
onactive: null
onaddtrack: null
oninactive: null
onremovetrack: null

**Comment by jlaine** [comment]
Does the unmodified example work?

**Comment by Nishanth009** [comment]
Thanks for the reply.
I have tried with different networks as well as firefox and chrome still the problem exists.
So i pulled out details about webrtc connection from firefox



Local Candidate | Remote Candidate | Component ID | ICE State | Priority | Nominated | Selected | Bytes sent | Bytes received
-- | -- | -- | -- | -- | -- | -- | -- | --
192.168.0.92:35872/undefined(host) | 192.168.0.2:60163/undefined(host) | 1 | failed | 9115005270299247000 | false | false | 0 | 0
192.168.0.92:35872/undefined(host) | 192.168.0.46:43144/undefined(host) | 1 | failed | 9115005270299247000 | false | false | 0 | 0
192.168.0.92:35872/undefined(host) | 180.151.125.33:43144/undefined(srflx) | 1 | failed | 7277816997780259000 | false | false | 0 | 0
192.168.0.92:35872/undefined(host) | 180.151.125.33:60163/undefined(srflx) | 1 | failed | 7277816997780259000 | false | false | 0 | 0
158.69.221.198:53824/undefined(relay) | 192.168.0.2:60163/undefined(host) | 1 | failed | 396069377058799600 | false | false | 0 | 0
158.69.221.198:53824/undefined(relay) | 192.168.0.46:43144/undefined(host) | 1 | failed | 396069377058799600 | false | false | 0 | 0
158.69.221.198:53824/undefined(relay) | 180.151.125.33:43144/undefined(srflx) | 1 | failed | 396069376186384400 | false | false | 0 | 0
158.69.221.198:53824/undefined(relay) | 180.151.125.33:60163/undefined(srflx)

----------------------------------------------------------------------------------------------------------------------
```
SDP
Local SDP (Offer)

v=0

o=mozilla...THIS_IS_SDPARTA-67.0.1 8700170719431430717 0 IN IP4 0.0.0.0

s=-

t=0 0

a=sendrecv

a=fingerprint:sha-256 AF:26:10:32:57:45:E5:92:B5:97:84:E2:F4:6F:4D:88:60:80:BF:3B:D4:9B:5C:1D:A0:53:21:79:B6:DB:35:28

a=group:BUNDLE 0 1

a=ice-options:trickle

a=msid-semantic:WMS *

m=video 53824 UDP/TLS/RTP/SAVPF 120 121 126 97

c=IN IP4 158.69.221.198

a=candidate:0 1 UDP 2122252543 192.168.0.92 35872 typ host

a=candidate:4 1 TCP 2105524479 192.168.0.92 9 typ host tcptype active

a=candidate:0 2 UDP 2122252542 192.168.0.92 42105 typ host

a=candidate:4 2 TCP 2105524478 192.168.0.92 9 typ host tcptype active

a=candidate:1 1 UDP 1686052863 180.151.125.33 35872 typ srflx raddr 192.168.0.92 rport 35872

a=candidate:1 2 UDP 1686052862 180.151.125.33 42105 typ srflx raddr 192.168.0.92 rport 42105

a=candidate:3 1 UDP 92217087 158.69.221.198 53824 typ relay raddr 158.69.221.198 rport 53824

a=candidate:3 2 UDP 92217086 158.69.221.198 53825 typ relay raddr 158.69.221.198 rport 53825

a=recvonly

a=end-of-candidates

a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid

a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time

a=extmap:5 urn:ietf:params:rtp-hdrext:toffset

a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1

a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1

a=fmtp:120 max-fs=12288;max-fr=60

a=fmtp:121 max-fs=12288;max-fr=60

a=ice-pwd:246a830aef19f1763c5069e0a1fea4ea

a=ice-ufrag:fad7dd41

a=mid:0

a=rtcp:53825 IN IP4 158.69.221.198

a=rtcp-fb:120 nack

a=rtcp-fb:120 nack pli

a=rtcp-fb:120 ccm fir

a=rtcp-fb:120 goog-remb

a=rtcp-fb:121 nack

a=rtcp-fb:121 nack pli

a=rtcp-fb:121 ccm fir

a=rtcp-fb:121 goog-remb

a=rtcp-fb:126 nack

a=rtcp-fb:126 nack pli

a=rtcp-fb:126 ccm fir

a=rtcp-fb:126 goog-remb

a=rtcp-fb:97 nack

a=rtcp-fb:97 nack pli

a=rtcp-fb:97 ccm fir

a=rtcp-fb:97 goog-remb

a=rtcp-mux

a=rtpmap:120 VP8/90000

a=rtpmap:121 VP9/90000

a=rtpmap:126 H264/90000

a=rtpmap:97 H264/90000

a=setup:actpass

a=ssrc:2132416765 cname:{9714664c-f86f-42b7-ad19-57a3a962dae4}

m=audio 53826 UDP/TLS/RTP/SAVPF 109 9 0 8 101

c=IN IP4 158.69.221.198

a=candidate:0 1 UDP 2122252543 192.168.0.92 56596 typ host

a=candidate:4 1 TCP 2105524479 192.168.0.92 9 typ host tcptype active

a=candidate:0 2 UDP 2122252542 192.168.0.92 44894 typ host

a=candidate:4 2 TCP 2105524478 192.168.0.92 9 typ host tcptype active

a=candidate:1 1 UDP 1686052863 180.151.125.33 56596 typ srflx raddr 192.168.0.92 rport 56596

a=candidate:1 2 UDP 1686052862 180.151.125.33 44894 typ srflx raddr 192.168.0.92 rport 44894

a=candidate:3 1 UDP 92217087 158.69.221.198 53826 typ relay raddr 158.69.221.198 rport 53826

a=candidate:3 2 UDP 92217086 158.69.221.198 53827 typ relay raddr 158.69.221.198 rport 53827

a=recvonly

a=end-of-candidates

a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level

a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level

a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid

a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1

a=fmtp:101 0-15

a=ice-pwd:246a830aef19f1763c5069e0a1fea4ea

a=ice-ufrag:fad7dd41

a=mid:1

a=rtcp:53827 IN IP4 158.69.221.198

a=rtcp-mux

a=rtpmap:109 opus/48000/2

a=rtpmap:9 G722/8000/1

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:101 telephone-event/8000

a=setup:actpass

a=ssrc:311879794 cname:{9714664c-f86f-42b7-ad19-57a3a962dae4}
```
```
Remote SDP (Answer)

v=0

o=- 3772330337 3772330337 IN IP4 0.0.0.0

s=-

t=0 0

a=sendrecv

a=group:BUNDLE 0 1

a=msid-semantic:WMS *

m=video 60163 UDP/TLS/RTP/SAVPF 120 126

c=IN IP4 192.168.0.2

a=candidate:b0bf24b9a4f2e7cd5ecbff46dc6fcbcd 1 udp 2130706431 192.168.0.2 60163 typ host

a=candidate:c9cd1250f76180bab9ae8c039f104580 1 udp 2130706431 192.168.0.46 43144 typ host

a=candidate:f4a2bb6f2a4b1b933095585cbd69c70c 1 udp 1694498815 180.151.125.33 43144 typ srflx raddr 192.168.0.46 rport 43144

a=candidate:380df8f5866b8cef660f9558d990eddc 1 udp 1694498815 180.151.125.33 60163 typ srflx raddr 192.168.0.2 rport 60163

a=sendonly

a=end-of-candidates

a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid

a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time

a=fingerprint:sha-256 33:2F:AD:79:CA:E1:14:53:72:55:9E:D5:B0:A3:D1:FF:9B:9E:2F:E8:54:81:83:DE:9C:D7:D1:05:51:06:3C:5A

a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1

a=ice-pwd:1daZwAdo5XywAfwGNMvafJ

a=ice-ufrag:l2As

a=mid:0

a=msid:a8aeaaee-2306-406f-8e00-d4a5600d1e85 e5ca6829-3863-41d3-a8a9-ec7434ee8b82

a=rtcp:9 IN IP4 0.0.0.0

a=rtcp-fb:120 nack

a=rtcp-fb:120 nack pli

a=rtcp-fb:120 goog-remb

a=rtcp-fb:126 nack

a=rtcp-fb:126 nack pli

a=rtcp-fb:126 goog-remb

a=rtcp-mux

a=rtpmap:120 VP8/90000

a=rtpmap:126 H264/90000

a=setup:active

a=ssrc:2142249799 cname:{f4fb6adf-5760-4f84-b1d9-d37c98f854b8}

m=audio 60163 UDP/TLS/RTP/SAVPF 109 0 8

c=IN IP4 192.168.0.2

a=candidate:b0bf24b9a4f2e7cd5ecbff46dc6fcbcd 1 udp 2130706431 192.168.0.2 60163 typ host

a=candidate:c9cd1250f76180bab9ae8c039f104580 1 udp 2130706431 192.168.0.46 43144 typ host

a=candidate:f4a2bb6f2a4b1b933095585cbd69c70c 1 udp 1694498815 180.151.125.33 43144 typ srflx raddr 192.168.0.46 rport 43144

a=candidate:380df8f5866b8cef660f9558d990eddc 1 udp 1694498815 180.151.125.33 60163 typ srflx raddr 192.168.0.2 rport 60163

a=inactive

a=end-of-candidates

a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid

a=fingerprint:sha-256 33:2F:AD:79:CA:E1:14:53:72:55:9E:D5:B0:A3:D1:FF:9B:9E:2F:E8:54:81:83:DE:9C:D7:D1:05:51:06:3C:5A

a=ice-pwd:1daZwAdo5XywAfwGNMvafJ

a=ice-ufrag:l2As

a=mid:1

a=msid:a8aeaaee-2306-406f-8e00-d4a5600d1e85 02c05b71-5a32-4bcb-a3a0-b72afffd7de0

a=rtcp:9 IN IP4 0.0.0.0

a=rtcp-mux

a=rtpmap:109 opus/48000/2

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=setup:active

a=ssrc:3538357049 cname:{f4fb6adf-5760-4f84-b1d9-d37c98f854b8}
```

**Comment by t-walker-wei** [comment]
> HI,
> 
> I am trying to send a video feed(animated flag) from aiortc peer to a javascript peer and display that at javascript (html) end. I used the "Webcam.py" example from aiortc examples and changed server based logic to websocket logic.The video feed is not getting transferred to the JavaScript peer. But i can see RTCTrackEvent and MediaStream is getting generated at js end.
> I have noticed " async def on_iceconnectionstatechange():
> print("ICE connection state is %s" % pc.iceConnectionState)"
> is also not called/pc.iceConnectionState is not getting printed
> i am attaching my codes for peers as well as event received at js end. Not sure why video transfer is not happening.
> 
> **both peers are at same network
> 
> Thanks
> 
> ## RTCTrackEvent
> bubbles: false
> cancelBubble: false
> cancelable: false
> composed: false
> currentTarget: RTCPeerConnection
> connectionState: "connecting"
> currentLocalDescription: RTCSessionDescription {type: "offer", sdp: "v=0
> ↵o=- 4812816766640867557 2 IN IP4 127.0.0.1
> ↵s…-event/16000
> ↵a=rtpmap:126 telephone-event/8000
> ↵"}
> currentRemoteDescription: RTCSessionDescription {type: "answer", sdp: "v=0
> ↵o=- 3772269318 3772269318 IN IP4 127.0.0.1
> ↵s…45 cname:{e0a38b54-788d-4d41-874a-5587c7a606d8}
> ↵"}
> iceConnectionState: "failed"
> iceGatheringState: "complete"
> localDescription: RTCSessionDescription {type: "offer", sdp: "v=0
> ↵o=- 4812816766640867557 2 IN IP4 127.0.0.1
> ↵s…-event/16000
> ↵a=rtpmap:126 telephone-event/8000
> ↵"}
> onaddstream: null
> onconnectionstatechange: null
> ondatachannel: null
> onicecandidate: null
> oniceconnectionstatechange: null
> onicegatheringstatechange: null
> onnegotiationneeded: null
> onremovestream: null
> onsignalingstatechange: null
> ontrack: null
> pendingLocalDescription: null
> pendingRemoteDescription: null
> remoteDescription: RTCSessionDescription {type: "answer", sdp: "v=0
> ↵o=- 3772269318 3772269318 IN IP4 127.0.0.1
> ↵s…45 cname:{e0a38b54-788d-4d41-874a-5587c7a606d8}
> ↵"}
> signalingState: "stable"
> **proto**: RTCPeerConnection
> defaultPrevented: false
> eventPhase: 0
> isTrusted: true
> path: []
> receiver: RTCRtpReceiver {track: MediaStreamTrack}
> returnValue: true
> srcElement: RTCPeerConnection {localDescription: RTCSessionDescription, currentLocalDescription: RTCSessionDescription, pendingLocalDescription: null, remoteDescription: RTCSessionDescription, currentRemoteDescription: RTCSessionDescription, …}
> streams: [MediaStream]
> target: RTCPeerConnection {localDescription: RTCSessionDescription, currentLocalDescription: RTCSessionDescription, pendingLocalDescription: null, remoteDescription: RTCSessionDescription, currentRemoteDescription: RTCSessionDescription, …}
> timeStamp: 1696.6149999971094
> track: MediaStreamTrack {kind: "video", id: "a1d19902-8636-479f-9825-f7c1888dafcf", label: "a1d19902-8636-479f-9825-f7c1888dafcf", enabled: true, muted: true, …}
> transceiver: RTCRtpTransceiver {mid: "0", sender: RTCRtpSender, receiver: RTCRtpReceiver, stopped: false, direction: "recvonly", …}
> type: "track"
> 
> ## MediaStream
> active: true
> id: "ba01271e-3cc1-4449-9d4c-4ce34202c855"
> onactive: null
> onaddtrack: null
> oninactive: null
> onremovetrack: null

Hello, did you solve this problem? @Nishanth009 
It keep **connectionstatechange failed** in browser.

**Comment by diversees** [comment]
Did anyone able to solve this?
