### ISSUE TITLE
processing frames on server and send them back with json

### ISSUE THREAD

**Issue by eyebies** [aiortc/aiortc#194]
I am doing some thing similar to 
https://github.com/aiortc/aiortc/issues/91.

I need to capture frames/video from browser send it to server, analyze them there and respond with json, processed frame. (If I can retain the frames on the client side, I don;t have to send the processed frames. I just need to respond with json.

My application takes 40 ms for each frame. I cannot skip frames. I also need to send a json back to the client for the dashboard. Kindly suggest if I can accomplish that, a constant latency is fine with my application but, I expect 25 fps at on the dashboard.
thanks!

**Comment by jlaine** [comment]
I'm sorry but this question is out of scope, I cannot respond to all the question along the lines "how do I do X".

**Comment by eyebies** [comment]
No problem. I understand. Thanks!
