### ISSUE TITLE
Adding support for the Janus TextRoom Plugin

### ISSUE THREAD

**Issue by sdjksdafji** [aiortc/aiortc#195]
Hi there,

I am trying to modify the example to work with Janus text room plugin. I am trying to use the following code to replace on same named function in the examples/janus/janus.py.

`async def run(pc, player, room, session):
    await session.create()
    print("session url: " + session._session_url);
    # configure media
    media = {"audio": False, "video": False, "data": True}

    # join text room
    plugin = await session.attach("janus.plugin.textroom")
    print("plugin url: " + plugin._url)

    await plugin.send({
        "body":{"request": "setup"}
    })

    print("setup data channel")
    channel = pc.createDataChannel("JanusDataChannel", ordered=False)
    channel_log(channel, "-", "created by local party")

    async def send_pings():
        while True:
            channel_send(channel, "ping %d" % current_stamp())
            await asyncio.sleep(1)

    async def setup_room():
        json_body = {
            "textroom": "join",
            "transaction": transaction_id(),
            "room": 1234,
            "username": transaction_id(),
            "display": "python_client"
        }

        channel_send(channel, json_body)

    @channel.on("open")
    def on_open():
        asyncio.ensure_future(setup_room())

    @channel.on("message")
    def on_message(message):
        channel_log(channel, "<", message)

        if isinstance(message, str) and message.startswith("pong"):
            elapsed_ms = (current_stamp() - int(message[5:])) / 1000
        print(" RTT %.2f ms" % elapsed_ms)

    await pc.setLocalDescription(await pc.createOffer())

    request = {"request": "configure"}
    request.update(media)
    response = await plugin.send(
        {
            "body": request,
            "jsep": {
                "sdp": pc.localDescription.sdp,
                "trickle": True,
                "type": pc.localDescription.type,
            },
        }
    )

    # apply answer
    answer = RTCSessionDescription(
        sdp=response["jsep"]["sdp"], type=response["jsep"]["type"]
    )
    await pc.setRemoteDescription(answer)`

However, I got the following error from Janus server:

`plugin response: {'janus': 'error', 'session_id': 2457052936624798, 'transaction': 'yFllYOfSOsfb', 'error': {'code': 490, 'reason': 'Error setting ICE locally'}}
Traceback (most recent call last):
  File "textroom.py", line 247, in <module>
    run(pc=pc, player=player, room=args.room, session=session)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "textroom.py", line 172, in run
    "type": pc.localDescription.type,
  File "textroom.py", line 39, in send
    assert data["janus"] == "ack"
AssertionError`

Could you take a look let me know what is the missing to work with the Janus text room plugin?

Thanks in advance.

**Comment by jlaine** [comment]
Does the unmodified example work?

I am the sole maintainer for this project and am unable to provide free consulting on custom projects

**Comment by sdjksdafji** [comment]
Thanks for the fast reply. Yes, the unmodified example works. The text plugin is just another plugin uses data channel. Do you know who might be familiar with the aiortc & Janus integration?
