### ISSUE TITLE
example server not working on remote machine

### ISSUE THREAD

**Issue by litanlitudan** [aiortc/aiortc#200]
The example server code works perfectly locally, even within a docker.
However, if I run the server code on a remote machine, and open the webpage from the local machine browser, ICE gathering state is always new.
Did I miss anything? Or it indeed takes very long to connect?

Much appreciate it.

**Comment by litanlitudan** [comment]
Turns out the issue was about the security.
Chrome doesn't allow me to acquire the web camera with an unauthorized source.
After I remapped the port to localhost, everything works perfectly.

**Comment by jlaine** [comment]
Thanks for clarifying. Alternatively you could run the server over SSL by either:

- using `--cert-file` and `--key-file` arguments
- or behind a reverse proxy such as nginx
