### ISSUE TITLE
Integrate Django

### ISSUE THREAD

**Issue by petryx** [aiortc/aiortc#202]
Hi,

This project is awesome. I am trying integrate this project with Django, in order to create a site to visualize a lot of security cams.

Somebody have a example of integration? Or a way todo this?

Thanks.

**Comment by jlaine** [comment]
Have you looked at #142 and #56? My answer here will be similar:

Django and aiortc use the same programming language, but there is little to no overlap between their respective scopes:

- Django is a web framework. It gives you a way to structure how you handle HTTP requests, perform database operations and send out HTTP responses for your web pages or API endpoints. 

- aiortc is all about the flow of realtime media (audio / video / data channels). It is useful if you want your Python code to take part in the media flow, for instance to apply some processing to the audio / video.

=> how do you envision these two parts interacting? Can you tell me anything more about what you are trying to do?

**Comment by petryx** [comment]
Hi Jlaine,

I saw those topics, but didn't help me.

My idea is usage Django as web Interface to manage the cameras (IP, User, Password, URL) and show the live streams from cameras, here come your project, instantiate the camera, get the rtsp feed and send to browser with low latency and  only video Full HD without audio.

So my question is: How usage your project to get the rtsp feeds (h.264) and send to browser? 

Develop the Django part for me is easy, but I don't yet how get the h.264 video and send to html5 without any plugin. Today I have a project in Nodejs with ffmpeg on the server side and jsmpeg(js) on the browser side, but the quality is bad and have high latency. Because this I think use WebRtc is improve the latency and quality.

**Comment by jlaine** [comment]
Specifically concerning "how to send RTSP to a browser" you can use the "webcam" example as a starting point:

https://github.com/aiortc/aiortc/tree/master/examples/webcam

As for how to architecture your application, I'm sorry but I'm unfortunately not going to be able to help you, I am unable to give out WebRTC tutorials. I suggest you read up on the subject or hire a freelancer.

**Comment by geogeorgiev** [comment]
Aiortc can be plugged in Django via Channels which provides async consumers used for websocket clients among other things.
