### ISSUE TITLE
How to send webcam stream to external server?

### ISSUE THREAD

**Issue by miguelwon** [aiortc/aiortc#204]
Hi,
Sorry, I'm no expert and was looking for a solution to send webcam stream from my raspberry pi cam to an external server. aiortc seems to do the job I'm after but I'm not able to adapt the shown examples to my needs. I'm able to run the example in my raspberry pi and opening the stream from the local address (quite slow but it runs). However, I don't understand from the example how I do the same task but connected to an external server in respect to my raspberry pi (3B). 
Any tips?
Btw, what will be the expected latency with such general set-up (raspberry pi 3b + camera recording at 30fps and streaming it to an external server)?
Thanks

**Comment by AlexVestin** [comment]
You can use the cli example using tcp-socket signaling to stream from the raspberry to an external server. Basically use the answer part for your server and the offer from the pi, you may need to modify the signaling code a bit. 

 The pi has a hard time getting 30fps with a resolution higher than 480p using software encoding. Aiortc transcodes video, so if you want to use a hardware accelerated camera (like the raspberry camera module) and want to skip re-encoding, you'll need to fork the project.

You can get less than a couple of seconds delay, obviously depending on your server as well.

**Comment by raghavendrajain** [comment]
@jlaine When I used digital ocean as external serve, the python webcam.py gives me the following error:

```
======== Running on http://0.0.0.0:8081 ========
(Press CTRL+C to quit)
Cannot open video device /dev/video0: No such file or directory
Error handling request
Traceback (most recent call last):
  File "/home/aiortc/examples/server/venv/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/aiortc/examples/server/venv/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "webcam.py", line 49, in offer
    player = MediaPlayer("/dev/video0", format="v4l2", options=options)
  File "/home/aiortc/examples/server/venv/lib/python3.6/site-packages/aiortc/contrib/media.py", line 221, in __init__
    self.__container = av.open(file=file, format=format, mode="r", options=options)
  File "av/container/core.pyx", line 226, in av.container.core.open
  File "av/container/core.pyx", line 148, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 180, in av.container.core.Container.err_check
  File "av/utils.pyx", line 107, in av.utils.err_check
av.AVError: [Errno 2] No such file or directory: '/dev/video0' (16: video4linux2,v4l2)
```

**Comment by jlaine** [comment]
@raghavendrajain Please refrain from hijacking unrelated issues. The message seems pretty clear, you don't seem to have a webcam on your server.

**Comment by raghavendrajain** [comment]
@jlaine I apologize! Will keep in mind.

**Comment by litgupta** [comment]
@AlexVestin you mentioned switching to tcp-socket based signaling. Currently, the example code uses 'copy-and-paste' based signaling. How can I switch to tcp-socket based one.

**Comment by jlaine** [comment]
I'm going to close this issue, as it's not clear what the "external server" is. If your "external server" supports things such as RTMP, your most efficient option is not going to involve WebRTC at all, you can do this entirely with a tool such as FFmpeg.
