### ISSUE TITLE
How to increase frame retrieving speed?

### ISSUE THREAD

**Issue by andriy-tsvikla** [aiortc/aiortc#205]
Hi. I am processing frames on backend in similar way as in example https://github.com/aiortc/aiortc/blob/master/examples/server/server.py 
Client webrtc video stream constraints, video only.
```
 { 
    width: 320,
    height: 240,
    frameRate: { max: 10 } 
}
```

`frame = await self.track.recv()` takes between 40-240 ms, 150 ms on average.
Is this the expected speed or should it run faster? How can i improve frame retrieving speed?
Is recv() call controlled by fps(called when frame received)?
Thanks.

**Comment by ianholing** [comment]
Hello @andriy-tsvikla I'm doing something similar and I got the same results. ¿Can you explain why did you close this issue? ¿Did you found any solution?
