### ISSUE TITLE
Sending results of frame processing via datachannel without delay?

### ISSUE THREAD

**Issue by andriy-tsvikla** [aiortc/aiortc#206]
Hi, i am processing video frame similar to https://github.com/aiortc/aiortc/blob/master/examples/server/server.py example.
And it works great, but i need to send processing result(Keypoints) so i try to call datachannel.send from VideoTransformTrack `async def recv(self)` function call. As example 
```
coro = self.send_callback(kp_dict) 
await asyncio.ensure_future(coro)  
```
 where send_callback is a constructor parameter     
```
@asyncio.coroutine
def send_callback(data):
        global datachannel
        if datachannel is not None:              
            serialized = json.dumps(data, cls=NumpyEncoder)
            datachannel.send(serialized).
```
But delay accumulates for datachannel data.
When i directly call `send_callback ` logic without coroutine, frame processing works much slower and problem with delay still exists.
Can you provide an example how this can be properly handled inside aiortc or i am doing something completely wrong?

**Comment by jlaine** [comment]
Would you mind stating how you solved your issue?

**Comment by andriy-tsvikla** [comment]
I switched to websockets

**Comment by raghavendrajain** [comment]
@andriy-tsvikla Please share the detailed solution and code, if you don't mind.
