### ISSUE TITLE
"python webcam.py --play-from rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov" stuck in ICE connection state is checking

### ISSUE THREAD

**Issue by jzucchetto** [aiortc/aiortc#207]
When I run the command python webcam.py --play-from rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov --verbose
the logs show:

INFO:aiohttp.access:172.17.0.1 [23/Sep/2019:16:04:03 +0000] "GET / HTTP/1.1" 200 809 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
INFO:aiohttp.access:172.17.0.1 [23/Sep/2019:16:04:03 +0000] "GET /client.js HTTP/1.1" 200 2210 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
DEBUG:ice:controlled - new -> closed
DEBUG:ice:Connection(0) protocol(0) connection_made(<_SelectorDatagramTransport fd=10 read=idle write=<idle, bufsize=0>>)
DEBUG:ice:Connection(0) protocol(0) > ('173.194.202.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\x7f\x99\x08\xbf\x1b@\x98\xb4\xe9\xcc\xd5\xb0')
DEBUG:ice:Connection(0) protocol(0) < ('173.194.202.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\x7f\x99\x08\xbf\x1b@\x98\xb4\xe9\xcc\xd5\xb0')
DEBUG:ice:controlled - new -> checking
INFO:aiohttp.access:172.17.0.1 [23/Sep/2019:16:04:04 +0000] "POST /offer HTTP/1.1" 200 2715 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
ICE connection state is checking

The video never plays. It seems like ICE connection gets stuck in checking state.

**Comment by jzucchetto** [comment]
I was able to fix the problem by passing in STUN server list in the server side and client side.
Below are the changes.

webcam.py
```python
    config = RTCConfiguration(iceServers=[
        RTCIceServer(urls=[
            'stun:stun.l.google.com:19302',
            'stun:stun1.l.google.com:19302',
            'stun:stun2.l.google.com:19302',
            'stun:stun3.l.google.com:19302',
            'stun:stun4.l.google.com:19302'
        ]),
    ])
    pc = RTCPeerConnection(configuration=config)
    pcs.add(pc)
```

client.js
```javascript
const servers = [
    { urls: [
        'stun:stun.l.google.com:19302',
        'stun:stun1.l.google.com:19302',
        'stun:stun2.l.google.com:19302',
        'stun:stun3.l.google.com:19302',
        'stun:stun4.l.google.com:19302'
    ]}
];

var pc = new RTCPeerConnection({
    sdpSemantics: 'unified-plan',
    iceServers: servers
});
```

**Comment by jlaine** [comment]
Thanks for taking the time to give your solution!

I have updated the webcam example to add a "Use STUN" checkbox. On the server side no changes should be necessary as the default config already uses Google's STUN server. Can you confirm it works for you?
