### ISSUE TITLE
No media appears on remote server

### ISSUE THREAD

**Issue by raghavendrajain** [aiortc/aiortc#209]
Hi, 
I want to test `https://github.com/aiortc/aiortc/tree/master/examples/server` on remote server, so I installed everything on `digital ocean cloud.` Now, after running `python server.py` the web page is displayed as expected, but no audio or video is working. Whats going wrong? 
@jlaine  

It gives an error:
```
Uncaught TypeError: Cannot read property 'getUserMedia' of undefined
    at start (client.js:169)
    at HTMLButtonElement.onclick ((index):78)
```

I found the solution [here]( https://github.com/leon-ai/leon/issues/97)

> Chrome disables features such as `getUserMedia` when it comes from an
> unsecured origin. `http://localhost` is considered as a secure origin by
> default, however if you use an origin that does not have an SSL/TLS
> certificate then Chrome will consider the origin as unsecured and
> disable `getUserMedia`.
> 
> What you can do is:
> 
> 1. Setup an SSL/TLS certificate. 
> 2. Or go to `chrome://flags`, search for the
> flag `unsafely-treat-insecure-origin-as-secure`, enter the origin you
> want to treat as secure such as `http://{YOUR HOST IP}:1337`, enable the
> feature and relaunch the browser. Let me know if that works.

**Comment by avaseghi** [comment]
I resolved this issue with mine but I'm still not seeing the video displayed in the browser. Can anyone tell me why??

**Comment by jlaine** [comment]
Right, this is why this example supports using TLS:

```
  --cert-file CERT_FILE
                        SSL certificate file (for HTTPS)
  --key-file KEY_FILE   SSL key file (for HTTPS)
```
