### ISSUE TITLE
Add ability to send external video stream.

### ISSUE THREAD

**Issue by abhiTronix** [aiortc/aiortc#210]
Hello, thanks for this awesome library,

I was wondering if it is possible to send external OpenCV video stream in [`addTrack()` function](https://github.com/aiortc/aiortc/blob/28cf22c2a82136784cc8ece6ca82143afdba5c86/aiortc/rtcpeerconnection.py#L331) instead of default `MediaPlayer` stream? I think that we can add additional `kind` parameter to this function definition, to override this `kind`  parameter manually and use OpenCV video stream as track. Please let me know if this possible, it would be really helpful for many applications.

**Comment by jlaine** [comment]
My experience with OpenCV for video handling is that it's not a good match for WebRTC: it lacks any notion of timing, so I have no plans for this. Processing individual frames works fine, but OpenCV's support for video input / output just isn't suited for the job.

**Comment by abhiTronix** [comment]
> OpenCV for video handling is that it's not a good match for WebRTC: it lacks any notion of timing, so I have no plans for this. 

@jlaine I really don't need OpenCV for video handling, I need to access the `aiortc`pipeline so that my own powerful multithreaded python video processing application called **[`vidgear`](https://github.com/abhiTronix/vidgear)** can work in conjunction with `aiortc` itself. In short, I'm using multi-threading to optimizing timing instead of asyncio.

 I meant to say that why don't we give the user the choice, to chose the stream they want to work with?, whether its the `MediaPlayer` stream provided by `aiortc` or a third party stream. If you don't want to provide support for the third party streams bugs you can clearly mention to the user to use this at their own risk. 

I really want optimized webrtc support in my **[`vidgear`](https://github.com/abhiTronix/vidgear)** application and thereby see `aiortc` as the perfect match, rather than implementing everything from scratch. Is there's a workaround you can think of ? Thank you.

**Comment by jlaine** [comment]
No-one is forcing you to use `MediaPlayer`, you can definitely implement your own media source, as illustrated here:

https://github.com/aiortc/aiortc/blob/28cf22c2a82136784cc8ece6ca82143afdba5c86/examples/videostream-cli/cli.py#L20

You need to subclass `MediaStreamTrack` and provide a `recv` method which returns your video frames at the right time.
