### ISSUE TITLE
Any plans to implement the iceRestart flag?

### ISSUE THREAD

**Issue by jjmaldonis** [aiortc/aiortc#211]
WebRTC has an `iceRestart` flag that allows WebRTC sessions to reconnect. What are the chances that there are any plans to add that?

Here are the WebRTC docs from Mozilla: https://developer.mozilla.org/en-US/docs/Web/API/RTCOfferOptions/iceRestart

**Comment by jlaine** [comment]
The chances are good if you submit a PR :)

I haven't had a chance to look at ICE restarts myself.

**Comment by jjmaldonis** [comment]
Unfortunately I doubt I'll be able to work on a PR. Is this something you're planning to put on your radar?

**Comment by W3AXL** [comment]
This would also be useful for my application, where the RTC connection can sometimes be running for days at a time. Currently the user must manually reconnect the stream when it fails.

I may look into the specifics of the `restartIce` function but I'm by no means an amazing python developer and I make no promises.

**Comment by xandfury** [comment]
I second this. Would really love this feature 🙂

**Comment by jlaine** [comment]
Adding support for ice restarts is potentially going to involve both aioice and aiortc. Would you have any pointers to specs on how this is supposed to work?
