### ISSUE TITLE
Implementing Data Channels

### ISSUE THREAD

**Issue by kumar88kanishk** [aiortc/aiortc#212]
Hi Author && Community,

I am fairly new to Python and wanted to implement airotc with face recognition (https://github.com/ageitgey/face_recognition),

Can anyone demonstrate how to create data channels so that whenever i see a known face i can update my channel with a counter of 1.
I have implemented channels from examples/server/server.py also the recognition algo seems to work like a charm with your ecosystem. 
Can you please help in decoupling the code from offer function,cuz as far as i understand i can see the offer function creates a channel in  examples/server/server.py, but i want to update the channel with a message outside the offer function
What should be done. Code is pasted below for your reference
 `import argparse
import asyncio
import json
import logging
import os
import platform
import ssl
import time
from aiohttp import web
from av import VideoFrame
from aiortc import RTCPeerConnection, RTCSessionDescription, VideoStreamTrack
from aiortc.contrib.media import MediaPlayer
import math
from sklearn import neighbors
import os.path
import pickle
from PIL import Image, ImageDraw
import face_recognition
from face_recognition.face_recognition_cli import image_files_in_folder
import cv2
ROOT = os.path.dirname(__file__)
pc = RTCPeerConnection()

class FacialRecogTransform(VideoStreamTrack):
    def __init__(self, track):
        super().__init__()  # don't forget this!
        self.track = track

    async def recv(self):
        frame = await self.track.recv()
        img = frame.to_ndarray(format="bgr24")
        knn_model_loaded = load_model(model_path="trained_knn_model.clf")
       
        # img = cv2.rectangle(img, (10, 10), (100, 100), (0, 0, 255), 2)
        # img = cv2.putText(img, "Dee", (100,50), cv2.FONT_HERSHEY_SIMPLEX, 2, 255)

        # Resize frame of video to 1/4 size for faster face recognition processing
        small_frame = cv2.resize(img, (0, 0), fx=0.25, fy=0.25)
        # Convert the image from BGR color (which OpenCV uses) to RGB color (which face_recognition uses)
        rgb_small_frame = small_frame[:, :, ::-1]
        # Find all people in the image using a trained classifier model
        # Note: You can pass in either a classifier file name or a classifier model instance
        predictions = predict(X_img_path=rgb_small_frame, knn_clf = knn_model_loaded)
             
        for name, (top, right, bottom, left) in predictions:
            
            # Scale back up face locations since the frame we detected in was scaled to 1/4 size
            top *= 4
            right *= 4
            bottom *= 4
            left *= 4
             # Draw a box around the face
            cv2.rectangle(img, (left, top), (right, bottom), (0, 0, 255), 2)

            # Draw a label with a name below the face
            cv2.rectangle(img, (left, bottom - 35), (right, bottom), (0, 0, 255), cv2.FILLED)
            font = cv2.FONT_HERSHEY_DUPLEX
            cv2.putText(img, name, (left + 6, bottom - 6), font, 1.0, (255, 255, 255), 1)
            #Display the resulting image

            #update analytics channel
            respondToAnalyticsChannel()

        # rebuild a VideoFrame, preserving timing information
        new_frame = VideoFrame.from_ndarray(img, format="bgr24")
        new_frame.pts = frame.pts
        new_frame.time_base = frame.time_base
        return new_frame

def predict(X_img_path, knn_clf=None, model_path=None, distance_threshold=0.6, number_of_times_to_upsample = 2):
    
    # Load image file and find face locations
    # X_img = face_recognition.load_image_file(X_img_path)
    X_face_locations = face_recognition.face_locations(X_img_path, number_of_times_to_upsample=number_of_times_to_upsample)
    # If no faces are found in the image, return an empty result.
    if len(X_face_locations) == 0:
        return []

    # Find encodings for faces in the test iamge
    faces_encodings = face_recognition.face_encodings(X_img_path, known_face_locations=X_face_locations)

    # Use the KNN model to find the best matches for the test face
    closest_distances = knn_clf.kneighbors(faces_encodings, n_neighbors=1)
    are_matches = [closest_distances[0][i][0] <= distance_threshold for i in range(len(X_face_locations))]

    # Predict classes and remove classifications that aren't within the threshold
    return [(pred, loc) if rec else ("unknown", loc) for pred, loc, rec in zip(knn_clf.predict(faces_encodings), X_face_locations, are_matches)]

def load_model(model_path=None):
    if model_path is None:
        raise Exception("Must supply knn classifier either thourgh knn_clf or model_path")
    else:
        with open(model_path, 'rb') as f:
            return pickle.load(f)

async def index(request):
    content = open(os.path.join(ROOT, "index.html"), "r").read()
    return web.Response(content_type="text/html", text=content)

async def javascript(request):
    content = open(os.path.join(ROOT, "client.js"), "r").read()
    return web.Response(content_type="application/javascript", text=content)

def respondToAnalyticsChannel():
    print('in respondToAnalyticsChannel')
    @pc.on("datachannel")
    def on_datachannel(channel):
        print("channel", channel)
        @channel.on("message")
        def on_message(message):
            data = json.loads(message)
            if 'known' not in data:
                raise ValueError("Known key missing")
            if 'unknown' not in data:
                raise ValueError("Unknown key missing")
            sending_data = json.dumps({"known": data["known"]+1, "unknown": data["unknown"]+1})
            channel.send(sending_data)

async def offer(request):
    params = await request.json()
    offer = RTCSessionDescription(sdp=params["sdp"], type=params["type"])
    pcs.add(pc)
    print("Created for %s", request.remote)
    respondToAnalyticsChannel()
    @pc.on("iceconnectionstatechange")
    async def on_iceconnectionstatechange():
        print("ICE connection state is %s" % pc.iceConnectionState)
        if pc.iceConnectionState == "failed":
            await pc.close()
            pcs.discard(pc)

    # open media source
    if args.play_from:
        player = MediaPlayer(args.play_from)
    else:
        options = {"framerate": "30", "video_size": "640x480"}
        if platform.system() == "Darwin":
            player = MediaPlayer("default:none", format="avfoundation", options=options)
        else:
            player = MediaPlayer("/dev/video0", format="v4l2", options=options)

    await pc.setRemoteDescription(offer)
    for t in pc.getTransceivers():
        if t.kind == "audio" and player.audio:
            pc.addTrack(player.audio)
        elif t.kind == "video" and player.video:
            tranform_video = FacialRecogTransform(
                player.video
            )
            pc.addTrack(tranform_video)

    answer = await pc.createAnswer()
    await pc.setLocalDescription(answer)

    return web.Response(
        content_type="application/json",
        text=json.dumps(
            {"sdp": pc.localDescription.sdp, "type": pc.localDescription.type}
        ),
    )

pcs = set()

async def on_shutdown(app):
    # close peer connections
    coros = [pc.close() for pc in pcs]
    await asyncio.gather(*coros)
    pcs.clear()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="WebRTC webcam demo")
    parser.add_argument("--cert-file", help="SSL certificate file (for HTTPS)")
    parser.add_argument("--key-file", help="SSL key file (for HTTPS)")
    parser.add_argument("--play-from", help="Read the media from a file and sent it."),
    parser.add_argument(
        "--port", type=int, default=8080, help="Port for HTTP server (default: 8080)"
    )
    parser.add_argument("--verbose", "-v", action="count")
    args = parser.parse_args()

    if args.verbose:
        logging.basicConfig(level=logging.DEBUG)

    if args.cert_file:
        ssl_context = ssl.SSLContext()
        ssl_context.load_cert_chain(args.cert_file, args.key_file)
    else:
        ssl_context = None

    app = web.Application()
    app.on_shutdown.append(on_shutdown)
    app.router.add_get("/", index)
    app.router.add_get("/client.js", javascript)
    app.router.add_post("/offer", offer)
    web.run_app(app, port=args.port, ssl_context=ssl_context)`

**Comment by jlaine** [comment]
I'm sorry but I cannot process raw code dumps like this. Can you please boil down your question to something more focused?

**Comment by jlaine** [comment]
No response from submitter, closing.
