### ISSUE TITLE
Can`t get microphone audio stream 

### ISSUE THREAD

**Issue by Glunky** [aiortc/aiortc#213]
Im sorry that i ask this question here, but i didnt find answer to my problem anywhere.
If we use `av.open("file.mp4")` we get audio and video streams. But string `av.open("/dev/video0")` returns only video stream. Is there any way to capture audio stream from webcam? I want to try send an audio and video streams from my webcam in videostream-cli example. Im sorry if question might be seems simple or dumb)

**Comment by jlaine** [comment]
Hi! The question definitely isn't dumb. You should be able to capture audio using `av.open("default", format="pulse")` for instance, see the following for more details on how to specify the device:

https://ffmpeg.org/ffmpeg-devices.html

For use with aiortc, this would be:

`player = MediaPlayer("default", format="pulse")`

This does mean you will need to distinct `MediaPlayer` instances, one to capture audio, one to capture video.

**Comment by Glunky** [comment]
It works, thanks!!)
But i have another issue. May be you can help?
I separated MediaPlayer on two instance - `video_player` and `audio_player`
```
    if args.play_from:
        audio_player = MediaPlayer("default", format="pulse")
        video_player = MediaPlayer("/dev/video0")
    else:
        audio_player = None
        video_player = None
```
To test that all work fine i change `__run_track(track, context) ` function in media.py like bellow:
   ```
 async def __run_track(self, track, context):
        if track.kind == "audio":
            RATE = 44100
            CHUNK = 1024

            p = pyaudio.PyAudio()
            audio = p.open(format=pyaudio.paInt16, channels=2, rate=RATE, output=True, frames_per_buffer=CHUNK)
        while True:
            try:
                frame = await track.recv()
                if track.kind == "audio":
                    record = frame.to_ndarray().ravel().tobytes()
                    audio.write(record, CHUNK)

                if track.kind == "video":
                    cv2.imshow("window", frame.to_ndarray())
                    cv2.waitKey(1)
            except MediaStreamError:
                return
            for packet in context.stream.encode(frame):
                pass
                #self.__container.mux(packet)
```
When i tested it singly like `audio_player = None` and `--record-to file.mp4` on answer side and conversely with `video_player = None` and `--record-to file.wav` its work fine, i saw webcam window and heard sound. But when i tried to combine them (players doesnt None) video became blurry and there was only few audio frames which then was interrupted and no further audio frames was received.
I thought that it may be because of codecs. I changed `addTrack(track)` function that it always assign mp3 codec to all audio files and tested it separately from video (--record-to file.mp3) . And i got same issue when audio frames interrupted after few seconds. I understood that audio works with pcm_s16le codec (.wav extension). So i changed function that it assign that codec always for all audio files. When i ran combine version i got `ValueError: 'mp4' format does not support 'pcm_s16le' codec` in `stream = self.__container.add_stream(codec_name)` string. I opened that function and saw that it doesnt have realization and it restore from docs and so i cant see and change it for me. What it might be with interrupted audio frames and blurry video? Am i do something wrong?

**Comment by Glunky** [comment]
Well, only ffmpeg do this work well, other libraries is not good solution for this issue. I record audio frames into one audio file and then just play it. But i get delay and cant synchronize audio and video. Will try to fix it.

**Comment by jlaine** [comment]
Let's keep the issue focused: as the original issue is fixed I'm closing this issue, feel free to open another one if you have another problem.

**Comment by yaguangtang** [comment]
> Well, only ffmpeg do this work well, other libraries are not good solution for this issue. I record audio frames into one audio file and then just play it. But i have a delay and cant synchronize audio and video. Looks like thataudio frames begin to be captured when we setting up sdp packet, but not when connection established. Will try to fix it.

can you please share how you play audio file at same  time it's being write by aiortc,thanks

**Comment by Glunky** [comment]
> > Well, only ffmpeg do this work well, other libraries are not good solution for this issue. I record audio frames into one audio file and then just play it. But i have a delay and cant synchronize audio and video. Looks like thataudio frames begin to be captured when we setting up sdp packet, but not when connection established. Will try to fix it.
> 
> can you please share how you play audio file at same time it's being write by aiortc,thanks

Sorry for delay, didnt see notification.
Yes, here is how i did it (only playing, without writing frames into file)
```
 async def __run_track(self, track, context):
        def playAudio():
            os.system("ffplay /home/ilya/Downloads/aiortc-master/examples/videostream-cli/a.wav")

        while True:
            if os.path.isfile("./a.wav") and not self.audio_is_playing:
                p1 = Process(target=playAudio)
                p1.start()
                self.audio_is_playing = True
            try:
                frame = await track.recv()
            except MediaStreamError:
                return
            for packet in context.stream.encode(frame):
                self.__container.mux(packet)
```
This part in media.py module in MediaRecorder class. So the main idea that you run another process using os.system("ffplay path_your_wav_file.wav")

**Comment by learncodingforweb** [comment]
mic_track = MediaPlayer("default", format="pulse")
pc.addTrack(mic_track.audio)
**exit from code no container format 'pulse'**

How can i stream audio from mic ? Anyone able to so, please update

**Comment by testpassword** [comment]
> mic_track = MediaPlayer("default", format="pulse") pc.addTrack(mic_track.audio) **exit from code no container format 'pulse'**
> 
> How can i stream audio from mic ? Anyone able to so, please update

I don't know how, but this help me:

```
apt install libavdevice-dev
pip3 uninstall av
pip3 install av --no-binary av
```
