### ISSUE TITLE
tweak to upload existing build wheels with twine

### ISSUE THREAD

**Issue by ezavesky** [aiortc/aiortc#214]
Ultimately supporting #120, would it be possible to tweak your travis scripts to upload the compiled wheel to pypi instead of just the source package?  I can get down to almost no build (e.g. not installing gcc or others) by using a conda docker image and then installing `ffmpeg`, `av`, and `netifaces` through one of their repos (happy to share this simple formula as well), but without a compiled `aiortc` wheel, it's still a bit of pain.

I use a different CI/CD, but here are the few changes that appear to be required for travis.

1. Looking at this line where travis scripts are [building the library](https://github.com/aiortc/aiortc/blob/master/.travis/script#L10) ...
2. Update to include [bdist_wheel](https://docs.travis-ci.com/user/deployment/pypi/#uploading-different-distributions) next to "sdist" in the above file/line
3. I don't think so, but you may need to duplicate [this environment](https://github.com/aiortc/aiortc/blob/master/.travis.yml#L39) either to include this as another build (e.g. if you want to keep source and binary separate).

While I don't have the full travis environment to test myself, I'm happy to experiment with changes for this issue if you need it.

**Comment by jlaine** [comment]
Providing proper binary wheels isn't just a matter of throwing a binary wheel built on a random OS onto pypi, you need to ensure it's built in a "standardised" environment.

I looked into providing binary wheel using `cibuildwheel` (as I do with `pylibsrtp`) but this was impossible for `manylinux1` as it relies on Linux versions so old that I couldn't compile libvpx.

The situation may change with `manylinux2010`, but AFAICT cibuildwheel doesn't yet support it:

https://github.com/joerick/cibuildwheel/issues/65

**Comment by ezavesky** [comment]
Thanks, that's a really good point.  Stopping short of making a docker image instead of a package wheel, I agree that you're right about a generic wheel.  In fact, because of the dependencies on things like `av`, I suspect that will be nearly impossible in a generic ecosystem.  

Perhaps the only recourse is really to tackle it head-on and go with a semi-closed ecosystem (e.g. just a few specific platforms to go with and reasonable "beyond python" packaging) as in conda and #120, as characterized in [this blog post](https://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions/#Myth-#6:-Now-that-pip-uses-wheels,-conda-is-no-longer-necessary).   Specifically looking at conda and what it would take to get there, the ["feedstock" for av builds](https://github.com/conda-forge/av-feedstock) is certainly not trivial.

Thanks for the time in the reply and analysis, but perhaps we should indeed wait for `cbuildwheel` or a volunteer for the conda port.  Until then, thanks for helping to keep this great library going as a viable alternative to two or three layers of java and others for real-time WebRTC servers.

**Comment by filips123** [comment]
You should really provide pre-built wheels on PyPI.

Building on Windows requires VS Build Tools which are very heavy and can take some time. Pre-built wheels would make installation easier and faster.

You should build and release wheels automatically with CI. Most CI providers support this, and there are also already systems that can automate building for multiple platforms.

**Comment by jlaine** [comment]
Compiling aiortc itself takes very little time. The bulk of the compile time comes from compiling `PyAV`. You are welcome to contribute binary wheels for PyAV to that project.

**Comment by jlaine** [comment]
@ezavesky @filips123 I've taken a first shot at producing binary wheels in this PR: #319 

You can find the artifacts here:

https://github.com/aiortc/aiortc/actions/runs/51345293

NOTE: these are wheels for aiortc itself, eliminating the need to have opus / vpx. PyAV is a different matter, which I am pursuing upstream (it's more complicated, because we need to decide what we include in the FFmpeg build)

**Comment by ezavesky** [comment]
👍 
This may not have all of the dependencies that PyAV provides, but another package, [moviepy](https://github.com/Zulko/moviepy/blob/master/setup.py#L68) extensively uses ffmpeg for content editing through a single dependency library called [imageio-ffmpeg](https://github.com/imageio/imageio-ffmpeg).

**Comment by jlaine** [comment]
imageio-ffmpeg is completely unrelated, that's just a wrapper around the FFmpeg executable. PyAV has a totally different goal: it's a binding into the FFmpeg libraries, allowing direct access to frames, etc..

**Comment by jlaine** [comment]
PyAV 8.0.0 is now available in the form of binary wheels on PyPI, and so is aiortc 0.9.28!
