### ISSUE TITLE
Installing on Raspberry Pi + Bug on Webcam example from other computer

### ISSUE THREAD

**Issue by THLCX** [aiortc/aiortc#216]
Hello

I'm trying to use Aiortc on my Rpi, but there is an error while trying to pip install aiortc :

> pkg-config returned flags we don't understand: -pthread -pthread

Same when I to pip install av

What can I do ? I can't find the specific install part for Rpi.

Also, the webcam example does not work when accessing server using an other computer's browser (it loop on ICE checking...) Is it a bug ?

**Comment by THLCX** [comment]
The solution was to compile ffmpeg from source include --enable-shared and link it.
Anyway, still no clue to understand why the webcam example does not work from an other computer ?

**Comment by jlaine** [comment]
ICE is very dependent on your network configuration, could you give me some more information about your exact setup: are the Pi and the computer on the same network, etc.. ?

**Comment by wanjinchang** [comment]
> The solution was to compile ffmpeg from source include --enable-shared and link it.
> Anyway, still no clue to understand why the webcam example does not work from an other computer ?

I also meet this problem，could you show how to link ffmpeg？？Thanks
