### ISSUE TITLE
H264 bytes array decode to av.VideoFrame

### ISSUE THREAD

**Issue by DiKey98** [aiortc/aiortc#217]
Hi! I find your framework very good. But I have question. How to convert h264 encoded bytes array (frames from my IP camera Axis) to decoded av.VideoFrame? Can you get example for it? Thanks.

**Comment by jlaine** [comment]
I unfortunately don't think `PyAV` currently supports parsing raw frames, to my knowledge it is only able to read frames which are stored in a container.
