### ISSUE TITLE
Not work example with videocamera

### ISSUE THREAD

**Issue by k1udde** [aiortc/aiortc#218]
Hello, i'm trying to use the webcam example. I change the example to stream a IP camera  
player = MediaPlayer(
        'rtsp://10.1.0.13/axis-media/media.amp?videocodec=h264&resolution=640x480',
        format='rtsp',
        options={
            "framerate": "30",
            "video_size": "600x480"
        }
But  after a couple of minutes an error appears -"no frame", and  the broadcast stops.Is there a way to fix this?

**Comment by jlaine** [comment]
RTSP support is provided by ffmpeg, I don't really have any insights here as I cannot access your server.

Are you able to play the RTSP stream using vlc?

By the way I don't think the `options` here are necessary.

**Comment by k1udde** [comment]
vlc play the stream without  stopping.

**Comment by jlaine** [comment]
I'm going to close this issue unless I have some way to reproduce and investigate the issue..
