### ISSUE TITLE
Chrome IOS, STUN

### ISSUE THREAD

**Issue by richlegrand** [aiortc/aiortc#219]
Hello, 
I'm able to run the webcam example and see it in Chrome Windows on another machine, local network, but when I bring it up on Chrome IOS, local network, I need to enable the STUN server.  (it works great when I do though.)  

Is this expected behavior?  I was expecting that running within the same network wouldn't require STUN.  Maybe I'm not understanding the use of STUN.  

thanks!

**Comment by richlegrand** [comment]
For my application I would like to be able to stream video locally when there is no internet connection.  This doesn't work from IOS Chrome or Safari because the STUN server is required (and hence the internet connection is required).  

At the root of the issue is in the sdp field of the offer.  From a desktop without STUN server (for example) I see this candidate:
'a=candidate:430735571 1 udp 2113937151 192.168.1.102 45590 typ host '

From IOS without a stun server, this candidates aren't present and the ICE connection is never made.  But with a stun server this candidate appears and is used:
 'a=candidate:842163049 1 udp 1677729535 66.90.166.74 49661 typ srflx raddr '

Is there a way I can work around this so I don't need an internet connection to connect from IOS to a local server?  If a workaround is found, I'm guessing it would be a useful addition to the code.  I'm more than happy to help find a solution... any hints would help :)

**Comment by lgrahl** [comment]
Short-term: No.

Mid-term: You can implement resolving mDNS addresses in aiortc which will likely be ported to iOS as well, ref #187.

Basically, it boils down to sending DNS requests to `224.0.0.251:5353` or `[ff02::fb]:5353` when a `*.local` candidate is being processed. See also https://github.com/rawrtc/rawrtc/pull/147 (much more convoluted because C).

**Comment by richlegrand** [comment]
So ice.py needs to do an mDNS lookup when it sees a .local address.  This seems like it shouldn't be too difficult.  I know very very little in this realm, so if there is something else I should know -- please tell me :)

**Comment by jlaine** [comment]
If you want to support mDNS, the first round of changes should be in `aioice` since that is where the ICE stack is implemented. The difficulty is that it probably involves a backwards-incompatible change to the API, see:

https://github.com/aiortc/aioice/issues/14

**Comment by richlegrand** [comment]
If anyone wants to help us implement along with other features, please send me a note (charmedlabs.com  (rich at))  This would be a paid gig.  Thanks!   

(Please see recent comments on  [https://github.com/aiortc/aioice/issues/14](14))

**Comment by richlegrand** [comment]
whoops -- I meant this link [](https://github.com/aiortc/aioice/issues/14)

**Comment by richlegrand** [comment]
whoops again -- [https://github.com/aiortc/aioice/issues/14](14)

**Comment by richlegrand** [comment]
OK, I see what's going on here -- the system is inserting the wrong link.  
This link: 
https://github.com/aiortc/aioice/issues/14
feeling pretty silly here...

**Comment by jlaine** [comment]
I'm closing this issue since mDNS candidates are now supported!
