### ISSUE TITLE
Mulitple cameras and broadcast

### ISSUE THREAD

**Issue by AntoninRousset** [aiortc/aiortc#220]
First of all thank you for the amazing work! I could easily get a video streaming of my webcams with very small latency.
Tell me if I've understood well, to stream multiple videos (cameras) to the same client, we cannot add videos (called `track`?) to a connections and we should rather open a connection for each video tag in our HTML. Looking at the webcam example I implemented it creating a route for every camera and opening a new pc each time it is called:
```python
@routes.post('/camera{cam_n}')
async def camera(request):
    cam_n = int(request.match_info['cam_n'])
    params = await request.json()
    offer = RTCSessionDescription(sdp=params["sdp"], type=params["type"])

    pc = RTCPeerConnection()
    pcs.add(pc)
```
I needed to tweak the javascript as well, because the ICE gathering was somehow colliding.
So far so good, how can I stream the same camera to multiple clients? I can open a new MediaPlayer for each, but they sure cannot share the same /dev/vide0. So I tried to share the same MediaPlayer for differents (or the same) clients, but it says the `track already has a sender`.
```python
    if cam_n not in players:
        path = cams[cam_n]['path']
        options = {"framerate": "30", "video_size": "640x480"}
        players[cam_n] = MediaPlayer(path, format="v4l2", options=options)
    player = players[cam_n]
```
I am really stuck with that /:

**Comment by caboteria** [comment]
I'm also looking to implement a webcam server that can survive multiple connects and disconnects.  Here's what I'm leaning towards: a Player that starts when the server does, and whose worker thread can publish to a collection of queues.  When a client connects, a Track is created and added to the Player's collection of queues and when the client disconnects that Track is removed.

Does this seem reasonable to you?

**Comment by AntoninRousset** [comment]
I was able to broadcast a camera to multiple clients (I tried with three) as follow:
When a client connects by posting an offer on the route _/camera_ its offer is send to a camera object:
```Python
from aiortc import RTCSessionDescription
@routes.post('/camera')
async def camera(request):
    params = await request.json()
    offer = RTCSessionDescription(sdp=params['sdp'], type=params['type'])
    answer = await camera.handle_offer(offer)
    return web.Response(content_type='application/json', text=json.dumps(answer))
```
that handle the offer:
```Python
# Camera object
async def handle_offer(self, offer):
        pc = self.create_peer_connection() # basically RTCPeerConnection()
        self.pcs.add(pc)
        await pc.setRemoteDescription(offer)
        for t in pc.getTransceivers():
            pc.addTrack(self.player.video)
        answer = await pc.createAnswer()
        await pc.setLocalDescription(answer)
        return {'sdp' : pc.localDescription.sdp, 'type' : pc.localDescription.type}
```
However if all the clients disconnect I get after some time:
> Some buffers are still owned by the caller on close.

And the camera stop working. But we are close to getting something...
Concerning your implementation, I don't really get how creating multiple threads will solve the problem. Can you elaborate a bit? Especially about the track you create; do you create a peer connection for each client? I think this last point is mandatory, isn't it?

**Comment by caboteria** [comment]
The current implementation has a worker thread that publishes to a single queue, and when the peer channel disconnects the thread is shut down.  I was thinking that the thread would be persistent and could publish to multiple queues/tracks that could come and go.

I built a small experiment on https://github.com/caboteria/aiortc/tree/persistent-webcam - in the examples/persistentwebcam directory the persistentwebcam PlayerStreamTrack stop() method doesn't stop the player.  It works for a single client, i.e., you can connect and disconnect from a browser multiple times and the server stays running.  I haven't tested if it supports multiple clients yet, probably not.

**Comment by AntoninRousset** [comment]
Okay, I ended adding these two lines on the top of my file:
```Python
from aiortc.contrib.media import MediaStreamTrack, MediaPlayer
MediaStreamTrack.stop = lambda: None
```
which should prevent aiortc from closing the worker.
I can tell you this works with multiple clients on multiple devices on local network.
If it does work for you, try to change the host, I had trouble with localhost and had to change to 0.0.0.0 or the complete local ip.
You can find my implementation here: [https://github.com/AntoninRousset/escaperoom/blob/master/escaperoom/misc.py](url)
