### ISSUE TITLE
Can not understand the code(( Help me pls

### ISSUE THREAD

**Issue by Glunky** [aiortc/aiortc#221]
Hi!
Please, can you explain me one moment? In videostream example we send offer sdp to answer side and then send answer sdp to the offer. Ok, in code `obj = await signaling.receive()` (in cli.py) we are waiting for getting offer sdp in obj variable, but wich variable getting answer sdp? I cant find this piece of code(( 
I just want create own mini server to not copy paste it every time, but connect automatically by sending answer and offer sdp to both sides.

**Comment by Glunky** [comment]
Is it obj too?)

**Comment by Glunky** [comment]
is it obj too?)

**Comment by lgrahl** [comment]
https://github.com/aiortc/aiortc/blob/master/aiortc/contrib/signaling.py

**Comment by Glunky** [comment]
Here only forming, not assignment

**Comment by jlaine** [comment]
Instead of inventing another signaling mechanism have you looked at the ones provided with the `aiortc` examples? There is support for signaling over a TCP socket, a UNIX socket and even appr.tc.

To list the available options:

```bash
 python examples/videostream-cli/cli.py -h
```

**Comment by Glunky** [comment]
Ok, will try this solution)
