### ISSUE TITLE
P2P DTLS client behavior on both endpoints

### ISSUE THREAD

**Issue by joafalves** [aiortc/aiortc#223]
Hello,

I'm trying to establish a connection between two clients using aiortc (both using this technology) using a middle server endpoint (gateway). I'm running into an issue that the originator is getting the server DTLS role every time, even when the answer has "setup=passive". This approach seems to work using the Web Browsers implementation (chrome, firefox, etc).

In my scenario, I want to make both the originator and the terminating-end to be active as DTLS clients (my gateway will receive DTLS handshakes from both, but does not initiate).

Do you have any clues how can I setup the **originator** to behave as a  **DTLS client** as well? 

Many thanks!

**Comment by joafalves** [comment]
FYI, as a workaround I've changed the `RTCDtlsTransport` `start` to always have the "client" role.

**Comment by jlaine** [comment]
You may have a valid point here, would you mind digging into the code?

**Comment by jlaine** [comment]
This should be fixed by 18cd51a6bca364167d1bbf201197efd02c63cfee

If that is not the case feel free to re-open the issue.
