### ISSUE TITLE
replaceable front-end and encoder

### ISSUE THREAD

**Issue by richlegrand** [aiortc/aiortc#226]
Hi y'all, I'm working with an embedded system that has a non-standard way of getting frames from a camera and hardware-accelerated encoders/decoders.

For using my own camera interface, I created my own modified copy of media.py and used that, which wasn't too difficult.  For using my own accelerated encoder things got messier (I applied some runtime patches to rtcrtpsender.py.)

Have you guys given some thought to being able to supply a custom image source and encoder?

thanks!

**Comment by jlaine** [comment]
I personnally have no plan for this. There have been a couple of PRs which stated they were going to implement this, but none got to a state where they were mergeable. You're welcome to submit a PR, provided it comes with full unit tests.
