### ISSUE TITLE
Access to local ice candidates

### ISSUE THREAD

**Issue by mayfield** [aiortc/aiortc#227]
I'm trying to figure out the right way to share ice candidates with my peers but can't seem to find a public API for doing so.  

It seems I could monitor the icegathers of the peerconnection for gathering state changes and then share the current set of local candidates from that instance, but access to this stuff seems to be considered private (leading dunder grammer).

In JS land I use the peer connection's `icecandiate` event for this and then the gathering state change event to flush a buffered collection of icecandidates so my signalling is a little smoother.  It would be great if this was possible in aiortc too.

**Comment by jlaine** [comment]
`aioice`, the library which `aiortc` uses for ICE does not trickle ICE candidates: you get all the candidates in one go. As such once you have called `setLocalDescription()` for your offer or answer, all your ICE candidates are listed in `pc.localDescription`.

**Comment by HSamiul** [comment]
Hi @jlaine,

I'm writing my own small server using aiortc and I can see a list of candidates in my `pc.localDescription`, as you pointed out. As `pc.localDescription.sdp` is a string, is there any reliable way to extract the candidates from there into a list of `RTCIceCandidate`? I can of course use string parsing, but I feel like there should be a tool in the API for this that I'm just not aware of. Thanks!

**Comment by HSamiul** [comment]
If anyone is facing a similar issue that my comment described:

Extracting the candidates from `pc.localDescription.sdp` is not necessary to establish a peer-peer connection.

When each peer sends their offer/answer to each other, their list of candidates is included in the offer/answer. The candidate exchange happens for you.

I think this is what jlaine already said in his above reply, it just didn't click with me immediately.
