### ISSUE TITLE
Problem when running setup.py

### ISSUE THREAD

**Issue by spectralcodec** [aiortc/aiortc#229]
Hello, I am trying to run **python3 setup.py** on Linux Mint 19.2 and receive this error message:

WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
ERROR: Failed to build one or more wheels
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/setuptools/installer.py", line 119, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpyrmyziia', '--quiet', 'pycparser']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    install_requires=install_requires,
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 721, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 777, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/installer.py", line 121, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpyrmyziia', '--quiet', 'pycparser']' returned non-zero exit status 1.

**Comment by jlaine** [comment]
The binary wheels for `pylibsrtp` and some other dependencies are now built for `manylinux2010`, but you need a modern `pip` to use them. Your best bet is to update your `pip` version using `pip install -U pip`.

**Comment by spectralcodec** [comment]
Thank you, now I receive this error when I run **python3 setup.py** :

WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-dhwtxp0f/pycparser/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-dhwtxp0f/pycparser/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-2y0ko9re
       cwd: /tmp/pip-wheel-dhwtxp0f/pycparser/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pycparser
ERROR: Failed to build one or more wheels
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/setuptools/installer.py", line 119, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpy_svpn0k', '--quiet', 'pycparser']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    install_requires=install_requires,
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 721, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 777, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/installer.py", line 121, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpy_svpn0k', '--quiet', 'pycparser']' returned non-zero exit status 1.

**Comment by spectralcodec** [comment]
Had to run **pip install wheel**
Now when I run **python3 setup.py install** I receive:

running install
running bdist_egg
running egg_info
writing src/aiortc.egg-info/PKG-INFO
writing dependency_links to src/aiortc.egg-info/dependency_links.txt
writing requirements to src/aiortc.egg-info/requires.txt
writing top-level names to src/aiortc.egg-info/top_level.txt
reading manifest file 'src/aiortc.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/aiortc.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
generating cffi module 'build/temp.linux-x86_64-3.7/aiortc.codecs._vpx.c'
already up-to-date
generating cffi module 'build/temp.linux-x86_64-3.7/aiortc.codecs._opus.c'
already up-to-date
building 'aiortc.codecs._opus' extension
gcc -pthread -B /home/chris/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/chris/anaconda3/include/python3.7m -c build/temp.linux-x86_64-3.7/aiortc.codecs._opus.c -o build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7/aiortc.codecs._opus.o
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/syslimits.h:7:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h:34,
                 from /home/chris/anaconda3/include/python3.7m/Python.h:11,
                 from build/temp.linux-x86_64-3.7/aiortc.codecs._opus.c:28:
/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h:194:15: fatal error: limits.h: No such file or directory
 #include_next <limits.h>  /* recurse down to the real one */
               ^~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by jlaine** [comment]
This error is downright weird, there is something broken with your gcc setup.

Could you try: `sudo apt install libc6-dev`?

**Comment by spectralcodec** [comment]
Thanks, now I have this error when running **python3 setup.py install**:

running install
running bdist_egg
running egg_info
writing src/aiortc.egg-info/PKG-INFO
writing dependency_links to src/aiortc.egg-info/dependency_links.txt
writing requirements to src/aiortc.egg-info/requires.txt
writing top-level names to src/aiortc.egg-info/top_level.txt
reading manifest file 'src/aiortc.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/aiortc.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
generating cffi module 'build/temp.linux-x86_64-3.7/aiortc.codecs._vpx.c'
already up-to-date
generating cffi module 'build/temp.linux-x86_64-3.7/aiortc.codecs._opus.c'
already up-to-date
building 'aiortc.codecs._opus' extension
gcc -pthread -B /home/chris/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/chris/anaconda3/include/python3.7m -c build/temp.linux-x86_64-3.7/aiortc.codecs._opus.c -o build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7/aiortc.codecs._opus.o
build/temp.linux-x86_64-3.7/aiortc.codecs._opus.c:493:10: fatal error: opus/opus.h: No such file or directory
 #include <opus/opus.h>
          ^~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by jlaine** [comment]
Take a look at the README, you need to install some dev libraries.

**Comment by spectralcodec** [comment]
Oops, I thought I already ran the apt install command listed in the README.  Now I receive this message:

running install
running bdist_egg
running egg_info
writing src/aiortc.egg-info/PKG-INFO
writing dependency_links to src/aiortc.egg-info/dependency_links.txt
writing requirements to src/aiortc.egg-info/requires.txt
writing top-level names to src/aiortc.egg-info/top_level.txt
reading manifest file 'src/aiortc.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/aiortc.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
generating cffi module 'build/temp.linux-x86_64-3.7/aiortc.codecs._vpx.c'
already up-to-date
generating cffi module 'build/temp.linux-x86_64-3.7/aiortc.codecs._opus.c'
already up-to-date
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/rtcdatachannel.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/rate.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/sdp.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/rtcconfiguration.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/rtcsctptransport.py -> build/bdist.linux-x86_64/egg/aiortc
creating build/bdist.linux-x86_64/egg/aiortc/codecs
copying build/lib.linux-x86_64-3.7/aiortc/codecs/_vpx.abi3.so -> build/bdist.linux-x86_64/egg/aiortc/codecs
copying build/lib.linux-x86_64-3.7/aiortc/codecs/g711.py -> build/bdist.linux-x86_64/egg/aiortc/codecs
copying build/lib.linux-x86_64-3.7/aiortc/codecs/base.py -> build/bdist.linux-x86_64/egg/aiortc/codecs
copying build/lib.linux-x86_64-3.7/aiortc/codecs/h264.py -> build/bdist.linux-x86_64/egg/aiortc/codecs
copying build/lib.linux-x86_64-3.7/aiortc/codecs/opus.py -> build/bdist.linux-x86_64/egg/aiortc/codecs
copying build/lib.linux-x86_64-3.7/aiortc/codecs/_opus.abi3.so -> build/bdist.linux-x86_64/egg/aiortc/codecs
copying build/lib.linux-x86_64-3.7/aiortc/codecs/__init__.py -> build/bdist.linux-x86_64/egg/aiortc/codecs
copying build/lib.linux-x86_64-3.7/aiortc/codecs/vpx.py -> build/bdist.linux-x86_64/egg/aiortc/codecs
copying build/lib.linux-x86_64-3.7/aiortc/rtcrtptransceiver.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/mediastreams.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/rtcrtpparameters.py -> build/bdist.linux-x86_64/egg/aiortc
creating build/bdist.linux-x86_64/egg/aiortc/contrib
copying build/lib.linux-x86_64-3.7/aiortc/contrib/signaling.py -> build/bdist.linux-x86_64/egg/aiortc/contrib
copying build/lib.linux-x86_64-3.7/aiortc/contrib/media.py -> build/bdist.linux-x86_64/egg/aiortc/contrib
copying build/lib.linux-x86_64-3.7/aiortc/contrib/__init__.py -> build/bdist.linux-x86_64/egg/aiortc/contrib
copying build/lib.linux-x86_64-3.7/aiortc/rtcpeerconnection.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/jitterbuffer.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/rtcicetransport.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/exceptions.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/utils.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/events.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/stats.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/__init__.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/rtp.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/rtcdtlstransport.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/rtcsessiondescription.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/rtcrtpreceiver.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/rtcrtpsender.py -> build/bdist.linux-x86_64/egg/aiortc
copying build/lib.linux-x86_64-3.7/aiortc/clock.py -> build/bdist.linux-x86_64/egg/aiortc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/rtcdatachannel.py to rtcdatachannel.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/rate.py to rate.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/sdp.py to sdp.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/rtcconfiguration.py to rtcconfiguration.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/rtcsctptransport.py to rtcsctptransport.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/codecs/g711.py to g711.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/codecs/base.py to base.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/codecs/h264.py to h264.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/codecs/opus.py to opus.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/codecs/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/codecs/vpx.py to vpx.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/rtcrtptransceiver.py to rtcrtptransceiver.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/mediastreams.py to mediastreams.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/rtcrtpparameters.py to rtcrtpparameters.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/contrib/signaling.py to signaling.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/contrib/media.py to media.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/contrib/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/rtcpeerconnection.py to rtcpeerconnection.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/jitterbuffer.py to jitterbuffer.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/rtcicetransport.py to rtcicetransport.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/exceptions.py to exceptions.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/utils.py to utils.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/events.py to events.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/stats.py to stats.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/rtp.py to rtp.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/rtcdtlstransport.py to rtcdtlstransport.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/rtcsessiondescription.py to rtcsessiondescription.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/rtcrtpreceiver.py to rtcrtpreceiver.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/rtcrtpsender.py to rtcrtpsender.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/clock.py to clock.cpython-37.pyc
creating stub loader for aiortc/codecs/_opus.abi3.so
creating stub loader for aiortc/codecs/_vpx.abi3.so
byte-compiling build/bdist.linux-x86_64/egg/aiortc/codecs/_opus.py to _opus.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/aiortc/codecs/_vpx.py to _vpx.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/aiortc.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/aiortc.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/aiortc.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/aiortc.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/aiortc.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
aiortc.codecs.__pycache__._opus.cpython-37: module references __file__
aiortc.codecs.__pycache__._vpx.cpython-37: module references __file__
creating 'dist/aiortc-0.9.22-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing aiortc-0.9.22-py3.7-linux-x86_64.egg
removing '/home/chris/anaconda3/lib/python3.7/site-packages/aiortc-0.9.22-py3.7-linux-x86_64.egg' (and everything under it)
creating /home/chris/anaconda3/lib/python3.7/site-packages/aiortc-0.9.22-py3.7-linux-x86_64.egg
Extracting aiortc-0.9.22-py3.7-linux-x86_64.egg to /home/chris/anaconda3/lib/python3.7/site-packages
aiortc 0.9.22 is already the active version in easy-install.pth

Installed /home/chris/anaconda3/lib/python3.7/site-packages/aiortc-0.9.22-py3.7-linux-x86_64.egg
Processing dependencies for aiortc==0.9.22
Searching for pylibsrtp>=0.5.6
Reading https://pypi.org/simple/pylibsrtp/
Downloading https://files.pythonhosted.org/packages/25/95/ec90962d3e7eea9fa11d57f4ee1cd8dace408f6858aa8a6f64d4dca6681c/pylibsrtp-0.6.4.tar.gz#sha256=c59e302361783ddd7160d1754c56eafd0d6d7d6538ad024a79d6d4c41a38d052
Best match: pylibsrtp 0.6.4
Processing pylibsrtp-0.6.4.tar.gz
Writing /tmp/easy_install-bzfcjb3f/pylibsrtp-0.6.4/setup.cfg
Running pylibsrtp-0.6.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-bzfcjb3f/pylibsrtp-0.6.4/egg-dist-tmp-5dws5v4d
build/temp.linux-x86_64-3.7/pylibsrtp._binding.c:492:10: fatal error: srtp2/srtp.h: No such file or directory
 #include <srtp2/srtp.h>
          ^~~~~~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by spectralcodec** [comment]
Finally got it installed, had to run:
pip install pysrtp
pip install aiohttp

**Comment by jlaine** [comment]
Great!
