### ISSUE TITLE
Is this a memory leakage

### ISSUE THREAD

**Issue by Nishanth009** [aiortc/aiortc#231]
I tried apprtc example program and it is working good. But i noticed while streaming the RAM is getting increased over the time and caused overflow. I am using version 0.9.22.
This is observed with example program without any modifications 
Is there any suggestion to prevent this issue

Thank you

**Comment by dsvictor94** [comment]
Hi,

what exactly version of  python do you use?
a long time ago I have a problem with memory leak with this lib, but the leak was in the async queue of python, fixed at some point in python3.5

You can see the issue #17. There mote info about the leak.

I do not use aiortc in production anymore, so I can not confirm that the leak still exists

Hope I helped you.

**Comment by jlaine** [comment]
I'm sorry I don't have enough information to move this issue forward. Feel free to reopen with some more data.
