### ISSUE TITLE
How to check which video codecs Am I using?

### ISSUE THREAD

**Issue by trojek** [aiortc/aiortc#233]
I stream as a server video from webcam. My offer endpoint look similar to this:

```
params = await request.json()
    offer = RTCSessionDescription(sdp=params["sdp"], type=params["type"])
    pc = RTCPeerConnection()
    pc_id = "PeerConnection(%s)" % uuid.uuid4()
    pcs.add(pc)

  @pc.on("iceconnectionstatechange")
    async def on_iceconnectionstatechange():
        log_info("ICE connection state is %s", pc.iceConnectionState)
        if pc.iceConnectionState == "failed":
            await pc.close()
            pcs.discard(pc)

    local_video = VideoTransformTrack(
        player.video, transform=params["video_transform"]
    )
    pc.addTrack(local_video)
    
    # handle offer
    await pc.setRemoteDescription(offer)

    # send answer
    answer = await pc.createAnswer()
    await pc.setLocalDescription(answer)
    
    return web.Response(
        content_type="application/json",
        text=json.dumps(
            {"sdp": pc.localDescription.sdp, "type": pc.localDescription.type}
        ),
    )
```
I found how to find list of possible codecs (`capabilities = RTCRtpSender.getCapabilities('video')`) but I don't know which codec is used.

How can I get informaction which codec Am I using? 
How can I use certain codec?

**Comment by trojek** [comment]
I printed the `offer` and I get: 

```RTCSessionDescription(sdp='v=0\r\no=mozilla...THIS_IS_SDPARTA-70.0.1 7556968831062366172 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=sendrecv\r\na=fingerprint:sha-256 E9:70:E5:AA:B6:B8:10:1B:B4:89:A3:19:6B:BC:FC:38:86:6E:B5:6E:CF:B7:B0:97:D1:F2:F2:E0:9D:3E:FE:A0\r\na=group:BUNDLE 0\r\na=ice-options:trickle\r\na=msid-semantic:WMS *\r\nm=video 40103 UDP/TLS/RTP/SAVPF 120 121\r\nc=IN IP4 10.10.10.192\r\na=candidate:0 1 UDP 2122252543 10.10.10.192 40103 typ host\r\na=candidate:1 1 TCP 2105524479 10.10.10.192 9 typ host tcptype active\r\na=candidate:0 2 UDP 2122252542 10.10.10.192 44566 typ host\r\na=candidate:1 2 TCP 2105524478 10.10.10.192 9 typ host tcptype active\r\na=recvonly\r\na=end-of-candidates\r\na=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:5 urn:ietf:params:rtp-hdrext:toffset\r\na=fmtp:120 max-fs=12288;max-fr=60\r\na=fmtp:121 max-fs=12288;max-fr=60\r\na=ice-pwd:a820afd8b4467562757b9d300fd86157\r\na=ice-ufrag:bbd9c33c\r\na=mid:0\r\na=rtcp:44566 IN IP4 10.10.10.192\r\na=rtcp-fb:120 nack\r\na=rtcp-fb:120 nack pli\r\na=rtcp-fb:120 ccm fir\r\na=rtcp-fb:120 goog-remb\r\na=rtcp-fb:121 nack\r\na=rtcp-fb:121 nack pli\r\na=rtcp-fb:121 ccm fir\r\na=rtcp-fb:121 goog-remb\r\na=rtcp-mux\r\na=rtpmap:120 VP8/90000\r\na=rtpmap:121 VP9/90000\r\na=setup:actpass\r\na=ssrc:953296844 cname:{f767f7d5-ed5c-45db-b91e-592aee3480f5}\r\n', type='offer'```

in which I can find: `rtpmap:120 VP8/90000\r\na=rtpmap:121 VP9/90000\r\` Does it mean that I use VP8 or VP9 codec? Or does it mean that client wants to use VP8 or VP9 but I can change it?

**Comment by Kazhuu** [comment]
If you're using Google Chrome as WebRTC client you can also take look at chrome://webrtc-internals/ web page from Chrome. It displays details about the transferred media.

**Comment by jlaine** [comment]
Printing the offer / answer is indeed a good starting point, it will tell you the intersection between the two endpoint's capabilities. For which codec is actually in use, you can look at the browser's debugging tools or sniff the traffic and examine the PT field of the RTP packets.
