### ISSUE TITLE
SDP rfc4585: AIORTC does not support a star in the parameters of "a=rtcp-fb:"

### ISSUE THREAD

**Issue by andrews239** [aiortc/aiortc#248]
remoteSDP:
.......
m=video 57659 RTP/SAVPF 99 97
b=TIAS:2000000
a=rtcp-mux
a=sendrecv
a=rtcp-fb:* nack
a=rtcp-fb:* nack pli
a=rtcp-fb:* goog-remb

  File "~/.local/lib/python3.8/site-packages/aiortc/sdp.py", line 455, in parse
    codec = find_codec(int(bits[0]))
ValueError: invalid literal for int() with base 10: '*'

**Comment by andrews239** [comment]
rtcp-fb-syntax = "a=rtcp-fb:" rtcp-fb-pt SP rtcp-fb-val CRLF

      rtcp-fb-pt         = "*"   ; wildcard: applies to all formats
                         / fmt   ; as defined in SDP spec

      rtcp-fb-val        = "ack" rtcp-fb-ack-param
                         / "nack" rtcp-fb-nack-param
                         / "trr-int" SP 1*DIGIT
                         / rtcp-fb-id rtcp-fb-param

      rtcp-fb-id         = 1*(alpha-numeric / "-" / "_")

      rtcp-fb-param      = SP "app" [SP byte-string]
                         / SP token [SP byte-string]
                         / ; empty

      rtcp-fb-ack-param  = SP "rpsi"
                         / SP "app" [SP byte-string]
                         / SP token [SP byte-string]
                         / ; empty

      rtcp-fb-nack-param = SP "pli"
                         / SP "sli"
                         / SP "rpsi"
                         / SP "app" [SP byte-string]
                         / SP token [SP byte-string]
                         / ; empty

**Comment by andrews239** [comment]
--- sdp.py-orig 2019-12-13 18:31:25.408617734 -0800
+++ sdp.py[6C2020-01-05 21:35:27.980990162 -0800
@@ -452,14 +452,19 @@
                         codec.parameters = parameters_from_sdp(format_desc)
                     elif attr == "rtcp-fb":
                         bits = value.split(" ", 2)
-                        codec = find_codec(int(bits[0]))
-                        codec.rtcpFeedback.append(
-                            RTCRtcpFeedback(
-                                type=bits[1],
-                                parameter=bits[2] if len(bits) > 2 else None,
+                        def codecappend(x):
+                            codec = find_codec(x)
+                            codec.rtcpFeedback.append(
+                                RTCRtcpFeedback(
+                                    type=bits[1],
+                                    parameter=bits[2] if len(bits) > 2 else None,
+                                )
                             )
-                        )
+                        if bits[0] == "*":
+                            for pt in current_media.fmt:
+                                codecappend(pt)
+                        else:
+                            codecappend(int(bits[0]))
         return session
     def __str__(self):

**Comment by andrews239** [comment]
```
--- sdp.py-orig 2019-12-13 18:31:25.408617734 -0800
+++ sdp.py 2020-01-05 21:35:27.980990162 -0800
@@ -452,14 +452,19 @@
                         codec.parameters = parameters_from_sdp(format_desc)
                     elif attr == "rtcp-fb":
                         bits = value.split(" ", 2)
-                        codec = find_codec(int(bits[0]))
-                        codec.rtcpFeedback.append(
-                            RTCRtcpFeedback(
-                                type=bits[1],
-                                parameter=bits[2] if len(bits) > 2 else None,
+                        def codecappend(x):
+                            codec = find_codec(x)
+                            codec.rtcpFeedback.append(
+                                RTCRtcpFeedback(
+                                    type=bits[1],
+                                    parameter=bits[2] if len(bits) > 2 else None,
+                                )
                             )
-                        )
+                        if bits[0] == "*":
+                            for pt in current_media.fmt:
+                                codecappend(pt)
+                        else:
+                            codecappend(int(bits[0]))
         return session
     def __str__(self):
```

**Comment by jlaine** [comment]
This looks like a good catch, if you can put together a pull request with appropriate unit tests I'd be happy to review it. Where is this SDP coming from?

**Comment by andrews239** [comment]
Hi, Jerem. 

Unfortunately, I do not have a suitable development site with full Internet access. If there is enough time, I will try to do PR. 
   
> Where is this SDP coming from?

This SDP was received from the server part of the product:
Cisco Meeting Application (WebRTC)
Version 2.5.4 (webclient2.158.ccb2c4e634)

**Comment by jlaine** [comment]
I didn't understand your comment about a "development site with full internet access", what do you mean?
