### ISSUE TITLE
PeerJS example

### ISSUE THREAD

**Issue by ivelin** [aiortc/aiortc#250]
I would like to report another win for aiortc. I've been able to port [PeerJS to python](https://github.com/ambianic/peerjs-python) and establish successful datachannel exchange. Its a concrete demonstration that its possible and practical to setup direct secure connection between Progressive Web Apps and Python edge devices. No need for man-in-the-middle servers that can see user data. My specific use case is edge AI inference and user UI communication without exposing any user data to cloud services.

If there is interest in a PeerJS interop example, I can work on a PR.

**Comment by jlaine** [comment]
This looks cool! It feels as though having this in its own project is the right way to go though?

**Comment by ivelin** [comment]
Just FYI, WebRTCHacks published my article related to this topic with reference to aiortc:
https://webrtchacks.com/private-home-surveillance-with-the-webrtc-datachannel/

**Comment by jlaine** [comment]
That's a very comprehensive article, I really enjoyed reading it, thanks for sharing!
