### ISSUE TITLE
DataChannel never emit close event

### ISSUE THREAD

**Issue by stalkerg** [aiortc/aiortc#253]
Subj. If you refresh tab in the browser and you loose connection without any notification, it's can be fine for media stream but for the data channel, it's like wrong. Also, I can see in logs DTL
```
dtls[2366] DEBUG client - DTLS shutdown by remote party
dtls[2366] DEBUG client - State.CONNECTED -> State.CLOSED
```

I want to properly close data channel on the server side if browser loose connection.

**Comment by jlaine** [comment]
What's this issue about exactly, do you mean the demo `server` example? If so the "fix" would be to add an event listener for `beforeunload` which closes the data channel.

As far as the library is concerned I'd have to re-read the RFCs, I'm not sure whether we're supposed to emit a "closed" event for cases such as abrupt termination of the connection. What's the behaviour in a pure peer-to-peer scenario (browser to browser, no aiortc involved)?

**Comment by jlaine** [comment]
Ping?

**Comment by stalkerg** [comment]
ohh sorry, forgot about it. 
1. Basically I solved it because if we close tab in the browser we also close the whole PeerConnection and I can catch it and manually free all data channels. 
2. At the same time, according to this https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/onclose if the system will close the channel it emmit this event. 
It should reduce complexity for manage DataChannels on the app side.

**Comment by stalkerg** [comment]
I found how I solved this issue:
```python
# If dtls transport is closed I suppose a browser disconnected
@channel.transport.transport.on("statechange")
async def on_close_transport():  # pylint: disable=unused-variable
    await peer_connection.close()
```
