### ISSUE TITLE
RTCDataChannel stream id never reuse

### ISSUE THREAD

**Issue by stalkerg** [aiortc/aiortc#256]
In the transport code, you never reset number to 0 if it reaches the max. 
https://github.com/aiortc/aiortc/blob/master/src/aiortc/rtcsctptransport.py#L1620
```python
        if stream_id is None:
                while self._data_channel_id in self._data_channels:
                    self._data_channel_id += 2
                stream_id = self._data_channel_id
                self._data_channels[stream_id] = channel
                self._data_channel_id += 2
                channel._setId(stream_id)
```

it can be ok for a custom client but on the browser, we have a very strict limitation:
stream_id < 1024 on Chrome and stream_id < 256 on Firefox. 
On the Chrome side, you can check MaxChannels param. 
As you can see, if I need often close and create DataChannel I very quickly reach this limitation. 

Also, some details here https://github.com/w3c/webrtc-pc/issues/2158 

I suppose should be a way to setup max_stream_id and try reused freed ids.

**Comment by jlaine** [comment]
I'm unfamiliar with the concept of recycling stream ids, are you sure that's a thing?

**Comment by stalkerg** [comment]
Yes, I am sure and make a test application - I even find this limitation in Chrome sources. 
Please check my link. 

It looks like browsers preallocate structure or array for all possible channels. 

Currently, to avoid this situation I start to make all new channels on browser-side and wrote a simple manager.

**Comment by lgrahl** [comment]
@jlaine You can reuse stream IDs once a stream has been reset from both sides.

**Comment by jlaine** [comment]
OK @stalkerg feel free to propose a PR

**Comment by jlaine** [comment]
@lgrahl the PR above does recycle stream IDs. However it still doesn't ensure we don't exceed the maximum allowed streams. Which limit should I be comparing to as there is a notion of inbound / outbound streams in SCTP?

**Comment by lgrahl** [comment]
Against the minimum of the negotiated amount of incoming and outgoing SCTP streams. See steps 3 and 4 in https://w3c.github.io/webrtc-pc/#sctp-transport-connected.

**Comment by jlaine** [comment]
Thanks @lgrahl !

@stalkerg would you mind giving the PR a try and report back whether it solves your problem?

NOTE: I am well aware there is currently no check that we have not exceeded the maximum number of allowed streams, but at least your stream IDs should get recycled.
