### ISSUE TITLE
Documentation lacks events

### ISSUE THREAD

**Issue by ibc** [aiortc/aiortc#263]
Events are not documented in the [doc](https://aiortc.readthedocs.io/en/latest/api.html). The only way to know about them is via the examples. Anyway, I don't know what to expect from here:

```python
@channel.on("message")
def on_message(message):
```

What is `message` supposed to be? is it an object? a string? a blob/buffer (or whatever it's called in Python)?

**Comment by jlaine** [comment]
You are right, docs are lacking for all events. For this specific event `message` can either be a `str` or `bytes` depending on whether a text or a binary message was sent by the remote party.

**Comment by ibc** [comment]
Yep, thanks, already figured it by looking at the code :)
