### ISSUE TITLE
Missing track.enabled getter/setter

### ISSUE THREAD

**Issue by ibc** [aiortc/aiortc#264]
After calling `track.enabled = false` (I mean JavaScript) in a track being sent via a PeerConnection, the RTP should contain silence (if audio) or black video frames (if video) at low bitrate. Or easier: do not send RTP until `track.enabled = true` is set.

This is the classic way of "pausing" a RTP being sent. AFAIS `aiortc` does not expose this API in the `MediaStreamTrack`. The way I'd do it is:

- Add a getter and setter `track.enabled`.
- When the user sets it to false or true, make the track emit a private/custom "enabledchange" event.
- The PeerConnection or the Transceiver managing that sending track is listening for its "enabledchange" event.
- When it happens, do whatever to stop sending RTP or just send silence / black frames.

**Comment by jlaine** [comment]
>     * When it happens, do whatever to stop sending RTP or just send silence / black frames.

Is simply "not sending RTP" acceptable?

**Comment by ibc** [comment]
If track.enabled=false is implemented it should stop producing frames or should produce silence/blank frames. The RTCRtpSender reads frames from the track and could just expose a way to pause the sending of RTP. In fact it has: sender.setConfiguration() with enabled:false in the sending stream. Both are different things.

**Comment by jlaine** [comment]
Let's keep this one around

**Comment by ibc** [comment]
😟

**Comment by jlaine** [comment]
@ibc do you have any plans to work on this?

**Comment by ibc** [comment]
Honestly I don't know Python and I'm not using this project lately.
