### ISSUE TITLE
If empty iceServers are given it internally fails

### ISSUE THREAD

**Issue by ibc** [aiortc/aiortc#266]
Passing an `RTCConfiguration` as follows to the `RTCPeerConnection` fails:

```
{ iceServers: [] }
```

**Comment by ibc** [comment]
Right now not sure if it fails or what happens. Passing a valid STUN server also makes it fail or never end:

`{ iceServers: [ { urls: ["stun:stun.ekiga.net:3478"] } ] }`

**Comment by jlaine** [comment]
I added a test for the "empty iceServers" case and I'm not seeing a failure, do you have any more indications on what to look for?

https://github.com/aiortc/aiortc/blob/93eea51bddb621a7538547500edf545bca29e91f/tests/test_rtcpeerconnection.py#L723

**Comment by ibc** [comment]
Wrong serialization here, sorry. No issue. Thanks for confirming that it's ok.

**Comment by ibc** [comment]
Just wondering (not an expert in Python). Given a `RTCConfiguration` with `iceServers` in JSON, how to construct an aiortc `RTCConfiguration` object with it?

**Comment by ibc** [comment]
I figured it out (more or less).
