### ISSUE TITLE
Use dataclasses instead of attrs

### ISSUE THREAD

**Issue by uriyyo** [aiortc/aiortc#272]
Feature request.

Since python 3.7 version `dataclasses` is a part of python standard library. At python 3.6 we can use `dataclasses` as a third-party package.

We can move the existing code base from `attrs` to `dataclasses`.

I can do it by myself.

**Comment by jlaine** [comment]
Yeah, this is one of the benefits of dropping support for Python 3.5 :)

On `aioquic` which has been Python 3.6+ from the start this is what I do:

https://github.com/aiortc/aioquic/blob/ee7fbbe9a4ebf93fb1f009dd59d4a89a5e704639/setup.py#L62

**Comment by jlaine** [comment]
A PR is most welcome. Like your typing changes, this is something I had on my radar but never found time for.

The one area I'd like a micro benchmark is for the SCTP chunk classes, especially DATA and SACK as they are on the hot path.
