### ISSUE TITLE
All VP8 and H264 RTP packets are keyframes after PLI

### ISSUE THREAD

**Issue by ibc** [aiortc/aiortc#275]
By sending video from `aiortc` to our server (using VP8 or H264) we've noticed that all RTP video packets generated by `aiortc` are key frames.

Is this intentional?

**Comment by jlaine** [comment]
It most certainly is not intentional! How do you diagnose the fact they are key frames?

**Comment by ibc** [comment]
We inspect video codec payloads in mediasoup to detect key frames. We need it to do smooth simulcast stream change, etc.

**Comment by ibc** [comment]
For instance our VP8 parser:

https://github.com/versatica/mediasoup/blob/v3/worker/src/RTC/Codecs/VP8.cpp

**Comment by jlaine** [comment]
OK, let's focus on VP8. I'm not sure I understand this:

https://github.com/versatica/mediasoup/blob/v3/worker/src/RTC/Codecs/VP8.cpp#L104

AFAICT this means you are reading the first byte after the VP8 payload descriptor, so the first byte of VP8 payload header?

https://tools.ietf.org/html/rfc7741#section-4.1

**Comment by jlaine** [comment]
I think I may have got my time units wrong, if 3000 doesn't mean "3 seconds" but 3000 / 90000 then yeah probably every frame is a key frame! Can you try setting the following and telling me how often you see a key frame?

```python
self.cfg.kf_max_dist = 3 * VIDEO_CLOCK_RATE
```

**Comment by ibc** [comment]
News: that's not the problem (or may be it's another, not sure). This is what really happens:

* When `aiortc` starts sending video RTP packets (VP8 or H264) it always send a key frame at the beginning (of course). Packets sent later are NO key frames.
* If the remote sends a RTCP PLI to `aiortc`, then `aiortc` gets **crazy** and every video packet becomes a key frame.

:)

**Comment by jlaine** [comment]
Wow, indeed. If you search for `__force_keyframe` in `RTCRtpSender` the problem is quite obvious: this flag should be cleared after encoding a key frame, but it's not.

**Comment by ibc** [comment]
🤭

**Comment by ibc** [comment]
BTW, the following options in `MediaPlayer` (to get webcam track in OSX) produce a RTP bitrate of ~10 mbps. Is it intentional? It seems too much IMHO.

```
file='default:none',
format='avfoundation',
options={ "framerate": '30', "video_size": '640x480' }
```
