### ISSUE TITLE
HTTP stream MediaPlayer: when are audio/video tracks created?

### ISSUE THREAD

**Issue by ibc** [aiortc/aiortc#284]
```py
player = MediaPlayer(
    'http://download.tsi.telecom-paristech.fr/'
    'gpac/dataset/dash/uhd/mux_sources/hevcds_720p30_2M.mp4')
```

1. When are the `player.audio` and `player.video` tracks created?
2. Immediately when creating the `player` so there will always be `audio` and `video` tracks into it even if some of them won't receive any real content?
3. Or later after getting the content of the stream by inspecting if there is audio and/or video?

If the tracks are created asynchronously (as per bullet 3 above) then we have a problem since we may try to access `player.video` and it does not exist yet.

**Comment by jlaine** [comment]
Ffmpeg starts by reading enough data to figure out what tracks are present afaict.

**Comment by ibc** [comment]
But that the MediaPlayer constructor "waits" until ffmpeg knows it? I mean: may it happen that I create a player, access to it's video track and it does not yet exist but will be created after a while once ffmpeg receives HTTP data?

**Comment by jlaine** [comment]
If memory serves `av.open` blocks until the tracks are known, so the MediaPlayer constructor blocks too. This is not ideal as it may block the event loop, but at least the streams are known.

**Comment by ibc** [comment]
ok, so no race condition here and proper `player.audio` and `player.video` tracks are always available after `MediaPlayer` has been created (assuming the file or URL has audio and video).

**Comment by jlaine** [comment]
That's right. If you're satisfied with the issue, let's close it :)

**Comment by ibc** [comment]
Thanks.
