### ISSUE TITLE
AudioStreamTrack import error

### ISSUE THREAD

**Issue by SoumenDas** [aiortc/aiortc#291]
While trying out the tutorials in RTC Bot [here](https://rtcbot.readthedocs.io/en/latest/examples/webrtc/README.html) I got this error. It seems AudioStreamTrack is not imported in __init__.py

![image](https://user-images.githubusercontent.com/3167177/75116902-dbbc8300-5692-11ea-84ab-60056aa9c3a3.png)
![image](https://user-images.githubusercontent.com/3167177/75116935-29d18680-5693-11ea-8533-219c18aaa35e.png)

**Comment by jlaine** [comment]
Thanks for catching this, it changed a few releases back and I obviously did not update the docs. You should now inherit from `MediaStreamTrack` directly for most usecases.
