### ISSUE TITLE
rtcsctptransport.py: struct.error: required argument is not an integer

### ISSUE THREAD

**Issue by ibc** [aiortc/aiortc#300]
Eventually I get this error when calling `await pc.close()`:

```
0 - closing -> closed
controlling - checking -> closed
Task exception was never retrieved
future: <Task finished coro=<RTCSctpTransport._transmit_reconfig() done, defined at /usr/local/lib/python3.7/site-packages/aiortc/rtcsctptransport.py:1548> exception=error('required argument is not an integer')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiortc/rtcsctptransport.py", line 1561, in _transmit_reconfig
    await self._send_reconfig_param(param)
  File "/usr/local/lib/python3.7/site-packages/aiortc/rtcsctptransport.py", line 1346, in _send_reconfig_param
    await self._send_chunk(chunk)
  File "/usr/local/lib/python3.7/site-packages/aiortc/rtcsctptransport.py", line 1333, in _send_chunk
    chunk,
  File "/usr/local/lib/python3.7/site-packages/aiortc/rtcsctptransport.py", line 427, in serialize_packet
    header = pack("!HHL", source_port, destination_port, verification_tag)
struct.error: required argument is not an integer
```

**Comment by jlaine** [comment]
I don't, so you're going to have to show me how :)

This means one of `source_port`, `destination_port` or `verification_tag` are probably `None`. Are you by any chance closing the peer connection before the SDP negotiation completes? Could you give a step-by-step?

**Comment by ibc** [comment]
> Are you by any chance closing the peer connection before the SDP negotiation completes? Could you give a step-by-step?

Is it enough if I say "yes" here? :)
Calling the `pc` in the middle of any async operation is or should be valid and legit.

**Comment by jlaine** [comment]
It kind of depends: is it enough for me to say "OK" here and do nothing more? :)

**Comment by ibc** [comment]
I just meant that yes, I probably call PC.close before SDP O/A completes. Just wondering if the lib shod be ready for that.

**Comment by jlaine** [comment]
I tried creating a data channel then closing it immediately before sending out the SDP and I do get a crash, but not exactly the one you encountered so the conditions must be different.

In any case my problem is I could not find an explanation in the specs of the expected behaviour when closing a data channel before it reaches the "open" `readyState`. Could you help me out?

**Comment by ibc** [comment]
Ok, I've reduced a bit the issue. Hope this helps:

```
worker: processRequest() [method:handler.createDataChannel]
handler: icegatheringstatechange [state:new]
worker: processRequest() [method:handler.createOffer]
worker: processRequest() [method:handler.setLocalDescription]
handler: signalingstatechange [state:have-local-offer]
handler: icegatheringstatechange [state:gathering]
Connection(4) protocol(2) connection_made(<_SelectorDatagramTransport fd=12 read=idle write=<idle, bufsize=0>>)
Connection(4) protocol(2) > ('66.102.1.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xe8y\x9e\x9cB\t\xecp\x18/\xd5\x1e')
Connection(4) protocol(2) < ('66.102.1.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\xe8y\x9e\x9cB\t\xecp\x18/\xd5\x1e')
handler: icegatheringstatechange [state:complete]
worker: processRequest() [method:handler.setRemoteDescription]
controlling - new -> closed
Connection(4) protocol(2) connection_lost(None)
handler: signalingstatechange [state:stable]
worker: processNotification() [event:datachannel.close]
0 - connecting -> closing
Task exception was never retrieved
future: <Task finished coro=<RTCSctpTransport._transmit_reconfig() done, defined at /Users/ibc/Library/Python/3.7/lib/python/site-packages/aiortc/rtcsctptransport.py:1548> exception=error('required argument is not an integer')>
Traceback (most recent call last):
  File "/Users/ibc/Library/Python/3.7/lib/python/site-packages/aiortc/rtcsctptransport.py", line 1561, in _transmit_reconfig
    await self._send_reconfig_param(param)
  File "/Users/ibc/Library/Python/3.7/lib/python/site-packages/aiortc/rtcsctptransport.py", line 1346, in _send_reconfig_param
    await self._send_chunk(chunk)
  File "/Users/ibc/Library/Python/3.7/lib/python/site-packages/aiortc/rtcsctptransport.py", line 1333, in _send_chunk
    chunk,
  File "/Users/ibc/Library/Python/3.7/lib/python/site-packages/aiortc/rtcsctptransport.py", line 427, in serialize_packet
    header = pack("!HHL", source_port, destination_port, verification_tag)
struct.error: required argument is not an integer
```

> In any case my problem is I could not find an explanation in the specs of the expected behaviour when closing a data channel before it reaches the "open" readyState. Could you help me out?

From what I read:

https://www.w3.org/TR/webrtc/#dom-rtcdatachannel-close

> 1. Let channel be the RTCDataChannel object which is about to be closed.
> 2. If channel.[[ReadyState]] is closing or closed, then abort these steps.
> 3. Set channel.[[ReadyState]] to closing.
> 4. If the closing procedure has not started yet, start it.

Fom https://www.w3.org/TR/webrtc/#data-transport-closing-procedure:

> An RTCDataChannel object's underlying data transport may be torn down in a non-abrupt manner by running the closing procedure. When that happens the user agent MUST queue a task to run the following steps:
>
> 1. Let channel be the RTCDataChannel object whose transport was closed.
> 2. Unless the procedure was initiated by the channel's close method, set channel.[[ReadyState]] to closing.
> 3. Run the following steps in parallel:
>    1. Finish sending all currently pending messages of the channel.
>    2. Follow the closing procedure defined for the channel's underlying transport:
>       1. In the case of an SCTP-based transport, follow [RTCWEB-DATA], section 6.7.
>    3. Render the channel's data transport closed by following the associated procedure.

From https://tools.ietf.org/html/draft-ietf-rtcweb-data-channel-13#section-6.7:

> 6.7.  Closing a Data Channel
>
>   Closing of a data channel MUST be signaled by resetting the
   corresponding outgoing streams [RFC6525].  This means that if one
   side decides to close the data channel, it resets the corresponding
   outgoing stream.  When the peer sees that an incoming stream was
   reset, it also resets its corresponding outgoing stream.  Once this
   is completed, the data channel is closed.  Resetting a stream sets
   the Stream Sequence Numbers (SSNs) of the stream back to 'zero' with
   a corresponding notification to the application layer that the reset
   has been performed.  Streams are available for reuse after a reset
   has been performed.
>
>   [RFC6525] also guarantees that all the messages are delivered (or
   abandoned) before the stream is reset.

No much more. However, both `pc.close()` and `datachannel.close()` are sync methods in the spec that are supposed to **never** fail or raise an error. They should just "close" the stuff unless already closed or closing. It should not matter when they are called. It would be crazy if the user should do lot of checks to see if it can safely call to `stop()` or not. It must just work.

**Comment by jlaine** [comment]
OK so your testcase is slightly different, you did generate the offer and apply the local description, thanks for that.

Regarding the closing procedure I need to dig a bit deeper and ask around, I'm a bit worried about leaving things in a "half-open" state.

**Comment by ibc** [comment]
> Regarding the closing procedure I need to dig a bit deeper and ask around, I'm a bit worried about leaving things in a "half-open" state.

May I know what you mean with "half-open" state? do you mean at SCTP association level?

**Comment by jlaine** [comment]
Yes I do. Unlike most implementations out there which rely on usrsctp, aiortc ships its own minimal SCTP implementation in Python.

**Comment by ibc** [comment]
Sure, I know :)

Which exact issue you mean related to the STCP association? Streams are supposed to be already allocated (aiortc allocates 65536 and AFAIS also allows later renegotiation via RESET). When a Datachannel is created (in "negotiated" mode as in my case) nothing extra should be done at SCTP association level, am I wrong?

**Comment by jlaine** [comment]
Ah.. negotiated data-channels, yet another case I need to test for "early stops".

**Comment by ibc** [comment]
Negotiated datachannels are easier IMHO. No need for in-band messages exchange but just verify the given `options.id` and see if it's an already negotiated and an available SCTP stream id. No need for SCTP messages exchange.

**Comment by jlaine** [comment]
@ibc can you give PR #306 a try?

**Comment by ibc** [comment]
It looks nice:

```
worker: processRequest() [method:handler.createOffer]
worker: processRequest() [method:handler.setRemoteDescription]
handler: signalingstatechange [state:have-remote-offer]
worker: processNotification() [event:datachannel.close]
0 - connecting -> closing
0 - closing -> closed
worker: processNotification() [event:datachannel.close]
666 - connecting -> closing
666 - closing -> closed
worker: processNotification() [event:handler.close]
controlling - checking -> closed
handler: signalingstatechange [state:closed]
handler: iceconnectionstatechange [state:closed]
controlling - closed -> failed
server - State.NEW -> State.CONNECTING
server x DTLS handshake failed (connection error)
server - State.CONNECTING -> State.FAILED
Connection(2) protocol(0) connection_lost(None)
controlling - failed -> closed
```
