### ISSUE TITLE
player.video.stop() never returns if called after player.audio.stop()

### ISSUE THREAD

**Issue by ibc** [aiortc/aiortc#301]
* I create a `MediaPlayer` from a mp4 file with audio and video.
* I call `player.audio.stop()` (it completes) followed by `player.video.stop()`.

Sometimes the second call does not return. I've confirmed it by adding these logs into my tests:

```py
if player.audio:
    print("stopping audio...")
    player.audio.stop()
    print("audio stopped")

if player.video:
    print("stopping video...")
    player.video.stop()
    print("video stopped")
```

Clearly, many times it produces:

```
stopping audio...
audio stopped
stopping video...
```

**Comment by jlaine** [comment]
You're going to have to be more specific than this, because my tests say otherwise:

https://github.com/aiortc/aiortc/blob/7d8fe31f68bfc6c7571fae9bfb39e2be5d6ccd78/tests/test_rtcpeerconnection.py#L1872-L1873

**Comment by ibc** [comment]
Call me crazy. Indeed the "block" just happens if, between both `player.audio.stop()` and `player.video.stop()` calls, I access some members of the player and its tracks. Working on a test.

**Comment by ibc** [comment]
ok, I'm afraid I cannot directly reproduce it in Python land because, in order to fail, I need some "pause" between above calls, and I'm not good at Python/asyncio. May I ask you to try a simplified fork of our repo instead? I've created a specific test for this issue:

```bash
$ git clone git@github.com:versatica/mediasoup-client-aiortc.git
$ cd mediasoup-client-aiortc/
$ git checkout aiortc-issue-301
$ npm install
$ npm test
```

The only relevant part of the code is in `worker/worker.py`. Everything else is just communication between the Node.js process and the spawned Python subprocess.

The output of `npm test` above is:

```
 RUNS  test/test.js
worker: starting mediasoup-client aiortc worker
Using selector: KqueueSelector
worker: run()

worker: processRequest() [method:createPlayer]
worker: request 'createPlayer' succeeded

worker: processNotification() [event:player.stopTrack]
calling player.audio.stop()...
player.audio.stop() done
worker: notification 'player.stopTrack' succeeded

worker: processNotification() [event:player.stopTrack]
calling player.video.stop()...
player.video.stop() done
worker: notification 'player.stopTrack' succeeded

worker: processNotification() [event:player.close]
calling player.audio.stop()...
player.audio.stop() done
calling player.video.stop()...
player.video.stop() done
WARN: and here the problem:
WARN: 'player.close' notification has completed, however there is no log 'worker: notification 'player.close' succeeded'
WARN: such a log should happen in the run() method of worker.py once processNotification() completes, but it does not so something is blocked here and it prevents the next call to 'dump' to succeed
 FAIL  test/test.js
  ✕ reproduce aiortc issue 301 (2010ms)

  ● reproduce aiortc issue 301

    : Timeout - Async callback was not invoked within the 2000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 2000ms timeout specified by jest.setTimeout.Error:
```

So, this is SUPER strange. Logs can be printed immediately after calling `player.video.stop()`. However logs after the sync `processNotification()` method that calls the former are not printed. Something is blocked somewhere... I think.

**Comment by jlaine** [comment]
I'm not sure what I'm looking at here, but it tells me "PASS":

``` PASS  test/test.jsest() [method:dump]
  ✓ reproduce aiortc issue 301 (280ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.609s, estimated 2s```

Maybe move this issue to your own repo until you have confirmation this is an `aiortc` bug?

**Comment by ibc** [comment]
OSX? Can you please repeat the test N times please? Eventually it works also for me.

**Comment by ibc** [comment]
sorry, I've simplified the test so now it's much more clear (pushed to the branch):

```
 RUNS  test/test.js
worker: starting mediasoup-client aiortc worker
Using selector: KqueueSelector
worker: run()

worker: processRequest() [method:createPlayer]
worker: request 'createPlayer' succeeded

// This is produced by:
//   worker._channel.notify(
//     'player.stopTrack', { playerId: audioTrack.data.playerId }, { kind: 'audio' });
//
worker: processNotification() [event:player.stopTrack]
calling player.audio.stop()...
player.audio.stop() done

// This is produced by:
//   worker._channel.notify(
//    'player.stopTrack', { playerId: videoTrack.data.playerId }, { kind: 'video' });
//
worker: notification 'player.stopTrack' succeeded
worker: processNotification() [event:player.stopTrack]
calling player.video.stop()...

// Here we should see "worker: processRequest() [method:dump]" but we don't
// because somehow the Python process is frozen or into an infinite loop or
// waiting for some async call that never completes

FAIL (timeout)
```

**Comment by ibc** [comment]
> Maybe move this issue to your own repo until you have confirmation this is an `aiortc` bug?

I'm extremely sure this is not a bug in my code. Not sure how to probe it though.

**Comment by ibc** [comment]
ok, please forget this issue until I have better info.

**Comment by ibc** [comment]
I'm in a scenario right now in which adding a fxxxxxing `console.warn('------foo')` into the unit test makes it always work. So I eat my above words. No idea where the issue is and does not look good.
