### ISSUE TITLE
Allow same track to be sent N times

### ISSUE THREAD

**Issue by ibc** [aiortc/aiortc#302]
In `rtcpeerconnection.py`:

```py
    def __assertTrackHasNoSender(self, track: MediaStreamTrack) -> None:
        for sender in self.getSenders():
            if sender.track == track:
                raise InvalidAccessError("Track already has a sender")
```

May I know why this constraint? is it artificial? Nothing in the spec prevents a PC from sending the same track N times in different transceivers (may be with different encoding settings).

**Comment by jlaine** [comment]
```6. Let senders be the result of executing the CollectSenders algorithm. If an RTCRtpSender for track already exists in senders, throw an InvalidAccessError.```

https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-addtrack

Also, there is absolutely no way a track can be sent multiple times short of completely overhauling the media pipeline: the `recv` method returns the next frame. If you have multiple senders you are going to randomly split your frames against your N senders.

**Comment by ibc** [comment]
> 6. Let senders be the result of executing the CollectSenders algorithm. If an RTCRtpSender for track already exists in senders, throw an InvalidAccessError.

That's true for `pc.addTrack()` method. However there is no such a constraint when using `pc.addTransceiver()`:

https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-addtransceiver

> Also, there is absolutely no way a track can be sent multiple times short of completely overhauling the media pipeline: the recv method returns the next frame. If you have multiple senders you are going to randomly split your frames against your N senders.

This is an implementation detail IMHO. In fact, what you say also means that if I create to peerconnections I cannot call `pc1.addTrack(track)` and `pc2.addTrack(track)` with the same `track` because both pc1 and pc2 would receive randomly splitted frames, right?

Maybe the problem here is that the encoding process should be separated from the track itself. The fact that an encoder is reading from a `track` should not avoid that a second encoder also reads from the same `track`.

**Comment by ibc** [comment]
I've looked a bit at the code. Unfortunately zero expertise with Python here. Anyway:

It comes to my mind that when the `"media-player"` thread in `PlayerStreamTrack` (`src/contrib/media.py`)  adds frames to `self._queue`, and then `PlayerStreamTrack.recv()` gets a frame, instead of returning such a frame it could emit a "frame" event. This way, multiple "track representations" (or whatever) could get frames from the source.

Does it sound super crazy?

**Comment by jlaine** [comment]
It's not "crazy" but you seem to forget `aiortc` is not purely about `MediaPlayer`: a very common usecase is for users to subclass `MediaStreamTrack`, as illustrated in multiple examples. Such deep changes to the media pipeline would require plenty of documentation and code which breaks in a clear fashion to tell users how they need to update their code.

I think the main issue is that the `recv` method is both what users who subclass `MediaStreamTrack` are asked to implement and what is consumed by the media "sinks" (MediaRecorder, RTCRtpSender). Once we have a clear idea of how the new pipeline should work, we should probably have two different interfaces:

- one method which users need to implement with an API as simple as the current one
- a different wrapper method which is what is actually consumed by media sinks. This would give us the opportunity to put some common code in the base `MediaStreamTrack` class such as: ensuring the track is "live" or raising the right exception, allowing multiple consumers for a track, etc..

**Comment by ibc** [comment]
Users may still implement such a `recv` method as today. However `aiortc` would call `track.recv()` and "emit" each frame so N media sinks would receive such a "frame" event. Yeah, I understand it's not as easy as that :)
