### ISSUE TITLE
Strange `trackId` value in stats

### ISSUE THREAD

**Issue by ibc** [aiortc/aiortc#303]
I call `pc.addTransceiver()` with a `track` (generated by a `MediaPlayer`) whose `id` is "296ff180-3e3a-44de-b9f9-e0440d686e84".

However when I print the `transceiver.sender.getStats()` I see a strange `trackId` value into it:

```json
{
      "bytesSent": 8643,
      "id": "outbound-rtp_4575985168",
      "kind": "audio",
      "packetsSent": 2881,
      "ssrc": 3795462943,
      "timestamp": 1582673816.716741,
      "trackId": "4575764560",
      "transportId": "transport_4575984272",
      "type": "outbound-rtp"
}
```

Here we have `"trackId": "4575764560"`, which does not make much sense.

**Comment by ibc** [comment]
Well, maybe this does not work:

```py
trackId=str(id(self.track)),
```

XD

PR soon.

**Comment by ibc** [comment]
Done in #305

**Comment by jlaine** [comment]
I'd have to re-read the specs, I'm not entirely convinced these IDs are supposed to be identical

**Comment by ibc** [comment]
https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-trackid

> #### Dictionary RTCOutboundRtpStreamStats Members
>
> **trackId of type DOMString**
> The identifier of the stats object representing the current track attachment to the sender of this stream, an RTCSenderAudioTrackAttachmentStats or RTCSenderVideoTrackAttachmentStats.

> #### Obsolete RTCSenderAudioTrackAttachmentStats dictionary
>
> An RTCSenderAudioTrackAttachmentStats object represents the stats about one attachment of an audio MediaStreamTrack to the RTCPeerConnection object for which one calls getStats.
>
> It appears in the stats as soon as it is attached (via addTrack, via addTransceiver, via replaceTrack on an RTCRtpSender object).
>
> If an audio track is attached **twice** (via addTransceiver or replaceTrack), there will be two RTCSenderAudioTrackAttachmentStats objects, one for each attachment. They will have the same "trackIdentifier" member, but different "id" members.
>
> This dictionary was made obsolete after its members were moved to "media-source", "sender" and "outbound-rtp" (to enable simulcast stats)

https://w3c.github.io/webrtc-stats/#dom-rtcstatstype-media-source

> #### media-source
>
> Statistics for the media produced by a MediaStreamTrack that is currently attached to an RTCRtpSender. This reflects the media that is fed to the encoder; after getUserMedia() constraints have been applied (i.e. not the raw media produced by the camera). It is either an RTCAudioSourceStats or RTCVideoSourceStats depending on its kind.

Those `RTCAudioSourceStats` or `RTCVideoSourceStats` inherit from `RTCMediaSourceStats`:

https://w3c.github.io/webrtc-stats/#dom-rtcmediasourcestats

> dictionary RTCMediaSourceStats : RTCStats {
>             DOMString       trackIdentifier;
>             DOMString       kind;
> };

> **trackIdentifier of type DOMString**
> The value of the MediaStreamTrack's id attribute 

So finally! So:

* `trackId` in `RTCOutboundRtpStreamStats` is deprecated and points to obsolete ` RTCSenderAudioTrackAttachmentStats` or `RTCSenderVideoTrackAttachmentStats`.
* `mediaSourceId` in `RTCOutboundRtpStreamStats` is what we want. It points to a `RTCAudioSourceStats` or `RTCVideoSourceStats`, which inherit from `RTCMediaSourceStats` and contains `trackIdentifier` matching the `track.id`.

The thing here is that AFAIK `aiortc` does not generate `mediaSourceId` nor its associated `RTCAudioSourceStats` or `RTCVideoSourceStats`.

**Comment by jlaine** [comment]
OK, so we should not have merged the PR.. :(

**Comment by ibc** [comment]
Well, there is no `mediaSourceId` in "outboud-rtp" stats pointing to an `RTCAudioSourceStats` or `RTCVideoSourceStats` in `aiortc`, so better have `trackId` somewhere for now.

**Comment by ibc** [comment]
You like `git push --force` umm? :)
