### ISSUE TITLE
sender.replaceTrack(): strange behavior (frozen video for N seconds)

### ISSUE THREAD

**Issue by ibc** [aiortc/aiortc#304]
In my experiments, `sender.replaceTrack()` works a bit randomly. When it "works", it keeps sending RTP all the time. However the remote (i.e. Chrome) cannot render the received RTP for ~10 seconds and gets frozen video instead (but it **does** receive RTP, confirmed). Asking for a key frame via RTCP PLI to `aiortc` does not make it work. After ~10 seconds, the receiver can render the video again.

Said that, the above happens if I replace a webcam track with another new webcam track. If I try to replace a webcam track with a file video track, the remote gets frozen video forever, and I think that there is no sending RTP anymore.

Do I miss something here in this regard?

**Comment by jlaine** [comment]
Yes, you missed issue #228. It's not currently functional
