### ISSUE TITLE
How specify audio codecs?

### ISSUE THREAD

**Issue by stalkerg** [aiortc/aiortc#308]
Currently, aiortc trying to use opus but in my case, I have already G722 stream and it's widely supported and I want to send it as is. 
Basically it's two questions, how to prepare proper SDP and how to send raw data without encoding? 

Thanks.

**Comment by jlaine** [comment]
You can use `RTCRtpTransceiver.setCodecPreferences`, see:

https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiver/setCodecPreferences
https://aiortc.readthedocs.io/en/latest/api.html#aiortc.RTCRtpTransceiver.setCodecPreferences

.. and an example here:

https://github.com/aiortc/aiortc/blob/master/tests/test_rtcpeerconnection.py#L885-L891

**Comment by stalkerg** [comment]
@jlaine ok, the main problem here - I can't add my own codec for example G722. 
I did it by monkey patching but it looks messy:
```python
class G722ProxyEncoder:
    def encode(self, frame, force_keyframe=False):
        return [frame.payload], frame.timestamp


class G722ProxyDecoder:
    def decode(self, encoded_frame):
        return [encoded_frame]


_get_encoder = codecs.get_encoder
_get_decoder = codecs.get_decoder


def get_encoder(codec):
    mimeType = codec.mimeType.lower()
    if mimeType == "audio/g722":
        return G722ProxyEncoder()
    else:
        return _get_encoder(codec)


def get_decoder(codec):
    mimeType = codec.mimeType.lower()
    if mimeType == "audio/g722":
        return G722ProxyDecoder()
    else:
        return _get_decoder(codec)


class JitterBuffer:
    def __init__(self, capacity: int, prefetch: int = 0) -> None:
        self._capacity = capacity
        self._prefetch = prefetch

    @property
    def capacity(self) -> int:
        return self._capacity

    def add(self, packet):
        return packet


codecs.get_encoder = get_encoder
codecs.get_decoder = get_decoder
rtcrtpreceiver.get_decoder = get_decoder
rtcrtpreceiver.JitterBuffer = JitterBuffer
rtcrtpsender.get_encoder = get_encoder

G722_CODEC = RTCRtpCodecParameters(
    mimeType="audio/G722",
    clockRate=8000,
    channels=1,
    payloadType=9
)
codecs.CODECS["audio"] = [G722_CODEC]
```

and yes, in my case I wont to avoid any encoding/decoding it's why I should also replace jitter buffer. 
It will be great to do something for making codecs pipeline from the user code.

**Comment by jlaine** [comment]
"Not encoding / decoding media" is out of scope as discussed in multiple tickets.

The whole media pipeline is based on the fact we carry decoded frames.

**Comment by stalkerg** [comment]
>As for adding G.722 : why not if FFmpeg handles it. Feel free to submit a PR (with unit tests).

Yes, for a normal pipeline I can do it. 

> The whole media pipeline is based on the fact we carry decoded frames.

In my case, I have SIP phone who sends me RTP packet and I just should send it over WebRTC.  As you can see it already works. Also, it really helps to reduce delays. 
Maybe we can introduce fake pipeline or proxy pipeline? Base on my monkey patch it's looks not so complicated.
