### ISSUE TITLE
Origin of latency

### ISSUE THREAD

**Issue by miguelwon** [aiortc/aiortc#309]
I used the [apprtc](https://github.com/aiortc/aiortc/blob/master/examples/apprtc/apprtc.py) example adapted to read a webcam to test the latency of the video stream (send only) in a local network and I get an average end-to-end of 350ms (measure from several photos that capture a stopwatch in both screens). Code of the `VideoImageTrack`:

```
class VideoImageTrack(VideoStreamTrack):
    """
    A video stream track that returns a rotating image.
    """

    def __init__(self):
        super().__init__()  # don't forget this!
        self.t1 = time.time()
        self.count = 0

    async def recv(self):
        pts, time_base = await self.next_timestamp()
        self.count += 1
        _, img = cap.read()
        t2 = time.time()
        frame = VideoFrame.from_ndarray(img, format="bgr24")
        frame.pts = pts
        frame.time_base = time_base
        print(1000*(time.time()-self.t1)/self.count,1000*(time.time()-t2))
        return frame
```

I also print how long it takes to capture each frame, resulting in an average of 38ms. 

So, my is question where does the remaining latency comes from? 312ms for the rest of the pipeline seem quite big to me.

**Comment by miguelwon** [comment]
So, meanwhile, I checked that after this [point](https://github.com/aiortc/aiortc/blob/11540a8ca1c3a9327f9d28884f29c4060fadcb10/src/aiortc/rtcrtpsender.py#L298) I have more 22 ms (mostly from the frame encoding).

**Comment by jlaine** [comment]
You need to rethink your code, here you are cumulating two delays:

- the asynchronous call to `next_timestamp` which will wait 1/30th of a second
- a blocking (bad) call to `cap.read()` which will wait some arbitrary time for the next frame and completely block your process in the meantime

=> you are guaranteed to fall behind.

In general, using OpenCV for video capture is very bad idea, it is not made for continuous capture and it has no concept of timestamps, so you have no idea when your frame was actually captured. If all you want to do is read from a webcam, you don't need to write your own code, simply use `MediaPlayer`:

https://aiortc.readthedocs.io/en/latest/helpers.html#aiortc.contrib.media.MediaPlayer

**Comment by miguelwon** [comment]
Ok, thanks for the explanation. I changed to use `MediaPlayer` but now it's overloading the CPU (I'm testing a raspberry pi 4). 

Also, another reason I was trying to use cap.read() is that I want to manipulate the frames.

**Comment by jlaine** [comment]
You can try lowering the frame rate if the Pi is unable to encode the frames in realtime.

Also note that you can write a "wrapper" track whose `recv()` methods does:

- call `recv()` on the video track returned by the MediaPlayer
- apply whatever manipulation you require
- returns the transformed video frame

You can find an example of such a track here:

https://github.com/aiortc/aiortc/blob/11540a8ca1c3a9327f9d28884f29c4060fadcb10/examples/server/server.py#L22
