### ISSUE TITLE
Hardware h264 encode/decode

### ISSUE THREAD

**Issue by dkumor** [aiortc/aiortc#323]
`aiortc` is a powerful tool for remotely sending video. However, its use for robots and small embedded devices is hampered by the fact that it can't use hardware acceleration for h264 on compute-constrained devices like the Raspberry Pi.

For the example of a Raspberry Pi, it is my understanding that enabling hardware acceleration would entail the following:
`h264 -> h264_mmal` at https://github.com/aiortc/aiortc/blob/master/src/aiortc/codecs/h264.py#L102
`libx264 -> h264_omx` at https://github.com/aiortc/aiortc/blob/master/src/aiortc/codecs/h264.py#L248

In the case of nvidia cards, enabling hardware acceleration would be  `h264->h264_cuvid` and `libx264->h264_nvenc`  (https://developer.nvidia.com/ffmpeg)

If my understanding is correct, I would be extremely happy if the choice of codec string for h264 were somehow exposed as an option, allowing someone using aiortc to use the hardware acceleration for their platform.

**Comment by dkumor** [comment]
Woops, duplicate of #116, sorry!

**Comment by Odianosen25** [comment]
Hello @dkumor,

Please I am stuck with this issue, and my PC really almost maxing out sometimes. Did this solution work after these changes?

Thanks
