### ISSUE TITLE
Some options were not used

### ISSUE THREAD

**Issue by Haesmen** [aiortc/aiortc#325]
Сan't pass option {'frames': 'v 1'} for ffmpeg to MediaRecorder. Need to record one frame, how to do it? sorry for my English

**Comment by jlaine** [comment]
I am sorry but I don't understand what you are trying to do here, could you please elaborate?

**Comment by Haesmen** [comment]
in examples/videostream-cli you can save "python cli.py answer --record-to video-% 3d.png", but I need only one file with the first frame, for this there is an option "-frames: v 1" in ffmpeg which I tried to transfer to MediaRecorder. Thanks for the answer
