### ISSUE TITLE
Docker install of aiortc

### ISSUE THREAD

**Issue by apexdodge** [aiortc/aiortc#327]
I've been trying to install the server example via docker, ubuntu base image v18.04 and it fails on the pip install av every time. Been at it for a couple days and tried everything I could find. This is the docker file I've been working off of: 

https://github.com/leader22/docker-aiortc-server-example/blob/master/Dockerfile

It looks good to me, but no dice.

Does anyone have a docker file that works for the server example?

**Comment by BrettRD** [comment]
I suspect it's a ffmpeg4 issue, I just hit that one in docker today.
see: https://github.com/aiortc/aiortc/issues/326

I had to
```
#upgrade ffmpeg for aiortc av dependency
RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:jonathonf/ffmpeg-4
RUN apt-get update && apt-get upgrade -y

#install aiortc dependencies
RUN apt-get install -y \
    libavdevice-dev \
    libavfilter-dev \
    libopus-dev \
    libvpx-dev \
    libsrtp2-dev \
    pkg-config

#get python3
RUN apt-get install -y \
    python3-pip

#install aiortc and other python libs
RUN pip3 install \
    aiortc
```

**Comment by jlaine** [comment]
@BrettRD thanks for weighing in! 

@apexdodge does it fix your issue?

**Comment by apexdodge** [comment]
@BrettRD it worked! Life saver, thanks guys.
