### ISSUE TITLE
Checking RTCCertificate validity

### ISSUE THREAD

**Issue by DurandA** [aiortc/aiortc#328]
I'd like to manually check certificate validity of other peers. The idea is to perform mutual authentication using peer certificates instead of adding another application layer for authentication.

I had a quick look at [_rtcdtlstransport.py_](https://github.com/aiortc/aiortc/blob/master/src/aiortc/rtcdtlstransport.py). I don't think there is a specific API for that yet, except maybe by patching `verify_callback()` that is called from _openssl_:
https://github.com/aiortc/aiortc/blob/ab9fa1f840a037c80a17dacf479fae7765c7bd2c/src/aiortc/rtcdtlstransport.py#L132-L134

Is this a feature that could be added to _aiortc_? Does it makes sense at all to do that with WebRTC? I supposed that yes since there is a [RTCCertificate Web API](https://www.w3.org/TR/webrtc/#rtccertificate-interface). My final goal is to build a file transfer application with end-to-end encryption similar to @warner's [magic-wormhole](https://github.com/warner/magic-wormhole) or [croc](https://github.com/schollz/croc) based on WebRTC.

**Comment by DurandA** [comment]
I think that this is supposed to be [_getRemoteCertificates_](https://www.w3.org/TR/webrtc/#dom-rtcdtlstransport-getremotecertificates) in the W3C API. Since I am not too sure about this approach, I asked the [question on StackOverflow](https://stackoverflow.com/questions/60922417/webrtc-mutual-authentication-using-certificates).

**Comment by jlaine** [comment]
I don't think validating a certificate chain makes sense for WebRTC: WebRTC endpoints generate self-signed certificates on the fly. What you *do* want to verify (which is done by aiortc) is that your peer certificate's fingerprint matches the one announced in SDP.

**Comment by DurandA** [comment]
Thanks for your reply.

Isn't the purpose of [_getRemoteCertificates_](https://www.w3.org/TR/webrtc/#dom-rtcdtlstransport-getremotecertificates) to validate other peer's certificate?

Additional, I found this is [WebRTC 1.0](https://www.w3.org/TR/webrtc/#persistent-information-exposed-by-webrtc):
> When establishing DTLS connections, the WebRTC API can generate certificates that can be persisted by the application (e.g. in IndexedDB). These certificates are not shared across origins, and get cleared when persistent storage is cleared for the origin.

I'm not sure if this is for performance reason (so that a certificate don't need to be re-generated each time) or on purpose so that applications can store other peer identities.

I'll close the issue for now until I can get an authoritative answer.
