### ISSUE TITLE
This library is lacking quality learning material.

### ISSUE THREAD

**Issue by jamiejackherer** [aiortc/aiortc#329]
The examples, although good for their purpose don't include a simple chat app.

I cannot figure out the most simple way to use aiortc for just simply chatting in a group chat. 

I know I need to use the datachannel flow but I cannot work it out. And extra example would be cool.

**Comment by jlaine** [comment]
Excellent, thank you for volunteering for this! I'm looking forward to your pull request.

**Comment by jlaine** [comment]
@jamiejackherer do you plan to address this issue or can I close it?
