### ISSUE TITLE
Android - WebRTC to aiortc

### ISSUE THREAD

**Issue by ShwetaChauhan18** [aiortc/aiortc#333]
Hi, I am working with aiortc for streaming video data from android to backend(who uses aiortc).
Now from android I generate offer and sent it to backend server. From backend server I got answer and save it.

But after that I am getting **onIceConnectionChange: CHECKING** and then onIceConnectionChange: FAILED and because of that I am not able to stream video data.

So, How can I exchange ICE packates in aiortc? or what I am asking is possible or not? 

I used : 

`ArrayList<PeerConnection.IceServer> iceServers = new ArrayList<>();    iceServers.add(PeerConnection.IceServer.builder("stun:stun.l.google.com:19302").createIceServer());`

**Comment by jlaine** [comment]
I really have nothing to go on here, could you provide things like the SDP being exchanged?

**Comment by ShwetaChauhan18** [comment]
Here is the answer I got from backend
`{


	
"sdp":"v=0 o=- 3795504069 3795504069 IN IP4 0.0.0.0 s=- t=0 0 a=group:BUNDLE audio video a=msid-semantic:WMS * m=audio 52802 UDP/TLS/RTP/SAVPF 111 0 8 c=IN IP4 192.168.0.103 a=recvonly a=mid:audio a=msid:216f6255-ac52-49d6-8cec-12934d0d07e6 f278e3d6-8de6-4d56-b4b6-ddd7d4e3bdca a=rtcp:9 IN IP4 0.0.0.0 a=rtcp-mux a=ssrc:2345380876 cname:6fbc1827-788d-4680-9661-04834f2e6e60 a=rtpmap:111 opus/48000/2 a=rtpmap:0 PCMU/8000 a=rtpmap:8 PCMA/8000 a=candidate:b89715db895181c999d86727b9f51bb3 1 udp 2130706431 192.168.0.103 52802 typ host a=candidate:cf8ef06208825ce085ab07b92f0d3cf2 1 udp 2130706431 10.8.0.146 51372 typ host a=candidate:e80addba40a8e15c833b46557f7ec693 1 udp 1694498815 150.129.165.127 3014 typ srflx raddr 192.168.0.103 rport 52802 a=end-of-candidates a=ice-ufrag:RM8p a=ice-pwd:38MWfcIWK7U1jwmlc0ulEl a=fingerprint:sha-256 28:6E:80:98:69:CA:D2:62:02:75:36:2A:9C:A1:D1:57:7C:13:C8:C3:52:D3:94:8B:F3:C8:19:47:CD:5F:FE:12 a=setup:active m=video 52802 UDP/TLS/RTP/SAVPF 96 97 100 101 c=IN IP4 192.168.0.103 a=recvonly a=extmap:13 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time a=mid:video a=msid:216f6255-ac52-49d6-8cec-12934d0d07e6 043e3bb7-8820-4ac7-8e2c-eb7f968cba3a a=rtcp:9 IN IP4 0.0.0.0 a=rtcp-mux a=ssrc-group:FID 4036425310 4231323663 a=ssrc:4036425310 cname:6fbc1827-788d-4680-9661-04834f2e6e60 a=ssrc:4231323663 cname:6fbc1827-788d-4680-9661-04834f2e6e60 a=rtpmap:96 VP8/90000 a=rtcp-fb:96 nack a=rtcp-fb:96 nack pli a=rtcp-fb:96 goog-remb a=rtpmap:97 rtx/90000 a=fmtp:97 apt=96 a=rtpmap:100 H264/90000 a=rtcp-fb:100 nack a=rtcp-fb:100 nack pli a=rtcp-fb:100 goog-remb a=fmtp:100 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42e01f a=rtpmap:101 rtx/90000 a=fmtp:101 apt=100 a=candidate:b89715db895181c999d86727b9f51bb3 1 udp 2130706431 192.168.0.103 52802 typ host a=candidate:cf8ef06208825ce085ab07b92f0d3cf2 1 udp 2130706431 10.8.0.146 51372 typ host a=candidate:e80addba40a8e15c833b46557f7ec693 1 udp 1694498815 150.129.165.127 3014 typ srflx raddr 192.168.0.103 rport 52802 a=end-of-candidates a=ice-ufrag:RM8p a=ice-pwd:38MWfcIWK7U1jwmlc0ulEl a=fingerprint:sha-256 28:6E:80:98:69:CA:D2:62:02:75:36:2A:9C:A1:D1:57:7C:13:C8:C3:52:D3:94:8B:F3:C8:19:47:CD:5F:FE:12 a=setup:active",
	"type":"answer"

}`

**Comment by ShwetaChauhan18** [comment]
@jlaine : I added offer and answer.

**Comment by jlaine** [comment]
The offer has absolutely no candidates, so there is no way for the connection to be established..
