### ISSUE TITLE
new offer/RTCPeerConnection from server side to client

### ISSUE THREAD

**Issue by adamteale** [aiortc/aiortc#334]
Hi!

Would anyone be willing to share with me some tips on how to create additional RTCPeerConnections FROM the server to a client/peer? 

(I am currently experimenting with the Server example)

For example once the first connection is created from the client/peer offer I would like to then create several additional connections to the peer FROM the server to send several video tracks (as I understand that it is not currently possible to add multiple tracks to a stream).

Is this sort of the idea?
- create a RTCPeerConnection instance (pc)
- create an offer (pc.createOffer()) and set it as the localDescription
- create a RemoteDescription using the existing connection's SDP 
- ?

I imagine I would need to extend the implementation in the client.js file to handle an offer from the server (some handler for "onTrack"?)? 

Or is it easier to send a message over the data channel to the client with something like "create new connection for track X" and have the client then create a new offer and add track X to it somehow?

Any help would be greatly appreciated!

Cheers

Adam

**Comment by adamteale** [comment]
Hi @jlaine ! Hats off to you for putting this library together! Thank you!

I have managed to get something working that resembles a multiple peer video chat (no audio yet)  that I think resembles a Multipoint Control Unit (MCU). 

This was a useful site:
https://www.html5rocks.com/en/tutorials/webrtc/basics/

I forked of aiortc and made a branch:
https://github.com/adamteale/aiortc/tree/feature/example-multiple-peers

If you or anyone has a moment to look at it I'd very much appreciate it. 

Currently running it over my local network seems to work - I generated the required cert/key pair and used https. 
It doesn't run very well (is quite slow) but the images from each computer/phone to appear.

Hopefully if I am actually on the right path I can put some time into making it run well and eventually document what I did to help others learning about webrtc / aiortc.

Many thanks!

Adam

**Comment by ilyas121** [comment]
Hi,

Any chance you could post an example? Link 404s :(

**Comment by dmzubr** [comment]
Also interested in this example:
aiortc/examples/server_rooms/

**Comment by Mohit-Ak** [comment]
@adamteale Can you please fix the broken link?
https://github.com/adamteale/aiortc

**Comment by adamteale** [comment]
@ilyas121 @Mohit-Ak @dmzubr apologies for the dead link, i have since reworked the solution i had and the repository is here:
http://github.com/adamteale/video_conference_example

It uses nginx, docker-compose, fastapi amongst other things.

It currently is setup for testing on a local network (you will see it is using a fixed ip address 192.168.100.7).
I have pretty much this setup working on a digital ocean droplet and have had up to 7 peers connected at once but it isn't the most reliable. 

In the production setup I have i added my own turn & stun server (coturn) to the DO droplet using - the peers find each other within a few seconds normally. Without adding the turn server sometimes peers don't find each other or it can simply take a long time for the ice.

I am in the process of writing up how I got this working.

I'd appreciate any feedback or PRs.

I had hoped to be able to have hundreds of peers connected to each other but it seems that in order to be able to that we would need to rework this so that the server distributes the streams, or maybe implement an MCU (multipoint control unit).
I had originally used the server to redistribute the streams but consumed the DO droplet i had. My implementation wasn't very good. I hope to look at it again soon.

**Comment by jangirrishabh** [comment]
@adamteale Hi! This is slightly off from the current discussion, but when you say 
' Or is it easier to send a message over the data channel to the client with something like "create new connection for track X" and have the client then create a new offer and add track X to it somehow?'

Did you figure out how to do this? Or any example in the current examples, any direction would be greatly appreciated! Thanks
