### ISSUE TITLE
Memory consumption is very high..

### ISSUE THREAD

**Issue by harry-dev98** [aiortc/aiortc#337]
using aiortc, I am trying to broadcast a stream from one webrtc connection to several others. one to many broadcast..
getting a stream from broadcaster's peer connection, i had to add those tracks to other peer connections. But when I store the stream tracks in some variable it consumes alot of memory(RAM) it increases rapidly like in 1 or 2 minutes it consumes about 3GB of RAM.
is there any other way without storing but still broadcasting.

**Comment by harry-dev98** [comment]
anyways thanks for aiortc.. <3

**Comment by jlaine** [comment]
Hi! As broadcasting is not natively supported, how did you solve your issue?

**Comment by harry-dev98** [comment]
i am storing the track as well as sending back to peer.. and anyone who is to connected to that room will create a new connection and that streams will be added

**Comment by hansenwuwu** [comment]
hi  , i am working on the same thing now.
I am taking peer A's stream, and i want send this stream to a "central server", and i store the track from peer A.
Then when a another peer (we say peer B) connect to the "central server", the server will add peer A track to it, and peer B can see peer A's stream.
But i came into a 2 issue,
First it seems consume a lot of resource, so when i connect 2 or 3 peer to server, it will be lag.
Second, when i use the "stored" track, and use "addTrack()" to attach to another connection, i will play the stream from start(when first time peer A connect with server). and go fastward.
Any idea or advise?
thanks !!!
