### ISSUE TITLE
[question] ice connection state stuck on "checking" / "connected"

### ISSUE THREAD

**Issue by adamteale** [aiortc/aiortc#339]
Hi!

I have been trying to work on an example of handling multiple peers / video tracks in the hope of creating a video conference.

I am finding that more often than not that a server->client ice connection state is stuck in “checking” or “connected”. I don’t see a “connectionstatechange complete” entry in the chrome://webrtc-internals log

When this occurs the video track doesn’t begin to be received in the client browser.

If I refresh the client browser then randomly the state will reach the “connected” state and video will be displayed.

I have been testing this using on my machine and on the local network (https), with and without stun and the results are the same.

My example project is here:
https://github.com/adamteale/aiortc/tree/master/examples/server_rooms

I've gone over there pages many many times and I am sure that I am following the correct procedure to establish a connection to a peer.

https://www.html5rocks.com/en/tutorials/webrtc/basics/
https://www.pkc.io/blog/untangling-the-webrtc-flow/
https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling
https://www.tutorialspoint.com/webrtc/webrtc_rtcpeerconnection_apis.htm

Any feedback would be appreciated!

Cheers

Adam

![camphoto_684387517](https://user-images.githubusercontent.com/7489774/79748277-29dcb400-82db-11ea-847b-813255fbed92.jpeg)

**Comment by adamteale** [comment]
Some good news, thanks to this SO post it seems to working:
https://stackoverflow.com/questions/38533288/how-to-begin-gathering-ice-candidates-for-peer-connection

> ICE gathering starts once you call setLocalDescription with the SDP you generated with createOffer or createAnswer.
> 
> If you don't want to use trickle ice, wait for the null candidate and then send the content of peerConn.localDescription.sdp -- which should include the candidates then.

So on the client side I now wait until the icecandidate event receives a null candidate then send the answer back to the server. So far so good!

**Comment by jlaine** [comment]
Fantastic, thanks for reporting back!
