### ISSUE TITLE
Missing "contentHint" MediaStreamTrack hint

### ISSUE THREAD

**Issue by dylan-brasseur** [aiortc/aiortc#340]
Hi,
I haven't found any mention of the "contentHint" track hint in your code.
Specs : https://www.w3.org/TR/mst-content-hint
It allows the senders and receivers to choose the right encoding/decoding patterns to optimise the quality of the content ("details" will give much better texts, but "motion" will give better webcams for examples)

Any plans about implementing this feature in aiortc ?

Thanks, Dylan

**Comment by jlaine** [comment]
This wasn't on my radar so I don't have any plans at the moment to implement it. However I'd gladly review a pull request.
