### ISSUE TITLE
SDP fails validation if answer media sections come in different order

### ISSUE THREAD

**Issue by ykvch** [aiortc/aiortc#341]
_Note: example is simplified purely synthetic for easy reproduce_

## Preconditions:
Use examples videostream-cli/cli.py
audio-video.mp4 contains 1 video and 1 audio track

## Steps:
1. Console0: run `python cli.py offer --play-from audio-video.mp4`
2. Console0: Copy offer message
3. Console1: run `python cli.py answer`
4. Console1: Paste offer (from step 2)
5. Console1: copy answer message
6. Edit answer to switch places of entire media sections (`m=`)
7. Console0: paste edited SDP answer

## Expected:
Connection established

Actual:
Error with traceback
```
Traceback (most recent call last):
  File "cli.py", line 155, in <module>
    loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "cli.py", line 109, in run
    await pc.setRemoteDescription(obj)
  File "/home/user/aiortc/src/aiortc/rtcpeerconnection.py", line 754, in setRemoteDescription
    self.__validate_description(description, is_local=False)
  File "/home/user/aiortc/src/aiortc/rtcpeerconnection.py", line 1148, in __validate_description
    raise ValueError("Media sections in answer do not match offer", answer_media, offer_media)
ValueError: ('Media sections in answer do not match offer', [('video', '1'), ('audio', '0')], [('audio', '0'), ('video', '1')])
```

## Possible fix
(rtcpeerconnection.py:1143)
```
offer_media = {(media.kind, media.rtp.muxId) for media in offer.media}
answer_media = {(media.kind, media.rtp.muxId) for media in description.media}  # use sets for validation
```

**Comment by jlaine** [comment]
Why would you mess with the order of `m=` sections? The error message is correct: answers MUST have their `m=` sections in the same order as the offer.

`
  For each "m=" line in the offer, there MUST be a corresponding "m="
   line in the answer.  The answer MUST contain exactly the same number
   of "m=" lines as the offer.  This allows for streams to be matched up
   based on their order.  This implies that if the offer contained zero
   "m=" lines, the answer MUST contain zero "m=" lines.
`

https://tools.ietf.org/html/rfc3264#section-6

**Comment by ykvch** [comment]
That paragraph missed my attention, thank You for explaining.

**Comment by ykvch** [comment]
That paragraph missed my attention, thank You for explaining.
