### ISSUE TITLE
aiortc failed to connect to remote janus server on DTLS protocol

### ISSUE THREAD

**Issue by moliqingwa** [aiortc/aiortc#346]
Here are the snapshot of DTLS during connecting to janus server.
It seems the client does NOT send "New Session Ticket" to finished the connection process, and it will cause janus server always to send Client Certificate to aiortc client.

Have you encounter this issue before? Thanks:)

![201587370177_ pic_hd](https://user-images.githubusercontent.com/6396473/80490493-04634080-8994-11ea-8c01-374b6219280b.jpg)

**Comment by jlaine** [comment]
Hi! I'm not sure I understand what you mean, as far as I know there is not concept of session tickets in DTLS. How would session resumption even work, since client and server generate certificate/key pairs on the fly?

**Comment by moliqingwa** [comment]
> Hi! I'm not sure I understand what you mean, as far as I know there is no concept of session tickets in DTLS. How would session resumption even work, since both parties generate certificate/key pairs on the fly?

The issue is resolved, by updating janus openssl version to 1.1.1. Thanks any way:)

**Comment by jlaine** [comment]
okidoki, thanks for letting me know!

**Comment by zhiyong0804** [comment]
@jlaine @moliqingwa i have the same problem, aiortc donot send "New Session Ticket" and "ChangeCipherSpec" to finish DTLS negotiation, cause dtls timeout error in janus server. so which version do you upgrade to fix it ? my version is 1.1.1d

**Comment by zhiyong0804** [comment]
i have fixed it with 1024 cert file in janus, but i donot think it's proper way, the root cause is package size assumed MTU, so the network drop it, You can verify this by using, e.g., a 4096 bits certificate, and capture the DTLS traffic with Wireshark, janus server processed it with filter BIO, and i think aiortc need do it too. @jlaine
