### ISSUE TITLE
What is the purpose of each example? (Janus)

### ISSUE THREAD

**Issue by esselesse** [aiortc/aiortc#348]
It is not quite clear, what **exactly** we should see when launch sample code.
For example, what do i need to do and see when i want to launch 'janus' sample?
Should the server be online?
How exactly should i launch it?

For example, what i do:
1) 
`python examples/server/server.py`
it launches

![image](https://user-images.githubusercontent.com/5176168/80802707-c85cf500-8bb8-11ea-9504-e683435e47fd.png)
seems to be ok.

2) in second terminal:
`python examples/janus/janus.py http://localhost:8080/janus`

and we have

> (venv) C:\Users\esselesse\Desktop\aiortc-master>python examples/janus/janus.py http://localhost:8080/janus
Traceback (most recent call last):
  File "examples/janus/janus.py", line 175, in <module>
    loop.run_until_complete(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "examples/janus/janus.py", line 95, in run
    await session.create()
  File "examples/janus/janus.py", line 58, in create
    data = await response.json()
  File "C:\Users\esselesse\venv\lib\site-packages\aiohttp\client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('http://localhost:8080/janus')

i know that i am beginner in python and this stuff at all, but why there is no mention of this kind of problem? or what i do wrong?

**Comment by esselesse** [comment]
and yes, there is a lot of such a stuff

> (venv) C:\Users\esselesse\Desktop\aiortc-master>pip install uvloop
Collecting uvloop
  Downloading uvloop-0.14.0.tar.gz (2.0 MB)
     |████████████████████████████████| 2.0 MB 547 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\esselesse\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\esselesse\\AppData\\Local\\Temp\\pip-install-g3j2twj1\\uvloop\\setup.py'"'"'; __file__='"'"'C:\\Users\\essel
esse\\AppData\\Local\\Temp\\pip-install-g3j2twj1\\uvloop\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' eg
g_info --egg-base 'C:\Users\esselesse\AppData\Local\Temp\pip-pip-egg-info-i2z_gmyk'
         cwd: C:\Users\esselesse\AppData\Local\Temp\pip-install-g3j2twj1\uvloop\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\esselesse\AppData\Local\Temp\pip-install-g3j2twj1\uvloop\setup.py", line 15, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Haesmen** [comment]
If I’m not mistaken, you have a problem with Janus. For example, does Janus 8080 listen on the port on the localhost.

**Comment by esselesse** [comment]
i just run the example with only change of address and port 
(just changed it to 127.0.0.1:8080, where server from server sample is working)

**Comment by Haesmen** [comment]
for example with janus should be configured https://github.com/meetecho/janus-gateway either use https://janus.conf.meetecho.com/

**Comment by esselesse** [comment]
> for example with janus should be configured https://github.com/meetecho/janus-gateway either use https://janus.conf.meetecho.com/

but where is some information about it in examples? because it is not clear without any mention

**Comment by jlaine** [comment]
There is a README.rst per example, in your case:

https://github.com/aiortc/aiortc/blob/master/examples/janus/README.rst

As stated in the README.rst this is a publisher which sends media to a Janus room. If you feel some additional information could be added feel free to submit a pull request.
