### ISSUE TITLE
librsvg ERROR on aiortc/examples/server

### ISSUE THREAD

**Issue by Sanix-Darker** [aiortc/aiortc#352]
After following steps on the README and launch `python server.py`, am getting this error :
```
Traceback (most recent call last):
  File "server.py", line 11, in <module>
    from av import VideoFrame
  File "/home/d4rk3r/.local/lib/python3.7/site-packages/av/__init__.py", line 9, in <module>
    from av._core import time_base, pyav_version as __version__, library_versions
ImportError: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end
```

How can i fix it please ? Am on Debian 10 Buster !

**Comment by jlaine** [comment]
Please reinstall in a clean virtual environment, or at the very least clear out your `~/.local/lib/python3.7` which apparently contains some bad packages.

**Comment by Sanix-Darker** [comment]
ok...i found how to fix it :
```
apt install libavdevice-dev libavfilter-dev libopus-dev libvpx-dev pkg-config
apt-get install libsrtp2-dev
```

And running `python server.py` as `root` !
```
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
```

**Comment by jlaine** [comment]
For the packages to install, yes this is documented in the README, maybe read it next time.

There is absolutely no reason to run the process as root.
