### ISSUE TITLE
Error when I click on the join button

### ISSUE THREAD

**Issue by shahabjld** [aiortc/aiortc#357]
Hey, 
I get the following error when I run apprc.py and then I open the browser and click on the join button.
`Traceback (most recent call last):
  File "apprtc.py", line 132, in <module>
    run(pc=pc, player=player, recorder=recorder, signaling=signaling)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "apprtc.py", line 86, in run
    await pc.addIceCandidate(obj)
TypeError: object NoneType can't be used in 'await' expression
`

**Comment by jlaine** [comment]
The `master` version of `aiortc` (not on PyPI yet) has a breaking API change: `addIceCandidate` is now a coroutine (see 31abde4c7f142527a2a59c76333aafe627d4b2c6), so your examples and `aiortc` version need to match.

Either:

- use `aiortc` from PyPI, and the examples from tag `0.9.28`

or

- use `aiortc` and examples from `master`
