### ISSUE TITLE
Peer to peer connection custom signaling server(tcp-socket)

### ISSUE THREAD

**Issue by SourceCodeZone** [aiortc/aiortc#358]
I am trying to make peer to peer connection from raspbarryPi to another webserver for webcam stream, where I have to usecustom signalling server using peerjs-server https://github.com/peers/peerjs-server. 

Basically I am using the code from datachannel client example https://github.com/aiortc/aiortc/tree/master/examples/datachannel-cli

The signaling server run at 192.168.1.140 and pot 7000, I confirmed signaling server is working by running html/js webrtc sample. 

But when I run below code, I am getting the some error.

`python3 test.py offer --signaling tcp-socket  --signaling-host 192.168.1.140 --signaling-port 7000 --signaling-path /
`
  ```
parser = argparse.ArgumentParser(description="Data channels ping/pong")
    parser.add_argument("role", choices=["offer", "answer"])
    parser.add_argument("--verbose", "-v", action="count")
    add_signaling_arguments(parser)

    args = parser.parse_args()

    if args.verbose:
        logging.basicConfig(level=logging.DEBUG)

    signaling = TcpSocketSignaling("192.168.1.140","7000")
    pc = RTCPeerConnection()
    if args.role == "offer":
        coro = run_offer(pc, signaling)
    else:
        coro = run_answer(pc, signaling)

    # run event loop
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(coro)
    except KeyboardInterrupt:
        pass
    finally:
        loop.run_until_complete(pc.close())
        loop.run_until_complete(signaling.close())
``` 

Error:
```
channel(chat) - created by local party
Traceback (most recent call last):
  File "test.py", line 119, in <module>
    loop.run_until_complete(coro)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "test.py", line 93, in run_offer
    await signaling.send(pc.localDescription)
  File "/home/pi/.local/lib/python3.7/site-packages/aiortc/contrib/signaling.py", line 203, in send
    await self._connect(True)
  File "/home/pi/.local/lib/python3.7/site-packages/aiortc/contrib/signaling.py", line 176, in _connect
    client_connected, host=self._host, port=self._port
  File "/usr/lib/python3.7/asyncio/streams.py", line 114, in start_server
    return await loop.create_server(factory, host, port, **kwds)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1378, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 99] error while attempting to bind on address ('192.168.1.140', 7000): cannot assign requested address

```

**Comment by jlaine** [comment]
Hi!

The arguments for the TCP signaling method are a bit confusing, maybe that's the source of the problem. 

The offerer becomes the TCP server, in the following example it will *listen on* port 7000 of `192.168.1.140`:

`python examples/datachannel-cli/cli.py --signaling tcp-socket --signaling-host 192.168.1.140 --signaling-port 7000 offer`

The answerer becomes the CP client, in the following example it will *connect to* port 7000 of `192.168.1.140`:

`python examples/datachannel-cli/cli.py --signaling tcp-socket --signaling-host 192.168.1.140 --signaling-port 7000 answer`

=> the IP address you pass is the one of the server (= offerer)

**Comment by SourceCodeZone** [comment]
Actually with the above example, I want to use custom signaling server https://github.com/peers/peerjs-server. And the IP of the server is 192.168.1.140 and port is 7000.

Can you please provide some examples using tcp-socket signaling. I have to achieve peer to peer communication using tcp-signaling.

**Comment by jlaine** [comment]
I just gave you an example for the TCP signaling example which ships with `aiortc`. This doesn't automagically make the signaling protocol the same as the one used by PeerJS.

Maybe take a look at:

https://github.com/ambianic/peerjs-python

**Comment by SourceCodeZone** [comment]
Thanks for the feedback, one more question, is it possible to achieve peer to peer connection between two client if both are in different network with current signaling method  provided by aiortc.

**Comment by jlaine** [comment]
Give the `apprtc` signaling method a try, it uses appr.tc's public server to convey signaling between the clients.

**Comment by SourceCodeZone** [comment]
I resolved it by using the implementation of WebsocketSignaling: as show in here https://github.com/ryogrid/aiortc-dc/blob/c24ab64f9a7be66e22d8050fc01f376e55e6f24b/aiortcdc/contrib/signaling.py#L180

For the signaling server I have used nodejs(on my own Ubuntu server) and the code here https://www.tutorialspoint.com/webrtc/webrtc_signaling.htm.
