### ISSUE TITLE
On RTCPeerConnection end

### ISSUE THREAD

**Issue by andriy-tsvikla** [aiortc/aiortc#359]
Hi, i am using modified server.py example.
I am trying to run logic in
```
@pc.on("iceconnectionstatechange")
  async def on_iceconnectionstatechange():
```  
 listener, on "closed", "failed", "disconnected" state,
 but it is not executed when i close connection from client.

Please help me understand is there any working way to detect when RTCPeerConnection ended from client side - closed/disconnected and run function after that? 
Or maybe i just need to fix my code and listener works as expected.
Thanks.

**Comment by nithins** [comment]
@andriy-tsvikla Have the same issue. It seems to be very hard to get an accurate read on the connection state. One way I've found that works for data channels works like follows 

```python
pc = RTCPeerConnection()
channel = pc.createDataChannel("datachannel")    

@channel.on("open")
def on_open():
    async def channelWatch():
        while True:
            if channel.transport.transport.state == "closed":
                pc.close()
                break 
            await asyncio.sleep(10)
    asyncio.channelWatch(channelWatch())
```

**Comment by Laityned** [comment]
Is there any progress in detecting if a peer connection is still valid or disconnected? 
Right now I still cannot detect if a peer client has disconnected and the peer client should be removed from the set of clients.

However what I noted is that the dtls transport detects that the connection is closed and the stream track too.
The rtp module is still logging a internetpackage

**Comment by jlaine** [comment]
There is a work-in-progress PR for this in #465

**Comment by jlaine** [comment]
RTCPeerConnection gained a `connectionState` attribute and a `connectionstatechange` event
