### ISSUE TITLE
possible memory leak with janus example and Alsa MediaRecorder

### ISSUE THREAD

**Issue by carltondraught** [aiortc/aiortc#361]
Hi there, first: thanks for the great project, its really cool :)

I am using the janus.py example as a starting point for a projet, and am noting a very fast accumulation of memory as soon as I add a 'live' MediaRecorder.

It seems easy to reproduce, around line [241](https://github.com/aiortc/aiortc/blob/master/examples/janus/janus.py#L241) of janus.py i insert:

```
# create media sink
recorder = MediaRecorder('hw:1,0', format='alsa')
```
(i.e. play the Janus audio on my local speaker, i can't work out how to pass that via command line param)

I launch the example against a local Janus but it works for the public instance as well:

```
python janus.py  https://janus.conf.meetecho.com/janus
```

and i can watch the memory go up > 1G in about 30s, in a seemingly linear fashion. It works fine, I can hear Janus audio, and Janus receives my video & audio, but after a short while i've consumed all my memory.

I played with [mem_top](https://pypi.org/project/mem_top/) and can observe certain objects which accumulate: (AudioLayout/AudioFrame)

```
refs:
5938	<class 'collections.deque'> deque([<av.AudioFrame 0, pts=960, 960 samples at 48000Hz, stereo, s16 at 0xab4f62f0>, <av.AudioFrame
1956	<class 'collections.deque'> deque([<av.VideoFrame #0, pts=237600 yuv420p 640x480 at 0xaac95670>, <av.VideoFrame #0, pts=243360 y
1694	<class 'dict'> {3982612: <weakref at 0xb67c8630; to 'type' at 0x3cc514 (type)>, 3960288: <weakref at 0xb67c8870; to
1467	<class 'dict'> {'__name__': 'lib', '__doc__': None, '__package__': None, '__loader__': None, '__spec__': None, '_or
1461	<class 'dict'> {'CRYPTOGRAPHY_PACKAGE_VERSION': <cdata 'char *' 0xacab2b50>, 'Cryptography_HAS_EC2M': 1, 'Cryptogra
1000	<class 'list'> [<aiortc.rate.RateBucket object at 0xabeaeb50>, <aiortc.rate.RateBucket object at 0xabeaeb70>, <aior
1000	<class 'list'> [<aiortc.rate.RateBucket object at 0xab4c8190>, <aiortc.rate.RateBucket object at 0xab4c81b0>, <aior
557	<class 'list'> ['argparse', 'asyncio', 'logging', 'random', 'string', 'time', 'mem_top', 'mem_top', 'aiohttp', 'aio
485	<class 'dict'> {'sys': <module 'sys' (built-in)>, 'builtins': <module 'builtins' (built-in)>, '_frozen_importlib':
482	<class 'set'> {'sunrast', 'libwebp', 'paf_audio', 'imm4', 'avrp', 'h261', 'truemotion2', 'utvideo', 'pcm_s24le_pla

bytes:
41020	 {'__name__': 'lib', '__doc__': None, '__package__': None, '__loader__': None, '__spec__': None, '_or
41020	 {'CRYPTOGRAPHY_PACKAGE_VERSION': <cdata 'char *' 0xacab2b50>, 'Cryptography_HAS_EC2M': 1, 'Cryptogra
24872	 deque([<av.AudioFrame 0, pts=960, 960 samples at 48000Hz, stereo, s16 at 0xab4f62f0>, <av.AudioFrame
20544	 {3982612: <weakref at 0xb67c8630; to 'type' at 0x3cc514 (type)>, 3960288: <weakref at 0xb67c8870; to
16500	 {'sunrast', 'libwebp', 'paf_audio', 'imm4', 'avrp', 'h261', 'truemotion2', 'utvideo', 'pcm_s24le_pla
10300	 {'sys': <module 'sys' (built-in)>, 'builtins': <module 'builtins' (built-in)>, '_frozen_importlib':
10300	 {'__name__': 'os', '__doc__': "OS routines for NT or Posix depending on what system we're on.\n\nThi
10300	 {'__name__': 'socket', '__doc__': "This module provides socket operations and some related functions
10300	 {'__name__': '_socket', '__doc__': 'Implementation module for socket operations.\n\nSee the socket m
10300	 {'__name__': '_socket', '__doc__': 'Implementation module for socket operations.\n\nSee the socket m

types:
8489	 <class 'function'>
6818	 <class 'tuple'>
5942	 <class 'av.audio.layout.AudioLayout'>
5941	 <class 'av.audio.frame.AudioFrame'>
5874	 <class 'av.video.format.VideoFormatComponent'>
5737	 <class 'dict'>
2684	 <class 'weakref'>
2518	 <class 'builtin_function_or_method'>
2102	 <class 'getset_descriptor'>
2002	 <class 'aiortc.rate.RateBucket'>
```

doing a:
```
sudo pmap 9884 
```

where 9884 is the pid of my python process also shows an ever-growing list of  entries like:
```
....
6c800000    904K rw---   [ anon ]
6c8e2000    120K -----   [ anon ]
6c900000    904K rw---   [ anon ]
6c9e2000    120K -----   [ anon ]
6ca00000    904K rw---   [ anon ]
6cae2000    120K -----   [ anon ]
....
```
Is this a known issue / abnormal, can you give me any advice on how to track down where the memory is accumulating ? 

For info I'm running on a raspberry pi, Python 3.7.3:

```
aiohttp==3.6.2
aioice==0.6.18
aiojobs==0.2.2
aiortc==0.9.28
av==8.0.1
```
```
ffmpeg version 4.1.4-1+rpt7~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Raspbian 8.3.0-6+rpi1)
```

cheers

-i

**Comment by carltondraught** [comment]
I should add to that that the memory leak only appears when there is another publisher in the room, in order for the MediaRecorder to be used. So to reproduce you need to join the room in your browser before executing the example, otherwise the memory stays constant.

**Comment by carltondraught** [comment]
ok so i worked it out, and i guess it was fairly simple.

The MediaRecorder I am using is just an audio player, (alsa soundcard), and the subscribe() method provided in the example asked to subscript to audio and video, so i suppose the video was accumulating in memory after never being consumed.

I added `"video": False` to the join/subscribe request dict on line [156](https://github.com/aiortc/aiortc/blob/master/examples/janus/janus.py#L156) and the memory stays constant at < 100K now.

might be interesting to add a comment to the example or the README for noobs like me.

thanks again for your awesome project ! :)

**Comment by jlaine** [comment]
Thanks for getting to the bottom of this. You are right, creating tracks which are never read from will accumulate in memory. I'm kind of surprised the call to `recorder.addTrack` didn't trigger an error when adding the video track to a container which doesn't support it?

**Comment by carltondraught** [comment]
To answer your question I just confirmed that in the `@pc.on("track")` callback `recorder.addTrack()` can be called for audio and video, on a recorder created like this:

```
recorder = MediaRecorder('hw:1,0', format='alsa')
```

.. and it 'works' in the sense that memory does not accumulate, and no type of error indicating that this device doesn't handle video is raised.

My original problem was that, knowing the output device was a soundcard, I avoided adding the track when its `kind` was video, and hence exploded my memory coz the track was never consumed.

I now specifically don't ask for it in the Janus subscribe method and therefore don't need to add it to the recorder. you can close the issue because there is no bug here in my opinion

if my project ever sees light i'll post a link to it from here for prosperity: it's a poormans' amazon ring -style doorbell using a pi/webcam to 'call' (via janus / aiortc) an app on my phone to eventually open the front gate.

thanks again,

-ivan
