### ISSUE TITLE
Slow Connection Outside of LAN

### ISSUE THREAD

**Issue by douglasJovenil** [aiortc/aiortc#362]
Hello guys, first of all, thanks for the lib, it's very useful.

I'm trying to implement a Python application using aiortc running on Raspberry, only to send a video stream to a JavaScript application using SimplePeer.

Currently I implemented a server with Node for hosting and Socket.IO for change messages, an application using JS for testing purposes and another application using Python.

### Problem
For explanation purposes, lets call the application that sends the stream of SENDER and the application that's receives of RECEIVER, then bellow there's a description and code of how the communication occurs:

#### JavaScript to JavaScript (LAN)
Just to exemplify how it woks, there's a gif showing the stream process between two browsers (JavaScript with SimplePeer) on same computer, with this example, we can say that my server is working fine, since the Sender and Receiver are changing messages between it.

![ezgif-6-e04c9a8ac5c7](https://user-images.githubusercontent.com/32784972/81935573-3943da00-95c7-11ea-81d9-9ec0e0d5047d.gif)

We can see that the first one to access the server will be the Sender, then will it generate a link with a token. When someone open another tab with this link, the connection will happen. In this case the stream works fine without disconnection or lagging, this code works in two different networks.

#### Python to JavaScript (LAN)
In this example is running a code with aiortc library that's connect to server and generate a room, then the Receiver will get this link and past it at navigator, this code will be explained with more details after. We can see in the next gif, at init of the stream occurs a little lag but after this the stream works properly.

![PythonToJavaScriptSameComputer](https://user-images.githubusercontent.com/32784972/81939443-b9b90980-95cc-11ea-9737-f54b37286f78.gif)

So I thought that my code is fine, but when i tried to run the same code in two different networks the problem appears.

#### Python to JavaScript (outside of LAN)

In this example I will get the URL generated for computer A (Python) and paste it at the navigator of computer B.

![PythonToJavaScriptDifferentNetwork](https://user-images.githubusercontent.com/32784972/81948574-44533600-95d8-11ea-9d2c-55414d0faaa7.gif)

So we can see, after a few frames the stream freezes. The python terminal show the following:

```bash
ICE connection state is checking
ICE connection state is completed
ICE connection state is failed
ICE connection state is closed
Task exception was never retrieved
future: <Task finished coro=<TurnClientMixin.delete() done, defined at /home/douglas/Desktop/sinostec/raspberry/app/venv/lib/python3.6/site-packages/aioice/turn.py:139> exception=TransactionFailed(Message(message_method=Method.REFRESH, message_class=Class.ERROR, transaction_id=b'e\x84\x03\xea}#Y,\xe9\xb9\xb2\x1f'),)>
Traceback (most recent call last):
  File "/home/douglas/Desktop/sinostec/raspberry/app/venv/lib/python3.6/site-packages/aioice/turn.py", line 151, in delete
    await self.request(request)
  File "/home/douglas/Desktop/sinostec/raspberry/app/venv/lib/python3.6/site-packages/aioice/turn.py", line 186, in request
    return await transaction.run()
  File "/home/douglas/Desktop/sinostec/raspberry/app/venv/lib/python3.6/site-packages/aioice/stun.py", line 292, in run
    return await self.__future
aioice.stun.TransactionFailed: STUN transaction failed (437 - Allocation Not Found)
```

I thought that can be a problem with the video transform of rotation but i tried to remove it and the problem persist.

### Code
Follows the code's principals steps :

> Sender request to the server for a room (URL), sending a token to the topic **join_caller** of the Socket.IO
```python
await sio.connect(host)
# the token object generates and token based on the actual datetime
await sio.emit('join_caller', { 'token': token.getToken() })
```

> Sender creates a RTCPeerConnection and add the video stream to it
```python
iceServers = []
iceServers.append(RTCIceServer('stun:stun.l.google.com:19302'))
iceServers.append(RTCIceServer('stun:numb.viagenie.ca'))
iceServers.append(RTCIceServer('turn:numb.viagenie.ca', username='username', credential='credential'))

pc = RTCPeerConnection(RTCConfiguration(iceServers))

options = {"framerate": "30", "video_size": "640x480"}
player = MediaPlayer("/dev/video0", format="v4l2", options=options)

if player and player.video:
    pc.addTrack(VideoTransform(player.video))
```

> Server creates an offer and set his LocalDescription with it, then awaits for a connection
```python
await pc.setLocalDescription(await pc.createOffer())
await sio.wait()
```

> Server adds the socket of the Sender to the room, using the received token as id for the room
```js
socket.on('join_caller', data => {
    console.log(`server join_caller: ${config.consts.EXTERNAL_HOST}/${data.token}`);
    addSocketToDiscussion(data.token, socket);
});
```

> Receiver join the room (URL) and creates a SimplePeer with initiator as false
```python
peer = new SimplePeer({
      initiator: false,
      trickle: false,
      config: { 
        iceServers: [
          { urls: 'stun:stun.l.google.com:19302' },
          { urls: 'stun:numb.viagenie.ca' },
          {
              urls: 'turn:numb.viagenie.ca',  
              username: 'username',
              credential: 'credential'
          }
        ] 
      },
      iceTransportPolicy: 'any',
});
```

> Receiver emit to topic **join_callee** sending the token
```python
# The URL generated by the server uses the token of Sender, so the Receiver gets this token by URL
signaling_server.emit('join_callee', {
      token: token.getToken()
});
```

> Server adds the socket of the Receiver to the room created previously and notify the Sender that's the Receiver already arrived, sending the token to topic **callee_arrived**
```js
socket.on('join_callee', data => {
    console.log(`server join_callee: ${data.token}`);

    addSocketToDiscussion(data.token, socket);
    sendResponse(data.token, socket.id, 'callee_arrived', data);
});
```

> Sender emit to topic **new_description** his **SDP** with type **offer**
```python
@sio.event
async def callee_arrived(data):
  sdp = loads(object_to_string(pc.localDescription))

  await sio.emit('new_description', {
    'token': token.getToken(),
    'sdp': sdp
  })
```

> Server sends the received **SDP** to the Receiver, using the topic **new_description**
```js
socket.on('new_description', data => {
    console.log(`server new_description: ${data}`);
    sendResponse(data.token, socket.id, 'new_description', data);
});
```

> Receiver gets the received **SDP** and fires an event of signal for his peer, that will set the LocalDescription and generates an answer.
```js
signaling_server.on('new_description', data => {
      console.log(`calle new_description ${data}`);
      peer.signal(data.sdp);
})
```

> Receiver sends the **SDP** with type **answer** to the topic **new_description**
```python
peer.on('signal', data => {
      signaling_server.emit('new_description', {
        token: token.getToken(),
        sdp: data
      });
});
```

> Server sends the received **SDP** to the Receiver
```js
socket.on('new_description', data => {
    console.log(`server new_description: ${data}`);
    sendResponse(data.token, socket.id, 'new_description', data);
});
```

> Receiver gets the **SDP** and set his RemoteDescription
```python
@sio.event
async def new_description(data):
  descr = object_from_string(dumps(data['sdp']))

  if isinstance(descr, RTCSessionDescription):
    await pc.setRemoteDescription(descr)
  elif isinstance(descr, RTCIceCandidate):
    pc.addIceCandidate(descr)
```

> Full Python code
```python
from aiortc import RTCIceCandidate, RTCPeerConnection, RTCSessionDescription, RTCConfiguration, RTCIceServer
from aiortc.contrib.signaling import object_to_string, object_from_string
from aiortc.contrib.media import MediaPlayer

from VideoTransform import VideoTransform
from json import loads, dumps
from Token import Token
import socketio
import asyncio
import pathlib


sio = socketio.AsyncClient(ssl_verify=False)
token = Token()

iceServers = []
iceServers.append(RTCIceServer('stun:stun.l.google.com:19302'))
iceServers.append(RTCIceServer('stun:numb.viagenie.ca'))
iceServers.append(RTCIceServer('turn:numb.viagenie.ca', username='username', credential='credential'))

pc = RTCPeerConnection(RTCConfiguration(iceServers))


def main():
  # Carrega as configuracoes do JSON
  current_path = pathlib.Path(__file__).parent.absolute()
  with open(f'{current_path}/config.json', 'r') as f:
    config = loads(f.readlines()[0])
  # Servidor nodejs
  host = config['consts']['EXTERNAL_HOST']

  loop = asyncio.get_event_loop()
  try:
    loop.run_until_complete(connect(host))
  except KeyboardInterrupt:
    pass
  finally:
    loop.run_until_complete(pc.close())

async def connect(host):
  await sio.connect(host)
  await sio.emit('join_caller', { 'token': token.getToken() })

  # add_tracks
  options = {"framerate": "30", "video_size": "640x480"}
  player = MediaPlayer("/dev/video0", format="v4l2", options=options)

  if player and player.video:
    pc.addTrack(VideoTransform(player.video))

  await pc.setLocalDescription(await pc.createOffer())
  
  await sio.wait()

@sio.event
async def callee_arrived(data):
  sdp = loads(object_to_string(pc.localDescription))

  await sio.emit('new_description', {
    'token': token.getToken(),
    'sdp': sdp
  })

@sio.event
async def new_description(data):
  descr = object_from_string(dumps(data['sdp']))

  if isinstance(descr, RTCSessionDescription):
    await pc.setRemoteDescription(descr)
  elif isinstance(descr, RTCIceCandidate):
    pc.addIceCandidate(descr)

@pc.on("iceconnectionstatechange")
async def on_iceconnectionstatechange():
  print(f'ICE connection state is {pc.iceConnectionState}')
  if pc.iceConnectionState == "failed":
    await pc.close()


if __name__ == '__main__':
  main()

```

### Software Configuration
- Python:
  - aiortc==0.9.28
  - aiohttp==3.6.2
  - aioice==0.6.18
  - av==8.0.1
- JavaScript Server:
  - "express": "^4.17.1",
  - "ngrok": "^3.2.7",
  - "socket.io": "^2.3.0"
- JavaScript Client:
  - [GetUserMedia](https://github.com/otalk/getUserMedia/blob/master/getusermedia.bundle.js) 
  - [SimplePeer](https://github.com/feross/simple-peer/blob/master/simplepeer.min.js) 

I hope the description hasn't been too long, but I tried to include all details about the communication. Also is worth to comment that I looked to at some examples make my code, they are:
- [Server-aiortc](https://github.com/aiortc/aiortc/tree/master/examples/server)
- [Balena-Cam](https://github.com/balenalabs/balena-cam/tree/eb3519da565fb25a4b532a9b823f82eb86ea484b/balena-cam/app)

In this examples, the approach is different, where the server gets the video stream and sends to the client, in my case is the opposite, the client gets the stream and sends the stream to server, then the server sends to the client, maybe the problem is related to it.

So if anyone has any ideia how to solve the connection Python to JavaScript outside of LAN, I appreciate it so much.

Greetings, Douglas Santos

**Comment by alanlei** [comment]
Ngrok will cause high latency issue. You should use webRTC instead of it.

**Comment by jlaine** [comment]
Your error seems to be due to aioice failing to keep the TURN allocation alive. There have been numerous fixes to the TURN code in recent releases, could you please retry and report back?
