### ISSUE TITLE
Using MediaRecorder with pulse audio

### ISSUE THREAD

**Issue by monkey-b** [aiortc/aiortc#363]
Hi,
First, congrats for this project. I like it very much.
I am not sure this is a bug/question for aiortc or for PyAV. 
I'm trying to implement a use case where I send audio/video to a party and receive audio from another party through the speakers in a janus videoroom.
I use a modified code from the janus example.

All the sending audio/video works great.
Receiving the audio is good. When i record it in a file, it gives me what I want.
`arecorder = MediaRecorder('recording.wav')`
(the codec in opus but for some reason I need to use wav extension.)

I can also playback the audio on speaker with alsa:
`arecorder = MediaRecorder('hw:0','alsa')`
However the mic picks up the speaker output leading to horrible echo in the sent audio feed.

To counter that, I am trying to playback the audio stream through pulseaudio (in order to use the echo-cancel module).
Recording through the echo-cancel is ok.
`aplayer = MediaPlayer('echoCancel_source', format='pulse')`

Playing the file through echo-cancel is fine using:

> ffmpeg -i recording.wav -f alsa -codec copy -ac 1 -device echoCancel_sink "streamname"
> aplay -D pulse recording.wav

I have been struggling to make MediaRecorder playback through the echoCancel_sink pulse device.
`arecorder = MediaRecorder('echoCancel_sink', format='pulse', options={'device': 'echoCancel_sink', 'name': 'application', 'stream_name': 'output', 'codec': 'copy'})`
Gives me this error
Invalid sample spec.

`arecorder = MediaRecorder('pulse', format='alsa', options={})`
Gives me ultra slow distorted sound, and the other feeds are slowed and delayed.
I get the same effect when using ffmpeg to play the file without -codec copy

Any idea of how i could play to echoCancel_sink, either through alsa or directly through pulse?
It feels like some options are missing or not taken into account when calling MediaRecorder.

Sorry if this request doesn't belong to the aiortc scope.
Any help/hint appreciated.

**Comment by monkey-b** [comment]
Here is the pulseaudio configuration for echo-cancellation:
/etc/pulse/client.conf
`autospawn = yes`

/etc/pulse/default.pa
```
load-module module-echo-cancel use_master_format=1 aec_method=webrtc aec_args="analog_gain_control=0\ digital_gain_control=1\ noise_suppression=1" source_name=echoCancel_source sink_name=echoCancel_sink
set-default-source echoCancel_source
set-default-sink echoCancel_sink
```

**Comment by jlaine** [comment]
Hi! `aiortc`'s `MediaRecorder` builds upon the FFmpeg libraries through the `PyAV` bindings. I suggest you take a look at the FFmpeg and PyAV documentations, as I'm unfortunately unable to test every possible configuration.
