### ISSUE TITLE
DTLS handshake failed when connected to janus

### ISSUE THREAD

**Issue by moliqingwa** [aiortc/aiortc#365]
![image](https://user-images.githubusercontent.com/6396473/82455968-30cb3200-9ae6-11ea-8da0-b80eb134b80b.png)

Does any of you have encounted this issue, it seems the DTLS handshake is not success on janus side, but on client side the aiortc seems it's handshake is a success ?

Besides, do the aiortc fragment the huge handshake package of DTLS, which size is larger than the MTU configuration, e.g. 1500?

The variable lib.OpenSSL_version_num is 0x1010103f.

Sincerely thanks:)

**Comment by xiaozhubenben** [comment]
I met this error too. How do you resolve this ? Please help ,thanks an advance.

**Comment by moliqingwa** [comment]
Actually, I knew the root cause is DTLS fragment issue, if the DTLS package is larger than MTU (default is 1500) bytes, and it will cause the issue.

Seems no good solution to solve this, so I use gstreamer instead.

**Comment by xiaozhubenben** [comment]
这位兄弟，我发现你做的事情跟我差不多啊，搞下神经网络，还弄视频哈哈。 btw use gstreamer did fix this problem?
