### ISSUE TITLE
Use picamera instead of MediaPlayer for x264 HW encoding

### ISSUE THREAD

**Issue by razvanphp** [aiortc/aiortc#366]
Not sure about expected performance, but with RPi4, using the HQ camera or even with Logitech C920, I only get 5fps for 1920x1080/30. For 640x480 it is rather ok. Obviously, the CPU usage is pretty high.

I tried the solution suggested in #323, but `h264_omx` just hangs and `h264_v4l2m2m` does not work either:
```
ICE connection state is checking
ICE connection state is completed
Undefined constant or missing '(' in 'baseline'
Unable to parse option value "baseline"
Error setting option profile to value baseline.
sender(video) Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/aiortc/rtcrtpsender.py", line 295, in _run_rtp
```

Can we even try to send already encoded H264 frames via custom VideoStreamTrack(MediaStreamTrack) object?

Thank you for this great lib!

**Comment by jlaine** [comment]
aiortc's media pipeline operates on decoded frames, so hardware acceleration is not used at all. Switching to a "passthrough" model would mean a deep overhaul of the media pipeline. This has already been discussed in multiple issues and PRs, so I invite you to browse the project history.
