### ISSUE TITLE
[Question] To Kurento: what could cause ICE Request/Response Request/Error

### ISSUE THREAD

**Issue by space88man** [aiortc/aiortc#369]
I am trying to connect a aiortc/MediaPlayer to a Kurento Media Server WebRtcEndPoint..

Having problems with ICE (local LAN). The CandidatePair is IPv4 on the local LAN and is shown as SUCCEEDED.

I am seeing alternating:

REQUEST/RESPONSE
REQUEST/ERROR 

on the winning candidate, and never reaching DTLS.

```
[2020-05-27 15:04:15.142 DEBUG:ice] Connection(0) protocol(0) > ('192.168.1.31', 29225) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\x14"z\xcf\x0f\xed\x82uD\x07\x1aK')                                                                                                                                                   
[2020-05-27 15:04:15.143 DEBUG:ice] Connection(0) protocol(0) < ('192.168.1.31', 29225) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\x14"z\xcf\x0f\xed\x82uD\x07\x1aK')                                                                                                                                                  

[2020-05-27 15:04:15.143 DEBUG:ice] Connection(0) protocol(0) < ('192.168.1.31', 29225) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xf0,$\xb1\xc2-Kjj\xe2\x02\xeb')                                                                                                                                                      
[2020-05-27 15:04:15.143 DEBUG:ice] Connection(0) protocol(0) > ('192.168.1.31', 29225) Message(message_method=Method.BINDING, message_class=Class.ERROR, transaction_id=b'\xf0,$\xb1\xc2-Kjj\xe2\x02\xeb')                                                                                                                                                        

[2020-05-27 15:04:15.144 INFO:ice] Connection(0) Check CandidatePair(('192.168.1.7', 56883) -> ('192.168.1.31', 29225)) State.IN_PROGRESS -> State.SUCCEEDED                                                                                              
```

Both browser -> kurento demo app, and browser -> aiortc demo app (webcam)  are working.

**Comment by jlaine** [comment]
I have nothing to go on here, can you give me a step by step description of how to reproduce?

**Comment by space88man** [comment]
Let me do a wireshark capture. Binding request comes in from the Kurento Media Server(KMS)
with error response from aiortc/aioice.

From KMS to aiortc:


Frame 6: 130 bytes on wire (1040 bits), 130 bytes captured (1040 bits)
Ethernet II, Src: RealtekU_f4:36:f6 (52:54:00:f4:36:f6), Dst: 22:05:ff:a3:2a:e2 (22:05:ff:a3:2a:e2)
Internet Protocol Version 4, Src: 192.168.1.31, Dst: 192.168.1.7
User Datagram Protocol, Src Port: 23338, Dst Port: 44356
Session Traversal Utilities for NAT
    [Response In: 7]
    Message Type: 0x0001 (Binding Request)
    Message Length: 68
    Message Cookie: 2112a442
    Message Transaction ID: 11d973c26d98abd3d0a9408a
    Attributes
        PRIORITY
            Attribute Type: PRIORITY (0x0024)
            Attribute Length: 4
            Priority: 1847591423
        ICE-CONTROLLED
            Attribute Type: ICE-CONTROLLED (0x8029)
            Attribute Length: 8
            Tie breaker: 9ac59cc15e138c41
        USERNAME: Z260:Vanq
            Attribute Type: USERNAME (0x0006)
            Attribute Length: 9
            Username: Z260:Vanq
            Padding: 3
        MESSAGE-INTEGRITY
            Attribute Type: MESSAGE-INTEGRITY (0x0008)
            Attribute Length: 20
            HMAC-SHA1: 0be3c7b45a9e2ca2830035f45cea7de6f6c1e5f5
        FINGERPRINT
            Attribute Type: FINGERPRINT (0x8028)
            Attribute Length: 4
            CRC-32: 0xc0c24584

Response from aiortc/aioice

Frame 7: 114 bytes on wire (912 bits), 114 bytes captured (912 bits)
Ethernet II, Src: 22:05:ff:a3:2a:e2 (22:05:ff:a3:2a:e2), Dst: RealtekU_f4:36:f6 (52:54:00:f4:36:f6)
Internet Protocol Version 4, Src: 192.168.1.7, Dst: 192.168.1.31
User Datagram Protocol, Src Port: 44356, Dst Port: 23338
Session Traversal Utilities for NAT
    [Request In: 6]
    [Time: 0.000725000 seconds]
    Message Type: 0x0111 (Binding Error Response)
    Message Length: 52
    Message Cookie: 2112a442
    Message Transaction ID: 11d973c26d98abd3d0a9408a
    Attributes
        ERROR-CODE 400 (Bad Request): Bad Request
            Attribute Type: ERROR-CODE (0x0009)
            Attribute Length: 15
            Reserved: 0000
            .... .100 = Error Class: 4
            Error Code: 0
            Error Reason Phrase: Bad Request
            Padding: 1
        MESSAGE-INTEGRITY
            Attribute Type: MESSAGE-INTEGRITY (0x0008)
            Attribute Length: 20
            HMAC-SHA1: 0145c411abe6b818d85772035a14abaebe9985e7
        FINGERPRINT
            Attribute Type: FINGERPRINT (0x8028)
            Attribute Length: 4
            CRC-32: 0xb2a0e588

**Comment by space88man** [comment]
The reverse direction aiortc->KMS BINDING request/BINDING success works,
This direction works:
Frame 4: 130 bytes on wire (1040 bits), 130 bytes captured (1040 bits)
Ethernet II, Src: 22:05:ff:a3:2a:e2 (22:05:ff:a3:2a:e2), Dst: RealtekU_f4:36:f6 (52:54:00:f4:36:f6)
Internet Protocol Version 4, Src: 192.168.1.7, Dst: 192.168.1.31
User Datagram Protocol, Src Port: 44356, Dst Port: 23338
Session Traversal Utilities for NAT
    [Response In: 5]
    Message Type: 0x0001 (Binding Request)
    Message Length: 68
    Message Cookie: 2112a442
    Message Transaction ID: d08fbb416f1cd6808534a9e7
    Attributes
        USERNAME: Vanq:0t0y
            Attribute Type: USERNAME (0x0006)
            Attribute Length: 9
            Username: Vanq:0t0y
            Padding: 3
        PRIORITY
            Attribute Type: PRIORITY (0x0024)
            Attribute Length: 4
            Priority: 1862270975
        ICE-CONTROLLING
            Attribute Type: ICE-CONTROLLING (0x802a)
            Attribute Length: 8
            Tie breaker: eb81809ab1c57a48
        MESSAGE-INTEGRITY
            Attribute Type: MESSAGE-INTEGRITY (0x0008)
            Attribute Length: 20
            HMAC-SHA1: df9e95822e35ef22ec01d0c4566a6b086639b0ea
        FINGERPRINT
            Attribute Type: FINGERPRINT (0x8028)
            Attribute Length: 4
            CRC-32: 0xa21657b1


Frame 5: 122 bytes on wire (976 bits), 122 bytes captured (976 bits)
Ethernet II, Src: RealtekU_f4:36:f6 (52:54:00:f4:36:f6), Dst: 22:05:ff:a3:2a:e2 (22:05:ff:a3:2a:e2)
Internet Protocol Version 4, Src: 192.168.1.31, Dst: 192.168.1.7
User Datagram Protocol, Src Port: 23338, Dst Port: 44356
Session Traversal Utilities for NAT
    [Request In: 4]
    [Time: 0.000344000 seconds]
    Message Type: 0x0101 (Binding Success Response)
    Message Length: 60
    Message Cookie: 2112a442
    Message Transaction ID: d08fbb416f1cd6808534a9e7
    Attributes
        XOR-MAPPED-ADDRESS: 192.168.1.7:44356
            Attribute Type: XOR-MAPPED-ADDRESS (0x0020)
            Attribute Length: 8
            Reserved: 00
            Protocol Family: IPv4 (0x01)
            Port (XOR-d): 8c56
            [Port: 44356]
            IP (XOR-d): e1baa545
            [IP: 192.168.1.7]
        USERNAME: Vanq:0t0y
            Attribute Type: USERNAME (0x0006)
            Attribute Length: 9
            Username: Vanq:0t0y
            Padding: 3
        MESSAGE-INTEGRITY
            Attribute Type: MESSAGE-INTEGRITY (0x0008)
            Attribute Length: 20
            HMAC-SHA1: d961790a726f2751a602e2e766aa61eacb351eff
        FINGERPRINT
            Attribute Type: FINGERPRINT (0x8028)
            Attribute Length: 4
            CRC-32: 0x89646295

**Comment by space88man** [comment]
[stun-1-pcap.zip](https://github.com/aiortc/aiortc/files/4687950/stun-1-pcap.zip)

**Comment by space88man** [comment]
SDP Offer
```
m=audio
a=ice-ufrag:0t0y                                                                                                                                                                                                                                         
a=ice-pwd:1Jc0fskQM0hNBJx13bbMTr

m=video
a=ice-ufrag:Z260                                                                                                            
a=ice-pwd:7fopTCAf5N24BF9lwL1gZT   
```

SDP answer:
```
m=audio 1 UDP/TLS/RTP/SAVPF 96 0                                                                                            
a=sendrecv                                                                                                                  
a=mid:0                                                                                                                     
a=rtcp:9 IN IP4 0.0.0.0                                                                                                     
a=rtpmap:96 opus/48000/2                                                                                                    
a=rtpmap:0 PCMU/8000                                                                                                        
a=rtcp-mux                                                                                                                  
a=setup:active                                                                                                              
a=ssrc:628688898 cname:user3516272740@host-bed56ec0                                                                         
a=ice-ufrag:Vanq                                                                                                                                                                                                                                         
a=ice-pwd:ePM7SlkdE6dwpPJbrdLSlF                                                                                                                                                                                                                         
a=fingerprint:sha-256 43:4B:6F:88:40:39:76:F6:69:90:9D:B1:4E:26:1A:40:4D:94:68:57:C1:A3:9D:34:5F:37:78:4F:9A:02:53:D1
m=video 1 UDP/TLS/RTP/SAVPF 97 99 101                                                                                       
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time                                                       
a=sendrecv                                                                                                                  
a=mid:1                                                                                                                     
a=rtcp:9 IN IP4 0.0.0.0                                                                                                     
a=rtpmap:97 VP8/90000                                                                                                       
a=rtpmap:99 H264/90000                                                                                                      
a=rtpmap:101 H264/90000                                                                                                     
a=rtcp-fb:97 nack                                                                                                           
a=rtcp-fb:97 nack pli                                                                                                       
a=rtcp-fb:97 goog-remb                                                                                                      
a=rtcp-fb:99 nack                                                                                                           
a=rtcp-fb:99 nack pli                                                                                                       
a=rtcp-fb:99 goog-remb                                                                                                      
a=rtcp-fb:101 nack                                                                                                          
a=rtcp-fb:101 nack pli                                                                                                      
a=rtcp-fb:101 goog-remb                                                                                                                                                                                                                                  
a=rtcp-mux                                                                                                                                                                                                                                               
a=fmtp:99 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42001f                                                                                                                                                                         
a=fmtp:101 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42e01f                                                                                                                                                                        
a=setup:active                                                                                                              
a=ssrc:3880303578 cname:user3516272740@host-bed56ec0                                                                        
a=ice-ufrag:Vanq                                                                                                                                                                                                                                         
a=ice-pwd:ePM7SlkdE6dwpPJbrdLSlF                                                                                                                                                                                                                         
a=fingerprint:sha-256 43:4B:6F:88:40:39:76:F6:69:90:9D:B1:4E:26:1A:40:4D:94:68:57:C1:A3:9D:34:5F:37:78:4F:9A:02:53:D1
```

**Comment by space88man** [comment]
Adding more print statements to aioice, it seems that the username  are mismatched leading, to ValueError in both integrity check and, if this is bypassed, another ValueError due to non-matching username.

**Comment by space88man** [comment]
I am closing the issue here as my explanation is too confusing. I will open a separate issue.
