### ISSUE TITLE
Add custom encryption

### ISSUE THREAD

**Issue by SourceCodeZone** [aiortc/aiortc#374]
I am planning to add custom encryption for videos steam like this one https://stackoverflow.com/questions/12524994/encrypt-decrypt-using-pycrypto-aes-256. I have found that the latest chrome version has insertableStream option which allow per-processing frame as explained here https://webrtchacks.com/true-end-to-end-encryption-with-webrtc-insertable-streams/. So is there any option with aiortc to add custom encryption. If not exist then the can I use  the approach like opencv per-processing example for encoding. 

Ref:

https://github.com/alvestrand/webrtc-media-streams/blob/master/explainer.md

**Comment by jlaine** [comment]
I have to admit I have no idea what you're trying to do, but you have access to aiortc's source code, feel free to hack away.

**Comment by SourceCodeZone** [comment]
Actually I want add custom encryption on the media(AES 256), I found that that latest chrome has some API like insertableStream where I can run encryption/decryption. I have to the same with aiortc, that is add custom encryption/decryption before send.

**Comment by jlaine** [comment]
OK, have fun!
