### ISSUE TITLE
Speed get really low when using multiple clients

### ISSUE THREAD

**Issue by shashank-yadav** [aiortc/aiortc#378]
Hi, first of all thanks a lot for creating this really useful and simple to use library! I was using the opencv server example to do some nontrivial server-side processing. It was working well with one client but as soon as I connected another client, the fps on client-side just halved. Is this an issue with recv? AFAIK (and that's not much), async functions are supposed to yield the main thread. Is there some way to take care of this? On another note, is there a better way to make it more scalable, to support say a few thousand clients? Thanks a lot for your help.
I was running my server on Ubuntu 20.04 with python 3.7

**Comment by jlaine** [comment]
I'm not sure what's expected here: yes, processing media streams is a CPU heavy operations, and serving two clients is going to use twice the resources.

**Comment by jlaine** [comment]
No reply from submitter, closing.
