### ISSUE TITLE
Problems about running webcam example

### ISSUE THREAD

**Issue by XingkaiEden** [aiortc/aiortc#384]
I have tried to run the webcam example, and here is what I got when I click start button on the page:

> ======== Running on http://0.0.0.0:8080 ========
> (Press CTRL+C to quit)
> Selected pixel format (yuv420p) is not supported by the input device.
> Supported pixel formats:
> uyvy422
> yuyv422
> nv12
> 0rgb
> bgr0
> Overriding selected pixel format to use uyvy422 instead.
> Abort trap: 6

And below is what I got for listing devices by using `ffmpeg -hide_banner -f avfoundation -list_devices true -i ""`

> [AVFoundation indev @ 0x7f9eaa605300] AVFoundation video devices:
> [AVFoundation indev @ 0x7f9eaa605300] [0] FaceTime HD Camera (Built-in)
> [AVFoundation indev @ 0x7f9eaa605300] [1] Capture screen 0
> [AVFoundation indev @ 0x7f9eaa605300] AVFoundation audio devices:
> [AVFoundation indev @ 0x7f9eaa605300] [0] MacBook Pro Microphone
> : Input/output error

Really need a help for this. Appreciate it ahead.

**Comment by jlaine** [comment]
Sorry there isn't going to be a "quick fix" for this, it involves:

- programmatically inspecting the device to determine what formats it supports
- applying conversion of every video frame

**Comment by joseph-long** [comment]
Strangely, I had this working with my MacBook Air's built-in camera, and all of a sudden I'm getting this issue.

**Comment by paulhobbel** [comment]
Hi there, I'm also a Mac user. I don't get the Abort trap: 6 error. However it streams 1-2 frames over WebRTC and then closes the `player_worker` thread. After some digging it seems like the `container.decode` throws an AVError 35 (EAGAIN), which means the device is still buffering. This means this should not be treated as error.

Related code: https://github.com/aiortc/aiortc/blob/d691ddc3df6bef7f3c3c70eeccfb9b39b1f5699a/src/aiortc/contrib/media.py#L103

**Comment by jlaine** [comment]
That sounds like a good catch! Could you try adding an `import errno` to the top of the file and patching the code like so:

```python
except (av.FFmpegError, StopIteration) as exc:
    if isinstance(exc, av.FFmpegError) and exc.errno = errno.EAGAIN:
        continue
```

**Comment by paulhobbel** [comment]
That does work I also added a small delay of 0.01

**Comment by jlaine** [comment]
Yes please! I'll try to figure out how to lock this condition

**Comment by jlaine** [comment]
@paulhobbel  I've put up a PR for your issue in #497. I still need to figure out how to write a test for it.

**Comment by paulhobbel** [comment]
I see, uhm, you have to somehow fake the error and make sure the player keeps running

**Comment by paulhobbel** [comment]
Can confirm that #497 fixed this issue

**Comment by jlaine** [comment]
@XingkaiEden could you confirm whether your issue still exists with aiortc 1.2.0 please?
