### ISSUE TITLE
How to set options for MediaRecorder?

### ISSUE THREAD

**Issue by JRafiei** [aiortc/aiortc#389]
I'm using the server.py example and trying to set ffmpeg options with the following code:
```
recorder = MediaRecorder('rtmp://localhost:1935/live/mystream', format='flv', options={
    'framerate': '1',
    'video_size': '720x404', 
    'vcodec': 'libx264',
    'maxrate': '768k',
    'bufsize': '8080k',
    'vf': '"format=yuv420p"',
    'g': '60'
})
```
The problem is that when I run the server I get the following message:
`WARNING:av.container.output:Some options were not used: {'framerate': '1', 'video_size': '720x404', 'vcodec': 'libx264', 'maxrate': '768k', 'bufsize': '8080k', 'vf': '"format=yuv420p"', 'g': '60'}`

Am I settings the options incorrectly or there is something that I'm missing?

By the way I found this issue that seems to be similar to my problem. Are they related?
[CRF flag seems to have no effect](https://github.com/PyAV-Org/PyAV/issues/371)

**Comment by jlaine** [comment]
`aiortc` just passes the options on to `PyAV`, I suggest you seek help there.
