### ISSUE TITLE
Using hardware accelerated h264 encoding

### ISSUE THREAD

**Issue by jpiat** [aiortc/aiortc#390]
Hi,

aiortc works perfectly fine on modern x86 machines but struggles on small embedded platform like the raspberry pi. I noticed that by default h264 encoding is performed in software using libx264 but embedded platform could really benefit from using the available hardware encoder. On the raspberry-pi, i tried using h264_omx in place of libx264 in codecs/h264.py but the encoder get stuck as soon as i push a frame. Do you have any idea of what it would require to get this to work ? Have you tried anything similar ?

**Comment by jlaine** [comment]
`aiortc` relies on `PyAV` for its FFmpeg bindings, and its readme states hardware acceleration is out of scope.
