### ISSUE TITLE
Media fingerprint is not fetched from SDP

### ISSUE THREAD

**Issue by dnsglk** [aiortc/aiortc#391]
Hi, I have been working on establishing connection with [Flashphoner WebRTC server](https://docs.flashphoner.com/display/WCS52EN/From+a+web+camera+in+a+browser+via+WebRTC). I came across an issue when trying to set remote SDP to RTCPeerConnection. Flashphoner puts fingerprint into the media section, not session. When SDP is parsed, the media is not populated with dtls and thus I get an error:

>    await pc.setRemoteDescription(obj)
>   File "/home/denisg/pyenv/pose-py37/lib/python3.7/site-packages/aiortc/rtcpeerconnection.py", line 754, in setRemoteDescription
>     self.__validate_description(description, is_local=False)
>   File "/home/denisg/pyenv/pose-py37/lib/python3.7/site-packages/aiortc/rtcpeerconnection.py", line 1126, in __validate_description
>     if description.type in ["answer", "pranswer"] and media.dtls.role not in [
> AttributeError: 'NoneType' object has no attribute 'role'

**Comment by dnsglk** [comment]
Please ignore closing this ticket. 
So, the dtls_role ('setup') is not provided in the session level. And hence the current_media.dtls is cleared, even though the fingerprint is present in the SDP for the media stream.
https://github.com/aiortc/aiortc/blob/main/src/aiortc/sdp.py#L448
Here is an example of SDP I need to import as a remote SDP:
`v=0
o=Flashphoner 0 1593868093386 IN IP4 3.120.31.143
s=Flashphoner/1.0
c=IN IP4 3.120.31.143
t=0 0

m=audio 31290 RTP/SAVPF 111 8 9
c=IN IP4 3.120.31.143
a=mid:0
a=rtpmap:111 opus/48000/2
a=rtpmap:8 PCMA/8000
a=rtpmap:9 G722/8000
a=ptime:20
a=ice-pwd:26f5bvnh1c2sr60q12f02cv0nl
a=ice-ufrag:6a586090/bdf7/11ea/840e/09909e677ffc4ap1r1eccv21j0
a=fingerprint:SHA-256 A1:90:C3:1D:C1:AF:1B:B6:D1:A9:75:11:AA:D1:0E:62:6E:C0:3D:9C:19:7D:8F:FB:1E:FD:55:97:11:A1:77:31
a=candidate:1 1 udp 2130706431 3.120.31.143 31290 typ host
a=candidate:1 2 udp 2130706431 3.120.31.143 31290 typ host
a=end-of-candidates
a=rtcp-mux
a=rtcp:31290 IN IP4 3.120.31.143
a=sendonly
a=ssrc:1868119667 cname:rtp/audio/6a586090-bdf7-11ea-840e-09909e677ffc
m=video 31292 RTP/SAVPF 102 125 127 108 96
c=IN IP4 3.120.31.143
a=mid:1
a=rtpmap:102 H264/90000
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:125 H264/90000
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:127 H264/90000
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:108 H264/90000
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:96 VP8/90000
a=rtcp-fb:* ccm fir
a=rtcp-fb:* nack
a=rtcp-fb:* nack pli
a=rtcp-fb:* goog-remb
a=extmap:13 urn:3gpp:video-orientation
a=ice-pwd:26f5bvnh1c2sr60q12f02cv0nl
a=ice-ufrag:6a586090/bdf7/11ea/840e/09909e677ffc4ap1r1eccv21j0
a=fingerprint:SHA-256 A1:90:C3:1D:C1:AF:1B:B6:D1:A9:75:11:AA:D1:0E:62:6E:C0:3D:9C:19:7D:8F:FB:1E:FD:55:97:11:A1:77:31
a=candidate:1 1 udp 2130706431 3.120.31.143 31292 typ host
a=candidate:1 2 udp 2130706431 3.120.31.143 31292 typ host
a=end-of-candidates
a=rtcp-mux
a=rtcp:31292 IN IP4 3.120.31.143
a=sendonly
a=ssrc:1414153318 cname:rtp/video/6a586090-bdf7-11ea-840e-09909e677ffc`

**Comment by jlaine** [comment]
I don't see how your error is in any way related to the fingerprint, the exception is quite clear: the DTLS role is not provided, which is not spec conformant, see RFC 5763:

```
      The endpoint MUST use the setup attribute defined in [RFC4145].
      The endpoint that is the offerer MUST use the setup attribute
      value of setup:actpass and be prepared to receive a client_hello
      before it receives the answer.
```

**Comment by dnsglk** [comment]
Hm, indeed, the RFC is quite clear. Thanks for pointing this out.
