### ISSUE TITLE
Routing video from one client to another

### ISSUE THREAD

**Issue by jgeary** [aiortc/aiortc#397]
I want to make a man-in-the-middle server that manages separate connections with streamers and viewers. So for example, it receives a video stream from one client and forwards it to another who views it. I can't use the direct p2p connections because I want the option to process the frames or quickly replace one streamer with another on the viewers screen.

Is this a good use case for aiortc, and if so, what is the best way to do it? I've already set up the example that uses opencv on the server from the user webcam, but I'm specifically curious about the simplest way to setup connections such that frames from one peer get routed to a viewing peer (ideally with low latency).

Thanks in advance.

**Comment by jlaine** [comment]
Are we talking about one-to-one routing? i.e. "receive media from peer A and relay it to a single peer B"?

**Comment by jgeary** [comment]
thanks @jlaine that's exactly what i figured once i read more. i went with [mediasoup](https://github.com/versatica/mediasoup) - highly recommend it as an SFU solution.
