### ISSUE TITLE
Sending H.264

### ISSUE THREAD

**Issue by Alick09** [aiortc/aiortc#399]
Can't find any example how to send H.264 encoded video using this module.
Please, can anyone help me and show what I missed or how I can do it?

**Comment by jlaine** [comment]
aiortc supports H.264, but it has a lower priority than VP8, so if your remote peer supports both, VP8 will get used.

You can however force codec selection by using: https://aiortc.readthedocs.io/en/latest/api.html#aiortc.RTCRtpTransceiver.setCodecPreferences

Here is an example:

https://github.com/aiortc/aiortc/blob/15d8fa411ef0bfd29f18a81c0d5032fc2563add4/tests/test_rtcpeerconnection.py#L2633
