### ISSUE TITLE
DTLS FAILED (connection error)

### ISSUE THREAD

**Issue by ghizlane-boudabza** [aiortc/aiortc#400]
Hi,
I use aiortc connect with my webrtc client, log shows DTLS handshake failed, and i cannot receive any media data from my server.

Here is session log，please give me some advice ,thanks.

DEBUG:ice:controlled - new -> checking
INFO:ice:Connection(0) Check CandidatePair(('192.168.43.102', 46492) -> ('192.168.0.68', 31354)) State.FROZEN -> State.WAITING
INFO:ice:Connection(0) Check CandidatePair(('192.168.9.56', 54139) -> ('192.168.0.68', 31354)) State.FROZEN -> State.WAITING
DEBUG:ice:Connection(2) protocol(2) connection_made(<_SelectorDatagramTransport fd=8 read=idle write=<idle, bufsize=0>>)
INFO:ice:Connection(0) Check CandidatePair(('192.168.43.102', 46492) -> ('192.168.0.68', 31354)) State.WAITING -> State.IN_PROGRESS
DEBUG:ice:Connection(0) protocol(0) > ('192.168.0.68', 31354) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'n3\x1bE\xa4\xe5\xd7\x0f\xa0\x8a-4')
INFO:ice:Connection(0) Check CandidatePair(('192.168.9.56', 54139) -> ('192.168.0.68', 31354)) State.WAITING -> State.IN_PROGRESS
DEBUG:ice:Connection(0) protocol(1) > ('192.168.0.68', 31354) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'Y6\xee\xb1Fq\x1b \xf6w?\x04')
DEBUG:turn:turn/tcp > ('<myserver-turn>', 443) Message(message_method=Method.CHANNEL_BIND, message_class=Class.REQUEST, transaction_id=b'Le\x94\xcf\x95\xeaw.%z\x82\x95')
DEBUG:turn:turn/tcp connection_made(<_SelectorSocketTransport fd=9 read=idle write=<idle, bufsize=0>>)
DEBUG:turn:turn/tcp > ('<myserver-turn>', 443) Message(message_method=Method.ALLOCATE, message_class=Class.REQUEST, transaction_id=b'\xe2S\xeb\x80\xba\x1d\xd1\xb7`:p\xa9')
DEBUG:turn:turn/tcp < ('<myserver-turn>', 443) Message(message_method=Method.CHANNEL_BIND, message_class=Class.RESPONSE, transaction_id=b'Le\x94\xcf\x95\xeaw.%z\x82\x95')
INFO:turn:TURN channel bound 16384 ('192.168.0.68', 31354)
DEBUG:ice:Connection(0) protocol(1) < ('192.168.0.68', 31354) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'3\xc1\xec\xeb\x16\xdb+\xff7P@}')
DEBUG:ice:Connection(0) protocol(1) > ('192.168.0.68', 31354) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'3\xc1\xec\xeb\x16\xdb+\xff7P@}')
DEBUG:turn:turn/tcp < ('<myserver-turn>', 443) Message(message_method=Method.ALLOCATE, message_class=Class.ERROR, transaction_id=b'\xe2S\xeb\x80\xba\x1d\xd1\xb7`:p\xa9')
DEBUG:turn:turn/tcp > ('<myserver-turn>', 443) Message(message_method=Method.ALLOCATE, message_class=Class.REQUEST, transaction_id=b'\xf3sy\x90\xd0n\xdc\x0c\x88\xa5)r')
DEBUG:ice:Connection(0) protocol(1) < ('192.168.0.68', 31354) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'Y6\xee\xb1Fq\x1b \xf6w?\x04')
INFO:ice:Connection(0) Check CandidatePair(('192.168.9.56', 54139) -> ('192.168.0.68', 31354)) State.IN_PROGRESS -> State.SUCCEEDED
INFO:ice:Connection(0) ICE completed
DEBUG:ice:controlled - checking -> completed
DEBUG:dtls:client - State.NEW -> State.CONNECTING
DEBUG:ice:Connection(0) protocol(1) < ('192.168.0.68', 31354) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xacS\xd0\x07\x1c\xe5\xacz\x86\x01\xa9\xea')
DEBUG:ice:Connection(0) protocol(1) > ('192.168.0.68', 31354) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\xacS\xd0\x07\x1c\xe5\xacz\x86\x01\xa9\xea')
DEBUG:turn:turn/tcp < ('<myserver-turn>', 443) Message(message_method=Method.ALLOCATE, message_class=Class.RESPONSE, transaction_id=b'\xf3sy\x90\xd0n\xdc\x0c\x88\xa5)r')
INFO:turn:TURN allocation created ('192.168.9.56', 59994)
DEBUG:ice:Connection(2) protocol(3) connection_made(<aioice.turn.TurnTransport object at 0x7f7661c6eac8>)

DEBUG:dtls:client - State.NEW -> State.CONNECTING
DEBUG:dtls:client x DTLS handshake failed (connection error)
DEBUG:dtls:client - State.CONNECTING -> State.FAILED

**Comment by jlaine** [comment]
Can you please provide me with a  step-by-step of how I can reproduce this?

**Comment by Schmiddo** [comment]
@ghizlane-boudabza did you manage to find a solution? I have the same problem.

**Comment by jlaine** [comment]
By the way, the error message indicates that the problem did *not* originate at the DTLS level.

It means the underlying ICE connection failed to connect or was broken before the DTLS handshake could complete. I would therefore suggest looking at what is going on with the TURN server, as I see the following:

`DEBUG:turn:turn/tcp < ('<myserver-turn>', 443) Message(message_method=Method.ALLOCATE, message_class=Class.ERROR, transaction_id=b'\xe2S\xeb\x80\xba\x1d\xd1\xb7:p\xa9')`

**Comment by jlaine** [comment]
No reply, closing
