### ISSUE TITLE
How to run examples in containers? 

### ISSUE THREAD

**Issue by DevinBayly** [aiortc/aiortc#401]
Hi there,

This may actually be a general webrtc question, but I was curious if anyone could explain how the `data-channel-cli` example might work from inside a docker container? When I have 2 containers on separate vms copying and pasting the offer & answer doesn't lead to a ping ponging which can be seen if running the script as separate processes on a single machine. 

Any assistance would be very helpful, and I expect this is something others might be curious about too?

**Comment by jlaine** [comment]
I'm going to close this as out of scope, I'm already swamped just supporting `aiortc`, I cannot turn the issue tracker into a general help forum.
