### ISSUE TITLE
How to set target bitrate for video streams?

### ISSUE THREAD

**Issue by matheus2740** [aiortc/aiortc#402]
Hi, I'm creating an application and didn't found a way to set the target bitrate on video streams. Seems like `b=AS:` is not supported (setting it had not effect). As a workaround I'm setting `aiortc.codecs.vpx.DEFAULT_BITRATE` for now. What's the proper way to do this? is this supported?
Thanks a lot

**Comment by jlaine** [comment]
Hi! No currently, there is not API for changing the bitrate.

I am not opposed to a PR implementing support for "b=AS:" but before implementing this, we should first fix the current bitrate calculations. They assume a constant frame rate at 30fps, which is not always the case.. I discovered this when switching the light off in the room where I was performing tests, this halved the webcam's framerate and threw the bitrate calculations off!

**Comment by freol35241** [comment]
First, thanks @jlaine for this library and your work supporting it!

I am also interested in this. The use case being a `aiortc` running on an edge device with only cellular connection (4G) which has enough bandwidth to support a high bitrate but where it would be nice to "constrain" the bitrate to keep the data usage low.

I tried the workaround suggested by @matheus2740 but could not get this to work properly, it seems like the `DEFAULT_BITRATE` is only used as a starting point and then the available bandwidth is estimated as time progress? This is an example from `chrome://webrtc-internals` for the case where `aiortc.codecs.vpx.DEFAULT_BITRATE` was manually set to `aiortc.codecs.vpx.MIN_BITRATE` as a trial case:
![image](https://user-images.githubusercontent.com/21332885/151148212-0fbf0cfa-7fb5-4d1e-93a0-cdd42170a5a3.png)

The stream starts with a bitrate of approx. 250 kbps (`aiortc.codecs.vpx.MIN_BITRATE`) but quickly increases to above 1 mbps.

I also tried with the following:
`aiortc.codecs.vpx.DEFAULT_BITRATE = aiortc.codecs.vpx.MAX_BITRATE = aiortc.codecs.vpx.MIN_BITRATE`
i.e, putting everything to 250 kbps which results in this:
![image](https://user-images.githubusercontent.com/21332885/151148956-65b20c85-8f94-43b8-87ed-8db234172691.png)


Forgive my ignorance (I have only just started dipping my toes in WebRTC) but, from a python user perspective, what is the difference of this approach in comparison with `b=AS:` in the SDP? Perhaps a simpler interface to these BITRATE levels would be enough for most usecases?

**Comment by Interpause** [comment]
In the case of a local webrtc connection where both the aiortc server and client are on the same network, with the video going from server to client, is there some way to increase the max bitrate for all the codecs at the same time? I guess setting `aiortc.codecs.*.MAX_BITRATE` would work but its hacky

**Comment by Tjoppen** [comment]
Having an proper official way to set the bitrate and/or crf would be nice. This also ties into #174, which should be reopened

**Comment by Tjoppen** [comment]
Issues don't go away just because someone hasn't commented on them in a while.

**Comment by Interpause** [comment]
And it's closed...
