### ISSUE TITLE
when trying to connect from other host got an error

### ISSUE THREAD

**Issue by rahooftkh** [aiortc/aiortc#405]
405 method not allowed
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8000/offer. (Reason: CORS preflight response did not succeed).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8000/offer. (Reason: CORS request did not succeed).

**Comment by jlaine** [comment]
What does "connecting from another host" mean?

**Comment by jlaine** [comment]
No reply from submitter, closing.
