### ISSUE TITLE
Build fails because of PyAV 

### ISSUE THREAD

**Issue by AbhishekPokala** [aiortc/aiortc#408]
## Error
Installing aiortc in a Raspberry Pi-4 (armv7l) fails using a pip install.

## Command used
python3.7 -m pip install aiortc

## Error Stack:
abhishek@ubuntu:~/PySyftBuildFolder$ python3.7 -m pip install aiortc
Defaulting to user installation because normal site-packages is not writeable
Collecting aiortc
  Using cached aiortc-0.9.28.tar.gz (1.2 MB)
Requirement already satisfied: aioice<0.7.0,>=0.6.17 in /home/abhishek/.local/lib/python3.7/site-packages (from aiortc) (0.6.18)
Collecting av<9.0.0,>=8.0.0
  Using cached av-8.0.2.tar.gz (2.3 MB)
Requirement already satisfied: cffi>=1.0.0 in /usr/local/lib/python3.7/site-packages (from aiortc) (1.14.2)
Collecting crc32c
  Using cached crc32c-2.0.1.tar.gz (25 kB)
Processing /home/abhishek/.cache/pip/wheels/2b/60/6f/01f97e3a90d25fad9ca48294524b2e2f82d0396075ba3a8b59/cryptography-3.0-cp37-cp37m-linux_armv7l.whl
Collecting pyee>=6.0.0
  Using cached pyee-7.0.2-py2.py3-none-any.whl (12 kB)
Collecting pylibsrtp>=0.5.6
  Using cached pylibsrtp-0.6.6.tar.gz (10 kB)
Requirement already satisfied: netifaces in /home/abhishek/.local/lib/python3.7/site-packages (from aioice<0.7.0,>=0.6.17->aiortc) (0.10.9)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/site-packages (from cffi>=1.0.0->aiortc) (2.20)
Requirement already satisfied: six>=1.4.1 in /home/abhishek/.local/lib/python3.7/site-packages (from cryptography>=2.2->aiortc) (1.15.0)
Using legacy 'setup.py install' for aiortc, since package 'wheel' is not installed.
Using legacy 'setup.py install' for av, since package 'wheel' is not installed.
Using legacy 'setup.py install' for crc32c, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pylibsrtp, since package 'wheel' is not installed.
Installing collected packages: av, crc32c, cryptography, pyee, pylibsrtp, aiortc
    Running setup.py install for av ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cuz2u6hl/av/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cuz2u6hl/av/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j_vhmkyd/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/abhishek/.local/include/python3.7m/av
         cwd: /tmp/pip-install-cuz2u6hl/av/
    Complete output (192 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.7
    creating build/lib.linux-armv7l-3.7/av
    copying av/datasets.py -> build/lib.linux-armv7l-3.7/av
    copying av/deprecation.py -> build/lib.linux-armv7l-3.7/av
    copying av/__init__.py -> build/lib.linux-armv7l-3.7/av
    copying av/__main__.py -> build/lib.linux-armv7l-3.7/av
    creating build/lib.linux-armv7l-3.7/av/data
    copying av/data/__init__.py -> build/lib.linux-armv7l-3.7/av/data
    creating build/lib.linux-armv7l-3.7/av/sidedata
    copying av/sidedata/__init__.py -> build/lib.linux-armv7l-3.7/av/sidedata
    creating build/lib.linux-armv7l-3.7/av/video
    copying av/video/__init__.py -> build/lib.linux-armv7l-3.7/av/video
    creating build/lib.linux-armv7l-3.7/av/codec
    copying av/codec/__init__.py -> build/lib.linux-armv7l-3.7/av/codec
    creating build/lib.linux-armv7l-3.7/av/container
    copying av/container/__init__.py -> build/lib.linux-armv7l-3.7/av/container
    creating build/lib.linux-armv7l-3.7/av/filter
    copying av/filter/__init__.py -> build/lib.linux-armv7l-3.7/av/filter
    creating build/lib.linux-armv7l-3.7/av/audio
    copying av/audio/__init__.py -> build/lib.linux-armv7l-3.7/av/audio
    creating build/lib.linux-armv7l-3.7/av/subtitles
    copying av/subtitles/__init__.py -> build/lib.linux-armv7l-3.7/av/subtitles
    running build_ext
    running config
    PyAV: 8.0.2 (unknown commit)
    Python: 3.7.0 (default, Aug 16 2020, 02:47:03) \n[GCC 7.5.0]
    platform: Linux-5.4.0-1015-raspi-armv7l-with-debian-buster-sid
    extension_extra:
    	include_dirs: [b'include', b'/usr/include/arm-linux-gnueabihf']
    	libraries: [b'avformat', b'avcodec', b'avdevice', b'avutil', b'avfilter', b'swscale', b'swresample']
    	library_dirs: []
    	define_macros: []
    	runtime_library_dirs: []
    config_macros:
    	PYAV_COMMIT_STR="unknown-commit"
    	PYAV_VERSION=8.0.2
    	PYAV_VERSION_STR="8.0.2"
    writing build/temp.linux-armv7l-3.7/include/pyav/config.h
    running cythonize
    building 'av.enum' extension
    creating build/temp.linux-armv7l-3.7/src
    creating build/temp.linux-armv7l-3.7/src/av
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/enum.c -o build/temp.linux-armv7l-3.7/src/av/enum.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/enum.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/enum.cpython-37m-arm-linux-gnueabihf.so
    building 'av.logging' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/logging.c -o build/temp.linux-armv7l-3.7/src/av/logging.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/logging.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/logging.cpython-37m-arm-linux-gnueabihf.so
    building 'av.option' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/option.c -o build/temp.linux-armv7l-3.7/src/av/option.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/option.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/option.cpython-37m-arm-linux-gnueabihf.so
    building 'av.buffer' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/buffer.c -o build/temp.linux-armv7l-3.7/src/av/buffer.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/buffer.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/buffer.cpython-37m-arm-linux-gnueabihf.so
    building 'av.stream' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/stream.c -o build/temp.linux-armv7l-3.7/src/av/stream.o
    src/av/stream.c: In function ‘__pyx_f_2av_6stream_wrap_stream’:
    src/av/stream.c:2232:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
       switch (__pyx_v_c_stream->codec->codec_type) {
       ^~~~~~
    In file included from /usr/include/arm-linux-gnueabihf/libavdevice/avdevice.h:51:0,
                     from src/av/stream.c:673:
    /usr/include/arm-linux-gnueabihf/libavformat/avformat.h:893:21: note: declared here
         AVCodecContext *codec;
                         ^~~~~
    src/av/stream.c: In function ‘__pyx_f_2av_6stream_6Stream__init’:
    src/av/stream.c:2850:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
       __pyx_t_1 = __pyx_v_stream->codec;
       ^~~~~~~~~
    In file included from /usr/include/arm-linux-gnueabihf/libavdevice/avdevice.h:51:0,
                     from src/av/stream.c:673:
    /usr/include/arm-linux-gnueabihf/libavformat/avformat.h:893:21: note: declared here
         AVCodecContext *codec;
                         ^~~~~
    src/av/stream.c:2970:15: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
         __pyx_t_6 = __pyx_v_self->_codec_context->codec;
                   ^
    src/av/stream.c: In function ‘__pyx_f_2av_6stream_6Stream__finalize_for_output’:
    src/av/stream.c:3663:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
       __pyx_t_7 = __pyx_f_2av_5error_err_check(avcodec_parameters_from_context(__pyx_v_self->_stream->codecpar, __pyx_v_self->_stream->codec), 0, NULL); if (unlikely(__pyx_t_7 == ((int)-1))) __PYX_ERR(0, 141, __pyx_L1_error)
       ^~~~~~~~~
    In file included from /usr/include/arm-linux-gnueabihf/libavdevice/avdevice.h:51:0,
                     from src/av/stream.c:673:
    /usr/include/arm-linux-gnueabihf/libavformat/avformat.h:893:21: note: declared here
         AVCodecContext *codec;
                         ^~~~~
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/stream.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/stream.cpython-37m-arm-linux-gnueabihf.so
    building 'av.plane' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/plane.c -o build/temp.linux-armv7l-3.7/src/av/plane.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/plane.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/plane.cpython-37m-arm-linux-gnueabihf.so
    building 'av.packet' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/packet.c -o build/temp.linux-armv7l-3.7/src/av/packet.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/packet.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/packet.cpython-37m-arm-linux-gnueabihf.so
    building 'av._core' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/_core.c -o build/temp.linux-armv7l-3.7/src/av/_core.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/_core.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/_core.cpython-37m-arm-linux-gnueabihf.so
    building 'av.error' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/error.c -o build/temp.linux-armv7l-3.7/src/av/error.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/error.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/error.cpython-37m-arm-linux-gnueabihf.so
    building 'av.format' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/format.c -o build/temp.linux-armv7l-3.7/src/av/format.o
    src/av/format.c: In function ‘__pyx_f_2av_6format_find_output_format’:
    src/av/format.c:3150:19: warning: implicit declaration of function ‘av_muxer_iterate’; did you mean ‘av_buffer_create’? [-Wimplicit-function-declaration]
         __pyx_v_ptr = av_muxer_iterate((&__pyx_v_opaque));
                       ^~~~~~~~~~~~~~~~
                       av_buffer_create
    src/av/format.c:3150:17: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         __pyx_v_ptr = av_muxer_iterate((&__pyx_v_opaque));
                     ^
    src/av/format.c: In function ‘__pyx_f_2av_6format_get_output_format_names’:
    src/av/format.c:3301:17: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         __pyx_v_ptr = av_muxer_iterate((&__pyx_v_opaque));
                     ^
    src/av/format.c: In function ‘__pyx_f_2av_6format_get_input_format_names’:
    src/av/format.c:3440:19: warning: implicit declaration of function ‘av_demuxer_iterate’; did you mean ‘av_demuxer_open’? [-Wimplicit-function-declaration]
         __pyx_v_ptr = av_demuxer_iterate((&__pyx_v_opaque));
                       ^~~~~~~~~~~~~~~~~~
                       av_demuxer_open
    src/av/format.c:3440:17: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         __pyx_v_ptr = av_demuxer_iterate((&__pyx_v_opaque));
                     ^
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/format.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/format.cpython-37m-arm-linux-gnueabihf.so
    building 'av.frame' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/frame.c -o build/temp.linux-armv7l-3.7/src/av/frame.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/frame.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/frame.cpython-37m-arm-linux-gnueabihf.so
    building 'av.utils' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/utils.c -o build/temp.linux-armv7l-3.7/src/av/utils.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/utils.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/utils.cpython-37m-arm-linux-gnueabihf.so
    building 'av.bytesource' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/bytesource.c -o build/temp.linux-armv7l-3.7/src/av/bytesource.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/bytesource.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/bytesource.cpython-37m-arm-linux-gnueabihf.so
    building 'av.dictionary' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/dictionary.c -o build/temp.linux-armv7l-3.7/src/av/dictionary.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/dictionary.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/dictionary.cpython-37m-arm-linux-gnueabihf.so
    building 'av.descriptor' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/descriptor.c -o build/temp.linux-armv7l-3.7/src/av/descriptor.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/descriptor.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/descriptor.cpython-37m-arm-linux-gnueabihf.so
    building 'av.data.stream' extension
    creating build/temp.linux-armv7l-3.7/src/av/data
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/data/stream.c -o build/temp.linux-armv7l-3.7/src/av/data/stream.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/data/stream.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/data/stream.cpython-37m-arm-linux-gnueabihf.so
    building 'av.sidedata.sidedata' extension
    creating build/temp.linux-armv7l-3.7/src/av/sidedata
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/sidedata/sidedata.c -o build/temp.linux-armv7l-3.7/src/av/sidedata/sidedata.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/sidedata/sidedata.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/sidedata/sidedata.cpython-37m-arm-linux-gnueabihf.so
    building 'av.sidedata.motionvectors' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/sidedata/motionvectors.c -o build/temp.linux-armv7l-3.7/src/av/sidedata/motionvectors.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/sidedata/motionvectors.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/sidedata/motionvectors.cpython-37m-arm-linux-gnueabihf.so
    building 'av.video.reformatter' extension
    creating build/temp.linux-armv7l-3.7/src/av/video
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/video/reformatter.c -o build/temp.linux-armv7l-3.7/src/av/video/reformatter.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/video/reformatter.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/video/reformatter.cpython-37m-arm-linux-gnueabihf.so
    building 'av.video.stream' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/video/stream.c -o build/temp.linux-armv7l-3.7/src/av/video/stream.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/video/stream.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/video/stream.cpython-37m-arm-linux-gnueabihf.so
    building 'av.video.plane' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/video/plane.c -o build/temp.linux-armv7l-3.7/src/av/video/plane.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/video/plane.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/video/plane.cpython-37m-arm-linux-gnueabihf.so
    building 'av.video.format' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/video/format.c -o build/temp.linux-armv7l-3.7/src/av/video/format.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/video/format.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/video/format.cpython-37m-arm-linux-gnueabihf.so
    building 'av.video.codeccontext' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/video/codeccontext.c -o build/temp.linux-armv7l-3.7/src/av/video/codeccontext.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/video/codeccontext.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/video/codeccontext.cpython-37m-arm-linux-gnueabihf.so
    building 'av.video.frame' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/video/frame.c -o build/temp.linux-armv7l-3.7/src/av/video/frame.o
    gcc -pthread -shared build/temp.linux-armv7l-3.7/src/av/video/frame.o -lavdevice -lavfilter -lavformat -lswscale -lswresample -lavcodec -lavutil -o build/lib.linux-armv7l-3.7/av/video/frame.cpython-37m-arm-linux-gnueabihf.so
    building 'av.codec.codec' extension
    creating build/temp.linux-armv7l-3.7/src/av/codec
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/arm-linux-gnueabihf -Iinclude -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -I/usr/local/include/python3.7m -Ibuild/temp.linux-armv7l-3.7/include -c src/av/codec/codec.c -o build/temp.linux-armv7l-3.7/src/av/codec/codec.o
    src/av/codec/codec.c: In function ‘__pyx_f_2av_5codec_5codec_get_codec_names’:
    src/av/codec/codec.c:4003:19: warning: implicit declaration of function ‘av_codec_iterate’; did you mean ‘av_codec_next’? [-Wimplicit-function-declaration]
         __pyx_v_ptr = av_codec_iterate((&__pyx_v_opaque));
                       ^~~~~~~~~~~~~~~~
                       av_codec_next
    src/av/codec/codec.c:4003:17: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         __pyx_v_ptr = av_codec_iterate((&__pyx_v_opaque));
                     ^
    src/av/codec/codec.c: In function ‘__pyx_pymod_exec_codec’:
    src/av/codec/codec.c:6117:36: error: ‘AV_CODEC_CAP_HARDWARE’ undeclared (first use in this function); did you mean ‘AV_CODEC_CAP_DR1’?
       __pyx_t_7 = __Pyx_PyInt_From_int(AV_CODEC_CAP_HARDWARE); if (unlikely(!__pyx_t_7)) __PYX_ERR(0, 121, __pyx_L1_error)
                                        ^~~~~~~~~~~~~~~~~~~~~
                                        AV_CODEC_CAP_DR1
    src/av/codec/codec.c:6117:36: note: each undeclared identifier is reported only once for each function it appears in
    src/av/codec/codec.c:6138:36: error: ‘AV_CODEC_CAP_HYBRID’ undeclared (first use in this function); did you mean ‘AV_CODEC_CAP_DR1’?
       __pyx_t_7 = __Pyx_PyInt_From_int(AV_CODEC_CAP_HYBRID); if (unlikely(!__pyx_t_7)) __PYX_ERR(0, 125, __pyx_L1_error)
                                        ^~~~~~~~~~~~~~~~~~~
                                        AV_CODEC_CAP_DR1
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cuz2u6hl/av/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cuz2u6hl/av/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j_vhmkyd/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/abhishek/.local/include/python3.7m/av Check the logs for full command output.

## System information
Linux ubuntu 5.4.0-1015-raspi #15~18.04.1-Ubuntu SMP Fri Jul 10 09:25:12 UTC 2020 armv7l armv7l armv7l GNU/Linux

**Comment by jlaine** [comment]
Exactly, this is not an issue with `aiortc`, I suggest you move this issue to the `PyAV` repo.
