### ISSUE TITLE
Handling streams from different android cameras

### ISSUE THREAD

**Issue by raghavendrajain** [aiortc/aiortc#409]
I cam get the stream of images from different android cameras. 

1, I want to do processing on each frame from each camera.
2. Save the result of processing in the database.

I do not need to display the frames anywhere.  Is `aiortc` suitable for this? Can you suggest some alternative, please?
I have studied the `server.py` example code and used it previously.

**Comment by jlaine** [comment]
Hi! WebRTC is about exchanging media and/or messages over the network between two peers. I'm not sure I understand how this fits in with your project?

**Comment by optimays** [comment]
Hi @jlaine Thanks for the kind reply and I apologize for the lack of clarity. I could find a solution to my problem using `Websockets` and understood that this is beyond the scope of WebRTC. I will close the question.

**Comment by raghavendrajain** [comment]
Hi @jlaine Thanks for the kind reply and I apologize for the lack of clarity. I could find a solution to my problem using Websockets and understood that this is beyond the scope of WebRTC. I will close the question.
