### ISSUE TITLE
The start button click on page load does not work on nginx

### ISSUE THREAD

**Issue by raghavendrajain** [aiortc/aiortc#410]
I want the streaming to start as soon as the page loads, I wrote this small function

```
// This starts the start button by default
window.onload = function(){
  document.getElementById('start').click();
}
```
When I run on the localhost, it works well. But when I use a reverse proxy like `Nginx`, the video stream on the webpage is not shown. I want the stream to start automatically without any page button pressing.

**Comment by jlaine** [comment]
I don't see what nginx has to do with WebRTC, it sounds more like a case of localhost vs other hosts.

Be aware that browsers often have a different behaviour on localhost vs other hosts, e.g. requiring user input.

**Comment by raghavendrajain** [comment]
@jlaine yes the unmodified example works perfectly fine! Its just that when I automate the clicking of START button, it does not work. As you said, browsers have different behavior and may require user input. So, that could be the issue.
