### ISSUE TITLE
MediaPlayer for windows

### ISSUE THREAD

**Issue by colesoria** [aiortc/aiortc#415]
I'm getting crazy, does anyone know how can I setup MediaPlayer for windows? In examples only works for Linux and Mac

**Comment by jlaine** [comment]
Please be more specific, what doesn't work for you? Are you unable to play audio/video from a file?

**Comment by Pnlmon** [comment]
He probably meant the example on https://aiortc.readthedocs.io/en/latest/helpers.html?highlight=MediaPlayer#aiortc.contrib.media.MediaPlayer

**Comment by nihalar** [comment]
How to read webcam in windows? It says '/dev/video0' file not found. What should be the filename for windows?

**Comment by Pnlmon** [comment]
> How to read webcam in windows? It says '/dev/video0' file not found. What should be the filename for windows?

https://stackoverflow.com/questions/43943113/what-is-windows-equivalent-to-linuxs-dev-video0
You need to specify the name of the video interface

**Comment by jlaine** [comment]
Supposing your camera name is "Integrated Camera", I think the syntax would be:

```
player = MediaPlayer('video=Integrated Camera', format='dshow', options={
    'video_size': '640x480'
})
```

Can you confirm whether this works so I can add it to the MediaPlayer documentation?

**Comment by jlaine** [comment]
Ping? Can anyone running Windows confirm whether the syntax above is correct so that I can update the docs?

**Comment by Pnlmon** [comment]
Yep it's working for me on Windows.
