### ISSUE TITLE
`pip install aiortc` type error with 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by geekcyl** [aiortc/aiortc#416]
ERROR: Command errored out with exit status 1:
     command: /home/reeman/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8YhM42/aiortc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8YhM42/aiortc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-Cu8Z_v
         cwd: /tmp/pip-install-8YhM42/aiortc/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8YhM42/aiortc/setup.py", line 9, in <module>
        with open(about_file, encoding="utf-8") as fp:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by geekcyl** [comment]
use python2

**Comment by jlaine** [comment]
Python2 is not supported, this is an asyncio-based project.
