### ISSUE TITLE
Ice connection state stuck at new state, when getting both local and remote description

### ISSUE THREAD

**Issue by hansenwuwu** [aiortc/aiortc#417]
I am trying to build my own webrtc connection with javascript and python.
I use javascript as start point, to send offer to python.
but on the python side, Ice connection state stuck at new state.

First, I start with javascript to create offer
and wait for ice gathering to complete, to make sure that my offer SDP include ICE candidate!
then send to python peer

```
// create offer & send to python
function negotiate() {
    return pc.createOffer().then(function(offer) {
        return pc.setLocalDescription(offer);
    }).then(function() {
        // wait for ICE gathering to complete
        return new Promise(function(resolve) {
            if (pc.iceGatheringState === 'complete') {
                resolve();
            } else {
                function checkState() {
                    if (pc.iceGatheringState === 'complete') {
                        pc.removeEventListener('icegatheringstatechange', checkState);
                        resolve();
                    }
                }
                pc.addEventListener('icegatheringstatechange', checkState);
            }
        });
    }).then(function() {

        // ----- send offer to python here ----- //

    });
}
```

Python then receive offer from javascript
```
    # handle offer received from javascript
    await pc.setRemoteDescription(offer)

    # send answer
    answer = await pc.createAnswer()
    await pc.setLocalDescription(answer)

    ## ----- send answer back to javascript ----- ##
```

Then back to javascript 
```
// setRemoteDescription for that answer
```

After doing these things,
with both peer set up local & remote description
and both description include ICE candidate

But the state of python side remain "new"
it just do nothing.

It'll be really grateful for someone who can help.

**Comment by jlaine** [comment]
Can you please try using the `server` example provided with aiortc and report what the behaviour is?

**Comment by jlaine** [comment]
No response from submitter, closing.
