### ISSUE TITLE
Installation issue on raspberry pi 4

### ISSUE THREAD

**Issue by junartho** [aiortc/aiortc#418]
Hi @jlaine 
when i was executing  command "pip3 install aiohttp aiortc opencv-python" there's an error installation like this:
**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ujuwrkn4/pylibsrtp/**

Fyi, i did "sudo apt install libsrtp2-dev"

What should i do next?

**Comment by jlaine** [comment]
I have nothing to go on here, please post a full log.

**Comment by hpgmiskin** [comment]
@junartho try installing with the PiWheels index as this could avoid the need to build a wheel locally.

```
pip3 install aiohttp aiortc opencv-python --extra-index-url=https://www.piwheels.org/simple
```

**Comment by jlaine** [comment]
This is being tracked here: https://github.com/piwheels/packages/issues/184
