### ISSUE TITLE
Using srt as a source in the webcam example produces a buffer error

### ISSUE THREAD

**Issue by medcelerate** [aiortc/aiortc#419]
I'm attempting to pull from an srt source using the MediaPlayer. I have a version of pyav built against a version of libav that has srt support enabled. However I am getting the below error (using mediaplayer in the webcam example).

```
SRT:RcvQ:worker*E:SRT.c: %888388940:No room to store incoming packet: offset=7935 avail=0 ack.seq=1932575440 pkt.seq=1932583375 rcv-remain=8191
```

If I simply do 
```
av.open('srt://{ip_here}:9000?mode=caller') 
```

I eventually get the same error but if I start decoding the streams immediately using a for loop then the error isn't encountered. This should be akin to pulling in an rtmp stream that is using h.264.

**Comment by jlaine** [comment]
This looks like it's outside the scope of `aiortc` and would better be addressed in `PyAV` itself.

**Comment by medcelerate** [comment]
I feel that pyav is correctly handling the stream but aiortc isn't executing an iteration on it immediately.

**Comment by jlaine** [comment]
Can you peovide steps to reproduce this, i.e. how do i launch an SRT server?

**Comment by medcelerate** [comment]
To launch an SRT server:
1. Download OBS
2. Configure video encoding settings to stream h.264 video
3. In stream settings set the output url to `srt://127.0.0.1:43560?mode=listener` this will launch an srt server on your local machine listening at port 43560
4. Make sure you use pyav with a version of ffmpeg that has srt enabled. The following dockerfile will build the appropriate ffmpeg. Make sure you install pyav with the --no-binary flag so it uses the native ffmpeg.
5. Use the MediaPlayer object constructor and pass in the srt url: `srt://127.0.0.1:43560?mode=caller`
6. Launch python script and errors will begin.

Normally if you immediately begin iterating over the video stream produced by pyav it does not error, but in the case of the MediaPlayer class the iteration is deferred for some time leading to the buffer issue.

```
FROM python:3.7
COPY requirements.txt /tmp

RUN curl -L https://github.com/markuslindenberg/ffmpeg-deb-srt/raw/master/pubkey.gpg | apt-key add -
RUN echo "deb https://ffmpeg-deb-srt.fra1.cdn.digitaloceanspaces.com/buster buster main" | tee /etc/apt/sources.list.d/ffmpeg-srt.list
RUN apt update && apt install -y libavcodec58=7:4.1.4-1~deb10u1+srt1 \
    libavdevice58=7:4.1.4-1~deb10u1+srt1 \
    libavfilter7=7:4.1.4-1~deb10u1+srt1 \
    libavformat58=7:4.1.4-1~deb10u1+srt1 \
    libavresample4=7:4.1.4-1~deb10u1+srt1 \
    libavutil56=7:4.1.4-1~deb10u1+srt1 \
    libpostproc55=7:4.1.4-1~deb10u1+srt1 \
    libswresample3=7:4.1.4-1~deb10u1+srt1 \
    libswscale5=7:4.1.4-1~deb10u1+srt1 \
    ffmpeg=7:4.1.4-1~deb10u1+srt1

RUN apt install -y libavformat-dev=7:4.1.4-1~deb10u1+srt1 \
    libavcodec-dev=7:4.1.4-1~deb10u1+srt1 \
    libavdevice-dev=7:4.1.4-1~deb10u1+srt1 \
    libavutil-dev=7:4.1.4-1~deb10u1+srt1 \
    libavfilter-dev=7:4.1.4-1~deb10u1+srt1 \
    libswscale-dev=7:4.1.4-1~deb10u1+srt1 \
    libswresample-dev=7:4.1.4-1~deb10u1+srt1 \
    libpostproc-dev=7:4.1.4-1~deb10u1+srt1

```
