### ISSUE TITLE
Possibility of lossless recording of packets

### ISSUE THREAD

**Issue by d3im** [aiortc/aiortc#420]
I think about lossless packet saving to file (e.g. MKV file) - I suppose it's not supported ATM, - it seems it depayloads packet and gets frame and it must be then reencoded. But would it work to just mux packets (audio+video) to e.g. MKV? Or somehow else. It should be HW friendly.

**Comment by jlaine** [comment]
This has been brought up multiple times, but I have yet to see a working PR for this. So as things stand the answer would be "no it's not supported".
