### ISSUE TITLE
Will not work with resolution > 720P (iPhone 8 Safari iOS 11)

### ISSUE THREAD

**Issue by slamjammin** [aiortc/aiortc#421]
All of the connection messages seem to go through, but for some reason the video will now. I am stuck.

Any thoughts of where to look?

This is for the server example with OpenCV

**Comment by steveseguin** [comment]
iPhone does not support higher than 720p30 with the H264 encoder.  You will need to use VP8 (or VP9 with experimental flag set currently) to go higher.
