### ISSUE TITLE
how to get RTCPeerConnection.connectionState?

### ISSUE THREAD

**Issue by guillaumeldc** [aiortc/aiortc#424]
Thanks for the cool library.

So far I've been able to integrate this to my react app using the webcam example with my HDMI capture cards.
I'm just not getting how to catch the event which tells me that the connection has closed.  
I would have thought that this event would be "iceconnectionstatechange" but for some reason when calling pc.close() on the remote (react app), no event 'closed' is being triggered.
the webcam example illustrate that very well when running with option -v. the sender is continuously sending RtcpSdesPacket packets even after connection stops. 

how can I catch the RTCPeerConnection.connectionState event? DTLS sends an event that connection was closed by remote though but I'm unable to catch this event... 

DEBUG:dtls:client - DTLS shutdown by remote party
DEBUG:dtls:client - State.CONNECTED -> State.CLOSED

The goal is to be able to fully end the coroutine that's running when the connection drops, browser or tab closes for example. Which is being done on webcam example when shutting down the server. At the moment, I create a data channel and send a kill message when I want to close the connection "fully". 

Thanks for the help.

**Comment by Laityned** [comment]
I think this is already tipped out in issue #359 . 
However I think we should implemented it as stated in the webrtc documention:

https://www.w3.org/TR/2021/REC-webrtc-20210126/#update-the-connection-state
and
https://www.w3.org/TR/2021/REC-webrtc-20210126/#dom-rtcpeerconnectionstate

The transport updates are already present in the the DTLS transport, so only a update on the peer connection should happen.

**Comment by jlaine** [comment]
There is a work-in-progress PR here #465

**Comment by jlaine** [comment]
RTCPeerConnection gained a `connectionState` attribute and a `connectionstatechange` event
