### ISSUE TITLE
Setting up codec preferences to disable VP8

### ISSUE THREAD

**Issue by jpiat** [aiortc/aiortc#427]
Hi, 

I'm trying to use aiortc webcam example but I want to force encoding to h264. When I set the codec preference to H264 codec only the offer still starts with VP8. Is there a way to make sure VP8 won't be part of the offer ?

Thanks

**Comment by jpiat** [comment]
Hi,

i found the answer to my question so i'll document here. When setting up preferred codecs for a transceiver, this preference is ignored when creating the local local RTP stream in rtcpeerconnection:
``
rtp = RTCRtpSendParameters(
            codecs=transceiver._codecs,
            headerExtensions=transceiver._headerExtensions,
            muxId=transceiver.mid,
        )
``

this list of codecs should be filtered using the_preferred_codecs property of the transceiver.

**Comment by jlaine** [comment]
Instead of playing with private API members have you tried using `setCodecPreferences` ?

https://aiortc.readthedocs.io/en/latest/api.html#aiortc.RTCRtpTransceiver.setCodecPreferences

See also:

https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiver/setCodecPreferences

**Comment by jpiat** [comment]
SetCodecPreference works to set the codec preference on the receiver side,
but what if you want the sender to only propose a reduced set of codecs ?
In aiortc the list of available codec on the sender side is statically
defined inside the codecs sub folder so if you have a sender that does not
propose VP8 encoding you have no way to remove it from the proposed codecs.

Le sam. 23 janv. 2021 à 14:15, Jeremy Lainé <notifications@github.com> a
écrit :
