### ISSUE TITLE
pip3 install av has a issue

### ISSUE THREAD

**Issue by 80lksky** [aiortc/aiortc#435]
src/av/codec/codec.c:6138:36: error: ‘AV_CODEC_CAP_HYBRID’ undeclared (first use in this function); did you mean ‘AV_CODEC_CAP_DR1’?
       __pyx_t_7 = __Pyx_PyInt_From_int(AV_CODEC_CAP_HYBRID); if (unlikely(!__pyx_t_7)) __PYX_ERR(0, 125, __pyx_L1_error)
                                        ^~~~~~~~~~~~~~~~~~~
                                        AV_CODEC_CAP_DR1
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-efvx_1xa/av/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-aheyo86y-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-efvx_1xa/av/

**Comment by jlaine** [comment]
Wrong project, if you have issues with PyAV please report them there. Also, PyAV provides binary wheels for most platforms nowadays, I'm surprised by this.
