### ISSUE TITLE
Using data-channels without media stack dependencies

### ISSUE THREAD

**Issue by ezdac** [aiortc/aiortc#436]
First of all, awesome work you are doing here.
For our open-source project (https://github.com/raiden-network/raiden), we are using `aiortc` 
as a data-communication layer without the need for the video and audio media stack.
Since `ffmpeg` / `PyAV` are heavy dependencies that complicate building and distribution for some platforms, we would like to be able to pull in only a subset of aiortc's functionalities without having to carry media dependencies with us.
Is there an easy way this is currently possible, and if not - are there plans in the near future to support this?

**Comment by lgrahl** [comment]
Duplicate of #78. And see the discussion of #243 for more insights.

**Comment by ezdac** [comment]
Okay, thank you and sorry for the duplicate. I will close this as we decided to go with the dependencies.
