### ISSUE TITLE
Low fps of output rtmp stream.

### ISSUE THREAD

**Issue by MsWik** [aiortc/aiortc#437]
Hello. I am trying to use this solution to relay webrtc-> rtmp. Faced a problem with low fps of the output video, while the processor load on the server does not exceed 10-15%. What can be done to ensure that the solution consumes all available resources?

**Comment by jlaine** [comment]
Hi, I don't quite understand what you are doing here, could you give me more information?

From the sound of it, you are receiving a video stream over WebRTC, decoding it and then re-encoding it to send it out via RTMP?
