### ISSUE TITLE
step time control in a stream

### ISSUE THREAD

**Issue by pujithaAIV** [aiortc/aiortc#439]
Is there any possibility to control time steps from python while streaming a video in the media player?
for ex: I would like to slide the video step-time in python, in order to change in web interface.
thanks

**Comment by jlaine** [comment]
Hi! I don't quite understand what you're trying to do, could you please elaborate?

**Comment by pujikodi** [comment]
Hi, thanks for your response. I would like to add a player that has a streaming function and add control functions (backward seek) which includes buffered frames in the player. So users can watch both live feed or previous frames by jumping to specific timestamps in the buffered video. Is there any possibility to keep buffered frames without deleting and syncing the video? ( similar as youtube live) thanks
