### ISSUE TITLE
MediaPlayer add microphone input (PyQt5)

### ISSUE THREAD

**Issue by el07694** [aiortc/aiortc#440]
How can we use a PyQt5 QAudioOutput (microphone) or QDataStream as input to MediaPlayer helper?

**Comment by jlaine** [comment]
There is zero intersection between `aiortc` and `PyQt5`. You can either:

- leverage the existing `MediaPlayer` which exposes FFmpeg's capabilities to acquire sound
- or write your own media source, based on whatever pipeline you wish
