### ISSUE TITLE
TCP ICE candidates are not supported

### ISSUE THREAD

**Issue by Laky-64** [aiortc/aiortc#443]
I can make passive offer on JavaScript but on this library i can't make

**Comment by jlaine** [comment]
Could you clarify what you mean by a "passive offer" and explain how you would do it with the standard Javascript API for WebRTC?

**Comment by watzon** [comment]
Super obscure question with bad english, but maybe they're referring to the ability to use a passive TCP candidate? https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Connectivity#tcp_candidate_types

**Comment by Laky-64** [comment]
Exactly

**Comment by jlaine** [comment]
Ah in that case the answer is simple: TCP candidates are not supported.

**Comment by rojserbest** [comment]
@jlaine can I get your Telegram username to talk over there?

**Comment by jlaine** [comment]
Sorry I don't use Telegram. Can we just keep the discussion on the issue tracker?

**Comment by rojserbest** [comment]
@jlaine sorry, yes we can...
And btw it's easy to install Telegram, it's just ~30 megabytes. If you changed your mind, join [this group](https://t.me/tgcallschat).

**Comment by jlaine** [comment]
Whether Telegram is easy to install is beside the point. There is a public issue tracker so that I don't have to engage in one-to-one discussions with every single aiortc user, and end up repeating myself.

**Comment by watzon** [comment]
Basically what they're trying, and failing, to say is that having TCP candidates be supported would be really helpful for a project that's being worked on for Telegram voice calls. I understand if you don't want to put in the work yourself to support TCP candidates, but would it be possible for someone to PR those changes in? And if so would you be willing to provide a bit of guidance to get that person started?

Unfortunately there don't seem to be many great alternatives at the moment, besides someone else writing a whole other library just for the TCP side of things.

**Comment by rojserbest** [comment]
And actually we're not single users, we're thousands.

**Comment by watzon** [comment]
@rojserbest there aren't thousands of people, especially not right now, that will be using pytgcalls. This is, admittedly, an edge case and not a feature that most people will need in a library like aiortc, which is why it doesn't exist yet. Additionally we aren't entitled to have Jeremy help us here. It would be nice to get this implemented in aiortc, but if that doesn't end up happening we can always write something ourselves.

**Comment by jlaine** [comment]
If you want to move this issue forward a good starting point would be to collect pointers to the various RFCs describing how TCP candidates work. Next, familiarize your self with https://github.com/aiortc/aioice/ as this is where the bulk of the changes (or even hopefully all the changes) will need to be me made. Whats is not clear to me is whether the WebRTC stack needs to be aware of the fact it's transmitting over TCP, or whether the ICE stack can hide the implementation details.

On a sidenote: one reason I did not implement support for TCP candidates is that transmitting audio/video over TCP is a textbook protocol mismatch, TCP has none of the desirable characteristics for this usecase.

**Comment by roj1512** [comment]
There is now an aiortc alternative that supports this: https://github.com/MarshalX/python-webrtc
