### ISSUE TITLE
I want to deploy it on a web server on which, multiple users can connect

### ISSUE THREAD

**Issue by AbhiAva** [aiortc/aiortc#444]
Hi there.

I am trying to build an application based on this and I wanted to know if I can deploy it on a server (lets say Nginx-Gunicorn based python websocket server). **My end use case will be to make this available on my digital ocean droplet with a specified IP, and to which multiple users can connect perpetually at anytime;** the size of the droplet is pretty huge so it can support an application with such set of specifications. What would be the best practice to follow to achieve such a goal?

Kindly let me know if there's a solution feasible for my use case.
Thanks in advance! Cheers.

**Comment by codebugged** [comment]
Hi @AbhiAva 
How did you solve this issue?

**Comment by AbhiAva** [comment]
> Hi @AbhiAva
> How did you solve this issue?

Hi @codebugged . Apologies for late response. I basically used [Gunicorn](https://docs.aiohttp.org/en/v0.20.0/gunicorn.html) with Aiohttp framework as a standalone with network proxy Nginx, and it's working just fine! Also, it would be of a huge advantage if you deployed your application with a network proxy monitoring tool like supervisord.
