### ISSUE TITLE
How do I avoid decoding and re-encoding in MediaPlayer/RTCRtpSender? 

### ISSUE THREAD

**Issue by jimcondon** [aiortc/aiortc#449]
I was looking at MediaPlayer in media.py. It decode the frames for both audio and video, which RTCRtpSender then re-encodes. Is there a way to configure the MediaPlayer and RTCRtpSender to not decode the data but to only demux it only and pass the input packets to RTCRtpSender? Or is there an example that does this? 

My input stream is H.264 video and AAC audio which the client accepts so the decode and encode is adding unneeded overhead.

**Comment by jlaine** [comment]
In what scenario are you decoding and re-encoding the SAME audio / video? An echo server?

There is no way to short-circuit audio/video encoding in aiortc currently. This question crops up periodically, and there was even an attempted PR in #136. However this rests on a misunderstanding of what WebRTC does: it is not a pipe which blindly forwards pre-encoded data, the WebRTC stack needs some degree of knowledge of what it is sending, at the very least for jitter buffer + error recovery.

**Comment by jimcondon** [comment]
Jeremy, thanks for the feedback. I'm interfacing with a camera that streaming h264 and aac packaged in a transport stream and interfacing it to a service that only supports webRTC. I'm trying to reduce the overhead so I'm looking to remove the encoding and decoding of the h.264 stream on my server. Do you not think this is possible with WebRTC or just aiortc?

**Comment by jlaine** [comment]
My understanding is that you cannot have a truly spec-compliant WebRTC implementation with encoding decoupled from the WebRTC stack. However, it is likely you can hack together something that works. I'm not adverse to review a PR in this direction, but so far the attempts I've seen were not brought to completion.
