### ISSUE TITLE
Audio not trasmitted/silent

### ISSUE THREAD

**Issue by Laky-64** [aiortc/aiortc#451]
I'm trying to trasmit the audio to the telegram server with using Pyrogram, but not working/is silent the audio

**Comment by jlaine** [comment]
Uhm OK, does this bear any relationship with aiortc?

**Comment by Laky-64** [comment]
I tried doing the same thing of broadcasting audio with Javascript + NodeJS(WebRTC) and it worked them

**Comment by jlaine** [comment]
Well good for you if it works in JavaScript I guess? I have no idea what you expect me to do about this issue, I really have nothing to go on.
