### ISSUE TITLE
Media player how to identify if stream stop

### ISSUE THREAD

**Issue by SourceCodeZone** [aiortc/aiortc#452]
I am running janus example with mjpeg url s Media player input, sometimes  the streams are breaking and how I can know that the video end or stream break, so I can quit the script.

        player = MediaPlayer("http://192.168.1.162:9032")
       -----------------------------------
       ----------------------------------
        # send video
            await publish(plugin=plugin, player=player)

            # exchange media for 10 minutes
            print("Exchanging media")
            while True:
                     #break if stream breaks.

**Comment by edjcai** [comment]
I'm having a similar issue where the stream is breaking up after running for a while (10 min). 

We noticed this error whenever the stream breaks: 
`Circular buffer overrun. To avoid, increase fifo_size URL option. To survive in such case, use overrun_nonfatal option`

**Comment by Laityned** [comment]
Are you only interested if the track of the webrtc connection stops? 
Or are you interested when the peer connection is closed?

**Comment by lehanesa** [comment]
> I'm having a similar issue where the stream is breaking up after running for a while (10 min).
> 
> We noticed this error whenever the stream breaks:
> `Circular buffer overrun. To avoid, increase fifo_size URL option. To survive in such case, use overrun_nonfatal option`

To stop that error add the overrun_nonfatal option to the url. For example:
udp://@IPADDRESS:PORT?overrun_nonfatal=1
