### ISSUE TITLE
ModuleNotFoundError: No module named 'aiortc.codecs._opus'

### ISSUE THREAD

**Issue by iscsrl** [aiortc/aiortc#466]
Installing latest release 1.1.1 I get this two errors trying to run the example **videostream-cli**:
`ModuleNotFoundError: No module named 'aiortc.codecs._opus'`
and
`from av import VideoFrame ` Cannot find reference 'VideoFrame' in '__init__.py | __init__.py' 

I tried installing `opus` separately and uninstalled/reinstalled also `av` lib but no luck with it.
Any tips?

**Comment by jlaine** [comment]
Did you actually install the "aiortc" package, this seems very strange indeed.

pip install -U pip
pip install -U aiortc

**Comment by ThisIsIsaac** [comment]
same issue. Even after running 

```
pip install -U pip
pip install -U aiortc
```
