### ISSUE TITLE
Does VP8 codec support alpha channel ?

### ISSUE THREAD

**Issue by arthurmchr** [aiortc/aiortc#468]
I am trying to create a video track with an alpha channel.
The images for the `VideoStreamTrack` came from opencv.
Using `VP8/90000` codec (through `sdpFilterCodec`, as show in exemple), I am not able to receive video alpha on the browser (chrome).
Maybe the problem is in the following :
`VideoFrame.from_ndarray(cv2.imdecode(np.frombuffer(result_image_buff, np.uint8), 1), format="bgra")`
`result_image_buff` is a png encoded image in opencv. If I use it directly in browser, I have the alpha channel.

Thanks for any suggestions.

**Comment by arthurmchr** [comment]
It seems that WebRTC does not support alpha channel yet :
https://stackoverflow.com/questions/40972777/alpha-transparency-in-capturestream-api-for-firefox-and-chrome-over-webrtc

**Comment by jlaine** [comment]
OK thanks for digging into this and reporting back!
