### ISSUE TITLE
Query: Is any implementation availble for receiving a WebRTC Stream published from WOWZA

### ISSUE THREAD

**Issue by amitvikram1985** [aiortc/aiortc#475]
We have to implement decoding of webrtc stream using python, We are kind of stuck in implementation.
Could any one provide some help on this so we can proceed?

Thanks in advance.

**Comment by jlaine** [comment]
I'm sorry but I'm going to close this as out of scope, this isn't a help forum. I would suggest you try other options such as StackOverflow.
