### ISSUE TITLE
Track signal not emit in setRemoteDescription even when media track availabe in received SDP offer

### ISSUE THREAD

**Issue by deep-saxena** [aiortc/aiortc#476]
Hi,

The received SDP message specifies media is available for audio and video. 

Following is the SDP message
```
v=0
o=WowzaStreamingEngine-next 2111977269 2 IN IP4 127.0.0.1
s=-
t=0 0
a=fingerprint:sha-256 C6:43:59:4F:77:FB:E1:D5:32:35:F0:C8:88:E0:16:62:C7:33:0C:2A:0E:11:30:F9:B7:F7:BB:B5:DC:DA:32:F1
a=group:BUNDLE video audio
a=ice-options:trickle
a=msid-semantic:WMS *
m=video 9 RTP/SAVPF 97
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=1;profile-level-id=42C020;sprop-parameter-sets=Z0LAIAkMjUAoAtkA8IhGoA==,aDBI48g=
a=cliprect:0,0,720,1280
a=framesize:97 1280-720
a=control:trackID=2
c=IN IP4 0.0.0.0
a=sendrecv
a=ice-pwd:45a0b726fce7d35253dc08c9091ea519
a=ice-ufrag:881fa4e3
a=mid:video
a=msid:{32434228-8da1-4f51-9aba-236b6535d28b} {4ae647a6-365a-4603-b10d-ac5565f98c22}
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-mux
a=setup:actpass
a=ssrc:106050586 cname:{b90cc410-4e38-4fd5-b94f-53d48f45c85b}
m=audio 9 RTP/SAVPF 96
a=rtpmap:96 OPUS/48000/2
a=control:trackID=1
c=IN IP4 0.0.0.0
a=sendrecv
a=ice-pwd:45a0b726fce7d35253dc08c9091ea519
a=ice-ufrag:881fa4e3
a=mid:audio
a=msid:{32434228-8da1-4f51-9aba-236b6535d28b} {98f9d6bb-d9ae-4e14-86b5-1b28c1f1e0a3}
a=rtcp-mux
a=setup:actpass
a=ssrc:1128997260 cname:{b90cc410-4e38-4fd5-b94f-53d48f45c85b}
```
As per my understanding "track" signal is emit when setRemoteDescription is called. But, for me it is not able to trigger  @pc.on("track").

What I require is i can get the stream in MediaStreamTrack. 
I am taking reference from [https://github.com/aiortc/aiortc/blob/main/examples/server/server.py](https://github.com/aiortc/aiortc/blob/main/examples/server/server.py)

**Comment by jlaine** [comment]
Can you please run the unmodified server example and report whether it works for you? Your assertion that the track event is not emitted seems excessively broad.

**Comment by deep-saxena** [comment]
The server example is working fine. I was also able to resolve the issue in my code. Now @pc.on("track") is getting triggered.  Thanks.

What's remaining is the code is waiting on recv() of Frame.
Now the code is stuck at frame = await self.track.recv() in VideoTransformTrack()

The last message received on the websocket connection is a remote ice candidate which I add  using the "await pc.addIceCandidate(remote_ice_candidate)"

Received ICE candidate.
"iceCandidates":[{"candidate":"candidate:0 1 TCP 50 35.244.42.162 1935 typ host generation 0","sdpMid":"","sdpMLineIndex":0}

This is the only ICE candidate i receive from the WOWZA publisher. No UDP protocal ICE candidates. Can you suggest what i am missing?

**Comment by deep-saxena** [comment]
Hi, thanks for your response. I am able to run the server example as-is. 
This is another code i am working on taking reference from server code. In that I receive only TCP ice candidate. But no TCP ice candidates are identified for the local system.

**Comment by jlaine** [comment]
How come are you unable to run the server example as-is?
