### ISSUE TITLE
When I use the webcam example, sometimes the screen will get blurred. Why and how to solve it ?

### ISSUE THREAD

**Issue by zhaopings** [aiortc/aiortc#478]

**Comment by jlaine** [comment]
I have nothing to go on here, please provide more information including steps to reproduce.

**Comment by zhaopings** [comment]
I'm building a video object detection system. I want to send the detection results and video to web synchronously. After studying the **server** example, my solution is to write the detection results to the buffer of Vp8Encoder, which means that I have slightly modified the source code:

*rtcrtpsender.py:*
![image](https://user-images.githubusercontent.com/28303246/108798392-afe71c80-75c8-11eb-92d7-9dbd4efea502.png)
*vpx.py(here **value** is detection results):*
![image](https://user-images.githubusercontent.com/28303246/108798681-59c6a900-75c9-11eb-91d4-0e03e87c0cc4.png)

In this way, the detection results are sent to web synchronously, but sometimes the screen gets blurred(here the blue rectangular boxes are detection results):

![1](https://user-images.githubusercontent.com/28303246/108798838-b3c76e80-75c9-11eb-9a60-bc81265f93e4.jpg)

Do you have any idea about this problem? Thank you！

**Comment by jlaine** [comment]
I can only solve bugs in aiortc, not your custom code. Does the unmodified code work?

Hacking the internals of aiortc is almost certainly not the way to go for your usecase, consider writing a custom MediaStreamTrack subclass.

**Comment by zhaopings** [comment]
Thanks for your help, I will try to solve it.

**Comment by jlaine** [comment]
OK, I'm going to close this issue. Feel free to re-open it if you find an actual bug in aiortc.

**Comment by jokecen** [comment]
> Thanks for your help, I will try to solve it.

Have you ever solved it?
