### ISSUE TITLE
Firefox issues with only mDNS candidates

### ISSUE THREAD

**Issue by ioioioio** [aiortc/aiortc#481]
Hello!
I've been trying to run the [example server](https://github.com/aiortc/aiortc/tree/main/examples/server) on Firefox without the audio and the video. Only the DataChannel. I've noticed when the audio and the video are both unchecked, the ping does not occur anymore. The ICE gathering state is "complete", the signaling state is "stable", but the ICE connection state is left to "new".

In fact, this is similar to what I am trying to do in my code with aiortc. My experiments seem to indicate that WebRTC won't work on Firefox if getUserMedia has not been called.

I am using aiortc 1.1.2, Ubuntu 20.10, Firefox 85.0.1, and  Python 3.8.6.

It works fine on Chromium.

I've tried  a [similar example](https://github.com/node-webrtc/node-webrtc-examples/tree/master/examples/ping-pong) on nodejs. It works fine. It seems to be a aiortc issue.

Thank you

**Comment by jlaine** [comment]
When the user had not granted permissions for getUserMedia, Firefox uses mDNS candidates, and I reported what looks like a bug in Firefox:https://bugzilla.mozilla.org/show_bug.cgi?id=1691189

**Comment by jlaine** [comment]
AFAICT this is still an issue.

**Comment by Interpause** [comment]
Ignore the above. I forgot to `await` `asyncio.sleep(0)` in my ICE candidate receiving logic, don't know why it would work at all in the first place, but I have verified the issue when switching networks no longer occurs.

**Comment by Interpause** [comment]
Follow up, killing all Chromium instances, including PWAs and (for extra measure) Electron-based apps worked without needing a full restart. Likely to be Chromium mDNS issue I guess.

**Comment by jlaine** [comment]
I don't believe Firefox has changed their behaviour so this is still relevant.

**Comment by jensbjorgensen** [comment]
yes, still an issue, just ran into this trying out the webcam.py code on Firefox 105.0 (ubuntu 20.04). I'd propose (and I'll submit a PR) that a comment at least be added to webcam.py warning that it might not work, would've saved me the hours futzing with it.
