### ISSUE TITLE
How to use one same port for audio and video 

### ISSUE THREAD

**Issue by lidedongsn** [aiortc/aiortc#482]
v=0
o=- 3823149922 3823149922 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic:WMS *
m=audio 64412 UDP/TLS/RTP/SAVPF 96 0 8
c=IN IP4 172.16.12.70
a=recvonly
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=mid:0
a=msid:72659b40-9c86-4f10-8f72-2ea25931ce30 e3921e7c-f493-44b6-a0aa-e06fc091463a
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc:1740652489 cname:a263f662-1d59-41c4-8cc1-fd0fb5714c7c
a=rtpmap:96 opus/48000/2
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=candidate:5b4d4430b6f6209e8994a021bed6d647 1 udp 2130706431 172.16.12.70 64412 typ host
a=candidate:23d2890b2f90d925994623d7d764d4cb 1 udp 2130706431 169.254.159.115 64414 typ host
a=candidate:bc7c2d7a8253d0aed9c2b99d287d772c 1 udp 2130706431 169.254.11.155 64416 typ host
a=end-of-candidates
a=ice-ufrag:KyxR
a=ice-pwd:Dm33ZZPkkMNl3WjQGsy0yx
a=fingerprint:sha-256 B6:7A:BB:33:0F:30:0D:70:AF:26:BB:F4:8B:2F:E2:C4:FE:C4:FD:91:48:9A:E1:14:9A:27:67:4F:BF:2D:69:39
a=setup:actpass
m=video 64411 UDP/TLS/RTP/SAVPF 97 98 99 100 101 102
c=IN IP4 172.16.12.70
a=recvonly
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=mid:1
a=msid:72659b40-9c86-4f10-8f72-2ea25931ce30 5cf7665f-7fe0-4166-96ca-d231495d6ad5
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc-group:FID 4291794168 3670621262
a=ssrc:4291794168 cname:a263f662-1d59-41c4-8cc1-fd0fb5714c7c
a=ssrc:3670621262 cname:a263f662-1d59-41c4-8cc1-fd0fb5714c7c
a=rtpmap:97 VP8/90000
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 goog-remb
a=rtpmap:98 rtx/90000
a=fmtp:98 apt=97
a=rtpmap:99 H264/90000
a=rtcp-fb:99 nack
a=rtcp-fb:99 nack pli
a=rtcp-fb:99 goog-remb
a=fmtp:99 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42001f
a=rtpmap:100 rtx/90000
a=fmtp:100 apt=99
a=rtpmap:101 H264/90000
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 goog-remb
a=fmtp:101 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42e01f
a=rtpmap:102 rtx/90000
a=fmtp:102 apt=101
a=candidate:5b4d4430b6f6209e8994a021bed6d647 1 udp 2130706431 172.16.12.70 64411 typ host
a=candidate:23d2890b2f90d925994623d7d764d4cb 1 udp 2130706431 169.254.159.115 64413 typ host
a=candidate:bc7c2d7a8253d0aed9c2b99d287d772c 1 udp 2130706431 169.254.11.155 64415 typ host
a=end-of-candidates
a=ice-ufrag:Nj6B
a=ice-pwd:bscZb2QiBYch6Di0vRqtdU
a=fingerprint:sha-256 B6:7A:BB:33:0F:30:0D:70:AF:26:BB:F4:8B:2F:E2:C4:FE:C4:FD:91:48:9A:E1:14:9A:27:67:4F:BF:2D:69:39
a=setup:actpass

**Comment by jlaine** [comment]
What's this SDP blob (an answer, an offer, produced by who) and what's your question exactly? 

aiortc has support for the BUNDLE negotiation [1] so if the remote party supports it, only one ICE connection will in fact be used.

[1] https://tools.ietf.org/html/draft-ietf-mmusic-sdp-bundle-negotiation-54

**Comment by lidedongsn** [comment]
> What's this SDP blob (an answer, an offer, produced by who) and what's your question exactly?
> 
> aiortc has support for the BUNDLE negotiation [1] so if the remote party supports it, only one ICE connection will in fact be used.
> 
> [1] https://tools.ietf.org/html/draft-ietf-mmusic-sdp-bundle-negotiation-54

I generate local **offer** above， port 64412 for receiving audio，port 64411 for receiving video
I just wanna to use single port for receiving both audio and video, Now my question is how to create one  one ICE connection

**Comment by lidedongsn** [comment]
![image](https://user-images.githubusercontent.com/6139634/108999440-4278e000-76dd-11eb-9a0c-f8d1db80f0f5.png)
yeah, I understand this. Bundle is using "m=mid". RFC is the answer . seems ok

**Comment by kazuph** [comment]
Hi.

First of all, aiortc is a very useful library. I use it in my project as well.
And I am sorry to comment on this Issue once closed, but I have a question.

Is the conclusion of this Issue that it is possible to receive audio and video on the one same port?
Also, what is the best way to do this?

Thanks.
