### ISSUE TITLE
Control bitrate and resolution

### ISSUE THREAD

**Issue by mslavescu** [aiortc/aiortc#484]
Hi @jlaine,

I would like to thank you for building this amazing WebRTC project!
I was able to use it to build OSSDC VisionAI a realtime video processing platform to help with development and testing of computer vision and machine learning algorithms for home automation/robotics/self-driving cars and many other applications. 

See the project here with a very easy to use Google Colab notebook:
https://github.com/OSSDC/OSSDC-VisionAI-Core

Here is a demo of the project in action:
Isn't this fun?! MediaPipe Holistic neural net model processed in real time on Google Cloud 
https://www.youtube.com/watch?v=0l9Bb5IC86E

I would like to be able to control dynamically the bitrate and resolution on aiortc side.
On Android app side I have resolution and fps settings, but even if bandwidth is enough the aiortc remote client is downgrading the resolution and bitrate. It could be because of my implementation also.

Is there any way to do this it programmatically and force (or be more conservative on) the resolution and bit rate as long as the bandwidth and latency can support it?

Also I have to use certain versions of these packages to get reliable communication:
python-engineio==3.14.2 python-socketio[client]==4.6.0

Are these the best versions for both Windows and Linux?

**Comment by jlaine** [comment]
The bitrate for video is under the control of a bandwidth estimation algorithm, as is the case in the WebRTC stack shipped by browsers. I'm not sure there is an official API for manually controlling the bitrate.

The resolution on the other hand is under your control, just change the size of the frames you pass to aiortc?

**Comment by mslavescu** [comment]
Thanks @jlaine!

I need to play a bit more with Android side, as I see that the peer res and bitrate doesn't change when I stream a video source from PC (video stream from DepthAI camera 4K sensor and processed on Myriad X, core of DepthAI cameras):
https://www.youtube.com/watch?v=poTrqPBsn4s

While when I use the phone stream it downgrades a lot (I assume Android does this), comes back a bit at the end (peer video is from phone processed on DepthAI camera Myriad X vision/AI processor connected on a Win10 PC)
https://www.youtube.com/watch?v=CdvpjKfNUWw

I have this issue on Raspberry Pi 4, and the performance drops a lot because of this:

No accelerated colorspace conversion found from yuv420p to bgr24.

I rebuild ffmpeg as described here, but still the same warning:
https://pimylifeup.com/compiling-ffmpeg-raspberry-pi/

Do I need to rebuild aiortc from source to use the new libs?

I can open a separate issue for this if needed.

**Comment by jlaine** [comment]
There should be no need to recompile ffmpeg, the one shipped with rasbpian is just fine. aiortc doesn't link against ffmpeg, so I don't see why you would need to recompile it.  PyAV is linked against ffmpeg but if you installed it from piwheels (the default), it will already be linked against the system's ffmpeg, so again not much incentive to compile it.

What tasks are you performing on the rasbperry pi? Also, where is aiortc being used in your setup?

**Comment by mslavescu** [comment]
The problem seems to be here:

https://github.com/OSSDC/OSSDC-VisionAI-Core/blob/master/race-ossdc-org_webrtc_processing.py#L156
img = frame.to_ndarray(format="bgr24")

I read the frame like this:
frame = await self.track.recv()

I followed the approach from here:
https://github.com/aiortc/aiortc/blob/main/examples/server/server.py#L38

Is there any way to get a cv2 BGR image frame directly from aiortc and skip the conversion?

Regarding applications, I want to use Raspberry Pi 4 and CM4 to process video with DepthAI cameras, and stream with aiortc like in this video:
https://www.youtube.com/watch?v=CdvpjKfNUWw

On PC I get 22 FPS, on RPi CM4 I get around 2-3 FPS, more then half of the time is lost because the colorspace conversion is not accelerated.

**Comment by jlaine** [comment]
> Is there any way to get a cv2 BGR image frame directly from aiortc and skip the conversion?
> 

I don't understand what you mean by "skip the conversion": the codec outputs yuv420p, that's a fact. So either you're able to manipulate the frame in that color space (in which case you can just do `img = frame.to_ndarray(format="yuv420p")`, or you're going to need a conversion..


> Do I need to recompile PyAV to get the ffmpeg x264 support?

Feel free to do so if you have a patched version of ffmpeg which implements accelerated conversions on Pi4. However please figure out yourself how to recompile PyAV, as this is error prone and more support that I am willing to provide.

> On PC I get 22 FPS, on RPi CM4 I get around 2-3 FPS, more then half of the time is lost because the colorspace conversion is not accelerated.

This is an assumption on your behalf. You didn't fully answer my question about what tasks the Pi4 performs. If it involves video encoding, that's going to be your number 1 CPU hog.

Anyway, this issue seems to be straying from aiortc itself, an my time is limited so I'm not sure I can help you much more here.

**Comment by mslavescu** [comment]
Thanks @jlaine for the explanations.
I understand that RPi has limited video encoding/decoding capabilities and that seems to be the performance bottleneck.
If I decrease the resolution to 640x480 I get acceptable latency and fps, and I could still use it as is in some applications using RPi also.

I'll play more with the WebRTC video settings and may ask more questions later.

Thanks again for this amazing project!

**Comment by jlaine** [comment]
OK, I'm going to close this : there is now support for hardware-accelerated H.264 encoding on Rasbberry Pi4. To try it out, use the "server" demo and force H264 as the codec.
