### ISSUE TITLE
WebRTC Python Desktop GUI?

### ISSUE THREAD

**Issue by madebylo** [aiortc/aiortc#486]
Hello,

My Project is  to control a RC Car with an Raspberry Pi and use WebRTC for the low latency Video connection.
I have the car, an raspberry pi, an root server and the controller pc.
The Raspberry and the Controller pc are not in the same network, because I don't want to use vpn. But I like to to control the care 10000 meters away.
I can create a Stream from Web Browser to Web Browser, no problem.

But my Question is, is it possible that I get live video from the car, but don't use a browser? I want to open a python gui on the car and press "Start Stream" and on the pc I want a python gui and press "Show stream"

I want this, because I like to write a awesome application without opening one python GUI to control forward, left, right ... and a browser to see the webrtc stream. A want all in one and I prefer a beautiful GUI.

It would be great if someone can help me. :)

**Comment by jlaine** [comment]
I definitely think you could write a Python GUI for displaying video: aiortc's media pipeline outputs decoded frames, so it's a question of writing some code to throw the pixels into whatever graphical toolkit you plan to use.

However if you're going throught the trouble of using a standard such as WebRTC which is.. well, web centric, you might consider going a different way. Why not make the remote control purely a web app?

**Comment by madebylo** [comment]
@jlaine Thank you for the answer, i will try both :)

**Comment by madebylo** [comment]
@jlaine but i think FaceTime working Same. Over WebRTC. Because of the low latency and That is what i Need! I wouldn't use webrtc if there Would be a other low latency Solution... :/

**Comment by jlaine** [comment]
OK.. well is there anything else that needs to be addressed here?
