### ISSUE TITLE
How to record from camera and show live instead of saving to a file? (videostream-cli)

### ISSUE THREAD

**Issue by madebylo** [aiortc/aiortc#492]
Hi,

I hope someone can help me!
I already have a connection between 2 videostream clients (offer, awnser) but i have the problem, that i dont want to record my video to a file (record-to) and i want to play it from the camera (play-from). I tried so many different things with cv2 to show the StreamTrack video, but i think i am on a very wrong way, can someone give me an example, i stuck since weeks at this point.

This is the code by jlaine. I use this code, but i like to change it to record from camera and play in a live stream window not record to a file.

`import argparse
import asyncio
import logging
import math
import vlc 

import cv2
import numpy
from av import VideoFrame

from aiortc import (
    RTCIceCandidate,
    RTCPeerConnection,
    RTCSessionDescription,
    VideoStreamTrack,
)
from aiortc.contrib.media import MediaBlackhole, MediaPlayer, MediaRecorder
from aiortc.contrib.signaling import BYE, add_signaling_arguments, create_signaling

class FlagVideoStreamTrack(VideoStreamTrack):
    """
    A video track that returns an animated flag.
    """

    def __init__(self):
        super().__init__()  # don't forget this!
        self.counter = 0
        height, width = 480, 640

        # generate flag
        data_bgr = numpy.hstack(
            [
                self._create_rectangle(
                    width=213, height=480, color=(255, 0, 0)
                ),  # blue
                self._create_rectangle(
                    width=214, height=480, color=(255, 255, 255)
                ),  # white
                self._create_rectangle(width=213, height=480, color=(0, 0, 255)),  # red
            ]
        )

        # shrink and center it
        M = numpy.float32([[0.5, 0, width / 4], [0, 0.5, height / 4]])
        data_bgr = cv2.warpAffine(data_bgr, M, (width, height))

        # compute animation
        omega = 2 * math.pi / height
        id_x = numpy.tile(numpy.array(range(width), dtype=numpy.float32), (height, 1))
        id_y = numpy.tile(
            numpy.array(range(height), dtype=numpy.float32), (width, 1)
        ).transpose()

        self.frames = []
        for k in range(30):
            phase = 2 * k * math.pi / 30
            map_x = id_x + 10 * numpy.cos(omega * id_x + phase)
            map_y = id_y + 10 * numpy.sin(omega * id_x + phase)
            self.frames.append(
                VideoFrame.from_ndarray(
                    cv2.remap(data_bgr, map_x, map_y, cv2.INTER_LINEAR), format="bgr24"
                )
            )
        

    async def recv(self):
        pts, time_base = await self.next_timestamp()

        frame = self.frames[self.counter % 30]
        frame.pts = pts
        frame.time_base = time_base
        self.counter += 1
        return frame

    def _create_rectangle(self, width, height, color):
        data_bgr = numpy.zeros((height, width, 3), numpy.uint8)
        data_bgr[:, :] = color
        return data_bgr

async def run(pc, player, recorder, signaling, role):
    
    def add_tracks():
        if player and player.audio:
            pc.addTrack(player.audio)

        if player and player.video:
            pc.addTrack(player.video)
        else:
            pc.addTrack(FlagVideoStreamTrack())

    @pc.on("track")
    def on_track(track):
        print("Receiving %s" % track.kind)

    # connect signaling

    if role == "offer":
        # send offer
        add_tracks()
        await pc.setLocalDescription(await pc.createOffer())
        await signaling.send(pc.localDescription)
    
    # consume signaling
    while True:
        obj = await signaling.receive()
        print(obj)

        if isinstance(obj, RTCSessionDescription):
            await pc.setRemoteDescription(obj)
            await recorder.start()

            if obj.type == "offer":
                # send answer
                add_tracks()
                await pc.setLocalDescription(await pc.createAnswer())
                await signaling.send(pc.localDescription)
        elif isinstance(obj, RTCIceCandidate):
            await pc.addIceCandidate(obj)
        elif obj is BYE:
            print("Exiting")
            break

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Video stream from the command line")
    parser.add_argument("role", choices=["offer", "answer"])
    parser.add_argument("--play-from", help="Read the media from a file and sent it."),
    parser.add_argument("--record-to", help="Write received media to a file."),
    parser.add_argument("--verbose", "-v", action="count")
    add_signaling_arguments(parser)
    args = parser.parse_args()

    if args.verbose:
        logging.basicConfig(level=logging.DEBUG)

    # create signaling and peer connection
    signaling = create_signaling(args)
    pc = RTCPeerConnection()

    # create media source
    if args.play_from:
        player = MediaPlayer(args.play_from)
        
    else:
        player = None

    # create media sink
    if args.record_to:
        recorder = MediaRecorder(args.record_to)
    else:
        recorder = MediaBlackhole()

    # run event loop
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(
            run(
                pc=pc,
                player=player,
                recorder=recorder,
                signaling=signaling,
                role=args.role,
            )
        )
    except KeyboardInterrupt:
        pass
    finally:
        # cleanup
        loop.run_until_complete(recorder.stop())
        loop.run_until_complete(signaling.close())
        loop.run_until_complete(pc.close())
`

Thanks to everybody, who can help me.

**Comment by madebylo** [comment]
@Laityned yes! Display the incoming track video! And send directly from my camera not from a file

**Comment by Laityned** [comment]
For sending direct from your camera, look at the webcam example. But shortly:
`
MediaPlayer("/dev/video0", format="v4l2", options=options)
`



 At this moment this example could only handle one single webrtc connection, however I have a WIP pull request, so you could connected multiple clients to the same camera source.


For displaying the camera, register incoming new tracks to your displaying class:
`
@pc.on("track")
    def on_track(track):
        print("Receiving %s" % track.kind)
        # track.kind is 'video' or 'audio'
        # register track to your own displaying class
`

Create a displaying class which will retrieve frames from this 'RemoteStreamTrack' using
`
frame = await track.recv() 
`

**Comment by madebylo** [comment]
Thank you @Laityned i will try this, but I don't know how to display, i know how to display a file, but I think I don't understand "what is a track" what format is this, I googled a lot like "how to display a track video". But I don't understand this, but I will try again! :)

**Comment by jlaine** [comment]
Using `MediaPlayer` with a webcam is documented:

https://aiortc.readthedocs.io/en/latest/helpers.html

As for displaying video, that is out of scope for this project, you're going to have to write your own code. aiortc deals with establishing peer connections and exchanging media / data. A good starting point would to write something similar to the `MediaBlackhole` [1] class but which displays the frames instead of discarding them.

[1] https://github.com/aiortc/aiortc/blob/71cd9334405886e5974441e192a816d54a5b16e5/src/aiortc/contrib/media.py#L47

**Comment by mslavescu** [comment]
@madebylo take a look at my project, it does what you need and more using aiortc:

https://github.com/OSSDC/OSSDC-VisionAI-Core

Try the Google Colab notebook to quickly see how it works, takes less than 5 min to get it running.

See demo videos here:

https://m.youtube.com/playlist?list=PLUop7b1Q1uZnneN4utdBh7OLYbKJlieQf

You can display the peer stream (even those from play-from, see videoUrl examples) locally, remotely (using MJPEG stream) at the same time view it after proceesing remotely through WebRTC.
