### ISSUE TITLE
Videoclient tcp-socket connection error.

### ISSUE THREAD

**Issue by madebylo** [aiortc/aiortc#494]
Hello,

this is my third issue, the two before were very helpful!
Now everything is working on localhost, I think, because I dont need to start a websocket on localhost.

But when i try to use my root server, to connect two clients from different networks, i always get an error.

Can you help me?

**Error:**

Traceback (most recent call last):
  File "cli.py", line 155, in <module>
    loop.run_until_complete(
  File "C:\Users\muehleh2\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "cli.py", line 102, in run
    await signaling.send(pc.localDescription)
  File "C:\Users\muehleh2\AppData\Local\Programs\Python\Python38\lib\site-packages\aiortc\contrib\signaling.py", line 203, in send
    await self._connect(True)
  File "C:\Users\muehleh2\AppData\Local\Programs\Python\Python38\lib\site-packages\aiortc\contrib\signaling.py", line 175, in _connect
    self._server = await asyncio.start_server(
  File "C:\Users\muehleh2\AppData\Local\Programs\Python\Python38\lib\asyncio\streams.py", line 94, in start_server
    return await loop.create_server(factory, host, port, **kwds)
  File "C:\Users\muehleh2\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 10049] error while attempting to bind on address ('212.227.209.131', 8080): die angeforderte adresse ist in diesem kontext ungültig

**Start Command:**

python cli.py --play-from testvideo.mp4 --record-to hansxo.mp4 --signaling tcp-socket --signaling-host 212.227.209.131 --signaling-port 8080 offer

**TCP-Server (on the root server):**

`#!/usr/bin/env python3

import socket
import sys

# Create a TCP/IP socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Bind the socket to the port
server_address = ('localhost', 10000)
print >>sys.stderr, 'starting up on %s port %s' % server_address
sock.bind(server_address)

# Listen for incoming connections
sock.listen(1)

while True:
    # Wait for a connection
    print >>sys.stderr, 'waiting for a connection'
    connection, client_address = sock.accept()

    try:
        print >>sys.stderr, 'connection from', client_address

        # Receive the data in small chunks and retransmit it
        while True:
            data = connection.recv(16)
            print >>sys.stderr, 'received "%s"' % data
            if data:
                print >>sys.stderr, 'sending data back to the client'
                connection.sendall(data)
            else:
                print >>sys.stderr, 'no more data from', client_address
                break
            
    finally:
        # Clean up the connection
        connection.close()`

**Comment by jlaine** [comment]
I think you may have got your server/client swapped. With the tcp-socket signaling method, the party which sends the offer acts as the server, so in your case it should be the machine which has the 212.227.209.131 IP address.
