### ISSUE TITLE
Add icecandidate event

### ISSUE THREAD

**Issue by paulhobbel** [aiortc/aiortc#499]
The javascript api has an `icecandidate` event that triggers when new icecandidates are available. As of right now this is not possible in aiortc yet. Are there any plans on adding this, would that require a lot of work?

I've already looked around in the code, but it seems like there's no support for that yet. I don't know whether this is mandatory as it seems like aiortc collects the icecandidates on beforehand and then creates the offer. Not sure what would happen on a network change

**Comment by sotaDetector** [comment]
I have the same confusion

**Comment by q920980002** [comment]
I have the same confusion too too too,i need send icecandidates to browser
