### ISSUE TITLE
Allow MediaPlayer to be closed on application shutdown

### ISSUE THREAD

**Issue by paulhobbel** [aiortc/aiortc#500]
Add a `stop()` function to the MediaPlayer so that an application can shutdown cleanly. This is also the case for the `webcam` example. This will only properly close if a peer connection was opened at least once.

I already wrote a stop function so I could do a PR

**Comment by paulhobbel** [comment]
Oh wait you can also use .audio.stop() and .video.stop

**Comment by jlaine** [comment]
> Oh wait you can also use .audio.stop() and .video.stop

**Comment by jlaine** [comment]
Sorry, accidentally closed the issue! This needs a bit of digging into, the introduction of MediaRelay introduced a new problem which was not present before.
