### ISSUE TITLE
Disabling VP8 in the webcam example

### ISSUE THREAD

**Issue by jpiat** [aiortc/aiortc#502]
Hi,

thanks for the work on integrating the omx encoder within aiortc so that raspberry users can benefit from hardware accelerated encoding. This approach is more generic than the one i used (using picamera h264 output). One issue that still remains (for me) is to disable VP8 which should be possible through setCodecPreferrences in the python code. I tried :

`capabilities = RTCRtpSender.getCapabilities("video")`
`preferences = list(filter(lambda x: x.name == "H264", capabilities.codecs))`
`preferences += list(filter(lambda x: x.name == "rtx", capabilities.codecs))`

`t.setCodecPreferences(preferences)`

in the offer function but VP8 is still used as the default. How do you disable VP8 in the webcam example ?

**Comment by jlaine** [comment]
This works nicely for me, I'll try to clean it up to get it commited:

```patch
--- a/examples/webcam/webcam.py
+++ b/examples/webcam/webcam.py
@@ -8,7 +8,7 @@ import ssl
 
 from aiohttp import web
 
-from aiortc import RTCPeerConnection, RTCSessionDescription
+from aiortc import RTCPeerConnection, RTCRtpSender, RTCSessionDescription
 from aiortc.contrib.media import MediaPlayer, MediaRelay
 
 ROOT = os.path.dirname(__file__)
@@ -68,6 +68,14 @@ async def offer(request):
     # open media source
     audio, video = create_local_tracks(args.play_from)
 
+    # configure preferred codecs
+    if video:
+        transceiver = pc.addTransceiver("video")
+        capabilities = RTCRtpSender.getCapabilities("video")
+        preferences = list(filter(lambda x: x.name == "H264", capabilities.codecs))
+        preferences += list(filter(lambda x: x.name == "rtx", capabilities.codecs))
+        transceiver.setCodecPreferences(preferences)
+
     await pc.setRemoteDescription(offer)
     for t in pc.getTransceivers():
         if t.kind == "audio" and audio:
```
