### ISSUE TITLE
Performance limitations

### ISSUE THREAD

**Issue by Laityned** [aiortc/aiortc#505]
At this moment, I have a performance drop in number of received frames when connecting multiple clients using the webcam.py example. However, I am not cpu limited or bandwith limited at this moment.

From what I could found, it is probably due to too long running task in the same event loop. 
Time analysis has shown that this are the long running lines of code:

https://github.com/aiortc/aiortc/blob/01ff209cc38e887edeb05cba1845cf458b31a0ac/src/aiortc/rtcdtlstransport.py#L668-L671

Could anyone confirm this and help thinking about a solutions to support more clients per webcam server (and boost the performance of the library)?

**Comment by jlaine** [comment]
These two functions call into C code which does the heavy lifting. I believe the global interpreter lock is not held while inside the C code, so multithreading might make sense. Could you try using loop.run_in_executor() on these (especially the second: protect()) and see if it makes any difference?
