### ISSUE TITLE
tcp-socket

### ISSUE THREAD

**Issue by iamkrs9** [aiortc/aiortc#507]
I dont know how to create a tcp-socket for signaling.
in my code after await signaling.send(pc.localDescription), the program just freezes.
I dont know how to proceed

Is there any example code to refer?

**Comment by roumenguha** [comment]
Hi Karan, did you figure it out? I'm also interested in using the TcpSocketSignaling class to establish a connection, but I'm having trouble figuring out how to use it. Would you mind sharing your code?

**Comment by iamkrs9** [comment]
I referred to the examples and used the consume_signaling function as a reference. I then pass argument 'tcp-socket' in the code itself so whenever it is run, it always does so with TcpSocketSignaling.

**Comment by roumenguha** [comment]
You're referring to the [videostream-cli](https://github.com/aiortc/aiortc/blob/01ff209cc38e887edeb05cba1845cf458b31a0ac/examples/videostream-cli/cli.py#L104) example?

**Comment by iamkrs9** [comment]
Yes and that same block is used as a separate dedicated function in many other examples.

**Comment by tejas-polakam** [comment]
Hi were you able to solve this issue? When I use TcpSocketSignaling(HOST, PORT) the examples always freeze. 

I just get this output when I use the verbose flag.

I am on MacOs, and I get the same problem when using UNIX-socket. The copy and paste socket doesnt work with macos.


```
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceGatheringState new -> gathering
DEBUG:aioice.ice:Connection(0) protocol(0) connection_made(<_SelectorDatagramTransport fd=8 read=idle write=<idle, bufsize=0>>)
DEBUG:aioice.ice:Connection(0) protocol(1) connection_made(<_SelectorDatagramTransport fd=9 read=idle write=<idle, bufsize=0>>)
DEBUG:aioice.ice:Connection(0) protocol(2) connection_made(<_SelectorDatagramTransport fd=10 read=idle write=<idle, bufsize=0>>)
DEBUG:aioice.ice:Connection(0) protocol(3) connection_made(<_SelectorDatagramTransport fd=11 read=idle write=<idle, bufsize=0>>)
DEBUG:aioice.ice:Connection(0) protocol(4) connection_made(<_SelectorDatagramTransport fd=12 read=idle write=<idle, bufsize=0>>)
DEBUG:aioice.ice:Connection(0) protocol(0) > ('173.194.219.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b':\x16i\xdc\r\xd1\xaa\x8e-\x9d\t\xba')
DEBUG:aioice.ice:Connection(0) protocol(1) > ('173.194.219.127', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xcd\x1af5\xbb!0\xa2\xe2g&{')
DEBUG:aioice.ice:Connection(0) protocol(1) < ('173.194.219.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\xcd\x1af5\xbb!0\xa2\xe2g&{')
DEBUG:aioice.ice:Connection(0) protocol(0) < ('173.194.219.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b':\x16i\xdc\r\xd1\xaa\x8e-\x9d\t\xba')
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceGatheringState gathering -> complete





```

**Comment by roumenguha** [comment]
I don't remember, sorry. I was trying to use this repo to solve an interview challenge so I only worked with it for a weekend
