### ISSUE TITLE
How to extract frames from RemoteStreamTrack

### ISSUE THREAD

**Issue by SatyamGaba** [aiortc/aiortc#508]
I am transmitting a video file from local pc to remote using MediaStreamTrack. I want to do computation on each frame received at the remote server. How can I access each frame at real-time (without saving it into filesystem). I would prefer to read each frame using  opencv

**Comment by jlaine** [comment]
I suggest you take a look at the examples folder, the "server" example does almost exactly that.

**Comment by SatyamGaba** [comment]
server example transforms the incoming track to a new track and transmits it to the browser. However, I want to process each frame and display it in real-time using OpenCV. I do not want to save the file.
From the previous issues, I understood that I should use MediaBlackHole but I do not understand how to integrate the openCV transformation function in it.
