### ISSUE TITLE
Transferring image to a client

### ISSUE THREAD

**Issue by iamkrs9** [aiortc/aiortc#510]
I set up a tcp-signaling mechanism and sent an image frame as an array to a client. The frame is being received as aiortc.rtcrtpreceiver.RemoteStreamTrack object on the client side. I figured that I can use recv() method on it as RemoteStreamTrack is an instance of MediaStreamTrack and from the examples on the aiortc GitHub, specifically the server.py example in server folder, they use the same thing. I would then get a Frame object after using recv() method which I could convert to ndarray using frame.to_ndarray on that and retrieve the image data in array which can then easily be processed with numpy and opencv.

When my code runs and event handler “track” triggers, I trigger the above process of recv() and converting the Frame to array by calling a class that I wrote as an extension of RemoteStreamTrack. But the code gets stuck at specifically the await self.frame.recv() method in the class that I wrote. Is this the correct approach? If yes then how can I proceed and if not then what should be done? Thank You

**Comment by jlaine** [comment]
First of all I'm sure I understand the usecase : if we're talking about sending a single frame, WebRTC is definitely overkill.

Concerning your code getting "stuck": I don't quite understand what you are doing, are you calling recv() inside the event handler for the "track" event? If so you're probably blocking the signaling exchange, so the remote party doesn't even start sending data to you.

The `VideoStreamTrack` demonstrates a specific case: when you want to create a track which acts as a transform on received data to send it back out. If what you want is a media "sink" (something which purely consumes received data). From the "track" event you might kick off a task which repeatedly receives frames from the track.

In the "track" event handler:

```python
asyncio.ensure_future(consume_track(track))
```
.. where `consume_track` looks like:

```python
async def consume_track(track):
    while True:
        try:
            frame = await track.recv()
            # do something with the frame
        except MediaStreamError:
            return
```

**Comment by iamkrs9** [comment]
The track object is a aiortc.rtcrtpreceiver.RemoteStreamTrack object. frame = await track.recv() on the RemoteStreamTrack doesn't return anything. Thats where the program is stuck. The program enters the while loop, and the last statement executed is frame = await track.recv(). After that, the control never returns. The program is just waiting on the recv() method to get something back I think.

What is happening? RemoteStreamTrack is itself an extension of the MediaStreamTrack class. Shouldn't it return a Frame on applying recv() method to it?

**Comment by jlaine** [comment]
recv() does return a frame, otherwise non for the examples would work.

Reread my message, the problem is most likely where / when you are calling this method.

**Comment by iamkrs9** [comment]
Thank you for your help. Lastly, after the server has successfully sent the stream to client, in order for the client to reply with text data, could it be done on the same channel or does there need to be renegotiation and an offer should be sent from the client to successfully send text while still keep receiving the stream from server?

**Comment by jlaine** [comment]
You can negotiate a datachannel and video in the same initial negotiation (as the `server` example does) and use the datachannel to send text in whichever direction you want.

**Comment by iamkrs9** [comment]
Thanks
