### ISSUE TITLE
Video stream missing frames

### ISSUE THREAD

**Issue by wildcat5566** [aiortc/aiortc#511]
Hello, I am trying to send images from the server, and then receive & access each frame from the client side.
I am using modified code from your examples `server` and `videostream-cli`.
However I seem to be missing several frames.
My code is as below:

server: As the examples instructed, I am generating videos and sending one frame at each time.
```
class Video(VideoStreamTrack):
    def __init__(self):
        super().__init__()
        self.counter = 0
        self.frames = []

        for i in range(100):
            img = np.ones((20, 30, 3), dtype=np.uint8) * i # simple testing program to send an array full of (index of frame)
            print(img[0][0])
            self.frames.append(VideoFrame.from_ndarray(img, format="bgr24"))
        
    async def recv(self):
        pts, time_base = await self.next_timestamp()

        frame = self.frames[self.counter % 100]
        frame.pts = pts
        frame.time_base = time_base
        self.counter += 1
        return frame

```

client:
```
@pc.on("track")
def on_track(track):
        print("Receiving %s" % track.kind)
        recorder.addTrack(track)
        pc.addTrack(Display(track)) # add track 

class Display(MediaStreamTrack):
    kind = "video"
    def __init__(self, track):
        super().__init__()
        self.track = track
        self.count = 0
        
    async def recv(self):
        frame = await self.track.recv()
        img = frame.to_ndarray(format="bgr24")

        print(self.count, img[0][0]) # here I can confirm that frames are lost
        self.count += 1
        return frame


```
I did not change much in the `__main__` and `run` sections.
The summary of the issue is that received counts and values do not match, therefore frame loss is confirmed.
Tried delaying every frame sending process with `asyncio.sleep(1)` but did not help.
Can anyone help please? Thanks.

EDIT: To clarify the issue, I added `asyncio.sleep(1)` to the sending process and found that the server sends 1 frame per second but the client receives 1 frame per 2 seconds.

**Comment by jlaine** [comment]
Please read the issue template, I cannot go over large blobs of custom code and debug your work..

**Comment by wildcat5566** [comment]
Very sorry for the inconvenience, I have fixed the content above.
I wonder if this is the right way for the client to access each frame received from the server?
Thanks!

**Comment by wildcat5566** [comment]
And there's one thing I am curious about the example, 
When we use the "client" option in `videostream-cli.py`, the received obj have type "offer". Why should we still be adding the example (flag) track in this case?

```
    # consume signaling
    while True:
        obj = await signaling.receive()

        if isinstance(obj, RTCSessionDescription):
            await pc.setRemoteDescription(obj)
            await recorder.start()

            if obj.type == "offer":
                add_tracks()
                await pc.setLocalDescription(await pc.createAnswer())
                await signaling.send(pc.localDescription)

```

**Comment by jlaine** [comment]
The "offer" and "answer" role relates to who is sending the SDP offer (so kicking off the negotiation) and who is answering. It does not need to match who is sending media, you are right : this was an arbitrary choice I made as I wanted to illustrate bidirectional media.

**Comment by wildcat5566** [comment]
Thank you for the explanation! Got it.
By the way I found the bug in my code (client side), it was because besides the new track I added, I still had the original recorder in my case which caused the delay. 
```@pc.on("track")
def on_track(track):
        print("Receiving %s" % track.kind)
        recorder.addTrack(track) ################## remove this
        pc.addTrack(Display(track)) # add track 

class Display(MediaStreamTrack):
    kind = "video"
    def __init__(self, track):
        super().__init__()
        self.track = track
        self.count = 0
        
    async def recv(self):
        frame = await self.track.recv()
        img = frame.to_ndarray(format="bgr24")

        print(self.count, img[0][0]) # here I can confirm that frames are lost
        self.count += 1
        return frame```
