### ISSUE TITLE
Displaying extracted image is not proper

### ISSUE THREAD

**Issue by Mohitkumaraian** [aiortc/aiortc#512]
I followed the example for VideoClient-cli french flag example and wrote a class that returns frames of ball bouncing of screen and sends it from server to client. When I received the images on the client side and converted these images to ndarray so that I can display them using cv2. These images weren't proper. The whole screen had the color of the ball. The screen was supposed to be black and the ball was supposed to be green. I'm getting a green screen instead of image. I created the class as an extension of VideoStreamStrack

**Comment by jlaine** [comment]
Well then fix your code, what can I do about it?
