### ISSUE TITLE
Plugging in output from ffmpeg-python to MediaPlayer doesn't work.

### ISSUE THREAD

**Issue by VishnuNairP** [aiortc/aiortc#513]
Hi,

I am trying to stream my screen using aiortc and python and while trying to pass in the ffmpeg output to mediaplayer, I get no output. 

I modified the webcam.py example from aiortc as given below. 
 ```
# open media source
    if args.play_from:
        process = (
            ffmpeg
            .input(format='gdigrab', framerate=60, filename="desktop")
            .output('pipe:', format='rawvideo', pix_fmt='rgb24')
            .run(capture_stdout=True)
        )

        video = (
            np
            .frombuffer(process, np.uint8)
        )

        player = MediaPlayer(video)
    else:
        options = {"framerate": "30", "video_size": "640x480"}
        if platform.system() == "Darwin":
            player = MediaPlayer("default:none", format="avfoundation", options=options)

```

But I can't get any output on the browser. 

I am thinking MediaPlayer is not the thing to use here. 
Could someone please tell what else to use here?

**Comment by jlaine** [comment]
I really don't see why you're throwing ffmpeg-python into the mix here, it's totally unrelated to aiortc.

aiortc uses PyAV which is a wrapper around the FFmpeg *libraries* (not the command line tool). 

Have you tried: `MediaPlayer("desktop", format="gdigrab")`?

**Comment by VishnuNairP** [comment]
Hi, I did try that. But I need the hardware encoding that is supported by ffmpeg, and I thought this would be the best place to ask about passing in encoded streams to aiortc.

**Comment by VishnuNairP** [comment]
> I really don't see why you're throwing ffmpeg-python into the mix here, it's totally unrelated to aiortc.
> 
> aiortc uses PyAV which is a wrapper around the FFmpeg _libraries_ (not the command line tool).
> 
> Have you tried: `MediaPlayer("desktop", format="gdigrab")`?

Hi, I did try that. But I need the hardware encoding supported by ffmpeg. I thought this would be the best place to ask about passing encoded streams through aiortc.

**Comment by jlaine** [comment]
Passing encoded streams is not supported.
