### ISSUE TITLE
send continuous image

### ISSUE THREAD

**Issue by ardeal** [aiortc/aiortc#518]
Hi,

I will read frame from a web camera, and then do some image processing. I then send the processed image to browser in real time.
Here are the steps I take:
<pre>
step 1: read frame(image) from camera
step 2: process the image
step 3: send the processed image to browser
step 4: repeat step 1
</pre>

my questions are:
1) I could send each image as xxx.jpg to browser. but image is not encoded, the size of the image might be much big. is this the best solution?

2) If I use FFMPEG or webrtc to encode the image but not continuous images(all images are separate image but not video stream), how to do this? is the encoding effective?

3) do you have good solution for my case?

**Comment by jlaine** [comment]
Take a look at the "server" example which does almost exactly what you describe.

**Comment by ardeal** [comment]
@jlaine ,
Hi,

I did check examples folder. I checked the code in webcam. but I have a few questions:
1) the input of webcam example is video stream from camera or video file. for my case, I will feed image to webrtc. How to feed image/images to it?

2) in webcam example,        you will use 
```python
player = MediaPlayer(play_from)
return player.audio, player.video
```
to read video. How get a frame from MediaPlayer or player.video?

3)  for my case, should I refer to webcam example or other example?

**Comment by jlaine** [comment]
I mentioned the `server` example, specifically its `VideoTransformTrack` class, as it does something close to what you describe: take some video, process it and produces transformed frames. Your usecase will be in essence the `webcam` example with a variant of `VideoTransformTrack` applied to the `MediaPlayer`'s video track.

All aiortc's "track" classes have a `recv()` coroutine which pulls the next audio / video frame.

**Comment by ardeal** [comment]
@jlaine ,
Hi,

Thank you!

I am trying to modify the code in server.py file.
By the following modification, I would like to read the image from a folder on my computer, and the push the image to browser on by one. however, I got failed:


```python

class VideoTransformTrack(MediaStreamTrack):
    """
    A video stream track that transforms frames from an another track.
    """

    kind = "video"

    def __init__(self, track, transform):
        super().__init__()  # don't forget this!
        self.track = track
        self.transform = transform

        self.image_index = 0
        self.image_root = r'D:\dataset\COCO\train2014'
        self.all_images = os.listdir(r'D:\dataset\COCO\train2014')

    async def recv(self):
        # frame = await self.track.recv()
        frame = await cv2.imread(os.path.join(self.image_root, self.all_images[self.image_index]))
        self.image_index += 1

        if self.transform == "cartoon":
```

**Comment by ardeal** [comment]
@jlaine ,
Dear Jlaine,

I did successfully run webcam.py. I just set play-from = 'xxxxx.mp4', and I could get video played on browser.
Then, I checked your code in webcam.py, and I notice your code(Code 1).  Audio and Video are created from MediaPlayer. 
I copy and p0ased your class VideoImageTrack(Code 2) and customize your code(Code 3) in webcam.py file.

It seems that I should inherit some other class and implement some other function the class.


I got the following error:
```python
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiohttp\web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiohttp\web_app.py", line 499, in _handle
    resp = await handler(request)
  File "D:/code_python/webrtc_top/TT/webcam/webcam.py", line 188, in offer
    await pc.setLocalDescription(answer)
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiortc\rtcpeerconnection.py", line 763, in setLocalDescription
    t._currentDirection = and_direction(t.direction, t._offerDirection)
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiortc\rtcpeerconnection.py", line 242, in and_direction
    return sdp.DIRECTIONS[sdp.DIRECTIONS.index(a) & sdp.DIRECTIONS.index(b)]
ValueError: None is not in list

```

Code 1:
```python
     # open media source
    audio, video = create_local_tracks(args.play_from)

    await pc.setRemoteDescription(offer)
    for t in pc.getTransceivers():
        if t.kind == "audio" and audio:
            pc.addTrack(audio)
        elif t.kind == "video" and video:
            pc.addTrack(video)

    answer = await pc.createAnswer()
    await pc.setLocalDescription(answer)

```

Code 2:
```Python
class VideoImageTrack(VideoStreamTrack):
    """
    A video stream track that returns a rotating image.
    """

    def __init__(self):
        super().__init__()  # don't forget this!
        self.img = cv2.imread(PHOTO_PATH, cv2.IMREAD_COLOR)

    async def recv(self):
        pts, time_base = await self.next_timestamp()

        # rotate image
        rows, cols, _ = self.img.shape
        M = cv2.getRotationMatrix2D((cols / 2, rows / 2), int(pts * time_base * 45), 1)
        img = cv2.warpAffine(self.img, M, (cols, rows))

        # create video frame
        frame = VideoFrame.from_ndarray(img, format="bgr24")
        frame.pts = pts
        frame.time_base = time_base

        return frame
```

Code 3:
```python
    # open media source
    audio, video = create_local_tracks(args.play_from)

    await pc.setRemoteDescription(offer)
    for t in pc.getTransceivers():
        pc.addTrack(VideoImageTrack())

    answer = await pc.createAnswer()
    await pc.setLocalDescription(answer)

```
