### ISSUE TITLE
Webcam example without Internet connection

### ISSUE THREAD

**Issue by kueblert** [aiortc/aiortc#524]
Hi,
the webcam example does not seem to work when there is no internet connection.
I am accessing the stream via http://127.0.0.1:8080 (0.0.0.0 didn't work for me on Windows),
There seems to be an issue with getting the ice candidates (none are found by the javascript client). The moment I plug in the internet connection, everything works nicely. I am nut using the STUN server.

Any guesses why this might be the case? 

Best,
Thomas

**Comment by HenryWInfinity** [comment]
Have you solved the problem?

**Comment by HenryWInfinity** [comment]
i met it too.

**Comment by kueblert** [comment]
Nope. No clue what's wrong with it. I am trying to circumvent the problem with a gstreamer wrapper for now, but it is not a good solution either.

**Comment by HenryWInfinity** [comment]
![image](https://user-images.githubusercontent.com/62539043/115391259-dcf32c80-a211-11eb-9ca7-7b8f724a95d2.png)
it still use an online stun server in rtcicetransport.py.
is there a method that i can do webrtc offline without a stun server?

**Comment by kueblert** [comment]
Removing the default does not have an effect. Still working with internet, not working without.

**Comment by filsav** [comment]
I have same issue. All works as expected when serving from `127.0.0.1:8000` with internet connection. Without internet connection it got stuck with `Peer connection (iceConnectionState) = "checking"`. Author, please help! How to run `aiortc` server on localhost while offline?

**Comment by jlaine** [comment]
What browser are you using?

For the connection to work you're going to need one of the following conditions to be met:

- access to a STUN server
OR
- a browser with a working mDNS stack. Firefox currently has a bug, see https://bugzilla.mozilla.org/show_bug.cgi?id=1691189

**Comment by kueblert** [comment]
I have tried with Chrome and Edge.

**Comment by nicarl** [comment]
I encountered a similar problem with local/offline connections on the same network were not getting established. 
I was able to solve it by the following things:

- use Chrome (the mentioned Firefox bug seems to be a problem)
- open the peer connection with `pc = RTCPeerConnection(
        configuration=RTCConfiguration(iceServers=[])
    )`
- the second part of the connection was established using javascript and it was also important to use `  const pc = new RTCPeerConnection({
    iceServers: []
  });`
- be aware that docker containers run in an isolated network and this can also lead to problems
