### ISSUE TITLE
How to record and save streamed video 

### ISSUE THREAD

**Issue by WinterOdin** [aiortc/aiortc#526]
Hi, I was looking around and I didn't saw something similar i just wanna stream audio and video from webcam into browser. Is this possible?

**Comment by jjehl** [comment]
Sure, aiortc is Design for that.

**Comment by WinterOdin** [comment]
Yeah i figured it out but know im facing another problem I wanna capture streamed media and save the stream to watch later

**Comment by jjehl** [comment]
No problem, aiortc have a MediaRecorder. Example Folder have a lot of working examples but you have to be aware that you need high skills in python programming in general and in network in particular.  aiortc is not very simple to understand but it is very powerfull.  To conclude, issues is not really the place for asking this kind of questions.
