### ISSUE TITLE
Provide a version of aiortc which is compatible with liberal license (BSD, MIT or equivalent)

### ISSUE THREAD

**Issue by youennf** [aiortc/aiortc#528]
aiortc license is flexible but some of its dependencies, in particular crc32c are LGPL.
It would be nice if there was a built-in option to use permissive-license dependencies.

**Comment by jlaine** [comment]
Hi @youennf, I considered switching from `crc32` to `google-crc32c`, and ran the following crude benchmark:

```python
import time

import crc32c
import google_crc32c

blob = bytes(1200)
iterations = 10000000

start = time.time()
for i in range(iterations):
    crc32c.crc32c(blob)
elapsed = time.time() - start
print("crc32c %d op/s" % (iterations / elapsed))

start = time.time()
for i in range(iterations):
    google_crc32c.value(blob)
elapsed = time.time() - start
print("google_crc32c %d op/s" % (iterations / elapsed))
```

The results on my machine (Intel Core i7) are systematically 4x slower using `google_crc32`, so a wholesale switch doesn't seem very compelling.

I then considered having an option to do `pip install aiortc[nogpl]` (the name is an example) which would use `google-crc32c` instead of `crc32`, but AFAICT Python's "extras" mechanism is only for installing additional packages, not replacing them.

**Comment by youennf** [comment]
@fippo , @alvestrand, any thoughts on the best way to proceed there.
Do you know why Google_crc32c is 4x slower?

**Comment by alvestrand** [comment]
Tagging @pwnall as the person who's last contributed to https://github.com/google/crc32c (he seems to be a Googler).
I suspect there may be something nonoptimal in compile switches or setup for the archtecture you're using - 4x is quite a lot.

**Comment by alvestrand** [comment]
also tagging @crwilcox who last contributed to https://github.com/googleapis/python-crc32c

**Comment by jlaine** [comment]
To be clear: I didn't compile anything myself. For both implementations, pip just picked up the binary wheel provided by each project.

**Comment by crwilcox** [comment]
Hey all! I expect that possibly the fallback, pure python crc32c might be used here?

A warning should be produced if that is happening though: https://github.com/googleapis/python-crc32c/blob/master/src/google_crc32c/__init__.py#L17
```
    "As the c extension couldn't be imported, `google-crc32c` is using a " 
    "pure python implementation that is significantly slower. If possible, "
    "please configure a c build environment and compile the extension"
```

**Comment by crwilcox** [comment]
It appears it really may be that much slower, which is shocking. 

```
❯ python -m venv venv; source venv/bin/activate
❯ code test_crc32c_v_google_crc32c.py
❯ pip install google-crc32c
Collecting google-crc32c
  Downloading google_crc32c-1.1.2-cp39-cp39-macosx_10_14_x86_64.whl (27 kB)
Collecting cffi>=1.0.0
  Using cached cffi-1.14.5-cp39-cp39-macosx_10_9_x86_64.whl (177 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Installing collected packages: pycparser, cffi, google-crc32c
Successfully installed cffi-1.14.5 google-crc32c-1.1.2 pycparser-2.20
❯ pip install crc32c
Collecting crc32c
  Downloading crc32c-2.2-cp39-cp39-macosx_10_9_x86_64.whl (28 kB)
Installing collected packages: crc32c
Successfully installed crc32c-2.2

❯ python test_crc32c_v_google_crc32c.py
crc32c 3435773 op/s
google_crc32c 946106 op/s

❯ python test_crc32c_v_google_crc32c.py
crc32c 3785717 op/s
google_crc32c 899703 op/s
```

that is 4-4.5x slower on Mac OS X 10.3 (2017-2018 era mbp). I am going to verify this isn't mac specific. I am also going to open an issue on our repo.

**Comment by youennf** [comment]
@Crwilcox, can you provide the link to the issue? Do you think the speed difference will be solvable in a not too distant future?

@jlaine, do you think that, in the meantime, we could create a branch in this repo that would use google_crc32c and that we would point to in WPT?

**Comment by lgrahl** [comment]
I think what's feasible, if @jlaine agrees, is to create a different variant of `setup.py` perhaps called `setup-nogpl.py` and make a tiny abstraction of the crc32c interface importing crc32c and then falling back to google-crc32c (until that has solved the speed issue).

**Comment by jlaine** [comment]
I've looked into it and didn't see a way to express "alternative" dependencies

**Comment by jlaine** [comment]
OK, so what I've done in PR #528 is to make the switch to `google-crc32` for the default installation (pip install aiortc). However if the `crc32` package is installed, it will preserve the previous behaviour and performance.

**Comment by jlaine** [comment]
`aiortc` 1.2.1 will be on PyPI in a couple of minutes, so Web Platform Tests can simply pick this version up.

**Comment by jlaine** [comment]
Thanks so much for reporting back @alvestrand !
