### ISSUE TITLE
"No start code is found" when decode frames with large resolution

### ISSUE THREAD

**Issue by jwzxgy2007** [aiortc/aiortc#539]
Hi, 

I use aiortc to receive stream from unreal engine, and there are no error when the res is 1024\*768, while errors occurred when the res higher than 1920\*1080, and the decoded frames are stuck.

The error is as follows:

    No start code is found.
    Error splitting the input into NAL units.

But when I use Chrome, the video is smooth.

And I checked the network usage. In chrome, the received speed is around 10\~20Mb/s whatever the res is. When use aiortc, it is 500KB\~1.5MB/s.

I guess the error or delay is due to low bandwidth, if I missed some configuration of bandwidth or something?

Thank you so much!

**Comment by jlaine** [comment]
Would you care to tell us more about how you solved you issue?

**Comment by jwzxgy2007** [comment]
> Would you care to tell us more about how you solved you issue?

I change the decode to h264_cuvid, and this error disappeared.😂

Because I am not familiar with ffmpeg, pyav, and I need to develop a project asap, I didn't dig into it.

By the way, thanks for your hard working to develop these projects!

**Comment by jwzxgy2007** [comment]
> Would you care to tell us more about how you solved you issue?

And for the network usage, I disable the RemoteBitrateEstimator and set a  constant bitrate for stream sender because I test it in LAN, and the bandwidth is sufficient.
