### ISSUE TITLE
JitterBuffer capacity

### ISSUE THREAD

**Issue by buendiya** [aiortc/aiortc#540]
According to https://chromium.googlesource.com/external/webrtc/+/HEAD/video/rtp_video_stream_receiver2.cc#58
```cpp
constexpr int kPacketBufferStartSize = 512;
constexpr int kPacketBufferMaxSize = 2048;
```
The WebRTC native video JitterBuffer start size is 512 and the max size is 2048. But aiortc video JitterBuffer capacity is set to 128. I want to know why 128 is chosen. Can you explain this to me? Thanks.

**Comment by jlaine** [comment]
I'd suggest reading the commit history as I was not the last person to touch the jitter buffer code

**Comment by buendiya** [comment]
Thanks.
