### ISSUE TITLE
Support abs-capture-time

### ISSUE THREAD

**Issue by cpagravel** [aiortc/aiortc#541]
It would be helpful if aiortc supported the `abs-capture-time` RTP extension - this is helpful for measuring latency or for AV sync.

https://webrtc.googlesource.com/src/+/refs/heads/master/docs/native-code/rtp-hdrext/abs-capture-time

It looks like that is not supported, though I see support for the abs-send-time.

I gave a stab at it, which I'll add in a separate post to keep things tidy.

I'm a bit unfamiliar with webRTC and this library, but I'm willing to lend a hand if someone might provide a bit of guidance.

**Comment by cpagravel** [comment]
To approach this I setup a short script so I could start testing functional changes. I did the following:

1. I setup the client and create offer sdp with the following code:
```
pc = RTCPeerConnection()
pc.addTrack(mediastreams.AudioStreamTrack())
pc.addTransceiver("video", direction="recvonly")
pc.createDataChannel("dataSendChannel")
offer = asyncio.get_event_loop().run_until_complete(pc.createOffer())
```
1. I manually added the line `a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-capture-time` to the offer sdp (recvonly side) I generated - I'm sure there is a better way to do this, but I wanted to start making progress.
E.g.
```
...
a=recvonly
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-capture-time
...
```
1. Then I set the local and remote descriptions
```
response_obj = start_live_stream(offer_sdp)  # Internal API
media_session_id = response_obj.media_stream_id
answer = response_obj.answer_sdp

desc = aiortc.RTCSessionDescription(sdp=answer, type="answer")
wait(pc.setRemoteDescription(desc))
```

What I found encouraging was the fact that the answer sdp included the line:
```
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-capture-time
```

At this point I'm able to receive frames from the stream. I believe I've done things properly (except for my offer sdp hack). However, I don't see any abs-capture-time header extensions. I assumed that they'll pass through the [configure function](https://github.com/aiortc/aiortc/blob/main/src/aiortc/rtp.py#L48). But I don't see any packets with id 3.

Any suggestions for what parts of the code I will need to update and what I may be doing wrong? Happy to look deeper into this.

**Comment by jlaine** [comment]
I'm not sure I understand how you plan to leverage this extension:

- on the send side : where would we get this information from?
- on the receive side : where would this information be exposed?

**Comment by sahewat** [comment]
This would be very useful for me as well. @cpagravel Do you have a working implementation?
