### ISSUE TITLE
Audio Jitter Buffer

### ISSUE THREAD

**Issue by buendiya** [aiortc/aiortc#543]
Hi.
If there is audio packet loss, the audio jitter buffer will always be full. And the audio latency will be much larger.
I tried this test.

```python
from aiortc.jitterbuffer import JitterBuffer, RtpPacket

def test_audio_packet_loss():
    sequence_numbers = list(range(0, 8)) + list(range(9, 30))
    jbuffer = JitterBuffer(capacity=16, prefetch=4)

    start_timestamp = 1234
    for sequence_number in sequence_numbers:
        packet = RtpPacket(sequence_number=sequence_number, timestamp=start_timestamp + sequence_number)
        packet._data = bytes(str(sequence_number).zfill(4), encoding='ascii')
        pli_flag, frame = jbuffer.add(packet)
        if frame:
            print(sequence_number, frame.data, len([p for p in jbuffer._packets if p]))
        else:
            print(sequence_number, frame)
```

And the output is
```txt
0 None
1 None
2 None
3 None
4 b'0000' 4
5 b'0001' 4
6 b'0002' 4
7 b'0003' 4
9 None
10 None
11 None
12 None
13 None
14 None
15 None
16 None
17 None
18 None
19 None
20 None
21 None
22 None
23 b'0009' 14
24 b'0010' 14
25 b'0011' 14
26 b'0012' 14
27 b'0013' 14
28 b'0014' 14
29 b'0015' 14
```

**Comment by jlaine** [comment]
That's true. Could you please investigate how other jitter buffer implementation behave and report back?

I assume they have some sort of mechanism to progressively discard audio frames to allow playout to catch up?

**Comment by buendiya** [comment]
Sorry. Reply so late. The relevant code in WebRTC native is complicated for me. According to [https://chromium.googlesource.com/external/webrtc/+/HEAD/modules/audio_coding/neteq/neteq_impl.cc#2015](url) , it looks like that it will always get at least one packet even when there is packet loss.

**Comment by jlaine** [comment]
Does anyone plan to pick this up?
