### ISSUE TITLE
Encoder relay

### ISSUE THREAD

**Issue by benhacka** [aiortc/aiortc#544]
I'm trying to create an encoder (output) pipeline or relay in existing terms. Is there any more elegant way other than storing and accumulating a buffer with the encoded frames?
I'm saying about a retranslating video from RTSP-cam[s] to many clients. After connecting several (let's say larger than 9) clients, the processor starts to be heavily loaded for a single cam but I have several cameras. 
I want to decode and encode only once for each camera and send encoded frames to all required clients.
Thanks in advance.

**Comment by jlaine** [comment]
This feels as though it has been brought up many, many times, I suggest you browse the existing issues for an explanation of why aiortc doesn't provide this. For instance:

https://github.com/aiortc/aiortc/issues/449

**Comment by benhacka** [comment]
> This feels as though it has been brought up many, many times, I suggest you browse the existing issues for an explanation of why aiortc doesn't provide this. 

Ohh okey. I see. Sorry for the duplicate. So it's time2h@ck 
Thanks!
