### ISSUE TITLE
Video recording trouble in Mediarecorder()

### ISSUE THREAD

**Issue by TohkenSenran** [aiortc/aiortc#546]
In example of "server.py",  I can't record the video because of error of "libx264" when I add the argument "--record-to test.mp4".
I'm using venv for virtual environment.

Where should I fix the code  or What options do I add in mediacorder() ?

======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
INFO:pc:PeerConnection(1065ce22-83b6-4c15-8a7e-9a9a6486d3c3) Created for 127.0.0.1
INFO:pc:PeerConnection(1065ce22-83b6-4c15-8a7e-9a9a6486d3c3) Track video received
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.27.208.1', 61195) -> ('172.27.208.1', 59722)) State.FROZEN -> State.WAITING
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.29.128.1', 61196) -> ('172.27.208.1', 59722)) State.FROZEN -> State.WAITING
INFO:aioice.ice:Connection(0) Check CandidatePair(('192.168.10.17', 61197) -> ('172.27.208.1', 59722)) State.FROZEN -> State.WAITING
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.27.208.1', 61195) -> ('172.29.128.1', 59723)) State.FROZEN -> State.WAITING
INFO:aioice.ice:Connection(0) Check CandidatePair(('2001:f74:84c0:4000:b824:722f:f78f:197f', 61198) -> ('2001:f74:84c0:4000:6029:2ed1:4115:97d3', 59724)) State.FROZEN -> State.WAITING
INFO:aioice.ice:Connection(0) Check CandidatePair(('2001:f74:84c0:4000:6029:2ed1:4115:97d3', 61199) -> ('2001:f74:84c0:4000:6029:2ed1:4115:97d3', 59724)) State.FROZEN -> State.WAITING
INFO:pc:PeerConnection(1065ce22-83b6-4c15-8a7e-9a9a6486d3c3) Connection state is connecting
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.27.208.1', 61195) -> ('172.27.208.1', 59722)) State.WAITING -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.27.208.1', 61195) -> ('172.27.208.1', 59722)) State.IN_PROGRESS -> State.SUCCEEDED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.27.208.1', 61195) -> ('192.168.10.17', 59726)) State.FROZEN -> State.WAITING
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.29.128.1', 61196) -> ('172.27.208.1', 59722)) State.WAITING -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('192.168.10.17', 61197) -> ('172.27.208.1', 59722)) State.WAITING -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.27.208.1', 61195) -> ('172.29.128.1', 59723)) State.WAITING -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.29.128.1', 61196) -> ('172.29.128.1', 59723)) State.FROZEN -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('192.168.10.17', 61197) -> ('172.29.128.1', 59723)) State.FROZEN -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('2001:f74:84c0:4000:b824:722f:f78f:197f', 61198) -> ('2001:f74:84c0:4000:6029:2ed1:4115:97d3', 59724)) State.WAITING -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('2001:f74:84c0:4000:6029:2ed1:4115:97d3', 61199) -> ('2001:f74:84c0:4000:6029:2ed1:4115:97d3', 59724)) State.WAITING -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('2001:f74:84c0:4000:b824:722f:f78f:197f', 61198) -> ('2001:f74:84c0:4000:b824:722f:f78f:197f', 59725)) State.FROZEN -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('2001:f74:84c0:4000:6029:2ed1:4115:97d3', 61199) -> ('2001:f74:84c0:4000:b824:722f:f78f:197f', 59725)) State.FROZEN -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.27.208.1', 61195) -> ('192.168.10.17', 59726)) State.WAITING -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.29.128.1', 61196) -> ('192.168.10.17', 59726)) State.FROZEN -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('192.168.10.17', 61197) -> ('192.168.10.17', 59726)) State.FROZEN -> State.FAILED
INFO:aioice.ice:Connection(0) ICE completed
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.29.128.1', 61196) -> ('172.27.208.1', 59722)) State.FAILED -> State.IN_PROGRESS
INFO:pc:PeerConnection(1065ce22-83b6-4c15-8a7e-9a9a6486d3c3) Connection state is connected
[libx264 @ 00000222c53aa9c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 00000222c53aa9c0] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 00000222c53aa9c0] 264 - core 161 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=7 lookahead_threads=7 sliced_threads=1 slices=7 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=1024 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00  
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.29.128.1', 61196) -> ('172.29.128.1', 59723)) State.FAILED -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('172.29.128.1', 61196) -> ('172.29.128.1', 59723)) State.IN_PROGRESS -> State.SUCCEEDED
INFO:aioice.ice:Connection(0) Check CandidatePair(('2001:f74:84c0:4000:b824:722f:f78f:197f', 61198) -> ('2001:f74:84c0:4000:6029:2ed1:4115:97d3', 59724)) State.FAILED -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('2001:f74:84c0:4000:6029:2ed1:4115:97d3', 61199) -> ('2001:f74:84c0:4000:6029:2ed1:4115:97d3', 59724)) State.FAILED -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('2001:f74:84c0:4000:b824:722f:f78f:197f', 61198) -> ('2001:f74:84c0:4000:b824:722f:f78f:197f', 59725)) State.FAILED -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('2001:f74:84c0:4000:6029:2ed1:4115:97d3', 61199) -> ('2001:f74:84c0:4000:b824:722f:f78f:197f', 59725)) State.FAILED -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('192.168.10.17', 61197) -> ('192.168.10.17', 59726)) State.FAILED -> State.IN_PROGRESS
INFO:aioice.ice:Connection(0) Check CandidatePair(('192.168.10.17', 61197) -> ('192.168.10.17', 59726)) State.IN_PROGRESS -> State.SUCCEEDED
[libx264 @ 00000222c53aa9c0] non-strictly-monotonic PTS
[libx264 @ 00000222c53aa9c0] non-strictly-monotonic PTS
[libx264 @ 00000222c53aa9c0] non-strictly-monotonic PTS
[mp4 @ 00000222c533e780] Application provided invalid, non monotonically increasing dts 
to muxer in stream 0: 42496 >= 42496
INFO:pc:PeerConnection(1065ce22-83b6-4c15-8a7e-9a9a6486d3c3) Track video ended
[mp4 @ 00000222c533e780] Application provided invalid, non monotonically increasing dts 
to muxer in stream 0: 56320 >= 56320
ERROR:asyncio:Exception in callback AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe..., 'test.mp4')>) at C:\Users\diceh\source\repos\aiortc\examples\server\lib\site-packages\pyee\_asyncio.py:55
handle: <Handle AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe..., 'test.mp4')>) at C:\Users\diceh\source\repos\aiortc\examples\server\lib\site-packages\pyee\_asyncio.py:55>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\diceh\source\repos\aiortc\examples\server\lib\site-packages\pyee\_asyncio.py", line 62, in _callback
    self.emit('error', exc)
  File "C:\Users\diceh\source\repos\aiortc\examples\server\lib\site-packages\pyee\_base.py", line 116, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "C:\Users\diceh\source\repos\aiortc\examples\server\lib\site-packages\pyee\_base.py", line 86, in _emit_handle_potential_error
    raise error
  File "C:\Users\diceh\source\repos\aiortc\examples\server\server.py", line 175, in on_ended
    await recorder.stop()
  File "C:\Users\diceh\source\repos\aiortc\examples\server\lib\site-packages\aiortc\contrib\media.py", line 380, in stop
    self.__container.mux(packet)
  File "av\container\output.pyx", line 204, in av.container.output.OutputContainer.mux  
  File "av\container\output.pyx", line 227, in av.container.output.OutputContainer.mux_one
  File "av\container\core.pyx", line 258, in av.container.core.Container.err_check      
  File "av\error.pyx", line 336, in av.error.err_check
av.error.ValueError: [Errno 22] Invalid argument: 'test.mp4'
INFO:pc:PeerConnection(1065ce22-83b6-4c15-8a7e-9a9a6486d3c3) Connection state is closed
Traceback (most recent call last):
  File "av\container\output.pyx", line 25, in av.container.output.close_output
TypeError: 'NoneType' object is not iterable
Exception ignored in: 'av.container.output.OutputContainer.__dealloc__'
Traceback (most recent call last):
  File "av\container\output.pyx", line 25, in av.container.output.close_output
TypeError: 'NoneType' object is not iterable
[libx264 @ 00000222c53aa9c0] frame I:1     Avg QP:23.38  size: 13436
[libx264 @ 00000222c53aa9c0] frame P:33    Avg QP:15.21  size: 10102
[libx264 @ 00000222c53aa9c0] frame B:90    Avg QP:22.42  size:  1044
[libx264 @ 00000222c53aa9c0] consecutive B-frames:  2.4%  1.6%  2.4% 93.5%
[libx264 @ 00000222c53aa9c0] mb I  I16..4: 16.8% 68.9% 14.2%
[libx264 @ 00000222c53aa9c0] mb P  I16..4:  0.4%  0.8%  0.5%  P16..4: 36.8% 15.8%  9.9% 
 0.0%  0.0%    skip:35.8%
[libx264 @ 00000222c53aa9c0] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8: 31.5%  1.9%  0.3% 
 direct: 0.5%  skip:65.9%  L0:43.3% L1:50.9% BI: 5.8%
[libx264 @ 00000222c53aa9c0] final ratefactor: 14.91
[libx264 @ 00000222c53aa9c0] 8x8 transform intra:60.2% inter:42.0%
[libx264 @ 00000222c53aa9c0] coded y,uvDC,uvAC intra: 72.3% 30.0% 19.1% inter: 13.1% 7.2% 1.8%
[libx264 @ 00000222c53aa9c0] i16 v,h,dc,p:  7% 56%  6% 31%
[libx264 @ 00000222c53aa9c0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 32% 27% 15%  3%  3%  4%  3% 
 5%  7%
[libx264 @ 00000222c53aa9c0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 42% 27% 11%  3%  3%  4%  3% 
 4%  3%
[libx264 @ 00000222c53aa9c0] i8c dc,h,v,p: 76% 14%  8%  2%
[libx264 @ 00000222c53aa9c0] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 00000222c53aa9c0] ref P L0: 66.1% 15.8% 15.4%  2.6%
[libx264 @ 00000222c53aa9c0] ref B L0: 91.3%  7.8%  0.9%
[libx264 @ 00000222c53aa9c0] ref B L1: 94.2%  5.8%
[libx264 @ 00000222c53aa9c0] kb/s:807.54

**Comment by TohkenSenran** [comment]
When I rewrite the argument "rate=30" of add_stream at 358 lines in media.py, This error is disappeared.

**Comment by jlaine** [comment]
OK thanks for reporting back
