### ISSUE TITLE
datachannel has a great latency

### ISSUE THREAD

**Issue by tsonglew** [aiortc/aiortc#547]
# My Code 

https://github.com/tsonglew/aiortc-datachannel-delay

run `python main.py` to start the server, then visit `localhost:8080` with a web browser

# My Problem

I'm trying to process the video frames from video track, and send back the result with datachannel. 

the result is replaced with `time.time()` in the above demo repo as following: 
``` python
self.channel.send(
      json.dumps({"now": time.time() * 1000})
)
```

the `<client receive from datachannel time> - <datachennl.send() time>` is considered as delay, and are `console.log`ed with code:
```javascript
ch.addEventListener("message", function (evt) {
	console.log(Date.now() - JSON.parse(evt.data).now);
});
```

the datachannel config is `{ordered: false, maxRetransmits: 0}`

# Output

<img width="198" alt="image" src="https://user-images.githubusercontent.com/14333766/125766778-698f9aee-2418-4fd5-ab81-c21b5be1e8fb.png">

as illustrated in the sreenshot, the delay is growing, but video and audio are fluent.

How can I get rid of the growing delay? Thx

**Comment by tsonglew** [comment]
found this problem is due to `RTCSctpTransport._transmit`, solved this by calling `RTCSctpTransport._send_chunk` to send data fragments directly

**Comment by tsonglew** [comment]
as a workaround, I altered my datachannel sending code like this

```python
self.channel.send(json.dumps({"now": time.time() * 1000}))
await self.channel._RTCDataChannel__transport._data_channel_flush()
await self.channel._RTCDataChannel__transport._transmit()
```

**Comment by jlaine** [comment]
Could you elaborate on this please ?

**Comment by tsonglew** [comment]
For apps sensitive to datachannel messages delay, the data should be transmitted immediately after calling `datachannel.send()`, but it isn't facts.

 Delay on datachannel could be reproduced in this demo: https://github.com/tsonglew/aiortc-datachannel-delay. Calling `RTCSctpTransport._data_channel_flush` and `RTCSctpTransport._transmit()` explicitly is a workaround.

I'm not familiar with aiortc and webrtc, but I guess there are two reasons:
1. user data are not tranmitted immediately after `RTCDataChannel.send`. The data are appended to `RTCSctpTransport._datachannel_queue` at first, and will be poped when `Future` `_data_channel_flush` comes, which means asyncio coroutine schduler might call this future after a period of time, and leads to the delay.
2. `RTCSctpTransport._send` run `self._transmit()` when `self._t3_handle` is `None`, and the condition is not alwalys meet when data comes.

I'm looking forward for your reply, Thx.

**Comment by Interpause** [comment]
Could above be implemented as a option when creating a data channel?

**Comment by jlaine** [comment]
I don't currently have any plans to change the code, I'm not seeing this behaviour in the DataChannel demo provided with aiortc.

**Comment by Interpause** [comment]
In my case, I am sending a dictionary containing pose estimations on a video feed at around 30Hz serialized using JSON. Ocassionally, the dict I send will be empty because no humans are detected. For some reason, instead of receiving an empty object, my web client receives `undefined` from the data channel. Using the above workaround as well as sending a timestamp in the dictionary resolved the issue.
