### ISSUE TITLE
profile-level-id=42e033

### ISSUE THREAD

**Issue by abbasloo** [aiortc/aiortc#549]
Hello,
I am writing a webrtc client side application by aiortc. The server sends an answer (since client sends the offer first) in which the profile-level-id is 42e033.  But in the client side, two options 42e01f and 42001f are available by aiortc. Is there any way to include 42e033 in the offer by aiortc?
 
PS: these numbers are related to H264 video codec.

**Comment by abbasloo** [comment]
Hello,
I am writing a webrtc client side application by aiortc. The server sends an answer (since client sends the offer first) in which the profile-level-id is 42e033.  But in the client side, two options 42e01f and 42001f are available by aiortc. Is there any way to include 42e033 in the offer by aiortc?
 
PS: these numbers are related to H264 video codec.

**Comment by jlaine** [comment]
I am not well versed enough in what each profile means, could you please collect the relevant specs and add them here?

**Comment by abbasloo** [comment]
Hello, I managed to rebuild the code on ubuntu by changing the H264 specification in aiortc/src/aiortc/codecs/__init__.py and it worked. Thanks! But now I have a new error from the decoder while receiving the stream 
[libx264 @ 0x7fffc5fc0640] non-strictly-monotonic PTS    
.
.
.
[libx264 @ 0x7fffc5fc0640] non-strictly-monotonic PTS                                                                                                                                                                                        [mp4 @ 0x7fffc5cff0c0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: -512 >= -512 

And after that the decoder stops. The output is just a short video with one frame!

**Comment by abbasloo** [comment]
And solved it by changing class MediaRecorder in the /aiortc/src/aiortc/contrib/media.py as follows for less frame per second

  async def __run_track(self, track, context):
      while True:
          try:
              for i in range(10):
                  frame = await track.recv()
          except MediaStreamError:
              return
          for packet in context.stream.encode(frame):
              self.__container.mux(packet)

It is not an elegant solution but works fine!
