### ISSUE TITLE
install mac os x

### ISSUE THREAD

**Issue by openmotion** [aiortc/aiortc#551]
Hello
i have a M1 mac
i have this error when i do : pip install aiortc
i installed : brew install ffmpeg opus libvpx pkg-config

Could not find libavformat with pkg-config.
  Could not find libavcodec with pkg-config.
  Could not find libavdevice with pkg-config.
  Could not find libavutil with pkg-config.
  Could not find libavfilter with pkg-config.
  Could not find libswscale with pkg-config.
  Could not find libswresample with pkg-config.

` ERROR: Command errored out with exit status 1:
     command: /opt/homebrew/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/8j/j4yjc2c512sbdxmlkfjf80640000gn/T/pip-install-o4xc9ios/av_48212e3d0d214f05bb55a94ce6374e8f/setup.py'"'"'; __file__='"'"'/private/var/folders/8j/j4yjc2c512sbdxmlkfjf80640000gn/T/pip-install-o4xc9ios/av_48212e3d0d214f05bb55a94ce6374e8f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/8j/j4yjc2c512sbdxmlkfjf80640000gn/T/pip-record-ekt1xq00/install-record.txt --single-version-externally-managed --compile --install-headers /opt/homebrew/include/python3.9/av
         cwd: /private/var/folders/8j/j4yjc2c512sbdxmlkfjf80640000gn/T/pip-install-o4xc9ios/av_48212e3d0d214f05bb55a94ce6374e8f/
    Complete output (48 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-11-arm64-3.9
    creating build/lib.macosx-11-arm64-3.9/av
    copying av/deprecation.py -> build/lib.macosx-11-arm64-3.9/av
    copying av/datasets.py -> build/lib.macosx-11-arm64-3.9/av
    copying av/__init__.py -> build/lib.macosx-11-arm64-3.9/av
    copying av/__main__.py -> build/lib.macosx-11-arm64-3.9/av
    creating build/lib.macosx-11-arm64-3.9/av/video
    copying av/video/__init__.py -> build/lib.macosx-11-arm64-3.9/av/video
    creating build/lib.macosx-11-arm64-3.9/av/codec
    copying av/codec/__init__.py -> build/lib.macosx-11-arm64-3.9/av/codec
    creating build/lib.macosx-11-arm64-3.9/av/container
    copying av/container/__init__.py -> build/lib.macosx-11-arm64-3.9/av/container
    creating build/lib.macosx-11-arm64-3.9/av/audio
    copying av/audio/__init__.py -> build/lib.macosx-11-arm64-3.9/av/audio
    creating build/lib.macosx-11-arm64-3.9/av/subtitles
    copying av/subtitles/__init__.py -> build/lib.macosx-11-arm64-3.9/av/subtitles
    creating build/lib.macosx-11-arm64-3.9/av/filter
    copying av/filter/__init__.py -> build/lib.macosx-11-arm64-3.9/av/filter
    creating build/lib.macosx-11-arm64-3.9/av/sidedata
    copying av/sidedata/__init__.py -> build/lib.macosx-11-arm64-3.9/av/sidedata
    creating build/lib.macosx-11-arm64-3.9/av/data
    copying av/data/__init__.py -> build/lib.macosx-11-arm64-3.9/av/data
    running build_ext
    running config
    PyAV: 8.0.3 (unknown commit)
    Python: 3.9.6 (default, Jun 28 2021, 19:24:41) \n[Clang 12.0.5 (clang-1205.0.22.9)]
    platform: macOS-11.3.1-arm64-arm-64bit
    extension_extra:
    	include_dirs: [b'include']
    	libraries: []
    	library_dirs: []
    	define_macros: []
    	runtime_library_dirs: []
    config_macros:
    	PYAV_COMMIT_STR="unknown-commit"
    	PYAV_VERSION=8.0.3
    	PYAV_VERSION_STR="8.0.3"
    Could not find libavformat with pkg-config.
    Could not find libavcodec with pkg-config.
    Could not find libavdevice with pkg-config.
    Could not find libavutil with pkg-config.
    Could not find libavfilter with pkg-config.
    Could not find libswscale with pkg-config.
    Could not find libswresample with pkg-config.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/homebrew/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/8j/j4yjc2c512sbdxmlkfjf80640000gn/T/pip-install-o4xc9ios/av_48212e3d0d214f05bb55a94ce6374e8f/setup.py'"'"'; __file__='"'"'/private/var/folders/8j/j4yjc2c512sbdxmlkfjf80640000gn/T/pip-install-o4xc9ios/av_48212e3d0d214f05bb55a94ce6374e8f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/8j/j4yjc2c512sbdxmlkfjf80640000gn/T/pip-record-ekt1xq00/install-record.txt --single-version-externally-managed --compile --install-headers /opt/homebrew/include/python3.9/av Check the logs for full command output.`

**Comment by tsonglew** [comment]
it's a PyAV problem, and installing ffmpeg-dev should help.

**Comment by jlaine** [comment]
Either way the issue is with pyav, not aiortc
