### ISSUE TITLE
I am trying the example webcam. When I click click on start button, it shows a javascript error- unexpected token in json at position 4. Can you please help me with this?

### ISSUE THREAD

**Issue by opusviz** [aiortc/aiortc#553]
Before filing an issue please verify the following:

* Check whether there is already an existing issue for the same topic.
* Ensure you are actually reporting an issue related to ``aiortc``. The goal
  of the issue tracker is not to provide general guidance about WebRTC or free
  debugging of your code.
* Clearly state whether the issue you are reporting can be reproduced with one
  of the examples provided with ``aiortc`` *without any changes*.
* Be considerate to the maintainers. ``aiortc`` is provided on a best-effort,
  there is no guarantee your issue will be addressed.

**Comment by lgrahl** [comment]
Please, follow the issue guidelines. If you're reporting a bug in the examples, please be more specific (e.g. post the stack trace).

**Comment by PyCoder040** [comment]
I'm having the exact same issue.  installed aiortc 1.3.2 via pip, localized the examples.  The live demo (from the webcam) works just fine.  But when supplying a h264 file, you get this.

```
# python webcam.py --play-from video.ts --play-without-decoding --video-codec video/H264
also tried with
# python webcam.py --play-from video.ts

======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
INFO:aiohttp.access:127.0.0.1 [02/Nov/2022:22:09:12 +0000] "GET / HTTP/1.1" 200 980 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
INFO:aiohttp.access:127.0.0.1 [02/Nov/2022:22:09:13 +0000] "GET /client.js HTTP/1.1" 200 2427 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/lib64/python3.10/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/data/workspace/aiortc/aiortc-main/examples/webcam/webcam.py", line 79, in offer
    audio, video = create_local_tracks(
  File "/data/workspace/aiortc/aiortc-main/examples/webcam/webcam.py", line 26, in create_local_tracks
    player = MediaPlayer(play_from, decode=decode)
TypeError: MediaPlayer.__init__() got an unexpected keyword argument 'decode'

```
The video.ts file was generated as follows:

`ffmpeg -i myrandomclip.ts -pix_fmt yuv420p -codec:v libx264 -profile:v baseline -level 31 -f mpegts video.ts `

**Comment by PyCoder040** [comment]
Interesting!!!

I just discovered why this doesn't work.  On a totally up to date Fedora 35 workstation, "pip3 install aiortc" pulls in what it claims to be version 1.3.2 (and about.py confirms that it's version 1.3.2).  Using this method, you get a /aiortc/src/aiortc/contrib/media.py that does NOT allow the decode keyword in MediaPlayer.__init__().  Look at the MD5 sums.

```
cd /usr/local/lib64/python3.10/site-packages/aiortc/
174c9cefae3790c77ee3f1d31ecab6ce  about.py
c7d78cb56d85782e897f74087c8a839f  contrib/media.py
```

But downloading 1.3.2 from github directly give a DIFFERENT fileset.  about.py still claims a version of 1.3.2.  

```
cd /tmp/x/aiortc/src/aiortc
174c9cefae3790c77ee3f1d31ecab6ce  about.py
325846d3d2d06c258fa53ecf29a415ad  contrib/media.py
```
