### ISSUE TITLE
Serious memory leak when not consuming tracks

### ISSUE THREAD

**Issue by thedjinn** [aiortc/aiortc#554]
When accepting a WebRTC connection containing a track, when the frames in this track are not consumed with `recv` (e.g. when not interested in the track's contents but being forced to have a full-duplex connection), aiortc will leak the track's audio frames. This consumes a lot of memory.

I suggest changing the AudioFrame queueing mechanism to use a ring buffer to mitigate this issue. This is what most real-time audio processing frameworks do. It will also save memory allocations because the queue size is fixed.

**Comment by ashat1701** [comment]
+ I faced that leaks too. VideoFrames also have this behaviour

**Comment by Saumya-NebCodes** [comment]
How to resolve this issue? kindly help

**Comment by ashat1701** [comment]
If you don't need video or audio, you can change js code (delete all pc.addTrack and add pc.addTransiever). If you need only some exact frames, you can call recv and consume all frames in loop and pick needed ones

**Comment by jlaine** [comment]
You need to consume all the accepted tracks, see the `MediaBlackhole` class for a sink which discards data.
