### ISSUE TITLE
Start player before running webRTC

### ISSUE THREAD

**Issue by nguyenhoaiphuong1913** [aiortc/aiortc#556]
How can I use MediaPlayer to read frame from camera without click "Start" button on browser. Because I want to get one by one frame from camera first and do some independent process and I don't want webrtc to work continuously in that process.

**Comment by ashat1701** [comment]
In MediaPlayer there are video and audio tracks. You can explicitly call recv on them to read audio or video tracks. But you need to be in same event loop with aiortc

**Comment by nguyenhoaiphuong1913** [comment]
@ashat1701 Thank you for your answer. But I still don't really understand. Could you give me an example?

**Comment by ashat1701** [comment]
```python
player = MediaPlayer(path)
audio_track = player.audio
video_track = player.video
audio_frame = await audio_track.recv()
video_frame = await video_track.recv()
```
Something like that.

**Comment by nguyenhoaiphuong1913** [comment]
@ashat1701 Thank you very much
