### ISSUE TITLE
Does the Raspberry PI 4B not support Google-CRC32C?

### ISSUE THREAD

**Issue by Canees** [aiortc/aiortc#558]
ity -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c src/google_crc32c/_crc32c.c -o build/temp.linux-aarch64-3.7/src/google_crc32c/_crc32c.o
  src/google_crc32c/_crc32c.c:3:10: fatal error: crc32c/crc32c.h: No such file or directory
   #include <crc32c/crc32c.h>
            ^~~~~~~~~~~~~~~~~
  compilation terminated.
  ERROR:root:Compiling the C Extension for the crc32c library failed. To enable building / installing a pure-Python-only version, set 'CRC32C_PURE_PYTHON=1' in the environment.
  error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for google-crc32c
  Running setup.py clean for google-crc32c
Failed to build google-crc32c
Installing collected packages: pylibsrtp, google-crc32c, aiortc
  Running setup.py install for google-crc32c ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-zemk6oyq/google-crc32c/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_30_twxh/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.7
    creating build/lib.linux-aarch64-3.7/google_crc32c
    copying src/google_crc32c/cext.py -> build/lib.linux-aarch64-3.7/google_crc32c
    copying src/google_crc32c/_checksum.py -> build/lib.linux-aarch64-3.7/google_crc32c
    copying src/google_crc32c/__config__.py -> build/lib.linux-aarch64-3.7/google_crc32c
    copying src/google_crc32c/__init__.py -> build/lib.linux-aarch64-3.7/google_crc32c
    copying src/google_crc32c/python.py -> build/lib.linux-aarch64-3.7/google_crc32c
    running build_ext
    building 'google_crc32c._crc32c' extension
    creating build/temp.linux-aarch64-3.7
    creating build/temp.linux-aarch64-3.7/src
    creating build/temp.linux-aarch64-3.7/src/google_crc32c
    aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c src/google_crc32c/_crc32c.c -o build/temp.linux-aarch64-3.7/src/google_crc32c/_crc32c.o
    src/google_crc32c/_crc32c.c:3:10: fatal error: crc32c/crc32c.h: No such file or directory
     #include <crc32c/crc32c.h>
              ^~~~~~~~~~~~~~~~~
    compilation terminated.
    ERROR:root:Compiling the C Extension for the crc32c library failed. To enable building / installing a pure-Python-only version, set 'CRC32C_PURE_PYTHON=1' in the environment.
    error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

/------------------------
Raspberry pi:
  Distributor ID: Debian
  Description:    Debian GNU/Linux 10 (buster)
  Release:        10
  Codename:       buster

**Comment by lgrahl** [comment]
I suggest to create an issue  in the respective project: https://github.com/googleapis/python-crc32c

**Comment by Canees** [comment]
> 我建议在各自的项目中创建一个问题：[https](https://github.com/googleapis/python-crc32c) : [//github.com/googleapis/python-crc32c](https://github.com/googleapis/python-crc32c)

thanks ,this problem has been solved
