### ISSUE TITLE
Transcoding unnecessary in janus example

### ISSUE THREAD

**Issue by rprata** [aiortc/aiortc#560]
Hi all, 

I'm using `janus` example in `raspberry pi`. However I have noticed that cpu processing is to large (~60%). Analyzing the source code, I saw that always decode/encode process happens, however my video codec input is the same of output (h264). 

Because of that, I removed transcode process to reduce the cpu processing (~3%), and now, I contribute with this [PR](https://github.com/aiortc/aiortc/pull/559) with changes. Please, could you review the code?

**Comment by Canees** [comment]
> 大家好，
> 
> 我`janus`在`raspberry pi`. 但是我注意到 cpu 处理太大（~60%）。分析源代码，我看到解码/编码过程总是发生，但是我的视频编解码器输入与输出相同（h264）。
> 
> 因此，我删除了转码过程以减少 cpu 处理（~3%），现在，我为这个[PR](https://github.com/aiortc/aiortc/pull/559)做出了改变。拜托，你能检查一下代码吗？

hello rprata,Can I add your contact information? I'd like to ask you some questions？

**Comment by rprata** [comment]
> > 大家好，
> > 我`janus`在`raspberry pi`. 但是我注意到 cpu 处理太大（~60%）。分析源代码，我看到解码/编码过程总是发生，但是我的视频编解码器输入与输出相同（h264）。
> > 因此，我删除了转码过程以减少 cpu 处理（~3%），现在，我为这个[PR](https://github.com/aiortc/aiortc/pull/559)做出了改变。拜托，你能检查一下代码吗？
> 
> hello rprata,Can I add your contact information? I'd like to ask you some questions？

@Canees, please, send me your question here or by e-mail.

**Comment by Canees** [comment]
I have installed AIORTC with PI, and you can get media stream without browser by looking at its documents. Examples are as follows:  
            self.webcam = MediaPlayer('/pythonAiortc/132.mp4')
            self.relay = MediaRelay()
            return None, self.relay.subscribe(self.webcam.video)

But execution has been problematic:
         Exception in thread Thread-1:
        Traceback (most recent call last):
          File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
            self.run()
          File "/pythonAiortc/send.py", line 28, in run
            audio, video = self.create_local_tracks()
          File "/pythonAiortc/send.py", line 22, in create_local_tracks
            self.webcam = MediaPlayer('/pythonAiortc/132.mp4')
          File "/usr/local/lib/python3.7/dist-packages/aiortc/contrib/media.py", line 252, in __init__
            self.__video = PlayerStreamTrack(self, kind="video")
          File "/usr/local/lib/python3.7/dist-packages/aiortc/contrib/media.py", line 166, in __init__
            self._queue = asyncio.Queue()
          File "/usr/lib/python3.7/asyncio/queues.py", line 34, in __init__
            self._loop = events.get_event_loop()
          File "/usr/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
            % threading.current_thread().name)
        RuntimeError: There is no current event loop in thread 'Thread-1'.
Also use :
           webcam = MediaPlayer("/dev/video0", format="v4l2", options={"framerate": "30", "video_size": "640x480"})
           relay = MediaRelay()
But it doesn't seem to be doing anything,Do you know the reason?

**Comment by rprata** [comment]
> I have installed AIORTC with PI, and you can get media stream without browser by looking at its documents. Examples are as follows:
> self.webcam = MediaPlayer('/pythonAiortc/132.mp4')
> self.relay = MediaRelay()
> return None, self.relay.subscribe(self.webcam.video)
> 
> But execution has been problematic:
> Exception in thread Thread-1:
> Traceback (most recent call last):
> File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
> self.run()
> File "/pythonAiortc/send.py", line 28, in run
> audio, video = self.create_local_tracks()
> File "/pythonAiortc/send.py", line 22, in create_local_tracks
> self.webcam = MediaPlayer('/pythonAiortc/132.mp4')
> File "/usr/local/lib/python3.7/dist-packages/aiortc/contrib/media.py", line 252, in **init**
> self.__video = PlayerStreamTrack(self, kind="video")
> File "/usr/local/lib/python3.7/dist-packages/aiortc/contrib/media.py", line 166, in **init**
> self._queue = asyncio.Queue()
> File "/usr/lib/python3.7/asyncio/queues.py", line 34, in **init**
> self._loop = events.get_event_loop()
> File "/usr/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
> % threading.current_thread().name)
> RuntimeError: There is no current event loop in thread 'Thread-1'.
> Also use :
> webcam = MediaPlayer("/dev/video0", format="v4l2", options={"framerate": "30", "video_size": "640x480"})
> relay = MediaRelay()
> But it doesn't seem to be doing anything,Do you know the reason?

@Canees , please delete this text and create a new issue with this.

**Comment by rprata** [comment]
Waiting for #559 resolution.

**Comment by RouquinBlanc** [comment]
👍 for those modifications! I've been wondering how to nicely avoid transcoding, in my case especially to act as a proxy dealing directly with RTP, and this solution is quite elegant!

I started some changes on my side to rather change the way the decoding / encoding loops get their decoder / encoder (which right now is a fixed call to `get_encoder` or `get_decoder`). Having the capability to get directly the raw packets is great, but it feels like it would be nice to continue later toward a more "plugable" encoding / decoding logic, so that we can plug anything in there as a decoder rather than the default pyav ones. It's tricky though and would require some refactoring to be done nicely. At least here, once the app gets the av.Packet, it can create its own decoder to deal with the incoming data if need be!

The scenarios I was thinking about:
* Encoding / decoding with a different codec, especially on platforms with hardware encoding like nvidia boards
* Or using another lib altogether

**Comment by rprata** [comment]
@RouquinBlanc, I closed this issue, because #559 was merge.
