### ISSUE TITLE
Changed the environment to be able to install, as a result, when using python version again  

### ISSUE THREAD

**Issue by Canees** [aiortc/aiortc#561]
root@raspberrypi:/pythonAiortc# python3 main.py
/usr/local/lib/python3.7/dist-packages/google_crc32c/__init__.py:29: RuntimeWarning: As the c extension couldn't be imported, `google-crc32c` is using a pure python implementation that is significantly slower. If possible, please configure a c build environment and compile the extension
  warnings.warn(_SLOW_CRC32C_WARNING, RuntimeWarning)

**Comment by Canees** [comment]
pip3 install crc32c

**Comment by lgrahl** [comment]
What's the question?

**Comment by rprata** [comment]
@Canees , We don't understand your question. Could explain more?

**Comment by Canees** [comment]
The CRC32C is reinstalled
