### ISSUE TITLE
Too high values from the "Jitter" statistic with local testing

### ISSUE THREAD

**Issue by robyanne92** [aiortc/aiortc#566]
Hi all,

I am using PeerConnection.getStats() in order to gets some statistics and evaluate the webrtc connection. Regarding the "Jitter" value (from the RTCInboundRtpStreamStats class) I noticed that, even with local tests (both peer on the same machine) this value is constantly in the range 200-600. I suppose that this value is measured in ms, and I would expect a value not over 25-30 ms. 
What does really represent this value?
Here is the async function that I use to retrieve the stats.

![image](https://user-images.githubusercontent.com/53224473/133105886-ffe42370-9470-479e-a37c-3d8f848fdc26.png)

Thanks in advance

Roberto

**Comment by jlaine** [comment]
Hi! I'd be happy to hear the results of your investigations, as I don't really have any insights off the top of my head.

**Comment by bluedodecahedron** [comment]
This seems to be still a problem. When looking at an "RTCRemoteInboundRtpStreamStats" object (retrieved with the getStats() method), the jitter value is always in the range of 800-1200 for me. If this is milliseconds, it makes no sense, because latency was never higher than 300ms.

Is the jitter value buggy or does it stand for something other than what is the norm?

**Comment by dryarullin** [comment]
@bluedodecahedron @jlaine I was also interested in this issue. I watch [this ](https://www.w3.org/TR/webrtc-stats/#dom-rtcreceivedrtpstreamstats-jitter) and then [this](https://www.rfc-editor.org/rfc/rfc3550#section-6.4.1). After this, it becomes clear that aiortc returns jitter value in some timestamps, not seconds. If I'm not mistaken, then to approximately get jitter in seconds you need to divide by clockRate. clockRate is predefined at 48000. So for you 800-1200 is converted to 16-25 ms. I also looked at Janus sources [1](https://github.com/meetecho/janus-gateway/blob/master/src/rtcp.c#L982) , [2](https://github.com/meetecho/janus-gateway/blob/6f6ac5eaf679bc2dc4d5de39051c22c233c38a74/src/rtcp.h#L245) , [3](https://github.com/meetecho/janus-gateway/blob/master/src/rtcp.c#L884) . Something similar is happening there.
