### ISSUE TITLE
Perfomance logging problems

### ISSUE THREAD

**Issue by ashat1701** [aiortc/aiortc#569]
I profiled my server and observed that logging is taking a lot of time.
![image](https://user-images.githubusercontent.com/9024337/133595717-3afa0e60-7a56-4346-b3ce-79a78a09ecde.png)
in rtcrtpsender.py. I think that maybe there should be some type of flag, that on or off logging (cause even if level of logging is error, python logger logs that messages anyway). 

![image](https://user-images.githubusercontent.com/9024337/133596695-20007bbc-220c-4c6f-b313-f5f50ecce7f1.png)
rtcpsender.py:315 we log every rtp packet, and there are more cases.

**Comment by ashat1701** [comment]
Also there is flame graph from sppedscope:
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/9024337/134433961-9bca56bd-bea4-47c7-b5d1-1d941f1e1307.png">

**Comment by jlaine** [comment]
Maybe try something like what is done in the SCTP stack:

https://github.com/aiortc/aiortc/blob/main/src/aiortc/rtcsctptransport.py#L733

Here log_debug is a noop unless debug logging is enabled. Could you try putting together a PR and providing some numbers on how performance is affected?
