### ISSUE TITLE
Created audio tracks never call `recv()`

### ISSUE THREAD

**Issue by W3AXL** [aiortc/aiortc#571]
I'll preface this by saying the default server example included with the repo works fine.

I have a webapp that originally used websockets to transfer audio along with other data. I'm trying to move the audio portion over to WebRTC, with the session signalling being done via the existing websocket connection. I'm essentially just adapting the server example to do bidirectional audio and removing the video portion entirely.

I might be misunderstanding how to do things correctly, but here is the python code on the server that responds to the SDP offer and sets up the audio tracks. It's almost identical to the example `server.py`:

```py
class MicStreamTrack(MediaStreamTrack):
    """
    An audio stream object for the mic audio from the client
    """
    kind = "audio"

    def __init__(self, track):
        super().__init__()
        self.track = track

    async def recv(self):
        logger.logVerbose("mic recv()")

        # Get a new PyAV frame
        frame = await self.track.recv()

        # Convert to float32 numpy array
        floatArray = frame.to_ndarray(format="float32")

        # Put these samples into the mic queue
        micSampleQueue.put_nowait(floatArray)

        logger.logVerbose("Put {} samples to mic queue".format(len(floatArray)))

class SpkrStreamTrack(MediaStreamTrack):
    """
    An audio stream object for the speaker data from the server
    """
    kind = "audio"

    def __init__(self):
        super().__init__()

    async def recv():
        logger.logVerbose("spkr recv()")

        # Get samples from speaker queue if available
        floatArray = await spkrSampleQueue.get()

        # Convert to audio 
        frame = AudioFrame.from_ndarray(floatArray, format='float', layout='mono')

        logger.logVerbose("Got {} speaker samples".format(frame.samples))

        # Return
        return frame

async def gotRtcOffer(offerObj):
    """
    Called when we receive a WebRTC offer from the client

    Args:
        offerObj (dict): WebRTC SDP offer object
    """

    global rtcPeer

    logger.logInfo("Got WebRTC offer")
    
    # Create SDP offer and peer connection objects
    offer = RTCSessionDescription(sdp=offerObj["sdp"], type=offerObj["type"])
    rtcPeer = RTCPeerConnection()

    # Create UUID for peer
    pcUuid = "PeerConnection({})".format(uuid.uuid4())
    logger.logVerbose("Creating peer connection {}".format(pcUuid))

    # ICE connection state callback
    @rtcPeer.on("iceconnectionstatechange")
    async def onIceConnectionStateChange():
        logger.logVerbose("Ice connection state is now {}".format(rtcPeer.iceConnectionState))
        if rtcPeer.iceConnectionState == "failed":
            await rtcPeer.close()
            logger.logError("WebRTC peer connection {} failed".format(pcUuid))
    
    # Audio track callback
    @rtcPeer.on("track")
    def onTrack(track):

        global micStream
        global rtcPeer

        logger.logVerbose("Got {} track from peer {}".format(track.kind, pcUuid))

        # make sure it's audio
        if track.kind != "audio":
            logger.logError("Got non-audio track from peer {}".format(pcUuid))
            return
        
        # Create the mic stream for this track
        micStream = MicStreamTrack(track)
        logger.logVerbose("Added mic track")

        # Send the speaker stream back
        spkrTrack = SpkrStreamTrack()
        rtcPeer.addTrack(spkrTrack)
        logger.logVerbose("Added speaker track")

        # Track ended handler
        @track.on("ended")
        async def onEnded():
            logger.logVerbose("Audio track from {} ended".format(pcUuid))

    # Handle the received offer
    logger.logVerbose("Creating remote description from offer")
    await rtcPeer.setRemoteDescription(offer)

    # Create answer
    logger.logVerbose("Creating WebRTC answer")
    answer = await rtcPeer.createAnswer()

    # Set local description
    logger.logVerbose("setting local SDP")
    await rtcPeer.setLocalDescription(answer)

    # Send answer
    logger.logVerbose("sending SDP answer")
    message = '{{ "webRtcAnswer": {{ "type": "{}", "sdp": {} }} }}'.format(rtcPeer.localDescription.type, json.dumps(rtcPeer.localDescription.sdp))
    messageQueue.put_nowait(message)

    logger.logVerbose("done")
```

All of the expected SDP log messages occur, and it appears on both ends (the web browser and the python script) that everything is set up properly. Both tracks are added and it looks like the connection goes fully active:

```
[09/22 13:09:56] (  gotRtcOffer   ) INFO: Got WebRTC offer
[09/22 13:09:56] (  gotRtcOffer   ) VERB: Creating peer connection PeerConnection(514e2bad-a415-412f-b741-1e16ab82b023)
[09/22 13:09:56] (  gotRtcOffer   ) VERB: Creating remote description from offer
[09/22 13:09:56] (    onTrack     ) VERB: Got audio track from peer PeerConnection(514e2bad-a415-412f-b741-1e16ab82b023)
[09/22 13:09:56] (    onTrack     ) VERB: Added mic track
[09/22 13:09:56] (    onTrack     ) VERB: Added speaker track
[09/22 13:09:56] (  gotRtcOffer   ) VERB: Creating WebRTC answer
[09/22 13:09:56] (  gotRtcOffer   ) VERB: setting local SDP
[09/22 13:10:01] (  gotRtcOffer   ) VERB: sending SDP answer
[09/22 13:10:01] (  gotRtcOffer   ) VERB: done
[09/22 13:10:01] (producer_hander ) INFO: sending WebRTC answer to ::1
[09/22 13:10:01] (onIceConnectionStateChange) VERB: Ice connection state is now checking
[09/22 13:10:02] (onIceConnectionStateChange) VERB: Ice connection state is now completed
```

I can even see the data being sent from the webpage to the server via the chrome WebRTC internals. However, the `recv()` callbacks on the python side for either track are never called. I'd expect to see a ton of prints as data is flowing every time the tracks get new data, but nothing ever happens after the RTC session connects. No errors occur on either the webpage or the python script either.

My limited understanding of WebRTC is preventing me from being able to figure out what's going wrong. Help would be greatly appreciated.

**Comment by preste-thsou** [comment]
Hello.
I believe you need a consumer of the track for the recv() to be called. For the audio in, you can use a recorder in the form of a MediaBlackHole() (from aiortc.contrib.media import MediaBlackhole), and add track to the recorder with recoder.addTrack(micStream), or recoder.addTrack(relay.suscribe(micStream)). For the audio out, I'm not sure whether your class SpkrStreamTrack without a track initialized can work, but you can always use the same track as the audio in, as in the server demo..

**Comment by W3AXL** [comment]
I'll try and see if setting up a dummy track makes things work. I guess I wasn't aware that you needed some kind of endpoint before `recv()` would be called, but I suppose that makes sense.

**Comment by W3AXL** [comment]
Still no dice - I added in the extra tracks but I'm still not getting any audio, nor are the `recv()` callbacks getting fired.

```py
    # Audio track callback when we get the mic track from the client
    @rtcPeer.on("track")
    def onTrack(track):

        global micTrack
        global spkrTrack
        global blackHole
        global rtcPeer

        logger.logVerbose("Got {} track from peer {}".format(track.kind, pcUuid))

        # make sure it's audio
        if track.kind != "audio":
            logger.logError("Got non-audio track from peer {}".format(pcUuid))
            return
        
        # Create the mic stream for this track, and add its output to a media blackhole so it starts
        micTrack = MicStreamTrack(track)
        blackHole = MediaBlackhole()
        blackHole.addTrack(micTrack)
        logger.logVerbose("Added mic track")

        # Create the speaker track and add the mic track as its input track (so it starts properly)
        spkrTrack = SpkrStreamTrack(micTrack)
        rtcPeer.addTrack(spkrTrack)
        logger.logVerbose("Added speaker track")
```

As before, no errors are occurring and all the SDP handshaking appears to be working just fine on both the python and the JS side of things:

```
[09/28 19:00:17] (  gotRtcOffer   ) INFO: Got WebRTC offer
[09/28 19:00:17] (  gotRtcOffer   ) VERB: Creating peer connection PeerConnection(c6f87cfc-d223-496d-b8f0-4bb2a128ce2e)
[09/28 19:00:17] (  gotRtcOffer   ) VERB: Creating remote description from offer
[09/28 19:00:17] (    onTrack     ) VERB: Got audio track from peer PeerConnection(c6f87cfc-d223-496d-b8f0-4bb2a128ce2e)
[09/28 19:00:17] (    onTrack     ) VERB: Added mic track
[09/28 19:00:17] (    onTrack     ) VERB: Added speaker track
[09/28 19:00:17] (  gotRtcOffer   ) VERB: Creating WebRTC answer
[09/28 19:00:17] (  gotRtcOffer   ) VERB: setting local SDP
[09/28 19:00:22] (  gotRtcOffer   ) VERB: sending SDP answer
[09/28 19:00:22] (  gotRtcOffer   ) VERB: done
[09/28 19:00:22] (producer_hander ) INFO: sending WebRTC answer to ::1
[09/28 19:00:22] (onIceConnectionStateChange) VERB: Ice connection state is now checking
[09/28 19:00:22] (onIceConnectionStateChange) VERB: Ice connection state is now completed
```

**Comment by preste-thsou** [comment]
Hello,

You need to start the blackhole when you want to start receiving the feed, and stop it when you're done : blackhole.start(), and blackhole.stop().. That should do it.
For the spkrtrack, for stability issue it will probably be better to generate it's own frames inside recv() : you can find an example of 8khz silence generation in the source code in aiortc/mediastreams.py , class AudioStreamTrack.

**Comment by W3AXL** [comment]
Alright, I believe I have half the problem figured out.

After calling `start()` on the `MediaBlackhole`, my mic stream is actually running and the `recv()` callback is called properly. The samples I get from `frame.to_ndarray(dtype=np.float32)` are not actually float samples, so that's something to figure out down the road, but for now it's at least working and I can hear something resembling audio through my speakers.

However, the speaker track still isn't starting and calling its `recv()` method, and I'm not sure why that is.

**Comment by preste-thsou** [comment]
Hello,

If you're not using a different track for in and out, and all you want to do is to relay the mic source into the speaker, then you need to use a relay (see my first post above), otherwise you can not have two consumers of the same track. In the code you posted 3 days ago, you're not using a Relay so that can't work. Use relay = MediaRelay(), and then relay.subscribe(your_track) each time you want to use the track.
If you're using different tracks for in and out, then the RTCP sender will consume the track you add to the PC and call the .recv() function. if that doesn't work, then you're recv() function inside spkrTrack is not generate frames as it should...

**Comment by W3AXL** [comment]
Apologies, I'm probably not explaining things well.

I do indeed have two different tracks:
- My mic track puts samples from the RTC connection into one queue that pyaudio pulls from for playback over another sound device (my speakers for testing). 
- My speaker track takes data from a queue that pyaudio populates with data from a microphone. It puts this data into a frame and sends it back over the RTC connection.

I'm guessing there may be an exception being thrown inside my speaker's `recv()` function, but I'm seeing no errors in my console because of threading. I'll do some more digging.

**Comment by W3AXL** [comment]
Does this look correct as a `MediaStreamTrack` subclass? My understanding is that you pass audio to the track consumer by returning an audio frame. I'm still not seeing any prints of `recv()` from this object.

```py
class SpkrStreamTrack(MediaStreamTrack):
    """
    An audio stream object for the speaker data from the server
    """
    kind = "audio"

    def __init__(self, track):
        super().__init__()
        self.track = track

    async def recv(self):
        logger.logVerbose("spkr recv()")

        # create empty data by default
        data = np.zeros(spkrBufferSize).astype(np.int16)

        # Only get speaker data if we have some in the buffer
        if spkrSampleQueue.qsize() > 1:
            try:
                data = spkrSampleQueue.get_nowait()

            except queue.Empty:
                pass

        # Convert to audio 
        frame = AudioFrame.from_ndarray(data, format='s16p', layout='mono')

        # Return
        return frame
```

**Comment by preste-thsou** [comment]
Hello Patrick,

A first remark is that, since you don't use the track in your init, you can just remove it from the constructor (and from your call).

Then, you may want to raise a MediaStreamError if the queue is Empty.

End then, as the probable cause for your troubles, what you are missing here is to set your frame properties correctly : frame.sample_rate, frame.time_base and frame.pts.

Consider adding this to your init: 
```
        self.sample_rate = 48000
        self.samples = 960
```
and then this inside you recv(): 

```
        if hasattr(self, "_timestamp"):
            self._timestamp += self.samples
            wait = self._start + (self._timestamp / self.sample_rate) - time.time()
            await asyncio.sleep(wait)
        else:
            self._start = time.time()
            self._timestamp = 0
```
and, after you created the frame and before returning it: 

```
        frame.pts = self._timestamp
        frame.sample_rate = self.sample_rate
        frame.time_base = fractions.Fraction(1, self.sample_rate)
```

**Comment by W3AXL** [comment]
I have taken your advice, but `recv()` is still not called.

```py
class SpkrStreamTrack(MediaStreamTrack):
    """
    An audio stream object for the speaker data from the server
    """
    kind = "audio"

    def __init__(self):
        super().__init__()
        self.samplerate = audioSampleRate
        self.samples = spkrBufferSize

    async def recv(self):
        logger.logInfo("spkr recv()")

        # Handle timestamps properly
        if hasattr(self, "_timestamp"):
            self._timestamp += self.samples
            wait = self._start + (self._timestamp / self.samplerate) - time.time()
            await asyncio.sleep(wait)
        else:
            self._start = time.time()
            self._timestamp = 0

        # create empty data by default
        data = np.zeros(spkrBufferSize).astype(np.int16)

        # Only get speaker data if we have some in the buffer
        if spkrSampleQueue.qsize() > 1:
            try:
                data = spkrSampleQueue.get_nowait()

            except queue.Empty:
                pass

        # Convert to audio 
        frame = AudioFrame.from_ndarray(data, format='s16p', layout='mono')

        # Update time stuff
        frame.pts = self._timestamp
        frame.sample_rate = self.samplerate
        frame.time_base = fractions.Fraction(1, self.samplerate)

        # Return
        return frame
```

The speaker queue can be empty, that's a valid state for my application as it's only populated with data some of the time. The array of zeroes I create first is there to populate the frame with empty data when there's no actual audio to send.

**Comment by preste-thsou** [comment]
Hello.. 

Well, I'm don't know what can cause the issue now, sorry...Do you see no logs at all from the recv(), or only one iteration of the logs ? Only one could mean that something is wrong with the frame you generate and cause the rtpcsender or encoder to stall, (so you need to play with the different format / options of the frame creation, like maybe use "s16" and not "s16p", and set samples = self.samples). Zero logs mean the recv() function is not called at all, and I don't see why it wouldn't,  You may want to active the --verbose mode of aiortc and see what you get in terms of PC negotiation traces, in particular in RTPCSender, and you can also look at chrome://webrtc-internals/ from Chrome client to see whether you see the PC track coming in to your browser. That's all I can say, sorry..

**Comment by guanfeii** [comment]
i have the same problem, have you solved?

**Comment by W3AXL** [comment]
No resolution yet. I do have some WebRTC internals debug info. 

First, here's the microphone track (outbound from the browser) which has been working fine so far:

![outbound_track](https://user-images.githubusercontent.com/29879554/139682172-1c6843c5-401d-4423-9e23-c4f204040632.PNG)

Next, the inbound track (remote inbound RTP) and the stats for the connection. Looks like the connection is being set up properly and audio packets are being sent back? I don't know exactly what I should be looking for here.

![inbound_track](https://user-images.githubusercontent.com/29879554/139682520-a69862c0-a3db-4bd7-93a5-764d0a3bc610.PNG)

Please let me know if you want to see any specific info from the WebRTC debug page.

**Comment by jlaine** [comment]
You need to write code that consumes any incoming tracks. The server example does this taking received tracks and sending them back after applying a transform to them.

**Comment by W3AXL** [comment]
I already handle the incoming audio from the javascript client fine. It's routed out to another audio device on the python server and seems to be working 100%.

The issue is the audio originating from the python server. I want to send audio data from the server back to the javascript client. The track I want to send, `SpkrStreamTrack` in the above code, never calls its `recv()` function which I want to use to fill the track with new audio samples.

Maybe I'm misunderstanding how to do this properly.

**Comment by W3AXL** [comment]
Any help would be appreciated with this issue. It's a very basic use case of the library and I'm not sure if it's my specific implementation or the library itself causing things not to work.

To boil down the problem to its essentials: I want to send raw audio samples via WebRTC from my python script to a javascript frontend. The other direction, audio from the javascript application to the python script, is working fine.

**Comment by W3AXL** [comment]
So logged the SDP that my server is sending back to my client:

```
v=0
o=- 3847360402 3847360402 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic:WMS *
m=audio 55785 UDP/TLS/RTP/SAVPF 111
c=IN IP4 192.168.0.100
a=recvonly
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=mid:0
a=msid:ceb88e58-4924-4adc-93ce-e0d1fe4e934b b2f59a59-3c84-49cf-9ea0-f859181352a2
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc:3706548357 cname:25557da6-6d9a-4372-a27b-343e93483b2c
a=rtpmap:111 opus/48000/2
a=candidate:53b13011c51e3a7e9ace60f1098b0d77 1 udp 2130706431 192.168.0.100 55785 typ host
a=candidate:4ad068542e013f1c98e07b9f94710232 1 udp 2130706431 192.168.22.1 55786 typ host
a=candidate:aa239e8fd1e0060c26c8942e87f2b953 1 udp 2130706431 192.168.135.1 55787 typ host
a=candidate:ff2e2f27cdc00fa2dc3c2c1990e204ae 1 udp 2130706431 10.10.10.9 55788 typ host
a=candidate:0d402153e6c97ea2f551899afceacd2d 1 udp 2130706431 192.168.132.2 55789 typ host
a=candidate:0d77cc54d84e58c767c3a262afb1cd70 1 udp 1694498815 209.252.171.205 55785 typ srflx raddr 192.168.0.100 rport 55785
a=end-of-candidates
a=ice-ufrag:4Iep
a=ice-pwd:LJTgVsZGFuzEEAGeq7rgar
a=fingerprint:sha-256 DC:2E:14:CA:BE:9F:82:39:34:19:74:D0:B6:DC:AD:4C:34:DD:4A:E7:12:24:CB:5B:25:26:D3:0C:9B:74:8E:0E
a=setup:active
```

**Notice the `a=recvonly` line.** Looks like maybe I'm forming the SDP before the speaker track gets added to the peer connection. Interesting that I'm doing things in the same order as the server example in this repo, but I guess maybe there's a slight timing difference that's causing the offer to get created before the audio track is added to the PeerConnection.

Would adding in some logic that waits to send the offer back to the client until the track is received be a suitable way to work around this?

**Comment by W3AXL** [comment]
I changed my code to add the speaker track _before_ creating any offers, and I think that's at least part of the problem solved! I finally get a `spkr recv()` log print!

```py
async def gotRtcOffer(offerObj):
    """
    Called when we receive a WebRTC offer from the client

    Args:
        offerObj (dict): WebRTC SDP offer object
    """

    global rtcPeer

    logger.logInfo("Got WebRTC offer")

    # Start audio on radios
    logger.logVerbose("Starting audio devices on radios")
    startSound()
    
    # Create SDP offer and peer connection objects
    offer = RTCSessionDescription(sdp=offerObj["sdp"], type=offerObj["type"])
    rtcPeer = RTCPeerConnection()

    # Create UUID for peer
    pcUuid = "Peer({})".format(uuid.uuid4())
    logger.logVerbose("Creating peer connection {}".format(pcUuid))

    # Create the speaker track
    spkrTrack = SpkrStreamTrack()
    rtcPeer.addTrack(spkrTrack)
    logger.logVerbose("Added speaker track")

    # ICE connection state callback
    @rtcPeer.on("iceconnectionstatechange")
    async def onIceConnectionStateChange():
        logger.logVerbose("Ice connection state is now {}".format(rtcPeer.iceConnectionState))
        if rtcPeer.iceConnectionState == "failed":
            await rtcPeer.close()
            logger.logError("WebRTC peer connection {} failed".format(pcUuid))
    
    # Audio track callback when we get the mic track from the client
    @rtcPeer.on("track")
    async def onTrack(track):

        global micTrack
        global spkrTrack
        global blackHole
        global rtcPeer

        logger.logVerbose("Got {} track from peer {}".format(track.kind, pcUuid))

        # make sure it's audio
        if track.kind != "audio":
            logger.logError("Got non-audio track from peer {}".format(pcUuid))
            return
        
        # Create the mic stream for this track, and add its output to a media blackhole so it starts
        micTrack = MicStreamTrack(track)
        blackHole = MediaBlackhole()
        blackHole.addTrack(micTrack)
        logger.logVerbose("Added mic track")
        await blackHole.start()
        logger.logVerbose("Started mic track")

        # Track ended handler
        @track.on("ended")
        async def onEnded():
            logger.logVerbose("Audio track from {} ended".format(pcUuid))

    await doRtcAnswer(offer)

    logger.logVerbose("done")
```

```
[12/01 09:50:29.166] (  gotRtcOffer   ) INFO: Got WebRTC offer
[12/01 09:50:29.166] (  gotRtcOffer   ) VERB: Starting audio devices on radios
[12/01 09:50:29.197] (   startAudio   ) INFO: Starting audio streams for Desk VHF XTL
[12/01 09:50:29.231] (  gotRtcOffer   ) VERB: Creating peer connection Peer(7ce5494d-244c-49b2-8100-3fac91d2c24f)
[12/01 09:50:29.231] (    __init__    ) VERB: SpkrStreamTrack initialized
[12/01 09:50:29.232] (  gotRtcOffer   ) VERB: Added speaker track
[12/01 09:50:29.232] (  doRtcAnswer   ) VERB: Creating remote description from offer
[12/01 09:50:29.233] (  doRtcAnswer   ) VERB: Creating WebRTC answer
[12/01 09:50:29.234] (  doRtcAnswer   ) VERB: setting local SDP
[12/01 09:50:29.234] (    onTrack     ) VERB: Got audio track from peer Peer(7ce5494d-244c-49b2-8100-3fac91d2c24f)
[12/01 09:50:29.234] (    onTrack     ) VERB: Added mic track
[12/01 09:50:29.235] (    onTrack     ) VERB: Started mic track
[12/01 09:50:34.278] (  doRtcAnswer   ) VERB: sending SDP answer
[12/01 09:50:34.278] (  gotRtcOffer   ) VERB: done
[12/01 09:50:34.279] (producer_hander ) INFO: sending WebRTC answer to ::1
[12/01 09:50:34.280] (onIceConnectionStateChange) VERB: Ice connection state is now checking
[12/01 09:50:34.382] (onIceConnectionStateChange) VERB: Ice connection state is now completed
[12/01 09:50:34.384] (      recv      ) INFO: spkr recv()
```

Now, I have to figure out why `recv()` only gets called once, when it should be called continuously. I'm guessing I'm doing something wrong inside the function itself, but I'm not getting any exceptions or error messages.

```py
async def recv(self):
        logger.logInfo("spkr recv()")

        # Handle timestamps properly
        if hasattr(self, "_timestamp"):
            self._timestamp += self.samples
            wait = self._start + (self._timestamp / self.samplerate) - time.time()
            await asyncio.sleep(wait)
        else:
            self._start = time.time()
            self._timestamp = 0

        # create empty data by default
        data = np.zeros(self.samples).astype(np.int16)

        # Only get speaker data if we have some in the buffer
        if spkrSampleQueue.qsize() > 1:
            try:
                data = spkrSampleQueue.get_nowait()
            except queue.Empty:
                pass

        # Convert to audio 
        frame = AudioFrame.from_ndarray(data, format='s16', layout='mono')

        # Update time stuff
        frame.pts = self._timestamp
        frame.sample_rate = self.samplerate
        frame.time_base = fractions.Fraction(1, self.samplerate)

        # Return
        return frame
```

**Comment by W3AXL** [comment]
### Success!

PyAV is _extremely_ picky with its input data format, and is also _extremely_ vague about what that format is.

Turns out, for a mono s16 sample array, it needs to be a **2-dimensional** array of **single valued-arrays**, like so:

```
[[0],[0],[0],...]
```

PyAV only reports errors via asserts with no actual error message. The relevant code to figure out what kind of array was needed is here:

https://github.com/PyAV-Org/PyAV/blob/9ac05d9ac902d71ecb2fe80f04dcae454008378c/av/audio/frame.pyx#L119-L127

Now my revised and working playback code is below:

```py
    async def recv(self):

        # Handle timestamps properly
        if hasattr(self, "_timestamp"):
            self._timestamp += self.samples
            wait = self._start + (self._timestamp / self.samplerate) - time.time()
            await asyncio.sleep(wait)
        else:
            self._start = time.time()
            self._timestamp = 0

        # create empty data by default
        data = np.zeros(self.samples).astype(np.int16)

        # Only get speaker data if we have some in the buffer
        if spkrSampleQueue.qsize() > 1:
            try:
                logger.logVerbose("Getting speaker samples from queue")
                data = spkrSampleQueue.get_nowait()
            except queue.Empty:
                pass

        # To convert to a mono audio frame, we need the array to be an array of single-value arrays for each sample (annoying)
        data = data.reshape(data.shape[0], -1).T
        # Create audio frame
        frame = AudioFrame.from_ndarray(data, format='s16', layout='mono')

        # Update time stuff
        frame.pts = self._timestamp
        frame.sample_rate = self.samplerate
        frame.time_base = fractions.Fraction(1, self.samplerate)

        # Return
        return frame
```

**Comment by preste-thsou** [comment]
Good, congrats. I agree with the statement on PyAV. In my company, we have been working extensively on various frame shapes coming from Text-to-Speech engines and it was tricky to use that through PyAV. Also, the aiortc lib brings its own layer of complexity with elements like mediarecorder or mediarelays that are very sensitive to frame.pts gaps, leading to crashes when the internet connexion is not 100% stable.. we are planning to release a blog articles with tricks and how-tos related to this lib, if you're interested I would be able to share a link when it's released

**Comment by dheerajkrgoyal** [comment]
> Good, congrats. I agree with the statement on PyAV. In my company, we have been working extensively on various frame shapes coming from Text-to-Speech engines and it was tricky to use that through PyAV. Also, the aiortc lib brings its own layer of complexity with elements like mediarecorder or mediarelays that are very sensitive to frame.pts gaps, leading to crashes when the internet connexion is not 100% stable.. we are planning to release a blog article with tricks and how-tos related to this lib, if you're interested I would be able to share a link when it's released

I went through your article. Its insightful. But I am still stuck. I want to process audio frames and convert speech into text and do processing when speech is silent. Can you help me?

**Comment by prad-human-007** [comment]
> I went through your article. Its insightful. But I am still stuck. I want to process audio frames and convert speech into text and do processing when speech is silent. Can you help me?

Did you get any solution for your problem ?
