### ISSUE TITLE
Specifying options to MediaPlayer for an rtmp causes segmentation fault.

### ISSUE THREAD

**Issue by entropical** [aiortc/aiortc#572]
I want to read from an rtmp stream, and write to webrtc.

`player_vid = MediaPlayer("rtmp://localhost/live/name", format="live_flv")`

This works, but has too much latency - around 5 seconds. If I use `ffplay.exe -fflags nobuffer -flags low_delay -f flv` there is minimal latency, around 1 seconds, which is sufficient.

I have tried various methods of passing options to MediaPlayer, but everything I have tried causes a segfault. 

I also tried to include the options in the URL, but they are explicitly blocked:

"Detected librtmp style URL parameters, these aren't supported by the libavformat internal RTMP handler currently enabled"

I have tried various combinations of the following, with `rtmp_buffer`, `fflags`, `-fflags`, etc:
```
player_vid = MediaPlayer("rtmp://localhost/live/name", format="live_flv",             
        options={"rtmp_buffer": "500"})
```

- Any suggestions?
- How can I find out more about the segfault?
- Can I use librtmp as the handler, rather than libavformat?

Thanks, Brock

**Comment by jlaine** [comment]
Can you try again with the latest PyAV version (8.1.0)? A hardcoded `max_analyze_duration` was removed and it may have changed the behaviour. Do you have a test URL to reproduce your issue as otherwise there is nothing I can do?

**Comment by bernardolansing** [comment]
I was facing a similar issue today. Video streaming was running fine, but as soon as I'd close the connection I'd run into a segmentation fault.

I managed to solve it by updating/installing ffmpeg in my system (`sudo apt install ffmpeg`). I think ffmpeg isn't actually a dependency for aiortc or its subdependencies, so the problem must be lying on one of the libraries that are installed along with it. Those are:

libavcodec-dev libavcodec59 libavdevice-dev libavdevice59 libavfilter-dev libavfilter8 libavformat-dev libavformat59 libavutil-dev libavutil57 libpostproc-dev libpostproc56 libswresample-dev libswresample4 libswscale-dev libswscale6

(just in case someone wants to dig deeper).
