### ISSUE TITLE
[Question] Can Track event handlers be async?

### ISSUE THREAD

**Issue by bmsan** [aiortc/aiortc#578]
Hello,

I am successfully running server->web client video streaming using as a starting point the example from https://github.com/aiortc/aiortc/tree/main/examples/server

I noticed that on my modified example if I change
```
     @pc.on("track")
    def on_track(track):
````
to

```
    @pc.on("track")
    async def on_track(track):
```

frames stop flowing.

I still need to check this on the original example, but is it expected that the track event to work only with synchronous handlers?

 I see that the "ended" event handler is by default asynchronous so I suspect something in my code is causing this.

**Comment by ashat1701** [comment]
Simple solution - you can call trampoline with create_task(coro, loop)

**Comment by jlaine** [comment]
There is nothing preventing event handlers from being asynchronous, `pyee` (which aiortc uses for it's events) supports this.

However in the specific case of the `server` example closely examine what this means: it means you have no guarantee that your local track will be added to the peer connection before sending your answer. If you want `on_track` to be async you're going to need to refactor how the answer is sent, by delaying the HTTP response.
