### ISSUE TITLE
Send Picture Loss Indication (PLI) when a keyframe is needed

### ISSUE THREAD

**Issue by jlaine** [aiortc/aiortc#58]
Currently `aiortc` implements the RTCP NACK mechanism to report missing RTP packets to the sender, allowing seamless recovery under moderate packet loss. However, in the event of heavy packet loss, it does not yet implement Picture Loss Indication (PLI) to request a full keyframe from the remote party. To do so we need to better understand the conditions under which a PLI should be sent.

Note: on the sender side, `aiortc` responds both to NACK and to PLI, so this is only a receiver side issue.

**Comment by notedit** [comment]
I want to know  why we do not send FIR  when a keyframe is needed.

**Comment by jlaine** [comment]
Regardless of whether we send FIR or PLI, the critical missing bit is detecting we need it - which I haven't had time to do yet. If you have time for a dive into the WebRTC code I'd be interested in a list of the criteria they use for this.

**Comment by koenvo** [comment]
> I want to know why we do not send FIR when a keyframe is needed.

I noticed some browsers ignore the FIR and do respond with a keyframe to a PLI

**Comment by jlaine** [comment]
Do you know what criteria are used to send out a PLI? I think the webrtc.org has a timer for "how long since a frame was last successfully decoded" and some other triggers.

**Comment by jlaine** [comment]
I had a deeper look at the code, and it looks like simply sending out a PLI is not going to be enough. In addition the jitter buffer code would need to be reworked to discard packets intelligently, otherwise it will keep waiting for the missing packets until it eventually overflows. In fact I'm not entirely convinced we can keep using a single jitter buffer implementation for audio and video. The webrtc.org codebase seems to use two distinct implementations.

**Comment by jlaine** [comment]
@Przem83 fixed this in 42f4e0f57b186aa15b0e731be37ca35afd780100
