### ISSUE TITLE
RTCP causes exception: ValueError: packet is too long

### ISSUE THREAD

**Issue by mschweig** [aiortc/aiortc#584]
Hi, 

I am trying to record a WebRTC stream using aiortc 1.2 on a raspberry pi with Ubuntu 20.04. 

Unfortunately I am getting the following error after 2-3 minutes of recording. I already tried to hardcode the stream size in media.py, but without success. Also tried it with older version of aiortc on another system. Same issue.

How can I solve this issue?

```
WARNING:aiortc.rtcdtlstransport:RTCDtlsTransport(client) Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiortc/rtcdtlstransport.py", line 531, in __run
    await self._recv_next()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiortc/rtcdtlstransport.py", line 630, in _recv_next
    await self._handle_rtp_data(data, arrival_time_ms=arrival_time_ms)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiortc/rtcdtlstransport.py", line 583, in _handle_rtp_data
    await receiver._handle_rtp_packet(packet, arrival_time_ms=arrival_time_ms)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiortc/rtcrtpreceiver.py", line 476, in _handle_rtp_packet
    packet.ssrc, sorted(self.__nack_generator.missing)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiortc/rtcrtpreceiver.py", line 560, in _send_rtcp_nack
    await self._send_rtcp(packet)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiortc/rtcrtpreceiver.py", line 547, in _send_rtcp
    await self.transport._send_rtp(bytes(packet))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pylibsrtp/__init__.py", line 207, in protect_rtcp
    return self.__process(packet, lib.srtp_protect_rtcp, SRTP_MAX_TRAILER_LEN)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pylibsrtp/__init__.py", line 231, in __process
    raise ValueError("packet is too long")
ValueError: packet is too long
```

**Comment by jlaine** [comment]
Hi, what is the other WebRTC implementation which you run `aiortc` against? I'm puzzled by the size of your packets, `pylibsrtp` accepts packets up to 1500 bytes long.

**Comment by le-chat** [comment]
Hello, I also have `ValueError: packet is too long` several minutes after start. In our setup Janus takes stream from IP-camera (by RTSP) and resends it via WebRTC to python handler (aiortc).

Below 172.20.0.5 is an address of python handler; I've run `sudo tshark -i any -Y 'ip.addr==172.20.0.5&&udp' > /tmp/udp-local.txt`, which printed info like
```
393540 263.855125842  10.99.98.99 → 172.20.0.5   UDP 1506 10083 → 40764 Len=1462
```
After that `grep UDP /tmp/udp-local.txt | awk '{print $11}' | cut -c 5- | sort -n | uniq -c | tail -n3` shows maximum packet length was 1464:
```
      4 1461
 181624 1462
    358 1464
```
And during time when this was captured we had `packet is too long`.

The size of UDP packets with headers may be greater than 1500 (1508?), but for vast majority packets `Len=1462` and the field after `UDP` is 1506 and aiortc is okay with them, so I assume `Len=...` is the size which matters.

**Comment by jlaine** [comment]
OK it looks like I misread the trace, the error is not about a *received* packet, it's about a *sent* packet. Specifically, we are trying to send an RTCP NACK packet which is too long. The maximum payload size which `pylibsrtp` is willing to protect is 1500 - SRTP_MAX_TRAILER_LEN, so 1356 bytes.

It looks like you are experiencing heavy packet loss on a video stream, which results in aiortc trying to send out an overly large RTCP packet. The fix would be to rework the NACK logic to keep the packet size under a fixed limit.

**Comment by le-chat** [comment]
Thank you for the fix. When are you going to make release with this commit?

**Comment by jlaine** [comment]
aiortc 1.3.2 should be on its way to PyPI as soon as CI completes.
