### ISSUE TITLE
[INFO] Python bindings for libwebrtc and C++ library with signaling server

### ISSUE THREAD

**Issue by doumdi** [aiortc/aiortc#587]
Hi,

I would like to let you know that we have implemented Python bindings for libwebrtc in the opentera-webrtc project on GitHub. We have also implemented a C++ client library, a Javascript library and a compatible signaling server.

I thought this might be useful to share some implementation and ideas, so here is the link:

[https://github.com/introlab/opentera-webrtc](https://github.com/introlab/opentera-webrtc) 

Thanks for your project!

Best regards,

Dominic Letourneau (@doumdi)
IntRoLab - Intelligent / Interactive / Integrated / Interdisciplinary Robot Lab @ Université de Sherbrooke, Québec, Canada

**Comment by jlaine** [comment]
Hi! Good to know there is one more webrtc implementation to choose from!

To give your project extra visibility maybe consider participating in:

https://github.com/sipsorcery/webrtc-echoes
