### ISSUE TITLE
[Server demo] H264 with HW acceleration(Cuda/h264_nvenc) - issues when streaming - jerky/tremor movement

### ISSUE THREAD

**Issue by bmsan** [aiortc/aiortc#588]
Hello,

I have tried to enable `h264_nvenc` (HW GPU encoding) inside the[ example server demo](https://github.com/aiortc/aiortc/tree/main/examples/server).
The end result is that the received video has a tremor in time(eg: something like the streams shows frames out of order: N, N-k, N+delta, N+delta-K, N+ 2*delta...)

This effect doesn't happen when using the default h264 or VP8.

This seems to affect `MediaStreamTrack` but not `MediaRecorder`

In the demo:
- I enabled the web client to request H264
- in aiortc code aiortc/codecs/h264.py I modified the H264Encoder to use `h264_nvenc` instead of  `h264_omx/libx264`
- In the codec options I've tried 
    - leaving them empty
    - Setting them to
    ```
    codec.options = {
        "profile": "baseline",
        "level": "31",
        # "tune": "zerolatency",  note this is commented as it doesn't seem to be supported
    }
    ```
 - I've tried setting codec_buffering to both True & False but I didn't see any change related to the tremor.
 - 
# Futher experiments I did to debug this issue:

1. Enabled video recording of the received media stream using MediaRecorder
where I forced `h264_nvenc` inside the add_track method:                 
```
stream = self.container.add_stream("h264_nvenc", rate=30)
```
The recorded video doesn't have this issue so it seems that the issue happens in the context of `MediaStreamTrack`

2. Instead of doing `Browser Webcam->Server->Browser` I have tried to stream the saved video from point 1, using `MediaPlayer`, `MediaPlayer Server -> Browser`. The issue appears in this configuration
 
3. On the decoder side I've tried using `h264_cuvid` instead of the `h264` but the issue is the same.
 
4. I've tried unsuccessfully reproducing this in ffmpeg, but the issue doesn't reproduce there.
```
ffmpeg  -c:v h264 -i in.mp4 -c:v h264_nvenc  A.mp4
ffmpeg  -c:v h264_cuvid -i in.mp4 -c:v h264_nvenc  B.mp4
```

5. I've tried unsuccessfully reproducing this in [pyav](https://github.com/PyAV-Org/PyAV), in their 
[numpy generate video example](https://github.com/PyAV-Org/PyAV/blob/main/examples/numpy/generate_video.py)

I've used there `h264_nvenc` and also tried 2 flavors with & without providing PTS information.

# My setup:

* OS: 5.4.0-90-generic # 101~18.04.1-Ubuntu
* aiortc==1.2.1
* av==8.0.3 built with --no-binary option
* ffmpeg built from sources:
    * nv-codec-headers tags/n11.0.10.1
    * ffmpeg tags/n4.4.1
    ```
    ./configure --enable-cuda-nvcc --enable-cuvid --enable-nvenc --enable-nonfree --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --disable-static --enable-shared
    ```
* NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2  
* python 3.9.7

**Comment by bmsan** [comment]
Any suggestions on what to debug further to get more information would be greatly appreciated .

**Comment by jlaine** [comment]
I really have no idea here, especially as I'm don't have a cuda-accelerated setup..

**Comment by lamhoangtung** [comment]
Have you solved this @bmsan ?

**Comment by pumelotea** [comment]
I encountered the same issue: I compiled PyAV 14 from source to enable the H264_nvenc encoder (compilation succeeded), then modified the aiortc 12.3 source code to support encoder configuration via the sender. While the code runs successfully and WebRTC initializes properly, the video output exhibits glitches and jitter. My NVIDIA graphics driver is version 570.

```
python -m av --codecs | grep h264

out:

 D.V.LS h264_cuvid         Nvidia CUVID H264 decoder
 .EV.LS h264_nvenc         NVIDIA NVENC H.264 encoder
 DEV.LS h264_v4l2m2m       V4L2 mem2mem H.264 encoder wrapper
```

**Comment by pumelotea** [comment]
@bmsan @lamhoangtung  i solved this problem !!!

this code is not enough!!!!!
```
codec.options = {
    "profile": "baseline",
    "level": "31",
    # "tune": "zerolatency",  note this is commented as it doesn't seem to be supported
}
```
fix it  like this ：
```
 codec.options = {
        "preset": "fast",
        "rc": "vbr",
 }
self.codec.profile = "baseline"
```
Nvidia H264_nvenc  codec  has own params, the default params is not correct, so need set in code! 
I test at `window11 with Nvidia 4070ti and AMD 3600 CPU`, it is work well .
Also, I test at `Macbook M4 Pro`,  use Apple `h264_videotoolbox` , webrtc also work well.


So !  you need change some other codec params , just try it!

**Comment by silencht** [comment]
@pumelotea 
oh, my hero! i love you, work well!
