### ISSUE TITLE
Wrong arguments order in candidate_from_sdp with Google Nest Cam WebRTC stream

### ISSUE THREAD

**Issue by danieleratti** [aiortc/aiortc#589]
I'm trying to read a WebRTC Stream from Google Nest Cam with the videostream-cli/cli.py example.

I've created an SDP offer with the following configuration:
```
pc.addTransceiver("audio", direction="recvonly")
pc.addTransceiver("video", direction="recvonly")
pc.createDataChannel(label="dataSendChannel")
await pc.setLocalDescription(await pc.createOffer())
```

And I got this SDP answer from Google:
`v=0\r\no=- 0 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 2 1\r\na=msid-semantic: WMS 15858084926298797471\/3462220087 virtual-6666\r\na=ice-lite\r\nm=audio 19305 UDP\/TLS\/RTP\/SAVPF 96\r\nc=IN IP4 172.253.117.127\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=candidate: 1 udp 2113939711 2607:f8b0:400e:c0a::7f 19305 typ host generation 0\r\na=candidate: 1 tcp 2113939710 2607:f8b0:400e:c0a::7f 19305 typ host tcptype passive generation 0\r\na=candidate: 1 ssltcp 2113939709 2607:f8b0:400e:c0a::7f 443 typ host generation 0\r\na=candidate: 1 udp 2113932031 172.253.117.127 19305 typ host generation 0\r\na=candidate: 1 tcp 2113932030 172.253.117.127 19305 typ host tcptype passive generation 0\r\na=candidate: 1 ssltcp 2113932029 172.253.117.127 443 typ host generation 0\r\na=ice-ufrag:ICOZDGWXSEYVE\/1H\r\na=ice-pwd:redacted\r\na=fingerprint:sha-256 69:74:37:47:12:20:18:7B:2B:E1:A8:F0:6B:3A:81:08:CF:70:21:D9:35:A9:12:94:67:98:B6:85:C9:BC:D6:2E\r\na=setup:passive\r\na=mid:0\r\na=sendrecv\r\na=msid:virtual-6666 virtual-6666\r\na=rtcp-mux\r\na=rtpmap:96 opus\/48000\/2\r\na=fmtp:96 minptime=10;useinbandfec=1\r\na=ssrc:6666 cname:6666\r\nm=video 9 UDP\/TLS\/RTP\/SAVPF 97 98 101 102\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:ICOZDGWXSEYVE\/1H\r\na=ice-pwd:redacted\r\na=fingerprint:sha-256 69:74:37:47:12:20:18:7B:2B:E1:A8:F0:6B:3A:81:08:CF:70:21:D9:35:A9:12:94:67:98:B6:85:C9:BC:D6:2E\r\na=setup:passive\r\na=mid:1\r\na=extmap:2 http:\/\/www.webrtc.org\/experiments\/rtp-hdrext\/abs-send-time\r\na=sendrecv\r\na=msid:15858084926298797471\/3462220087 15858084926298797471\/3462220087\r\na=rtcp-mux\r\na=rtpmap:97 VP8\/90000\r\na=rtcp-fb:97 ccm fir\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtcp-fb:97 goog-remb\r\na=rtpmap:98 rtx\/90000\r\na=fmtp:98 apt=97\r\na=rtpmap:101 H264\/90000\r\na=rtcp-fb:101 ccm fir\r\na=rtcp-fb:101 nack\r\na=rtcp-fb:101 nack pli\r\na=rtcp-fb:101 goog-remb\r\na=fmtp:101 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:102 rtx\/90000\r\na=fmtp:102 apt=101\r\na=ssrc-group:FID 3462220087 259725458\r\na=ssrc:3462220087 cname:3462220087\r\na=ssrc:259725458 cname:3462220087\r\nm=application 9 DTLS\/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:ICOZDGWXSEYVE\/1H\r\na=ice-pwd:redacted\r\na=fingerprint:sha-256 69:74:37:47:12:20:18:7B:2B:E1:A8:F0:6B:3A:81:08:CF:70:21:D9:35:A9:12:94:67:98:B6:85:C9:BC:D6:2E\r\na=setup:passive\r\na=mid:2\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n`

The code crashes in the candidate_from_sdp function, and debugging it I found that in the following code:

```
    bits = sdp.split()
    assert len(bits) >= 8

    candidate = RTCIceCandidate(
        component=int(bits[1]),
        foundation=bits[0],
        ip=bits[4],
        port=int(bits[5]),
        priority=int(bits[3]),
        protocol=bits[2],
        type=bits[7],
    )
```
I have the candidate arguments in a different order than expected:
sdp content: ` 1 udp 2113939711 2607:f8b0:400e:c0a::7f 19305 typ host generation 0`
so the bits array contains:
`['1', 'udp', '2113939711', '2607:f8b0:400e:c0a::7f', '19305', 'typ', 'host', 'generation', '0']`

**Comment by lgrahl** [comment]
The foundation (or the component ID) is missing. None of these parts are optional, see [RFC 5254, sec 15.1](https://www.rfc-editor.org/rfc/rfc5245#section-15.1). So, I'd advise to confront Google with that. :slightly_smiling_face:

Nothing aiortc can do here though.

**Comment by danieleratti** [comment]
I understand, but in JavaScript with the vanilla RTCPeerConnection, the same output format is accepted and works fine.

Real example:

```
    const myPeerConnection = new RTCPeerConnection
    const ms = new MediaStream
    [...]
    const sessionDescription = new RTCSessionDescription({ type: "answer", sdp: answer })
    myPeerConnection.setRemoteDescription(sessionDescription)
    myPeerConnection.addEventListener("track", (e => { ms.addTrack(e.track), document.getElementById("remote-stream").srcObject = ms }))
```

example of sdp answer (whose format isn't accepted by Aiortc):
`v=0\r\no=- 0 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 2 1\r\na=msid-semantic: WMS 10069509210505182064\/3462220087 virtual-6666\r\na=ice-lite\r\nm=audio 19305 UDP\/TLS\/RTP\/SAVPF 111\r\nc=IN IP4 172.253.117.127\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=candidate: 1 udp 2113939711 2607:f8b0:400e:c0a::7f 19305 typ host generation 0\r\na=candidate: 1 tcp 2113939710 2607:f8b0:400e:c0a::7f 19305 typ host tcptype passive generation 0\r\na=candidate: 1 ssltcp 2113939709 2607:f8b0:400e:c0a::7f 443 typ host generation 0\r\na=candidate: 1 udp 2113932031 172.253.117.127 19305 typ host generation 0\r\na=candidate: 1 tcp 2113932030 172.253.117.127 19305 typ host tcptype passive generation 0\r\na=candidate: 1 ssltcp 2113932029 172.253.117.127 443 typ host generation 0\r\na=ice-ufrag:5YATKLO1YTMYO+QQ\r\na=ice-pwd:redacted\r\na=fingerprint:sha-256 69:74:37:47:12:20:18:7B:2B:E1:A8:F0:6B:3A:81:08:CF:70:21:D9:35:A9:12:94:67:98:B6:85:C9:BC:D6:2E\r\na=setup:passive\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:3 http:\/\/www.ietf.org\/id\/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=sendrecv\r\na=msid:virtual-6666 virtual-6666\r\na=rtcp-mux\r\na=rtpmap:111 opus\/48000\/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=ssrc:6666 cname:6666\r\nm=video 9 UDP\/TLS\/RTP\/SAVPF 98 99 125 107 96 97\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:5YATKLO1YTMYO+QQ\r\na=ice-pwd:redacted\r\na=fingerprint:sha-256 69:74:37:47:12:20:18:7B:2B:E1:A8:F0:6B:3A:81:08:CF:70:21:D9:35:A9:12:94:67:98:B6:85:C9:BC:D6:2E\r\na=setup:passive\r\na=mid:1\r\na=extmap:2 http:\/\/www.webrtc.org\/experiments\/rtp-hdrext\/abs-send-time\r\na=extmap:13 urn:3gpp:video-orientation\r\na=extmap:3 http:\/\/www.ietf.org\/id\/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=sendrecv\r\na=msid:10069509210505182064\/3462220087 10069509210505182064\/3462220087\r\na=rtcp-mux\r\na=rtpmap:98 VP9\/90000\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=rtcp-fb:98 goog-remb\r\na=fmtp:98 profile-id=0\r\na=rtpmap:99 rtx\/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:125 H264\/90000\r\na=rtcp-fb:125 transport-cc\r\na=rtcp-fb:125 ccm fir\r\na=rtcp-fb:125 nack\r\na=rtcp-fb:125 nack pli\r\na=rtcp-fb:125 goog-remb\r\na=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:107 rtx\/90000\r\na=fmtp:107 apt=125\r\na=rtpmap:96 VP8\/90000\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:96 goog-remb\r\na=rtpmap:97 rtx\/90000\r\na=fmtp:97 apt=96\r\na=ssrc-group:FID 3462220087 259725458\r\na=ssrc:3462220087 cname:3462220087\r\na=ssrc:259725458 cname:3462220087\r\nm=application 9 DTLS\/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:5YATKLO1YTMYO+QQ\r\na=ice-pwd:redacted\r\na=fingerprint:sha-256 69:74:37:47:12:20:18:7B:2B:E1:A8:F0:6B:3A:81:08:CF:70:21:D9:35:A9:12:94:67:98:B6:85:C9:BC:D6:2E\r\na=setup:passive\r\na=mid:2\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n`


As you can notice the candidates are in the following format:
`1 udp 2113939711 2607:f8b0:400e:c0a::7f 19305 typ host generation 0` and they works in JS

**Comment by lgrahl** [comment]
Then the browser you've tried has more relaxed parsing. But it's still a standard violation and would be complicated to work around in a general sense.

You can of course workaround it yourself by fixing the candidates... or contacting Google to fix their stuff. :wink:

**Comment by danieleratti** [comment]
I managed to get this Nest stream working. Actually it was pretty simple: it wasn't a wrong arguments order but just the missing foundation value (the first one).

In case, I've created the pull request #590 if you want to add this more relaxed version of the protocol in this project considering Google Chrome is accepting it.

**Comment by juberti** [comment]
I'd actually suggest filing a bug at bugs.webrtc.org about this, Chrome really ought not to do this. I can route it to the right people once filed.
