### ISSUE TITLE
How to change the transform parameter the moment of video processing

### ISSUE THREAD

**Issue by MiMoody** [aiortc/aiortc#594]
I'm using the "server" example
Initially, the parameter "transform == edges" ( VideoTransformTrack(
relay.subscribe(track), transform=params["video_transform"]
))
But when you click on the button in the browser, I want to change this parameter to "transform == cartoon"
How can I do this without breaking the connection?

**Comment by bmsan** [comment]
@MiMoody you can do some minimal modifications to the demo to obtain what you want.

In the demo there is a data channel connection between the web browser and the server which you can use for this purpose. 


- On the server side you can see the [data channel message handler](https://github.com/aiortc/aiortc/blob/main/examples/server/server.py#L127)

You can use a handle to the  instantiated [VideoTransformTrack object](https://github.com/aiortc/aiortc/blob/main/examples/server/server.py#L146) and change the transform parameter from there.

- On the client side you can use the data channel object `[``dc```](https://github.com/aiortc/aiortc/blob/main/examples/server/client.js#L124)

**Comment by MiMoody** [comment]
@bmsan

**Comment by MiMoody** [comment]
Thank you very much for the answer, I have already implemented it, everything works
