### ISSUE TITLE
How to fetch live stream and use for computer vision application ?

### ISSUE THREAD

**Issue by yogii786** [aiortc/aiortc#598]
How to fetch live stream for the video processing from USB camera attached with raspberry pi

**Comment by bmsan** [comment]
Maybe the examples in this repo will help you.
There is for instance an webcam example you can see here: https://github.com/aiortc/aiortc/tree/main/examples/webcam

**Comment by jlaine** [comment]
Let's move this to discussions instead, I'm trying to declutter the issues tracker.
