### ISSUE TITLE
Unable to trigger callback method with peer connection

### ISSUE THREAD

**Issue by rocco-haro** [aiortc/aiortc#609]
Hello, 

First of all, thank you for your efforts with maintaining the project! 

Ok, let's jump in. 

I've been referencing the example server, and realized that I'm unable to access the video streams here https://github.com/aiortc/aiortc/blob/main/examples/server/server.py#L36 UNLESS the peer connection instance calls the addTrack() method. 

There can exist a use case where the outcome of the video transformation does not need to be transmitted back to another peer, and instead could just either sink to the server, or even relay the transformed frame to a different connection. 

For example, client writes local track -> server receives peer track -> server transforms in real-time -> server sends frame elsewhere. 

In our use case, we have no intention of returning the transformed media back, but without calling pc.addTrack(), the recv function defined in the class does not get called in real-time. A workaround is to just return the frame, but we are wasting compute resources by re-encoding a frame and returning it to the client when it isn't necessary. 

My question is how is one supposed to mimick the callback behavior of pc.addTrack() without having to return a frame?

**Comment by rocco-haro** [comment]
I took the liberty of responding to another issue here https://github.com/aiortc/aiortc/issues/608#issuecomment-1004443300 to give y'all a bit more bandwidth :)

**Comment by jlaine** [comment]
Hi @rocco-haro,

You might want to have a look at some other examples, as the demo here is precisely for the case you described: the client sends data, the server transforms it and returns it.

If you purely want the server to receive data and not send anything back, you indeed do not need to call `pc.addTrack()`. You *do* however need to connect some sort of "sink" to the received track, i.e. something which will repeatedly call `recv()`. On the received track.

You can for instance look at the `MediaBlackHole` sink which just reads and discards media to write your own consumer:

https://github.com/aiortc/aiortc/blob/a4acc4c656c12ce1bc23edc2c365167edd6a9237/src/aiortc/contrib/media.py#L49

**Comment by rocco-haro** [comment]
Thanks @jlaine! Will give this a shot.

**Comment by tejas-polakam** [comment]
Hello I am facing a similar issue with a similar usecase.

My business logic is 

Server generates video -> Sends to client -> Client recieves track -> Client sends text data to server -> Server recieves.


I'm wondering, does the server have to create the data connection or can the client also create the data connection.

Would it be like server creates and sends offer with track data to client. Client receives the offer and returns data connection answer. Is that possible?

**Comment by dheerajkrgoyal** [comment]
Even with any MediaSink (recorder or blackhole) it doesn't seem to be working. It seems like we need to have pc.addTrack() mandatorily to invoke recv() function.
