### ISSUE TITLE
Invalid data found when processing input

### ISSUE THREAD

**Issue by Grand-0616** [aiortc/aiortc#612]
Hello, there will be a lot of invalid data when my program keeps getting frames and taking screenshots. This problem is inevitable. After a task lasts for a long time, ICE invalidates the certificate and stops getting frames, but it still consumes a lot of CPU resources. 
![Uploading `8_3JRBP][C5`1PVFT
![RS`_W6B{L}$CK}T5YP9$%P9](https://user-images.githubusercontent.com/54706543/148750446-e2fb8b41-0790-4adb-86ad-b8422583045f.png)
KN2~Q.png…]()

**Comment by jlaine** [comment]
I don't understand your issue, sorry. Maybe try a discussion to see if anyone understands it.
