### ISSUE TITLE
Very poor video when encoding webcam video with H264.

### ISSUE THREAD

**Issue by relent95** [aiortc/aiortc#618]
When a sender encodes webcam video with H264, the decoded images on a receiver are very poor, as can be seen at the middle browser window in the following screenshot.
![aiortc_issue_618_example](https://user-images.githubusercontent.com/13058392/151338466-e5c97f66-288f-4296-9334-6f7d312af293.png)
The screen images were being fed into the v4l2 lookback device and two local server processes(webcam.py) were sending encoded video streams to the chrome browsers.
You can see an original video source on the left, a poor video on the middle and a normal video on the right.
The right one is from the server run with the fixed **aiortc.codecs.h264.H264Encoder**(It's mentioned at the end of the writing).

I tested with the official webcam.py example, patched like the following to enforce it uses H264 instead of VP8.
(add 3 lines before calling **pc.setRemoteDescription()**)
```
async def offer(request):
    ...
    from aiortc.codecs import get_capabilities
    caps = [c for c in get_capabilities('video').codecs if c.mimeType == 'video/H264']
    pc.addTransceiver('video', direction = 'recvonly').setCodecPreferences(caps)
    await pc.setRemoteDescription(offer)
```
I am using aiortc 1.2.1 and av 8.1.0 on Ubuntu 20.04.

I analyzed the problem.
In **aiortc.codecs.h264.H264Encoder._encode_frame()**, the **frame** argument was returned by an av decoder. So its picture type should be reset before sending to an av encoder.
I found a quick-and-dirty fix like the following.
(add 1 line before calling self.codec.encode())
```
    def _encode_frame(
        ...
        frame.pict_type = av.video.frame.PictureType.NONE
        for package in self.codec.encode(frame):
        ...
```

**Comment by jlaine** [comment]
Could you please elaborate I'm not sure I understand?

**Comment by relent95** [comment]
I will summarize the issue. The current H264Encoder implementation does not reset picture type of input frames before calling av.CodecContext.encode(), which causes a poor video on the receiving peer.
It's a poorly documented feature of the ffmpeg library. See this stackoverflow question.[https://stackoverflow.com/questions/19456745/libavcodec-libx264-do-not-produce-b-frames]

**Comment by jlaine** [comment]
OK would you care to put together a PR?

**Comment by jlaine** [comment]
To make sure I understand, does this issue also affect `MediaRecorder`, which also takes frames end sends them to an encoder?

**Comment by relent95** [comment]
Sorry, I am just a newbie to aiortc project and not prepared to make a PR.
For the question on `MediaRecorder`, this issue will also affect `MediaRecorder` if frames are from the capture devices.
But as far as I know, `MediaRecorder` are used to record frames received from the remote peer and in that case there will be no problem because picture types will be automatically initialized to 0(AV_PICTURE_TYPE_NONE) by PyAV or ffmpeg.

**Comment by relent95** [comment]
I tested your commit and it works flawlessly. Thanks.

**Comment by jlaine** [comment]
Thanks for the feedback @relent95 !

**Comment by HysUnknown** [comment]
@relent95 Hello, I have set --video-codec to video/H264, but it still looks fuzzy on the client side. How do you solve this?
`python webcam.py --video-codec="video/H264"`
display effect：
![1710301920566](https://github.com/aiortc/aiortc/assets/39686680/53c3ae09-0f30-4adb-bca5-6c5557377dde)
