### ISSUE TITLE
Forward raw RTP packets

### ISSUE THREAD

**Issue by xesdiny** [aiortc/aiortc#627]
I want to use aiortc for a client connection to get a UDP stream and forward to a RTP port, if I use RtpConnection, aiortc is going to set up and RTCRtpReceiver which will consume the RTP packets. How can I construct UDP `recv()` raw data while How about forwarding it without decoding it? And obtain and decode the RTP stream through ffmpeg or Gstreamer.

**Comment by xesdiny** [comment]
I am now using `MediaRecorder(('rtp://localhost:1935/myStream.sdp',format='flv'))`, the packet has been unpacked and decoded and restored to frame, and `av` reports an error Data doesn't look like RTP packets, make sure the RTP muxer is used

**Comment by jlaine** [comment]
If all you want to do is forward RTP packets, I think `aiortc` is the wrong project, you might well be able to do this out of the box with the ffmpeg command line. `aiortc` does a lot more than that, it negotiates a network path, establishes an encrypted connection, negotiates codecs, etc.. And yes, it does consume your RTP data.

**Comment by xesdiny** [comment]
I was wondering if I could override the `__run_track()` method in `MediaRecorder` to send the `packet` in `for packet in context.stream.encode(frame):` to a constructed RtpSession?

**Comment by jlaine** [comment]
I don't think MediaRecorder is the way to go. You could however take a look here, as there is some raw RTP packet forwarding going on:

https://github.com/jlaine/aiortc-wpt-demo
