### ISSUE TITLE
fails test_g711.PcmaTest on s390x and ppc64

### ISSUE THREAD

**Issue by jonassmedegaard** [aiortc/aiortc#637]
Building aiortc 1.3.0 or 1.2.1 fails test_g711.PcmaTest on either [s390x](https://buildd.debian.org/status/fetch.php?pkg=python-aiortc&arch=s390x&ver=1.3.0-1&stamp=1643759532&raw=0) or [ppc64](https://buildd.debian.org/status/fetch.php?pkg=python-aiortc&arch=ppc64&ver=1.3.0-1&stamp=1643787551&raw=0) with same error message:
```
____________________________ PcmaTest.test_decoder _____________________________

self = <tests.test_g711.PcmaTest testMethod=test_decoder>

    def test_decoder(self):
        decoder = get_decoder(PCMA_CODEC)
        self.assertTrue(isinstance(decoder, PcmaDecoder))
    
        frames = decoder.decode(JitterFrame(data=b"\xd5" * 160, timestamp=0))
        self.assertEqual(len(frames), 1)
        frame = frames[0]
        self.assertEqual(frame.format.name, "s16")
        self.assertEqual(frame.layout.name, "mono")
>       self.assertEqual(bytes(frame.planes[0]), b"\x08\x00" * 160)
E       AssertionError: b'\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00[1232 chars]\x08' != b'\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08[1232 chars]\x00'

tests/test_g711.py:20: AssertionError
=========================== short test summary info ============================
FAILED tests/test_g711.py::PcmaTest::test_decoder - AssertionError: b'\x00\x0...
============= 1 failed, 361 passed, 69 skipped in 94.08s (0:01:34) =============
E: pybuild pybuild:367: test: plugin distutils failed with: exit code=1: cd /<<PKGBUILDDIR>>/.pybuild/cpython3_3.9/build; python3.9 -m pytest  --timeout=30
dh_auto_test: error: pybuild --test --test-pytest -i python{version} -p "3.10 3.9" returned exit code 13
```

Same error occurred for release 1.2.1 (for [ppc64)[https://buildd.debian.org/status/fetch.php?pkg=python-aiortc&arch=ppc64&ver=1.2.1-3&stamp=1641153363&raw=0) and [s390x](https://buildd.debian.org/status/fetch.php?pkg=python-aiortc&arch=s390x&ver=1.2.1-3&stamp=1639094930&raw=0))

Perhaps an endian issue?

**Comment by jlaine** [comment]
Hi @jonassmedegaard! That does look very much like an endianness issue, the bytes seem to be swapped..

**Comment by jlaine** [comment]
Hi @jonassmedegaard! I am now convinced the code is correct and the test is wrong, so I'm going to try and put together a patch for you to try out.

**Comment by jonassmedegaard** [comment]
hit me! :-D

**Comment by jonassmedegaard** [comment]
Success on ppc64 so far - not yet built for s390x: https://buildd.debian.org/status/package.php?p=python-aiortc&suite=sid
