### ISSUE TITLE
MediaStreamTrack, recv running in parallel 

### ISSUE THREAD

**Issue by JoeyChuuichi** [aiortc/aiortc#639]
I am currently working on customizing the example code [[here]](https://github.com/aiortc/aiortc/blob/main/examples/server/server.py). In particular, my project will collect video streams at the frontend and do "transforms" similar to this example code but using deep learning architecture. It works relatively ok now but there is a big lagging issue. 

By running this example code without any transformation, video fps is ~30, which I believe refers to the property of my camera. And my deep learning framework can run in around ~15 fps. So I think the "recv" function in the example tries to process **every** frame sent by the frontend and it accumulates the lagging effects. 

I plan to solve this issue by distributing the computation load to multiple GPUs on the server. But it is not quite clear to me how to do it because I cannot find documents about how this "recv" function is called (maybe in the class of "MediaStreamTrack"(https://aiortc.readthedocs.io/en/latest/api.html#media)?) 

I guess we can solve this problem according to this pipeline:
- first it detects which GPU is available
- then send the frame from ```frame = await self.track.recv()``` to this corresponding GPU
- while it is computing the backend then receives new frame and assign this task to another GPU.

The problem is that I cannot do the execution of "recv" in parallel. The current code seems to be one-thread processing, i.e., it needs to finish the whole "transform" process and then recall this function again.

Is there any approach so that we can modify the execution of "recv" so that we can do it in parallel?

**Comment by jlaine** [comment]
For threading: just run whatever costly code you have using `run_in_executor` : https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor

However that won't change the problem that you might not be able to process all the frames. In that case, just drop every other incoming frame, which can be as easy as calling `recv()` twice on your incoming frames.

**Comment by opusviz** [comment]
> For threading: just run whatever costly code you have using `run_in_executor` : https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor
> 
> However that won't change the problem that you might not be able to process all the frames. In that case, just drop every other incoming frame, which can be as easy as calling `recv()` twice on your incoming frames.

Thank you
