### ISSUE TITLE
Lower fps mediaplayer aiortc

### ISSUE THREAD

**Issue by MiMoody** [aiortc/aiortc#643]
hello, please tell me how can I lower the fps when streaming a video file from webcam.py to the server.  I tried to use the framerate parameter of the MediaPlayer class, but it didn't work (((

**Comment by MiMoody** [comment]
@jlaine file 
![image](https://user-images.githubusercontent.com/57176330/153798749-60d92c2f-3716-4e8e-8512-a5e7062a25e0.png)

**Comment by jlaine** [comment]
Ok then this makes no sense, the frame rate is determined by your source file.
