### ISSUE TITLE
The remote web could not see  the video if use the h264_omx to encoder the video frame ,but it works while using the libx264

### ISSUE THREAD

**Issue by lxqiong** [aiortc/aiortc#644]
It was happened in examples janus.py 
The remote web could not see  the video if use the h264_omx to encoder the video frame 
But it works while is using the libx264 to encode the video frame.
the issue is no sps

**Comment by jlaine** [comment]
What device is this on?

**Comment by lxqiong** [comment]
pi raspberry

**Comment by rprata** [comment]
@lxqiong Please, what are you doing? Please, tell me more information about your test in raspberry to help you.

**Comment by lxqiong** [comment]
> It was happened in examples janus.py
> The remote web could not see the video if use the h264_omx to encoder the video frame
> But it works while is using the libx264 to encode the video frame.
> the issue is no sps

**Comment by rprata** [comment]
Try to encode video using h264_omx in other device (for example in your pc)?
