### ISSUE TITLE
Runtime error: "Event loop closed" on pc.setRemoteDescription(obj) when client side receives a web-RTC answer.

### ISSUE THREAD

**Issue by ronenc** [aiortc/aiortc#646]
This is an aiortc issue and is reproduceable.
I'm using the aiortc examples with socket.io transport.
Ice connection is always 'checking' never completed.
It works fine with the client.js as the client, but not when connected via a signaling socket.io server.

**Comment by ronenc** [comment]
![image](https://user-images.githubusercontent.com/10868269/154829409-e6dacd95-73a1-498e-a966-eeeed98a0e8e.png)

**Comment by jlaine** [comment]
I don't recognize the code you've posted, it looks like this is your own custom code..

**Comment by ronenc** [comment]
Sorry for that.
I'm using mine signaling server. to of course I changed the examples code to handle the messaging to the signaling server.
But other than that I'm using the webcam.py example as one peer and the videostream cli.py as the other peer as close as possible to the origin, all 3 work on a local pc.
I manage to use the client.js and see video when working with the webcam.py as the second peer (with the modified code).
No matter what I try, I cannot pass the candidate check WAITING state. I can see it on both peers.
And also sometimes I get the 'Event loop is close' error message when I try to set the answer remote description.

Please if you can guide me with this.



The peers

**Comment by jlaine** [comment]
I really cannot answer that, it depends too much on how you wrote your main loop. Do you get the same error on the examples provided with aiortc?

**Comment by ronenc** [comment]
The example provided by aiortc using a javascript client. It works fine.
I've managed to run all samples and see the video using the client.js peer.

Do you have an example of a client, in python or any other language  that manage to establish an ice connection through a signaling server, except the client.js sample?
Since the client.js is working, it looks like the issue is on the python client side.
Ice candidate do exchange between my peers but the ice connection is not established.

**Comment by ronenc** [comment]
There is a difference between the client.js implementation and the python cli.py:
client.js starts with:
function negotiate() {
    pc.addTransceiver('video', {direction: 'recvonly'});
    pc.addTransceiver('audio', {direction: 'recvonly'});
    return pc.createOffer().then(function(offer) {

cli.py starts with:
    add_tracks()
        await pc.setLocalDescription(await pc.createOffer())

Which method should be used?

**Comment by pavan7parekh** [comment]
Hi @ronenc 

I am getting same error "Event loop closed" on setRemoteDescription(answer) 

Can you please help me?
