### ISSUE TITLE
Sample Websocket

### ISSUE THREAD

**Issue by Digital-Thor** [aiortc/aiortc#679]
I'm trying to understand the [filexfer.py](https://github.com/aiortc/aiortc/tree/main/examples/datachannel-filexfer) websocket example so that I can generalize it to use a commercial websocket service (such as [Pusher Channels](https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol/#channel-events-pusher-channels-greater-client)).  Based on `filexfer.py --help`, I believe the transfer commands for using a localhost websocket are of the form:
```
python3 filexfer.py -v -s tcp-socket --signaling-host localhost --signaling-port 8765 send README.md
python3 filexfer.py -v -s tcp-socket --signaling-host localhost --signaling-port 8765 receive rx.md
```
Is there recommended websocket server and config (for linux) that can be used as a localhost, so that the above command syntax works?  (For instance this one: https://simple-websocket.readthedocs.io/en/latest/intro.html.  Open to any other approach.)

Best, 
-Thor

**Comment by jlaine** [comment]
Hi Thor, there is currently no WebSocket signalling method in the code, the commands you sent will just establish a raw TCP socket. You are welcome to expand `aiortc/contrib/signaling.py` to add such a method and contribute it as a PR :)

**Comment by Digital-Thor** [comment]
Thanks Jeremy.  So are we talking about simply opening a tcp socket, as in: 
`sudo firewall-cmd --add-port=8765/tcp` ?

**Comment by jlaine** [comment]
Ah. No this is not about firewalling, it's a question of which protocol is being "spoken". TCP provides a raw stream of ordered / error corrected bytes. WebSockets are a more complicated protocol built on top of TCP. If these notions don't ring a bell, putting together a pull request to implement this may be a bit of a challenge.

**Comment by Digital-Thor** [comment]
Okay.  I have seen this websocket approach, https://github.com/ryogrid/aiortc-dc/blob/c24ab64f9a7be66e22d8050fc01f376e55e6f24b/aiortcdc/contrib/signaling.py#L180 but unfortunately it didn't work for me.  No worries.  I'll just use the copy-and-paste approach for now.
