### ISSUE TITLE
Memory leaks from AudioFrame lines in G.711/OPUS codecs 

### ISSUE THREAD

**Issue by W3AXL** [aiortc/aiortc#680]
I noticed what appeared to be a memory leak occurring in my script during execution. Using tracemalloc I was able to narrow it down to the AIORTC audio codec being used. In my project I use either OPUS or G.711, and the issue appears to be the same in both cases.

Here's outputs from tracemalloc snapshots for only a few minutes of runtime. Both codecs were already using upwards of 25 MB in this short timespan. Over a few hours, memory usage can get upwards of 1GB or more. 

**G.711:**
```
Top Memory Users:
./lib/python3.9/site-packages/aiortc/codecs/g711.py:25: size=24.9 MiB, count=479536, average=54 B
...
```

**OPUS:**
```
Top Memory Users:
./lib/python3.9/site-packages/aiortc/codecs/opus.py:29: size=26.1 MiB, count=540716, average=51 B
...
```

Both lines called out in the above traces are creations of `AudioFrame` objects, so I'm guessing something isn't getting disposed of properly when the frames are eventually used.

**Comment by jlaine** [comment]
Hi! Can you be more specific about how you are testing as there are many potential code paths involved here? Can I use one of the examples provided with aiortc to reproduce and if so could you detail the scenario?

**Comment by jlaine** [comment]
Oh and the most obvious thing you want to check is that you are actually consuming any audio frames you receive, otherwise you're going to build up a huge queue of AudioFrame! All the examples do this, even if it's just hooking up a MediaBlackhole which discards the frames.

**Comment by W3AXL** [comment]
I'm trying to get the server example working to test with, but it needs to be modified to support SSL connections since `getUserMedia` can't be called from a non-secure webpage anymore.

In the meantime, I may have discovered I'm actually not consuming all the tracks that I'm sending the server. Your point about `MediaBlackhole` made me go back through my code. Could be a non-issue, which in that case it's egg on my face.

Standby.

**Comment by W3AXL** [comment]
Okay, this one is my bad.

I was getting multiple tracks from the web client but only attaching the first one to any output. The other two I was just returning the `ontrack` callback without doing anything. Adding & attaching `MediaBlackhole`s to these tracks seems to have solved the memory issue.

**Comment by jlaine** [comment]
The server example *should* support , for precisely the reason you mention. If you find it needs changes please feel free to submit a PR with any required changes 

Regarding consuming the media tracks, this is not the first time it comes up so I'm wondering:

- what would be a good place to mention this in the docs?
- should we impose a maximum queue length and drop frames if a backlog builds up? Emit a warning?

Any PR to improve the experience of first time users is welcome! Anyway thanks for reporting back.
