### ISSUE TITLE
Using safari to publish webcam stream , with default codecs disconnects after some time.

### ISSUE THREAD

**Issue by kbtoch** [aiortc/aiortc#682]
I am using the examples/server with opencv and mediapipe for virtual background in live webrtc stream to aws ubuntu t2 micro instance. While using safari browser the live webcam streaming works but it disconnects after some time

Below is the logs generated

[libx264 @ 0x7f126c5df680] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7f126c5df680] profile Constrained Baseline, level 3.1, 4:2:0, 8-bit
[h264 @ 0x7f1280000e00] No start code is found.
[h264 @ 0x7f1280000e00] Error splitting the input into NAL units.
WARNING:aiortc.codecs.h264:H264Decoder() failed to decode, skipping package: [Errno 1094995529] Invalid data found when processing input
[h264 @ 0x7f1280000e00] No start code is found.
[h264 @ 0x7f1280000e00] Error splitting the input into NAL units.
WARNING:aiortc.codecs.h264:H264Decoder() failed to decode, skipping package: [Errno 1094995529] Invalid data found when processing input

**Comment by jlaine** [comment]
I have nothing to go on here, other than a supposition you are feeding invalid data into the decoder..
