### ISSUE TITLE
Renegotiation: invalid remapping of generic header extension mappings (extmap)

### ISSUE THREAD

**Issue by aliebald** [aiortc/aiortc#686]
# Abstract

When renegotiating using createOffer, the generic header extension mappings get remapped with already existing IDs.

And:

Track ends unexpected on renegotiation.

# What I'm trying to do

I'm trying to add renegotiation to a simple SFU server using aiortc with a single web / typescript client. This client sends a video stream to the server, which simply sends the same stream back. The setup is similar to the [server](https://github.com/aiortc/aiortc/tree/main/examples/server) example.

My original goal was to have multiple clients, but I simplified it for this issue and debugging purposes. A full minimal example can be found [here](https://github.com/aliebald/aiortc-issue-686).

When trying to renegotiate, the following JavaScript exception is thrown when `setRemoteDescription` is called on the client.

    Uncaught (in promise) DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set remote video description send parameters for m-section with mid='0'.

## Procedure

1. Web Client connects to aiortc server (sending initial offer [[1]](#Reference) via fetch, waiting for response)
2. Later, a renegotiation is manually started:
3. Renegotiation started by the server:
    - [Server side] Call createOffer on RTCPeerConnection
    - [Server side] Call SetLocalDescription on RTCPeerConnection with the above offer
    - [Server side] Send the offer [[2]](#Reference) to the client using the data channel
    - [Client side] Call setRemoteDescription on the peer connection with the above offer [Exception from above is thrown here]
    - [Client side] Create answer and set local description
    - [Client side] Send new local description to server
    - [Server side] Set new remote description

In case the client starts the renegotiation, the above error does not occur.

# Invalid remapping of already negotiated extensions

Looking at the internal WebRTC logs of Chrome, the problem seems to be caused by a `extmap` remapping.
Chrome internal WebRTC log:

    [19048:12108:0330/171900.878:ERROR:webrtc_media_engine.cc(126)] Extension negotation failure: urn:ietf:params:rtp-hdrext:sdes:mid was identified by 9 but is proposed changed to 1
    [19048:11824:0330/171900.878:ERROR:sdp_offer_answer.cc(761)] Failed to set remote offer sdp: Failed to set remote video description send parameters for m-section with mid='0'.

As you can see in [[1]](#Reference) and [[2]](#Reference), the generic header extension mappings (`extmap`) either get removed or remapped with already existing IDs.
According to the following two sources, this seems to be in violation with the WebRTC standard:

The following comment can found in the source code of the Chrome WebRTC implementation, next to the origin of the exception (`\src\media\engine\webrtc_media_engine.cc`, `ValidateRtpExtensions()`, starting at line 98):

    // Validate the extension list against the already negotiated extensions.
    // Re-registering is OK, re-mapping (either same URL at new ID or same
    // ID used with new URL) is an illegal remap.

In addition to this, section 6 page 10 of [RFC5285](https://datatracker.ietf.org/doc/html/rfc5285) seems to forbid remapping:

    Identifiers values in the valid range MUST NOT be altered (remapped).

The aiortc [documentation](https://aiortc.readthedocs.io/en/latest/api.html?highlight=createOffer#aiortc.RTCPeerConnection.createOffer) for createOffer reads _`Create an SDP offer for the purpose of starting a new WebRTC connection to a remote peer`_. So It could be that createOffer is not intended for renegotiation (only for a _new connection_), however I did not find any alternative and `tests/test_rtcpeerconnection.py` -> `test_setRemoteDescription_media_datachannel_bundled` (starting line 4827) uses the same approach, with createOffer, as I do.

# Workaround

It is possible to avoid the above error by removing all extmap mappings in the initial offer in the client and adding only the two mappings aiortc uses with the exact IDs (before setLocalDescription()).

This might not be a good solution, but avoids the error and allows for further testing.

# Second issue: Track ends on renegotiation

**Note:** This is getting long and the following could be a second issue or unrelated question. However, I cannot rule out any connection, so I'm including it in this issue.

With the above workaround (or when the renegotiation is started by the client), every time a renegotiation takes place (either initiated by the client or the server), the track from the client to the server is closed / emits a `ended` event. This means a renegotiation would be required to add the track again, which would also stop it.

Looking at chromes webrtc-internals, the `RTCMediaStreamTrack_sender` stops for a millisecond on renegotiation, but keeps sending afterwards. The `RTCMediaStreamTrack_receiver` stops receiving new frames but is not closed.

I have also tested my frontend with a second backend implementation using NodeJs and [wrtc](https://www.npmjs.com/package/wrtc) to see if the frontend or my approach might be the problem. Using this alternative backend and the exact same frontend, renegotiation was no problem and no tracks ended unexpectedly on renegotiation.

# Conclusion

I would very much appreciate help with the above issues to implement a proper renegotiation with a web client. I have been trying to get an aiortc server going for a while now.

# Reference

<details>
<summary>[1] Initial sdp send client</summary>
<br>

    v=0
    o=- 5484545361404245694 2 IN IP4 127.0.0.1
    s=-
    t=0 0
    a=group:BUNDLE 0 1
    a=extmap-allow-mixed
    a=msid-semantic: WMS SjL4cswFfJLm45X8L4HrEICPScgQ43ft1rEz
    m=video 64224 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 121 125 107 108 109 124 120 123 119 35 36 41 42 114 115 116 117 118
    c=IN IP4 [local ipv4]
    a=rtcp:9 IN IP4 0.0.0.0
    [a=candidate..., ice candidates]
    a=ice-ufrag:t+5R
    a=ice-pwd:tJ3ibTxelpbMmSPPle6paPNW
    a=ice-options:trickle
    a=fingerprint:sha-256 [hash]
    a=setup:actpass
    a=mid:0
    a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
    a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
    a=extmap:3 urn:3gpp:video-orientation
    a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
    a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
    a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
    a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
    a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
    a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
    a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
    a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
    a=sendrecv
    a=msid:SjL4cswFfJLm45X8L4HrEICPScgQ43ft1rEz de3f941e-a478-4081-af79-5ff936a4b0b1
    a=rtcp-mux
    a=rtcp-rsize
    a=rtpmap:96 VP8/90000
    a=rtcp-fb:96 goog-remb
    a=rtcp-fb:96 transport-cc
    a=rtcp-fb:96 ccm fir
    a=rtcp-fb:96 nack
    a=rtcp-fb:96 nack pli
    a=rtpmap:97 rtx/90000
    a=fmtp:97 apt=96
    a=rtpmap:98 VP9/90000
    a=rtcp-fb:98 goog-remb
    a=rtcp-fb:98 transport-cc
    a=rtcp-fb:98 ccm fir
    a=rtcp-fb:98 nack
    a=rtcp-fb:98 nack pli
    a=fmtp:98 profile-id=0
    a=rtpmap:99 rtx/90000
    a=fmtp:99 apt=98
    a=rtpmap:100 VP9/90000
    a=rtcp-fb:100 goog-remb
    a=rtcp-fb:100 transport-cc
    a=rtcp-fb:100 ccm fir
    a=rtcp-fb:100 nack
    a=rtcp-fb:100 nack pli
    a=fmtp:100 profile-id=2
    a=rtpmap:101 rtx/90000
    a=fmtp:101 apt=100
    a=rtpmap:127 H264/90000
    a=rtcp-fb:127 goog-remb
    a=rtcp-fb:127 transport-cc
    a=rtcp-fb:127 ccm fir
    a=rtcp-fb:127 nack
    a=rtcp-fb:127 nack pli
    a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
    a=rtpmap:121 rtx/90000
    a=fmtp:121 apt=127
    a=rtpmap:125 H264/90000
    a=rtcp-fb:125 goog-remb
    a=rtcp-fb:125 transport-cc
    a=rtcp-fb:125 ccm fir
    a=rtcp-fb:125 nack
    a=rtcp-fb:125 nack pli
    a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
    a=rtpmap:107 rtx/90000
    a=fmtp:107 apt=125
    a=rtpmap:108 H264/90000
    a=rtcp-fb:108 goog-remb
    a=rtcp-fb:108 transport-cc
    a=rtcp-fb:108 ccm fir
    a=rtcp-fb:108 nack
    a=rtcp-fb:108 nack pli
    a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
    a=rtpmap:109 rtx/90000
    a=fmtp:109 apt=108
    a=rtpmap:124 H264/90000
    a=rtcp-fb:124 goog-remb
    a=rtcp-fb:124 transport-cc
    a=rtcp-fb:124 ccm fir
    a=rtcp-fb:124 nack
    a=rtcp-fb:124 nack pli
    a=fmtp:124 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
    a=rtpmap:120 rtx/90000
    a=fmtp:120 apt=124
    a=rtpmap:123 H264/90000
    a=rtcp-fb:123 goog-remb
    a=rtcp-fb:123 transport-cc
    a=rtcp-fb:123 ccm fir
    a=rtcp-fb:123 nack
    a=rtcp-fb:123 nack pli
    a=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d001f
    a=rtpmap:119 rtx/90000
    a=fmtp:119 apt=123
    a=rtpmap:35 H264/90000
    a=rtcp-fb:35 goog-remb
    a=rtcp-fb:35 transport-cc
    a=rtcp-fb:35 ccm fir
    a=rtcp-fb:35 nack
    a=rtcp-fb:35 nack pli
    a=fmtp:35 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=4d001f
    a=rtpmap:36 rtx/90000
    a=fmtp:36 apt=35
    a=rtpmap:41 AV1/90000
    a=rtcp-fb:41 goog-remb
    a=rtcp-fb:41 transport-cc
    a=rtcp-fb:41 ccm fir
    a=rtcp-fb:41 nack
    a=rtcp-fb:41 nack pli
    a=rtpmap:42 rtx/90000
    a=fmtp:42 apt=41
    a=rtpmap:114 H264/90000
    a=rtcp-fb:114 goog-remb
    a=rtcp-fb:114 transport-cc
    a=rtcp-fb:114 ccm fir
    a=rtcp-fb:114 nack
    a=rtcp-fb:114 nack pli
    a=fmtp:114 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f
    a=rtpmap:115 rtx/90000
    a=fmtp:115 apt=114
    a=rtpmap:116 red/90000
    a=rtpmap:117 rtx/90000
    a=fmtp:117 apt=116
    a=rtpmap:118 ulpfec/90000
    a=ssrc-group:FID 864463700 3980397911
    a=ssrc:864463700 cname:rwD5PXXST/SmcFzm
    a=ssrc:864463700 msid:SjL4cswFfJLm45X8L4HrEICPScgQ43ft1rEz de3f941e-a478-4081-af79-5ff936a4b0b1
    a=ssrc:864463700 mslabel:SjL4cswFfJLm45X8L4HrEICPScgQ43ft1rEz
    a=ssrc:864463700 label:de3f941e-a478-4081-af79-5ff936a4b0b1
    a=ssrc:3980397911 cname:rwD5PXXST/SmcFzm
    a=ssrc:3980397911 msid:SjL4cswFfJLm45X8L4HrEICPScgQ43ft1rEz de3f941e-a478-4081-af79-5ff936a4b0b1
    a=ssrc:3980397911 mslabel:SjL4cswFfJLm45X8L4HrEICPScgQ43ft1rEz
    a=ssrc:3980397911 label:de3f941e-a478-4081-af79-5ff936a4b0b1
    m=application 64228 UDP/DTLS/SCTP webrtc-datachannel
    c=IN IP4 [local ipv4]
    [a=candidate..., ice candidates]
    a=ice-ufrag:t+5R
    a=ice-pwd:tJ3ibTxelpbMmSPPle6paPNW
    a=ice-options:trickle
    a=fingerprint:sha-256 [hash]
    a=setup:actpass
    a=mid:1
    a=sctp-port:5000
    a=max-message-size:262144

    Some information was replaced by short descriptors inside brackets []

</details>
<br>
<details>
<summary>[2] Renegotiation sdp send by server</summary>
<br>

    v=0
    o=- 3857653574 3857653574 IN IP4 0.0.0.0
    s=-
    t=0 0
    a=group:BUNDLE 0 1 2
    a=msid-semantic:WMS *
    m=video 63392 UDP/TLS/RTP/SAVPF 97 98 99 100 101 102
    c=IN IP4 [local ipv4]
    a=sendrecv
    a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
    a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
    a=mid:0
    a=msid:1e8072f8-18f9-425e-9429-0f27e956ef4f 1c1ca013-148e-4109-9d87-4ad4c1397aa9
    a=rtcp:9 IN IP4 0.0.0.0
    a=rtcp-mux
    a=ssrc-group:FID 2844999704 304029223
    a=ssrc:2844999704 cname:a51697fd-9644-40f8-9370-39b7dd111fc0
    a=ssrc:304029223 cname:a51697fd-9644-40f8-9370-39b7dd111fc0
    a=rtpmap:97 VP8/90000
    a=rtcp-fb:97 nack
    a=rtcp-fb:97 nack pli
    a=rtcp-fb:97 goog-remb
    a=rtpmap:98 rtx/90000
    a=fmtp:98 apt=97
    a=rtpmap:99 H264/90000
    a=rtcp-fb:99 nack
    a=rtcp-fb:99 nack pli
    a=rtcp-fb:99 goog-remb
    a=fmtp:99 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42001f
    a=rtpmap:100 rtx/90000
    a=fmtp:100 apt=99
    a=rtpmap:101 H264/90000
    a=rtcp-fb:101 nack
    a=rtcp-fb:101 nack pli
    a=rtcp-fb:101 goog-remb
    a=fmtp:101 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42e01f
    a=rtpmap:102 rtx/90000
    a=fmtp:102 apt=101
    [a=candidate..., ice candidates]
    a=ice-ufrag:Ty1K
    a=ice-pwd:EJhfCCvEZrunSR8OdVvHxv
    a=fingerprint:sha-256 [hash]
    a=setup:actpass
    m=application 63392 UDP/DTLS/SCTP webrtc-datachannel
    c=IN IP4 [local ipv4]
    a=mid:1
    a=sctp-port:5000
    a=max-message-size:65536
    [a=candidate..., ice candidates]
    a=ice-ufrag:Ty1K
    a=ice-pwd:EJhfCCvEZrunSR8OdVvHxv
    a=fingerprint:sha-256 [hash]
    a=setup:actpass
    m=video 58804 UDP/TLS/RTP/SAVPF 97 98 99 100 101 102
    c=IN IP4 [local ipv4]
    a=sendrecv
    a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
    a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
    a=mid:2
    a=msid:1e8072f8-18f9-425e-9429-0f27e956ef4f a66a1d70-3813-405e-8fce-914c9ec6d487
    a=rtcp:9 IN IP4 0.0.0.0
    a=rtcp-mux
    a=ssrc-group:FID 3406800535 2442756233
    a=ssrc:3406800535 cname:a51697fd-9644-40f8-9370-39b7dd111fc0
    a=ssrc:2442756233 cname:a51697fd-9644-40f8-9370-39b7dd111fc0
    a=rtpmap:97 VP8/90000
    a=rtcp-fb:97 nack
    a=rtcp-fb:97 nack pli
    a=rtcp-fb:97 goog-remb
    a=rtpmap:98 rtx/90000
    a=fmtp:98 apt=97
    a=rtpmap:99 H264/90000
    a=rtcp-fb:99 nack
    a=rtcp-fb:99 nack pli
    a=rtcp-fb:99 goog-remb
    a=fmtp:99 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42001f
    a=rtpmap:100 rtx/90000
    a=fmtp:100 apt=99
    a=rtpmap:101 H264/90000
    a=rtcp-fb:101 nack
    a=rtcp-fb:101 nack pli
    a=rtcp-fb:101 goog-remb
    a=fmtp:101 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42e01f
    a=rtpmap:102 rtx/90000
    a=fmtp:102 apt=101
    [a=candidate..., ice candidates]
    a=ice-ufrag:Mi9D
    a=ice-pwd:G0DPsntsBD8zBx2MWWDFqu
    a=fingerprint:sha-256 [hash]
    a=setup:actpass

    Some information was replaced by short descriptors inside brackets []

</details>
<br>
<details open>
<summary>[3] Minimal example</summary>

This example was moved to [this repo](https://github.com/aliebald/aiortc-issue-686). It is now a complete example including a basic frontend.

</details>

## Software versions

-   OS: Windows 10
-   Chrome: Version 100.0.4896.60 (Official Build) (64-Bit)
-   Python: 3.10.2
-   aiortc: 1.3.1

# Edits 

__Edit 1:__
Created a full minimal example with front and backend for easy reproduction. It can be found [here](https://github.com/aliebald/aiortc-issue-686). The old backend code was removed, a slightly improved version can be found in the new example.

**Comment by jlaine** [comment]
Let's re-open this, the point is valid.

**Comment by jlaine** [comment]
Still relevant!
