### ISSUE TITLE
onIceCandidate support！！

### ISSUE THREAD

**Issue by diybl** [aiortc/aiortc#693]
hope add this event function

on one candidate address has been got, then call this function

**Comment by diybl** [comment]
`pc.onIceCandidate = (candidate) async {
      if (candidate == null) {
        print('onIceCandidate: complete!');
        return;
      }
      // This delay is needed to allow enough time to try an ICE candidate
      // before skipping to the next one. 1 second is just an heuristic value
      // and should be thoroughly tested in your own environment.
      await Future.delayed(
          const Duration(seconds: 1),
          () => _send('candidate', {
                'to': peerId,
                'from': _selfId,
                'candidate': {
                  'sdpMLineIndex': candidate.sdpMLineIndex,
                  'sdpMid': candidate.sdpMid,
                  'candidate': candidate.candidate,
                },
                'session_id': sessionId,
              }));
    };`


this is flutter-webrtc demo

**Comment by jlaine** [comment]
aiortc doesn't do ICE trickle, all candidates are gathered at once so there is no "icecandidate" event

**Comment by aijyo** [comment]
> aiortc doesn't do ICE trickle, all candidates are gathered at once so there is no "icecandidate" event

I want to use aiortc for webrtc client development, but I found that this library does not support the icecandidate event, but our signaling server requires the client to upload the local ice candidate to the server. If aiortc is used, is there any way to obtain this icecandidate?
