### ISSUE TITLE
peer connections keeps waiting

### ISSUE THREAD

**Issue by opusviz** [aiortc/aiortc#697]
I am testing server.py example. it works fine at localhost. But peer connection keeps waiting when I move this to online. I am using ubuntu, nginx and using proxy so that my https://domain.com is sent to 127.0.0.1:8080. I have attached the response at the sever which shows status of peer connection. I could not find a way to add screenshot. It start with state.forzen, then state.waitng , state.waiting and then state.failed. IceFailed.
I am using ssl at server which is accepted by chrome.

**Comment by jlaine** [comment]
This looks like a problem with your local setup, not aiortc itself. Can you check whether the following demo works:

https://webrtc.aiortc.org/

**Comment by opusviz** [comment]
Thank you for your response. Yes when I click on this link, it works well in my browser. 
Do I need to allow any port for stun server from my web server firewall?

**Comment by jlaine** [comment]
The demo server I linked:

- does not have run its own STUN server, it uses aiortc's default configuration which is to use the Google one
- allows inbound UDP traffic on ports 1024 - 65535, both for IPv4 and IPv6

**Comment by opusviz** [comment]
Thank you for quick response. I am also using google stun server as shown in this example. But I have not allowed any ports. Do I need to allow these two ports from my server?

**Comment by jlaine** [comment]
> Thank you for quick response. I am also using google stun server as shown in this example. But I have not allowed any ports. Do I need to allow these two ports from my server?

Yes you need to open the UDP ports, otherwise how would the traffic reach you? You cannot simply count on "connection tracking" to open the ports for you, otherwise connections to NAT'd clients are likely to fail.

**Comment by opusviz** [comment]
Thank you.  I have opened these two ports.  I am still getting the same problem. It opens the camera in browser but server keeps waiting.

**Comment by jlaine** [comment]
OK well I'm sorry you're going to have to chase this one down yourself, I cannot provide support for "how to host your aiortc-based solution". The demo I provided makes me fairly confident this is a hosting/configuration issue and not a bug in aiortc.

**Comment by opusviz** [comment]
Thank you.

**Comment by opusviz** [comment]
It is working now. I was confused about the ports. I had allowed only these two ports. I did not realize i was supposed to allow this range. i allowed incoming traffic at all ports and now it is working. Thank you.

**Comment by jlaine** [comment]
Ah sorry my message did not clearly indicate it was a port range!
