### ISSUE TITLE
webcam example- can not find the device with name integrated camera

### ISSUE THREAD

**Issue by opusviz** [aiortc/aiortc#700]
Server example is working on my localhost. But webcam example gives the error  - can not find the device integrated camera.
How can I fix this?

**Comment by jlaine** [comment]
You most probably need to change the arguments passed to MediaPlayer. Check the FFmpeg devices docs to see possible arguments for your specific platform.

Also please use discussions when asking for help, so that issues can stay focused on actual bugs.
