### ISSUE TITLE
Webcam.py --video-codec video/H264 --play-without-decoding weird behavior

### ISSUE THREAD

**Issue by unitw** [aiortc/aiortc#712]
I encountered a strange behavior regarding the standard webcam.py example.
Im using the newest feature " --video-codec video/H264 --play-without-decoding" on my raspberry pi.
If im connecting from any client over the local network (android/ios/chome/firefox) it works the first time, after that only chrome on my windows machine works but the image quality gets signficantly worse than the first connect.
Steps to reproduce:
1. start python webcam.py --video-codec video/H264 --play-without-decoding
2.  connect from firefox/ios/android browser with start
3.  press stop button
4.  refresh and press start again

I verified ice gathering is working and even the h264_omx encoder is starting to run but no feed is shown on the client side.
Only Chrome is working and is displaying a much blurrier image .

**Comment by jlaine** [comment]
@rprata this one's for you :)

**Comment by rprata** [comment]
[@unitw could you tell me more information about your test? I don't understand this:
```
If im connecting from any client over the local network (android/ios/chome/firefox) it works the first time, after that only chrome on my windows machine works but the image quality gets signficantly worse than the first connect.
``` 

It works in all browser fine, except in Chrome? 

Please, tell me how to you generate h264 streaming too.

**Comment by rprata** [comment]
@unitw , removing `--play-without-decoding` the result is the same or not?

**Comment by unitw** [comment]
`--play-without-decoding` makes the whole system unresponsive because of cpu usages over 100%

**Comment by rprata** [comment]
Please, could me send video information profile (codec, pix_fmt, timestamp...) to check it? I does not have a PI Kamera.

**Comment by unitw** [comment]
i use the  following commands to configure the camera:
```
v4l2-ctl -d /dev/video0 -c video_bitrate_mode=1,video_bitrate=2000000,h264_profile=0,h264_i_frame_period=60
v4l2-ctl -d /dev/video0 -v pixelformat=H264,width=640,height=480
v4l2-ctl -d /dev/video0 -p 30
```

**Comment by rprata** [comment]
You could configure pixelformat to `yuv420p`?

**Comment by unitw** [comment]
i tried to configure ffmpeg to do the job with:
`options = {"framerate": "30", "video_size": "640x480","pix_fmt": "YUV420P"}`
but it seems to have no effect.

**Comment by rprata** [comment]
Hi,
Is it possible to use test this codec option in ffmpeg: libx264? `-c:v libx264 -vcodec copy`. I could not reproduce the same problem. 

It can be related with this issue: https://github.com/aiortc/aiortc/issues/644

**Comment by unitw** [comment]
I ended up using  @jpiat 's fork with the EncodedMediaStreamTrack and [ PiH264StreamTrack](https://github.com/jpiat/aiortc/blob/main/examples/picamera/pitrack.py). The only problem with that approach was that it was limited to only one concurrent mediatrack with for i wrote a picamera stream relay myself. 
So the issue still exists but it was easier to ignore pyav and all the other stuff and sending a h264 stream via picam and the EncodedMediaStreamTrack directly.
Maybe incorporate some of this forks changes to make this kind of work around easier?

**Comment by rprata** [comment]
I could you help to work in new approach, however I don't have a PiKamera. If you open a PR related with this, I can review for you.

**Comment by rprata** [comment]
@unitw 

I googled your problem and found it: https://community.octoprint.org/t/low-latency-h264-streaming-support-w-webrtc/36996/36?page=2

@johnboiles made some [configurations](https://community.octoprint.org/t/low-latency-h264-streaming-support-w-webrtc/36996/37) to work with PI Camera:

```
v4l2-ctl -d /dev/video0 -v pixelformat=H264,width=1920,height=1080
v4l2-ctl -d /dev/video0 -c video_bitrate_mode=1,video_bitrate=4000000,h264_profile=4,h264_i_frame_period=60,h264_level=11,repeat_sequence_header=1
v4l2-ctl -d /dev/video0 -p 30

/home/pi/aiortc/venv/bin/python /home/pi/aiortc/examples/webcam/webcam.py --play-without-decoding --preferred-codec=video/H264 --video-options='{"video_size": "1920x1080", "framerate": "30", "input_format": "h264", "pixelformat": "H264"}' 
```

Please, could test it in your side?

**Comment by unitw** [comment]
> I googled your problem and found it: https://community.octoprint.org/t/low-latency-h264-streaming-support-w-webrtc/36996/36?page=2

before i opened this issue i already tried this approach. it worked with the fork from @johnboiles, but unreliable with the newest main-branch. Also the cpu usage overall was still quiet high.
I'm gonne open an pr with an minimal example for a raspberry pi w.

**Comment by rprata** [comment]
@unitw 

For used in `octoprint` is https://github.com/aiortc/aiortc/pull/559 first version before many revision. I think that something was lost. 

Please, I notice that a specific line for webcam was lost in `demux` worker. Please could test in your side this branch? 
https://github.com/aiortc/aiortc/pull/717

**Comment by unitw** [comment]
ill test and report back
