### ISSUE TITLE
RTCPeerConnection LegacySdp=True by default

### ISSUE THREAD

**Issue by brubbel** [aiortc/aiortc#716]
Short question:
Is there a valid reason why _sctpLegacySdp is active by default?
I suppose most browsers support the newer format since 4 years ago.

https://github.com/aiortc/aiortc/blob/713fb644b95328f8ec1ac2cbb54def0424cc6645/src/aiortc/rtcpeerconnection.py#L308

Cfr:
https://blog.mozilla.org/webrtc/how-to-avoid-data-channel-breaking/

**Comment by jlaine** [comment]
Because that line of code dates back to 2018 when support for the newer format was not ubiquitous?

**Comment by brubbel** [comment]
No specific reason to not use the newer SDP format, thanks!

**Comment by jlaine** [comment]
I don't understand why you closed this issue, I do think you have a valid point here.

Question: what's the current state of support for the "new" SDP format? If all browsers support it and offer it when they are the initiator, maybe it's time to simply drop support for the "old" format?

**Comment by rprata** [comment]
@jlaine, is interesting to update readme with `aiortc` browser compatibility?

**Comment by brubbel** [comment]
> I don't understand why you closed this issue, I do think you have a valid point here.
Not confident enough in webrtc to request code changes (yet :)
