### ISSUE TITLE
janus example bogusly calls webcam.py

### ISSUE THREAD

**Issue by jonassmedegaard** [aiortc/aiortc#725]
Recent git commit 713fb64 introduced option `--play-without-decoding` to example script `janus.py`, and added an example commandline to `examples/janus/README.rst`.

...but that commandline calls `webcam.py` (not `janus-py`).

**Comment by rprata** [comment]
Thank you. 

This PR (https://github.com/aiortc/aiortc/pull/726) will fix it.

**Comment by jlaine** [comment]
Thank @jonassmedegaard fixed by @rprata's PR
