### ISSUE TITLE
Why is aiortc trying to connect out to DoD servers?

### ISSUE THREAD

**Issue by davidtbo** [aiortc/aiortc#727]
Hello,

Can you explain why aiortc is trying to connect out to 11.112.132.188? Whois for that IP address returns that it's registered to the US Department of Defense.

This call Is my intended call and it succeeds:
INFO:aioice.ice:Connection(2) Check CandidatePair(('192.168.X.Y', 62406) -> ('192.168.X.Y', 55079)) State.IN_PROGRESS -> State.SUCCEEDED

This call is not one that I made:
INFO:aioice.ice:Connection(2) Check CandidatePair(('11.112.132.188', 61578) -> ('192.168.X.Y', 55079)) State.WAITING -> State.FAILED

I should note that this is happening in development code on my laptop, so it's not some other legitimate traffic hitting this server that's unrelated to my development. I should also note it happens every time I connect.

I searched your code for that IP and I didn't find anything directly, but I'm a bit concerned about a backdoor of some sort. Please advise.

Best,
Dave

**Comment by opusviz** [comment]
I am following this thread.

**Comment by lgrahl** [comment]
For starters, I'd suggest to diff your installed aioice and aiortc version against the tagged release code on GitHub. If there is no difference, we'd need more info on where this IP is picked up (log context).

**Comment by atomdog** [comment]
lol

**Comment by jlaine** [comment]
The left-hand of the candidate pair is *your* IP address, so you're not connecting *to* `11.112.132.188` but *from* `11.112.132.188`?

**Comment by davidtbo** [comment]
No, I was not.

**Comment by jlaine** [comment]
Either you *are* connecting `11.112.132.188` or your STUN server is telling you that you are:

https://github.com/aiortc/aioice/blob/f08956b4d92f479bc04c7a04576d5d08f102a790/src/aioice/ice.py#L146-L147
