### ISSUE TITLE
Does not work on Raspberry Pi anymore. Any plan to upgrade for the latest Raspberry Pi operating system?

### ISSUE THREAD

**Issue by DevelopDaily** [aiortc/aiortc#743]
Raspberry Pi has upgraded its operating system to Pi OS.

The `webcam `example works very well on the Raspberry Pi 4B with Pi OS if the "Legacy Camera" is enabled by hand. But, the Raspberry Pi will eventually discontinue the "Legacy Camera" option. So, has anybody planned to upgrade the `aiortc`?

One of the major changes of the Pi OS is to start to use `libcamera`, which is well documented here https://www.raspberrypi.com/documentation/accessories/camera.html

**Comment by rprata** [comment]
Is it possible to use this: https://www.raspberrypi.com/documentation/accessories/camera.html#rtsp

In this case we will start with `libcamera` and `vlc` a rtsp server h264. After that you can open this with option `--from <rtsp-url>`.

I believe that it can help you.

**Comment by DevelopDaily** [comment]
> Is it possible to use this: https://www.raspberrypi.com/documentation/accessories/camera.html#rtsp

Yes.

Could you please elaborate on the `--from` option? I cannot find it in the code. Did you mean `--play-from`?

Thanks.

**Comment by rprata** [comment]
Sorry. I mistake in my last answer:

1 - Run this command to start rtsp server: `libcamera-vid -t 0 --inline -o - | cvlc stream:///dev/stdin --sout '#rtp{sdp=rtsp://:8554/stream1}' :demux=h264` (according this [docs]( https://www.raspberrypi.com/documentation/accessories/camera.html#rtsp).

2 - Run webcam example like these: `python webcam.py --play-from rtsp://<ip-addr-of-server>:8554/stream1 --video-codec video/H264`.

3 - If CPU usage increase too much (100%), try to use ` --play-without-decoding` option in aiortc example: python webcam.py --play-from rtsp://<ip-addr-of-server>:8554/stream1 --play-without-decoding --video-codec video/H264`

Please, after tests share your results.

**Comment by DevelopDaily** [comment]
I ran it either way and got this from the `webcam.py` after I pressed the "Start" button on the web page:

```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/camera/.local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/home/camera/.local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/camera/test/aiortc/examples/webcam/webcam.py", line 79, in offer
    audio, video = create_local_tracks(
  File "/home/camera/test/aiortc/examples/webcam/webcam.py", line 26, in create_local_tracks
    player = MediaPlayer(play_from, decode=decode)
TypeError: __init__() got an unexpected keyword argument 'decode'
INFO:aiohttp.access:127.0.0.1 [03/Jul/2022:17:56:38 +0000] "POST /offer HTTP/1.1" 500 244 "http://127.0.0.1:8080/" "Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.106 Safari/537.36"

```

**Comment by rprata** [comment]
Good...

`aiortc` latest version (v1.3.2) in pip not included yet `decode` option. Try to install through this repository (`pip install -e .`).

I believe that you need to configure others`Pyav` options. For example, try to force framerate to `30fps`: `options={"fps": "30"}...

Sorry, but I don't have a PiCamera and a raspberry with `libcamera` configured to test in my side.

**Comment by DevelopDaily** [comment]
Thanks for the advice. I installed the latest from the repository. The video quality is drastically better now without doing anything else.

There is one major outstanding issue: jitter.

I point the camera toward a tree in the wind. The video on the browser shows the wavering leaves of the tree frozen periodically. The amazing thing is that the leaves move 4 seconds and freeze for 1 second. Again, the video on the camera preview window on the sending side is very smooth.

Is there a jitter butter that can be configured?

Please take a look at the` chrome://webrtc-internals/`. The `framesReceived/s` is rather steady (`30 fps`), but the `framesDropped` is almost linear, showing a pattern of systematically dropping frames. The `jitter` happens all the time.

![jitter](https://user-images.githubusercontent.com/54299975/177211346-14bce53b-241b-425f-8792-c4ffb0f36d98.png)

**Comment by rprata** [comment]
RTP packet sent by aiortc <= 1300k. So, your internet bandwidth and hardware (raspberry) could impact in your results.

Is it necessary to use 30fps? Try to decrease this value and check the behavior.

Suggestion: use option `rtsp_transport = tcp` or other [rtsp option](https://ffmpeg.org/ffmpeg-protocols.html#rtsp).

And also, feel free to collaborate with project ;).

**Comment by DevelopDaily** [comment]
If I learn the ropes well, I'd love to do something for the project, which is very interesting.

The bandwidth seems to be OK. I do the testing on the local WiFi. Actually, I can stream the video from the camera to YouTube and use another machine to watch it. It is quite smooth. I tried `15 fps` anyway and it didn't help.

In the `aiortc `project, can I print out the number of sent frames? I want to find out where the frames are dropped.

By the way, where to set `rtsp_transport = tcp` ?

**Comment by Ddvos** [comment]
Hi @DevelopDaily ,

Did you manage to make it work correctly? I am very curious, I have the new 64MP Arducam camera which is also using the```libcamera``` library. Can you explain how you make ```libcamera``` work inside Aiortc? Thanks for any help.

**Comment by DevelopDaily** [comment]
@Ddvos The procedure written on July 2 by rprata works. But the jitter problem remains.

**Comment by ayufan** [comment]
I hooked the aiortc to [camera-streamer](https://github.com/ayufan-research/camera-streamer/commits/webrtc) which is build on top of libcamera. However, I do continue seeing quite high jitter and occasional frame drops in remuxing mode. This does not happen when pushing h264 via jsmuxer. There's no rtsp as the frames are passed internally. It appears like aiortc would drop frames from time to time. Secondly, I noticed that CPU usage in remuxing mode is way higher than using rtsp-to-webrtc via https://github.com/mpromonet/webrtc-streamer.

Ref.:
- https://github.com/ayufan-research/camera-streamer/commit/b906af205aa759d9792a9a6d8f09ccf9d6d7e4a6
- https://github.com/ayufan-research/camera-streamer/tree/webrtc#webrtc-experimental-support

**Comment by rprata** [comment]
@DevelopDaily Is it possible to reduce frame to 720p (HD) and check jitter again? About `rtsp_transport = tcp` is a ffmpeg option (you can set in `webcam.py` line `26`, `MediaPlayer` constructor. For example:
```
    if play_from:
        player = MediaPlayer(
            play_from,
            decode=decode,
            options={
                "rtsp_transport": "tcp",
                "rtsp_flags": "prefer_tcp",
            }
        )
        return player.audio, player.video

```

**Comment by hackernese** [comment]
> Raspberry Pi has upgraded its operating system to Pi OS.
> 
> The `webcam `example works very well on the Raspberry Pi 4B with Pi OS if the "Legacy Camera" is enabled by hand. But, the Raspberry Pi will eventually discontinue the "Legacy Camera" option. So, has anybody planned to upgrade the `aiortc`?
> 
> One of the major changes of the Pi OS is to start to use `libcamera`, which is well documented here https://www.raspberrypi.com/documentation/accessories/camera.html

I don't think it is going to be gone forever. It can still be turned on through raspi-config and used with older camera module versions like V2 - 8M or the 5 Megapixel - Rev1.3.

Either way, I have tried all given methods from above, and it does seem like the jittering and delaying still happen quite frequently for me. However, since I am using the latest version, which is V3 and it requires the usage of picamera2, I figured out a way to utilize that library alongside `aiortc.MediaStreamTrack` that creates a smooth live streaming process (at least on my computer), which I have also discussed here in another issue: https://github.com/aiortc/aiortc/issues/826#issuecomment-1703263362
