### ISSUE TITLE
'Absolute Send Time' WebRTC extension bug

### ISSUE THREAD

**Issue by EmanueleOversonic** [aiortc/aiortc#745]
Hi,
I get the following warning upon the successfull connection of the two peers (but in fact it is an error since it prevent completely the tracks to be sent and received):
```
[WARNING][2022-06-28 13:00:29,863](72026)aiortc.rtcdtlstransport: RTCDtlsTransport(client) Traceback (most recent call last):
  File "/home/bob/ws/modules/streaming-module/venv/lib/python3.8/site-packages/aiortc/rtcdtlstransport.py", line 531, in __run
    await self._recv_next()
  File "/home/bob/ws/modules/streaming-module/venv/lib/python3.8/site-packages/aiortc/rtcdtlstransport.py", line 630, in _recv_next
    await self._handle_rtp_data(data, arrival_time_ms=arrival_time_ms)
  File "/home/bob/ws/modules/streaming-module/venv/lib/python3.8/site-packages/aiortc/rtcdtlstransport.py", line 575, in _handle_rtp_data
    packet = RtpPacket.parse(data, self._rtp_header_extensions_map)
  File "/home/bob/ws/modules/streaming-module/venv/lib/python3.8/site-packages/aiortc/rtp.py", line 710, in parse
    packet.extensions = extensions_map.get(extension_profile, extension_value)
  File "/home/bob/ws/modules/streaming-module/venv/lib/python3.8/site-packages/aiortc/rtp.py", line 89, in get
    values.abs_send_time = unpack("!L", b"\00" + x_value)[0]
struct.error: unpack requires a buffer of 4 bytes
```

I investigated a bit and I understood that is caused by the RTP extension "Absolute Send Time" ([https://webrtc.googlesource.com/src/+/refs/heads/main/docs/native-code/rtp-hdrext/abs-send-time](https://webrtc.googlesource.com/src/+/refs/heads/main/docs/native-code/rtp-hdrext/abs-send-time))
In the specification it is written that this extension is 4 bytes long, but the code in aiortc/rtp.py seems to ignore this and try to get the extension value as for any other extension. Then this value is unpacked but being too short an exception from the struct package is thrown.
You think all this I supposed is right? 
I can try patching it and sending you a first fix.
Have a great day

**Comment by EmanueleOversonic** [comment]
Update:
Trying to fix it, I noticed the logic in aiortc/rtp.py follow the standard RFC 5285, and I noticed that this standard has been obsoleted by RFC 8285. I think this work is an update more than a bug fix. Maybe I could try to update all to the current standard RFC 8285, but it would take me a lot of time (and unfortunately I am very poor of time this period...), I will let you know guys! Continue with this great job anyway!

**Comment by jlaine** [comment]
@juberti any thoughts?

**Comment by juberti** [comment]
8285 is a fairly minor update to 5285 IIRC. So I'm not sure that that's the core issue here. Similarly, I would expect the extension parser to use the transmitted length rather than assuming any specific length for the extension.

Do you have a dump of a packet that the parser chokes on?

**Comment by EmanueleOversonic** [comment]
Yes, here are some packets that trigger the bug:
[rtp_abs_send_time_failed.zip](https://github.com/aiortc/aiortc/files/9008911/rtp_abs_send_time_failed.zip)
I think it is the biggest one that contain the invalid header (i.e. a video frame). I should have disabled TLS for the capture, but let me know if there is any problem.
By the way, I cannot understand the logic of packing/unpacking headers in rtp.py: why after the magic words 0x\be\de is appended the length in bytes of all the extensions and not the number of extensions as specified in RFC 5285? I think it could be the reason of the bug. Also, i noticed that in the broken packet the extension length has a value of "1", but it should be greater since 'mid' and 'abs_send_time' extensions are both included (and that is why the bug is triggered, the unpack doesn't receive enough bytes).

**Comment by EmanueleOversonic** [comment]
Hi,
You had time to investigate on this issue using the provided dumped packets?

**Comment by david-goldb** [comment]
Hi, is there something new to update regarding this one? 
I experience the same thing when I try to receive the `rtp_data`...

**Comment by juberti** [comment]
I will look into this in the next week or two.

**Comment by david-goldb** [comment]
After I removed this `a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\n` from the offer before I sent it to the master peer, I was able to stream media between the two peers. It looks fine - no delay and good sync of audio-video tracks.

**Comment by david-goldb** [comment]
@juberti do we have any updates?

**Comment by jlaine** [comment]
Could this be related to #686 ? I am wondering if we are negotiating extension IDs correct.

**Comment by juberti** [comment]
@eerimoq, thanks for digging into this! I think your workaround would be a good short-term fix (and we can add a note to `codecs/__init__.py` to warn people about this for the future.

**Comment by juberti** [comment]
Made a PR at https://github.com/aiortc/aiortc/pull/900
