### ISSUE TITLE
how do I disable buffer?

### ISSUE THREAD

**Issue by opusviz** [aiortc/aiortc#749]
How do I disable buffer in server.py in server example. I tried subscribe(track, buffered=True). It accepts this argument but it still buffers. How do I stop buffering. This is the complete code -
pc.addTrack(
                VideoTransformTrack(
                    relay.subscribe(track, buffered=False), transform=params["video_transform"]
                )
            )

**Comment by jlaine** [comment]
I don't understand the issue, what is being "buffered"?

**Comment by opusviz** [comment]
Video is being buffered. It starts well and if the internet is a bit slow, it gradually gets delivered a bit later so that after 10 seconds of video streaming, I will get back the current frame from the server in two or three seconds.

**Comment by opusviz** [comment]
Thank you. I increased to 4 CPU and it is working fine now.
