### ISSUE TITLE
Memory leak in webcam.py example

### ISSUE THREAD

**Issue by buttonman** [aiortc/aiortc#751]
When I run the webcam.py, the memory usage increases, and when I restart the browser or press the stop button, the memory does not decrease.

I repeated start -> refresh browser or click stop button -> start
<img width="508" alt="스크린샷 2022-07-19 오후 2 28 19" src="https://user-images.githubusercontent.com/14156590/179674572-9b33eca5-6b72-4e75-b85c-34929b043e6d.png">

the memory increases to 2GB
![스크린샷 2022-07-19 오후 2 36 26](https://user-images.githubusercontent.com/14156590/179677231-3b3d1678-0229-4c25-a1f7-81348f8bb842.png)

Actually it started at about 400MB memory.
![스크린샷 2022-07-19 오후 2 27 57](https://user-images.githubusercontent.com/14156590/179676870-1a219289-8bf2-4975-9373-bbe023f3b352.png)

And I waited until all connections are closed but there is no changes
![스크린샷 2022-07-19 오후 2 36 34](https://user-images.githubusercontent.com/14156590/179676989-f17b60da-546a-458e-a717-9e15dc10f897.png)

I tested it with:

- aiortc: 1.3.2
- pyav. : 9.2.0

**Comment by jlaine** [comment]
Any progress determining the cause?
