### ISSUE TITLE
Can't hear client-side Audio after first burst of audio

### ISSUE THREAD

**Issue by tand22** [aiortc/aiortc#758]
I'm sending audio back to the client using this setup.

```python
class AudioStreamSendTrack(MediaStreamTrack):
    kind = "audio"

    def __init__(self, audio_send_queue: asyncio.Queue):
        super().__init__()
        self.audio_send_queue = audio_send_queue
        self.resampler = AudioResampler(format='s16', layout='mono', rate=22050)

    async def recv(self):
        frame: AudioFrame = await self.audio_send_queue.get()
        frame = self.resampler.resample(frame)[0] # Opus requires s16
        time.sleep(0.015) # 15ms

        return frame
```

As I add the first batch of packets to the queue, the queue is cleared and the audio is heard on the client device (I have both iOS and JavaScript client-side code). Upon any subsequent adding of batches of packets to the queue, the queue is also cleared and I can see similar logs in debug mode in relation to the packets being sent, however I get no sound on the client-side anymore. 

I can see that the MediaStreamTrack is remaining enabled and not muted on the client-side, so am unsure of what is causing this behaviour. Any advice on how I should debug this further or what could be the cause?

**Comment by tand22** [comment]
Turns out the counter I was using to set the .pts on the frame was getting reset with each burst of packets, hence that's why I wasn't hearing anything after the first burst.

**Comment by learncodingforweb** [comment]
please can you help me, how to read mic and send audion on webrtc connection. i am unable to find any resource, which will help me to send audio from mic?
