### ISSUE TITLE
Improving audio latency?

### ISSUE THREAD

**Issue by W3AXL** [aiortc/aiortc#775]
My application is running bidirectional OPUS audio, and currently I'm seeing one-way latencies (audio in to audio out) of **500-600ms**. This is using the OPUS codec, when using U-LAW I see even higher latencies (900ms-1s). All communication is being done on a hardwired LAN, so network latency is not a factor. Ideally, I'd love to get latencies below 300ms as this would make the app much more responsive and real-time. Tests using online loopback websites reveal that WebRTC can easily get sub-100ms latencies even across the internet, so something similar should be possible with my current setup. This leads me to believe the `aiortc` library (or the audio backend libraries like PyAV) are the cause of the majority of the latency I'm seeing.

I'm wondering if there's any suggestions for tweaking the library for better performance? Or at least places to investigate for bottlenecks? CPU usage on the server is not being maxed out - I'm running two concurrent bidirectional OPUS streams and overall CPU usage stays below 30%.

**Comment by mariokrous** [comment]
Hi, I am also having issues with audio.
Jitter is too high, always in the range 700-1200.
After testing different connection setups, I  observed the following:

Establishing a connection between 2 aiortc peers: high jitter seems to affect the audio quality.
Establishing a connection between an aiortc peer and a web browser peer: Jitter is lower and audio quality is pretty good.

Listening to aiortc peer's audio has high latency in both cases.
Listening to web browser peer's audio works fine
Overall CPU usage stays low.

I think that the audio encoding part does not work properly.
It still needs further investigation but for now I cannot find out what else might affect the audio quality.
