### ISSUE TITLE
DataChannel-only 'feature' without codec dependencies?

### ISSUE THREAD

**Issue by warner** [aiortc/aiortc#78]
Great stuff! I'd love to use this in [magic-wormhole](https://github.com/warner/magic-wormhole).. I only need the DataChannel, though. Any idea how hard it'd be to define a 'feature' for the codecs, so `pip install aiortc[video]` gets you the dependencies on the codecs, but `pip install aiortc[datachannel]` does not?

**Comment by jlaine** [comment]
I'd like the default install to keep pulling in the necessary bits for all of aiortc to work (I don't want to get swamped with "why doesn't media work" tickets), but if you want to put together a PR to have a "no media" variant I'll definitely look at it.

**Comment by warner** [comment]
Cool, thanks, I'll see what I can do. One solution might be to split off a separate `aiortc-datachannel` distribution, then make `aiortc` depend upon it. Might be easier than using features, and would retain the "depend on just `aiortc` to get everything" property.

**Comment by jlaine** [comment]
I'm closing this: we have binary wheels for all of our dependencies on a wide array of platforms.
