### ISSUE TITLE
Does offer sdp have an expiration duration?

### ISSUE THREAD

**Issue by yifan97** [aiortc/aiortc#781]
```
pc = RTCPeerConnection()
pc.addTrack(mediastreams.AudioStreamTrack())
pc.createDataChannel("dataSendChannel")
offer = asyncio.get_event_loop().run_until_complete(pc.createOffer())
```
Do we have an expiration duration on the offer generated above? In other words, once this offer is generated, can it be used after a long time?

**Comment by jlaine** [comment]
I don't understand what you mean, the WebRTC specs have no notion of "expiration" on SDP offers.
