### ISSUE TITLE
Is this possible to read sound card output on linux using MediaPlayer?

### ISSUE THREAD

**Issue by JaktensTid** [aiortc/aiortc#782]
Hi, I was checking 'webcam' example, wondering - is there a way to get sound card output?

I tried to pass default, name of device as the 'file input' parameter, but nothing works.
It just keeps saying me that 'File or directory does not exist'

Also tried `MediaPlayer('hw:0', format='alsa')` and `MediaPlayer('hw:0', format='pulse')`
But it also says me, no container format 'alsa'

**Comment by jlaine** [comment]
I see you've already reported this in the right place here: https://github.com/PyAV-Org/PyAV/issues/1032
