### ISSUE TITLE
aiortc with OpenCV imshow

### ISSUE THREAD

**Issue by praveenVnktsh** [aiortc/aiortc#785]
Hey guys, im having the same issue!

### Discussed in https://github.com/aiortc/aiortc/discussions/734

<div type='discussions-op-text'>

<sup>Originally posted by **ahmadmughees** June  6, 2022</sup>
Hi, Thanks for amazing framework, 

I just encounter a bug when using aiortc and OpenCV imshow fuction. 

Whenever I even simply import the aiortc, my program hangs on the opencv imshow function. Minimum example is as follows, 

```import cv2
import numpy as np
import aiortc # if you comment this line, the program will work fine

img = 255 * np.ones((512, 1920 // 2, 3), dtype=np.uint8)
for i in range(1000):
    cv2.imshow("win", img)
    print(i)
    cv2.waitKey(1)
```
The library versions are
```
aiortc==1.3.2
opencv-python==4.5.5.64
```
Thanks alot. 
</div>

**Comment by jlaine** [comment]
Holding up the event loop with imshow / waitKey seems like a terrible idea.

Also there is a known incompatibility between PyAV and OpenCV: https://github.com/PyAV-Org/PyAV/issues/978
