### ISSUE TITLE
Stream video to client without offering webcam from client side

### ISSUE THREAD

**Issue by TemaisgameNoobas** [aiortc/aiortc#786]
Before filing an issue please verify the following:

* Check whether there is already an existing issue for the same topic.
* Ensure you are actually reporting an issue related to ``aiortc``. The goal
  of the issue tracker is not to provide general guidance about WebRTC or free
  debugging of your code.
* Clearly state whether the issue you are reporting can be reproduced with one
  of the examples provided with ``aiortc`` *without any changes*.
* Be considerate to the maintainers. ``aiortc`` is provided on a best-effort,
  there is no guarantee your issue will be addressed.

Hello. I am trying to do video streaming to client without offering webcam from client side.
I couldn't find the example for it.
Is there any way to do it??

**Comment by jlaine** [comment]
Check the "webcam" example.
