### ISSUE TITLE
How to make server stream video without asking the client to do it

### ISSUE THREAD

**Issue by TemaisgameNoobas** [aiortc/aiortc#787]
Before filing an issue please verify the following:

* Check whether there is already an existing issue for the same topic.
* Ensure you are actually reporting an issue related to ``aiortc``. The goal
  of the issue tracker is not to provide general guidance about WebRTC or free
  debugging of your code.
* Clearly state whether the issue you are reporting can be reproduced with one
  of the examples provided with ``aiortc`` *without any changes*.
* Be considerate to the maintainers. ``aiortc`` is provided on a best-effort,
  there is no guarantee your issue will be addressed.

Hello. How do i make the server to stream a video, then when you open the page you can view the video. The server streams the video without asking the client to do it.
I checked the webcam example, it didn't worked and just sending a error about json.
Also, how do i make it switch the video after the first video ends??

**Comment by DerGenaue** [comment]
You need the client to allow the server to stream video to it.

I did it by:
```js
pc.createOffer(
    {
        iceRestart: true,
        offerToReceiveVideo: true,
        offerToReceiveAudio: true
    }
)
```
