### ISSUE TITLE
1920x1080 support?

### ISSUE THREAD

**Issue by vsakkas** [aiortc/aiortc#789]
Does `aiortc` support 1920x1080 for video? I've adapted the example code from `server.py` into my project and athough I can do 1280x720 without any issues, I haven't been able to get 1080p.

I know that `getUserMedia` can do 1920x1080 with the right contraints.

When I convert the track to a numpy array (using the example code), the array shape is 1280x720. What could be causing this?

**Comment by ipekmuhammet** [comment]
same

**Comment by thai-phan** [comment]
I have 1920x1080 camera but it will loaded 640x480 by default and  when select 1280x720 from client it return 990x557.
I debbuged these value from decode function:
`img = lib.vpx_codec_get_frame(self.codec, it)`

**Comment by jlaine** [comment]
Can you clarify what your issue is exactly? Are you looking to receive 1920x1080, or receive it (from aiortc's perspective)?
