### ISSUE TITLE
Weird behavior while trying to connect to livekit

### ISSUE THREAD

**Issue by dguerizec** [aiortc/aiortc#800]
Hello,

I'm developing a python client SDK for livekit, and I ran into a weird problem.

In rctpeerconnection.py, in the __connect() method, I have to patch line 1018 to disable SCTP to make it work.

As far as I know, SCTP is used for datachannels. I don't need to use the datachannel, but livekit sends it in its initial offer.

The problem I'm seeing, is that the sctp transport is being connecting, somehow preventing the DTLS/RTP transport to connect.

I'm not sure my explanation is clear, since I'm very new to webrtc, but I've put an example here:
https://github.com/dguerizec/livekit-client-sdk-python

In this repo, the subscriber example only works when I disable SCTP in RTCPeerConnection.__connect().

If I don't disable SCTP, the dtlsTransport.state is always "connecting", thus never receiving from the transceiver.

Is there something I'm doing wrong ?

Initial offer from livekit-server:
```
v=0
o=- 4261650069995738642 1672227076 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 5F:CF:73:AD:E0:DE:D0:8B:7A:B4:FF:38:57:7A:3F:BD:99:1B:82:CB:04:DB:A4:50:C3:04:1C:0B:17:BC:47:9A
a=ice-lite
a=extmap-allow-mixed
a=group:BUNDLE 0
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:0
a=sendrecv
a=sctp-port:5000
a=ice-ufrag:qJHytwgzRTlkmPiM
a=ice-pwd:yXckeNWryDvwkHPMQXcOaZrPsASfqaGo
```

I can provide other debug information if needed, along with network traces.

**Comment by jlaine** [comment]
You're going to need to provide more information to convince me `aiortc` is doing anything wrong here. All I have is an initial SDP offer and "then something doesn't work".

**Comment by dguerizec** [comment]
OK, I'll try to find some time to get a minimal example showing the problem with only aiortc.
Basically, when there are multiple offers, and the first offer only contains a webrtc data channel, the subsequent offers will not take any other A/V channel into account.
