### ISSUE TITLE
RTCPeerConnection stuck in "connecting" state, and tracks don't return frames

### ISSUE THREAD

**Issue by kennytheeggman** [aiortc/aiortc#801]
I have a very basic ``aiortc`` client that connects to another ``aiortc`` server that streams a ``MediaStreamTrack`` to connected clients. The server has a web client which works perfectly, as expected, however the ``aiortc`` client does not work at all. The following is the very basic outline for how the client is written:

```python
async def run():
    pc = RTCPeerConnection()

    pc.addTransceiver("video", direction="recvonly")

    blackhole = MediaBlackhole()

    @pc.on("track")
    async def on_track(track):
        print(track)
        blackhole.addTrack(track)
        frame = await track.recv()
        print(frame)

    offer = await pc.createOffer()

    await pc.setLocalDescription(offer)

    r = requests.post("http://localhost:8080/offer", json={"sdp": offer.sdp, "type": offer.type})
    b = r.json()
    sd = RTCSessionDescription(sdp=b["sdp"], type=b["type"])

    await pc.setRemoteDescription(sd)
    await blackhole.start()

loop = asyncio.get_event_loop()
loop.run_until_complete(run())
loop.run_forever()
```

After some debugging I noticed that when ``dtlsTransport.start`` in the rtcpeerconnection.py file is called when ``setRemoteDescription`` is called by my code, the ``self._recv_next()`` method call in rtcdtlstransport.py is awaited forever since the queue is empty. Since my server implementation is fine on the browser client, I am inclined to believe that there is something wrong with my ``aiortc`` client. Some guidance in this regard would be much appreciated, thanks!

**Comment by dguerizec** [comment]
Hi @kennytheeggman 

Your problem looks like I'm experiencing and I described in #800
Can you try the fix I proposed in #802 ?

**Comment by kennytheeggman** [comment]
Hi @dguerizec 

Thanks for the suggestion, I couldn't quite figure out how you patched the SCTP section, and I am still receiving no frames. I have however narrowed down the issue to the initial SSL handshake not being completed when both transports (client and server) think they are both the server, which seems to be the default behavior with ``aiortc``. If you could clarify what your fix was in #802 , that'd be great too.

Thanks!

**Comment by kennytheeggman** [comment]
After some more digging, it seems that the SSL handshake has normal behavior, however when the server does not find any valid candidate pairs to the client, resulting in the ``iceTransport``'s connection state to remain "checking". This is strange as this behavior doesn't occur when the browser is the client. Even stranger is that the client has a large number of valid candidate pairs, even though I thought the ICE gathering process should be symmetric?

**Comment by kennytheeggman** [comment]
This seems to be an issue with the ICE connection in the ``ice.py`` file of ``aioice`` instead of ``aiortc``, but I'll share my findings here too. When ICE connections are gathered, this library is meant to have redundancy, which means information about remote candidates when have 2 sources:

1. Through the ``add_remote_candidate`` method, which is called when a candidate is added by the ``IceTransport`` object, then adding the candidates to the ``_early_checks`` queue, which is verified by ``check_incoming`` upon connection attempt.
2. Through the ``request_received`` method, which is called whenever a request is sent over the connection. Normally, this allows remote candidates to be added to the connection after the ``_early_checks``, which is immediately verified by ``check_incoming``.

Note that the ``check_incoming`` method is called by the following lines of code (lines 1024 to 1026 in ``ice.py``)
```python
        if not self._check_list:
            self._early_checks.append((message, addr, protocol))
        else:
            self.check_incoming(message, addr, protocol)
```

In an ordinary connection, ``_early_checks``, and thus ``_check_list`` is populated early by the offer/answer exchange, however, an ``aiortc`` client, which uses ORTC rather than WebRTC does not populate ``_early_checks`` until messages are sent through STUN. 

Since ``aioice`` operates under the assumption that if the ``_early_checks`` have been verified, ``_check_list`` is then no longer empty, when ``_early_checks`` is not populated, ``request_received`` assumes the ``_early_checks`` have not been verified, though they actually have been. As a result, it skips the ``check_incoming`` method, which is the one essential to adding the remote candidates. Because of this, the remote candidates are never added, and thus the SSL handshake never completes and the queue remains empty.
