### ISSUE TITLE
Remote/Local transceiver order can cause unexpected full crashes due to createOffer

### ISSUE THREAD

**Issue by kennytheeggman** [aiortc/aiortc#803]
Odd behavior occurs when you try to use ``aiortc`` as a standalone RTC video receiver which acts as the offerer. When the order of the media information in the offer that is sent by the video receiver to the video sender does not match the order that the video receiver stores locally, when each ``iceTransport`` object is started, the ICE connection fails to complete on all video channels. This is because when an ICE connection needs to be established, STUN messages are sent from the "client" to the "server" (I use these terms loosely because the rest of RTC is peer to peer), which include self identification. 
This self identification consists of:

1. Username: consists of a remote username and a local username, where the remote username is determined by the offer/answer that is received by either end
2. Password: randomly generated and should have no issues if the packets are not tampered with

ICE must ensure that the usernames match before proceeding in the connection (as a safety measure against tampered packets). Note that in ``aiortc``, the usernames are sent/received with simple ``for`` iteration:

On the "client" (rtcpeerconnection.py in ``createOffer``):
```python
for i in range(max(len(local_media), len(remote_media))):
    ...
    description.media.append(
        create_media_description_for_transceiver(
            transceiver,
            cname=self.__cname,
            direction=transceiver.direction,
            mid=mid,
        )
    )
    ...
```

On the "server" (rtcpeerconnection.py in ``__connect``):
```python
for transceiver in self.__transceivers:
    ...
    await iceTransport.start(self.__remoteIce[transceiver])
    ...
```
which eventually calls:
```python
rx_username = "%s:%s" % (self.local_username, self.remote_username)
    if message.attributes.get("USERNAME") != rx_username:
        raise ValueError("Wrong username")
```

For some reason, the order in which the offer is parsed when sent to the "server" is the reverse of the order in which the transceivers are added to the peer connection, which means if there is more than 1 transceiver, the username expected by the "server" during the first iteration no longer matches the username sent by the "client" during the first iteration. As a result, the connection is abandoned by the "server", despite another transceiver's data may match what is being sent by the "client".

Here is an example of the different usernames that may be compared
![image](https://user-images.githubusercontent.com/82221723/210154326-8244058d-7448-4fb1-969e-6c4485e7d4fd.png)
![image](https://user-images.githubusercontent.com/82221723/210154316-aba1a636-e01b-4129-a211-e6d796bd56e7.png)
Though both usernames are valid, they are not being matched to the correct transceiver and the ICE gathering never completes.

So far, the behavior I have observed shows that the order of the transceivers in the offer is always the reverse of the order of transceivers in the ``RTCPeerConnection.__transceivers`` property, which is why I have implemented a temporary fix using the following code:
```python
peer_connection._RTCPeerConnection__transceivers = peer_connection._RTCPeerConnection__transceivers[::-1]
```
that simply reverses the order that the transceivers are stored. This is not a robust fix however, as I am uncertain of the consistency with which the order is mixed, so my suggestion for a fix would be to sort the transceivers on both ends by their ``mid``s, which is information constant on both sides. 

Note that Chromium's implementation seems to have no trouble with this. This leads me to believe that their implementation checks all of its transceivers' usernames when forming connections, so the state where the "server" is checking for a transceiver's username that has yet to be sent is avoided. Perhaps this would be a more robust fix for this issue.

**Comment by jlaine** [comment]
Hm, it looks as though you may be on to something here. Would you mind digging in the WebRTC specs to check where the expected behaviour is defined?
