### ISSUE TITLE
Certificate error when creating RTCDtlsTransport with Cryptography 39.0.0

### ISSUE THREAD

**Issue by khlukekim** [aiortc/aiortc#804]
- With Cryptography 39.0.0, RTCPeerConnection fails to create RTCDtlsTransport
- RTCCertificate can't find self._cert._x509 while running _create_ssl_context()
- This seems to due to one of the backwards incompatible changes from Crytography 39.0.0 updates (https://cryptography.io/en/latest/changelog/).
- I don't have much background in crypto, so I'm not sure if this is just some change of the procedure acquiring a certificate or Cryptography's removing our necessary function. 

- Maybe related to #766, but Cryptography is not deprecated yet. 

- Please use Cryptography < 39 for now.

**Comment by mristin** [comment]
Just a note for other users: this also applies to the examples in https://github.com/aiortc/aiortc/tree/main/examples/server.

When installing dependencies, this worked for me:

```
pip install aiohttp aiortc opencv-python
pip uninstall -y cryptography
pip install cryptography<39
```

The example worked then flawlessly.
