### ISSUE TITLE
When is next release?

### ISSUE THREAD

**Issue by eerimoq** [aiortc/aiortc#811]
Hi!

I'm interested in using the MediaPlayer without transcoding. I noticed that it is implemented but not part of an official release yet. Are there any plans on releasing this?

**Comment by skvark** [comment]
It would be nice to have also Python 3.11 pre-built packages.

**Comment by jlaine** [comment]
It would be nice to have co-maintainers, I have very little spare time and I have way too many projects to maintain. Just maintaining aiortc means in fact maintaining:

- aioice
- pylibsrtp
- pyav
- aiortc

**Comment by eerimoq** [comment]
I can help out. I'm no expert on video or WebRTC, but I think I'll manage.

**Comment by jlaine** [comment]
> I can help out. I'm no expert on video or WebRTC, but I think I'll manage.

Great, I'd appreciate some help, especially with triaging issues and reviewing PRs (does a PR clearly explain what it is aiming for? does it have full unit tests?). Let's see how that goes and we can take it from there. Thanks for stepping up!

**Comment by jlaine** [comment]
aiortc 1.4.0 should be on PyPI in about 15mn!
