### ISSUE TITLE
Quality problems with H264 Codec and Server example

### ISSUE THREAD

**Issue by bluedodecahedron** [aiortc/aiortc#825]
Hey, I have the following setup:
- The [aiortc server](https://github.com/aiortc/aiortc/blob/main/examples/server/server.py) from the aiortc examples is running on a Windows machine 
- An Android phone is connecting to the server (Using Google's Java WebRTC implementation)

This works perfectly fine as long as I'm using a VP8 Encoder/Decoder. Using the H264 Codec, the video stream sent to the aiortc server also looks fine (Tested this by recording it). However, the video stream sent back to the Android system is very bad quality-wise (low PFS, bad image). Looking at the Sender Statistics, the server receives millions of bytes, but only sends back a couple thousand.

A similar issue also happens with the original server example, using the following setup:
- [Aiortc server](https://github.com/aiortc/aiortc/blob/main/examples/server/server.py) from original example, runs on Windows
- [Javascript client](https://github.com/aiortc/aiortc/blob/main/examples/server/client.js) from original example (Using Firefox/Chrome on Windows/Android using Virtual Camera/Phone Camera -> all same result)

Here, the quality seems fine originally, but degrades within 30-60 seconds of connection, eventually losing all colors and getting ultra blurry. This also does not happen with VP8, only with H264.

Could it be that the aiortc H264 Codec is not compatible with other implementations?

**Comment by jlaine** [comment]
This was possibly fixed by https://github.com/aiortc/aiortc/pull/796
