### ISSUE TITLE
iceConnectionState stucking at checking and connectionState at connecting

### ISSUE THREAD

**Issue by quanggdungg0609** [aiortc/aiortc#829]
Hello, I'm a beginner using the 'aiortc' library, i use aiortc to open the connect from the raspberry pi to a web browser for send the video stream from pi camera to client. I created a new RTCPeerConnection on the raspberry pi and create a offer SDP and send offer to client through socket.io. But when received the answser SDP from the client and set it into the peer, the iceConnectionState stucking at 'checking' state and the same probleme with connectionState with 'connecting' state. At the beginning im just try on the same network.
Here my code on raspberry pi:

```
async def __initPeer(self, client: str):
        logging.info(f"Prepare to negociate with {client}")
        #Create Peer
        peer=RTCPeerConnection()
        peer.addTrack(self.__relay.subscribe(self.__player.video))
        # peer.onicecandidate=on_icecandidate
        # create offer SDP
        offer= await peer.createOffer()
        await peer.setLocalDescription(offer)
        logging.info("Peer created ready to emit offer SDP")
        # emit offer SDP to clients
        serializeSDP=json.dumps({"type":offer.type, "sdp":offer.sdp})
        message={
            "target":client,
            "payload":serializeSDP
        }
        try:
            await self.__sio.emit("offer",message)
        except:
            logging.error("Cannot emit offer SDP")
        self.__peers.update({client:peer})

```
and from the client with javascript for the answer SDP:

```
socket.on("offer",async data=>{
    logger.debug("on 'offer' event")
    if (typeof data.payload!=="object"){
        data.payload=JSON.parse(data.payload)
    }
    let peer, answer
    try{
        const result=await common.CreatePeerConnection(data.payload)
        peer=result.peer
        answer=result.answer
        
    }catch (error){
        console.log("error: ", error)
    }

    console.log(answer)
    peersList.set(data.id,peer)
    const message={
        target:data.id,
        payload:answer
    }
    socket.emit("answer", message)
})
```

The output on raspberry is like that after i set remote session description to the peer:

> 2023-02-23 19:30:04,300 - DEBUG - RTCPeerConnection() setRemoteDescription(answer)
v=0
o=- 5062119667559254634 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 97 98 99 100 101 102
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:fkvU
a=ice-pwd:vC07bMESpTny5SHQyZtz6Gdt
a=ice-options:trickle
a=fingerprint:sha-256 F6:8B:60:82:81:A0:9D:46:E7:9C:BA:2A:EC:DD:A8:FB:D4:7B:50:60:AD:F6:EF:52:D3:5B:DD:B0:11:AE:77:35
a=setup:active
a=mid:0
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=recvonly
a=rtcp-mux
a=rtpmap:97 VP8/90000
a=rtcp-fb:97 goog-remb
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtpmap:98 rtx/90000
a=fmtp:98 apt=97
a=rtpmap:99 H264/90000
a=rtcp-fb:99 goog-remb
a=rtcp-fb:99 nack
a=rtcp-fb:99 nack pli
a=fmtp:99 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:100 rtx/90000
a=fmtp:100 apt=99
a=rtpmap:101 H264/90000
a=rtcp-fb:101 goog-remb
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=fmtp:101 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:102 rtx/90000
a=fmtp:102 apt=101
2023-02-23 19:30:04,305 - DEBUG - RTCIceTransport(controlling) - new -> checking
2023-02-23 19:30:04,305 - DEBUG - RTCPeerConnection() iceConnectionState new -> checking
2023-02-23 19:30:04,306 - DEBUG - RTCPeerConnection() connectionState new -> connecting

**Comment by mariokrous** [comment]
It seems that you are not getting any ice candidates from the web browser.
Connection state changed to connecting because you set the remote sdp.

Unless you receive ice candidates and add them to aiortc peer (add remote candidate function), you cannot establish a connection..

**Comment by quanggdungg0609** [comment]
> It seems that you are not getting any ice candidates from the web browser.
> 
> Connection state changed to connecting because you set the remote sdp.
> 
> 
> 
> Unless you receive ice candidates and add them to aiortc peer (add remote candidate function), you cannot establish a connection..
> 
> 

Thank you, i fixed the error with your reminder.

**Comment by bernardolansing** [comment]
> It seems that you are not getting any ice candidates from the web browser. Connection state changed to connecting because you set the remote sdp.
> 
> Unless you receive ice candidates and add them to aiortc peer (add remote candidate function), you cannot establish a connection..

I am not receiving ICE candidates from Python side. From the browser side (same computer) I am receiving 5 of them. Any idea on what is happening?

**Comment by mariokrous** [comment]
> > It seems that you are not getting any ice candidates from the web browser. Connection state changed to connecting because you set the remote sdp.
> > Unless you receive ice candidates and add them to aiortc peer (add remote candidate function), you cannot establish a connection..
> 
> I am not receiving ICE candidates from Python side. From the browser side (same computer) I am receiving 5 of them. Any idea on what is happening?

The issue has been closed. Maybe you can open a new [discussion ](https://github.com/aiortc/aiortc/discussions/new/choose) and get some feedback.
