### ISSUE TITLE
Implement ulpfec (RFC 5109)

### ISSUE THREAD

**Issue by Tjoppen** [aiortc/aiortc#830]
Currently there is no FEC support, especially not on the sender side. I suspect basic single-level FEC would go a long way to kill video freezes for high-bitrate video. RFC 5109 is implemented in Chromium and Firefox (and possibly other browsers) via libwebrtc. Worth noting that "FEC" here just amounts to parity, meaning XOR of data from multiple packets. There is nothing like Reed-Solomon or anything like that going on.

**Comment by jlaine** [comment]
Sure a PR is welcome.
