### ISSUE TITLE
Streaming in two different machines in a same local network.

### ISSUE THREAD

**Issue by wagaabderrahim** [aiortc/aiortc#834]
I have a small problem concerning the streaming in a local network. I started the application on a local server and I did not encounter any problem.

 On another machine on the same network, the index page is displayed but the video part is not displayed and an error message is displayed in the console knowing that the STUN server is activated.

![failedwebrtc](https://user-images.githubusercontent.com/61705784/223393934-fff98933-f941-41e2-8598-988054c15f36.PNG)

![console webrtc](https://user-images.githubusercontent.com/61705784/223394447-a78a0301-5d2a-4c1c-910d-5aab97dc81bd.PNG)

knowing that in my server I have disabled the firewall.

**Comment by mariokrous** [comment]
I don't see any error
