### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by eerimoq** [aiortc/aiortc#842]
Hello!

Would be lovely with a new release that contains the `aioice` bump to 0.8.0 for TURN over TCP fix. It's already on main, so just a tag and publish to PyPI is needed.

Thanks, Erik

**Comment by jlaine** [comment]
Right you are, this is overdue. I've bumped the required `aioice` version to 0.9.0 so that we also pick up your fix for spurious ICE state transitions.

**Comment by jlaine** [comment]
aiortc 1.5.0 is available from PyPI
