### ISSUE TITLE
aiortc and flutter-webrtc communication

### ISSUE THREAD

**Issue by YuioiuY** [aiortc/aiortc#861]
Hello everyone, I have a problem, I'm working on an application that just needs to broadcast a video. The architecture is simple, p2p. But there is a nuance, I am trying to contact another flutter-webrtc based application using aiortc. If the answer and offer don't cause problems, then when I get to the candidates, everything falls down. Everything works locally.

I analyzed the messages and noticed 
1) the candidates differ
aiortc - `3216bfbfa496996c65f1dc28fb78079d 1 udp 2130706431 101.101.101.101 54321 typ host generation 0 ufrag 4ErP`
flutter-webrtc - `1114921598 1 udp 41885439 80.80.80.80 12345 typ relay raddr 100.100.100.100 rport 44146 generation 0 ufrag 6+cW network-id 4 network-cost 10`

2) I just don't know where to get some of the required parameters and I don't know if it's possible to get them somewhere
-- network-id ? network-cost ?

Tell me what you can do or try to implement in order to establish and configure the connection or is it simply impossible.

**Comment by mariokrous** [comment]
Hello, 

it seems that aiortc provides a host candidate and flutter-webrtc provides a relay candidate. 
In order to establish a connection you need one of the following pairs of candidates:
host- host
srflx - srflx
relay - relay

aiortc can gather relay candidates but you need to configure a relay server. 
if you want to make it work locally, check if flutter-webrtc can provide host candidates.

**Comment by YuioiuY** [comment]
Thanks for the answer, tomorrow I will look and think at work, if it suddenly dawns and works or not, I will write.

**Comment by YuioiuY** [comment]
@mariokrous 
OH, MY GOD, EVERYTHING WORKS!!! Thank you very much! indeed, my mistake was that I did not specify the turn server at the beginning of development. Thanks again!

**Comment by YuioiuY** [comment]
@mariokrous 
Good afternoon, yesterday I spent the whole day fiddling with the video settings for local transmission and finally began to engage in remote connection to my program. And again I was faced with the fact that I do not understand how to correctly draft a candidate for aiortc, so that flutter-webrtc could accept it. The most important and obvious differences that I observe are: 

1. foundation in aiortc looks like _**f98981c30fc331fe258681c79fbc1ab5**_, and in flutter-webrtc like this _**1114921598**_ 
2. this is what is in the candidate that comes to me with flutter-webrtc and which is accordingly expected as I understood it _**network-id**_ and _**network-cost**_

I looked through the documentation on aiortc, on webrtc in general, and did not see anyone mentioning and explaining what network settings are and why they are needed. And as a result, two questions, such a unique foundation is not a problem, is it? after all , there are examples with js where , according to the idea , these parameters are calmly perceived ? And the second question, do I understand correctly that aiortc does not use in any way _**network-id**_ and _**network-cost**_ ?

Regarding the fact that you mentioned candidate pairs, I realized that there are such explicit pairs as, for example, host-host, I have them and in theory everything should work, but only so far in theory :D

**Comment by mariokrous** [comment]
Hello,

answering your questions..

#1 from [here](https://www.rfc-editor.org/rfc/rfc8445)

> Foundation: An arbitrary string used in the freezing algorithm to
group similar candidates. It is the same for two candidates that
have the same type, base IP address, protocol (UDP, TCP, etc.),
and STUN or TURN server. If any of these are different, then the
foundation will be different.

#2 aiortc doesn't use network-cost. Does the flutter-webrtc support it?


So what's exactly your problem right now?
