### ISSUE TITLE
Unified plan tracks not received if  added both audio and video tracks 

### ISSUE THREAD

**Issue by manoj-thamizhan** [aiortc/aiortc#868]
Hi , I'm actually implementing sfu for video conferencing using aiortc ,

The issue is when multiple video and multiple audio tracks are added to peerconnection the receiver don't receive any media 
but it works absolutely fine with either multiple video or multiple audio but not with both

```
    def append_tracks(self):
        for client in clients: # clients are set of objects that contains video tracks and peer connection
            if client.video_track == None: # May be current user most of the times
                self.pc.addTransceiver(trackOrKind="video",direction="recvonly")

            else :
                self.pc.addTransceiver(trackOrKind="video",direction="sendonly")
                tr = relay.subscribe(client.video_track,buffered=False)

                self.pc.addTrack(tr)
            

            if client.audio_track == None:
                self.pc.addTransceiver(trackOrKind="audio",direction="recvonly")

            else:
                self.pc.addTransceiver(trackOrKind="audio",direction="sendonly")
                ar = relay.subscribe(client.audio_track,buffered=False)
                
                self.pc.addTrack(ar)
```
           when commented one section audio or video it works perfectly fine

**Comment by learncodingforweb** [comment]
Can you help me, how to transmit single audio from mic to webrtc connection. i am unable find any resource, which will help me.

**Comment by manoj-thamizhan** [comment]
@learncodingforweb  Yeah for sure but I think it is inappropriate to use issues section for irrelevant discussions , email me with this email address:
     manojleema12345@gmail.com
