### ISSUE TITLE
unable to play audio on speaker received from webrtc

### ISSUE THREAD

**Issue by learncodingforweb** [aiortc/aiortc#888]
Hi, 
   I am able successfully receive audio track and able to record audio into .wav file. But unable to play it on speaker. I have following code snippet

audio recorder is working fine
```
self.player = AudioPlayerTrack()

@pc.on("track")
async def on_track(track):
     if track.kind == "audio":
         print("audio play request recieved", dir(track))
         t = time.time()
         self.recorder = MediaRecorder(f'audio_{t}.wav')
         self.recorder.addTrack(track)
         await self.recorder.start()
         self.player.track=track
         print("end")
                
         @track.on("ended")
         async def on_ended():
             print("audio request ended")
```

audio player is declared as
```
class AudioPlayerTrack():
    def __init__(self):
        super().__init__()
        self.track = None
        self.audio = pyaudio.PyAudio()
        self.stream = self.audio.open(format=pyaudio.paInt16,
                            channels=1,
                            rate=44100,
                            output=True,
                            frames_per_buffer=4096)

    async def play(self):
        try:
            audio_frames = await self.track.recv()
            if audio_frames:
                    for frame in audio_frames:
                        # Convert audio frame to bytes
                        audio_bytes = frame.to_ndarray().tobytes()

                        # Write audio data to the PyAudio stream
                        self.stream.write(audio_bytes)
        except Exception as e:
            print(e)
    
    def stop(self):
        self.stream.stop_stream()
        self.stream.close()
        self.audio.close()
```
**I am not able to play sound on speaker. Can anyone help me how to do?**

**Comment by manoj-thamizhan** [comment]
Hi , I understand your problem 
`        relay = MediaRelay()
         self.recorder.addTrack(relay.subscribe(track))
         await self.recorder.start()
         self.player.track=relay.subscribe(track)`
         
When track is added to a sink like recorder  or player it empties the frame hence no frame is received to other one attached to the track , using mediarelay solves this problem ,

You can import it in MediaRelay from aiortc.contrib.media

**Comment by learncodingforweb** [comment]
Even After i comment out recording functionality, still i am not able to play it on speaker? Please can you provide me snippet for audio track play on speaker

**Comment by manoj-thamizhan** [comment]
While true the try block in play function

**Comment by learncodingforweb** [comment]
```
class AudioPlayerTrack():
    def __init__(self):
        super().__init__()
        self.track = None
        self.audio = pyaudio.PyAudio()
        self.stream = self.audio.open(format=pyaudio.paInt16,
                            channels=1,
                            rate=44100,
                            output=True,
                            frames_per_buffer=4096)

    async def play(self):
        try:
            while True:
                audio_frames = await self.track.recv()
                print(len(audio_frames))
                if audio_frames:
                    for frame in audio_frames:
                        # Convert audio frame to bytes
                        audio_bytes = frame.to_ndarray().tobytes()

                        # Write audio data to the PyAudio stream
                        self.stream.write(audio_bytes)
                else:
                    audio_bytes = b''  # Initialize audio_bytes with an empty value
        except Exception as e:
            print(e)
    
    def stop(self):
        try:
            self.stream.stop_stream()
        except:
            pass
        try:
            self.stream.close()
        except:
            pass
        try:
            self.audio.terminate()
        except:
            pass
```

**object of type 'av.audio.frame.AudioFrame' has no len()**

Please can you provide me code snippet for audio play on speaker

**Comment by manoj-thamizhan** [comment]
Just remove the **for loop** inside, because recv function only returns a frame not the list of frames

**Comment by learncodingforweb** [comment]
I unable to understand, what is solution? Please can you provide concise solution?

**Comment by manoj-thamizhan** [comment]
`class AudioPlayerTrack():
    def __init__(self):
        super().__init__()
        self.track = None
        self.audio = pyaudio.PyAudio()
        self.stream = self.audio.open(format=pyaudio.paInt16,
                            channels=1,
                            rate=44100,
                            output=True,
                            frames_per_buffer=4096)

    async def play(self):
        try:
            while True:
                audio_frames = await self.track.recv()
                print(len(audio_frames))
                if audio_frames:
                    
                    # Convert audio frame to bytes
                    audio_bytes = frame.to_ndarray().tobytes()

                    # Write audio data to the PyAudio stream
                    self.stream.write(audio_bytes)
                else:
                    audio_bytes = b''  # Initialize audio_bytes with an empty value
        except Exception as e:
            print(e)
    
    def stop(self):
        try:
            self.stream.stop_stream()
        except:
            pass
        try:
            self.stream.close()
        except:
            pass
        try:
            self.audio.terminate()
        except:
            pass`
            
try this code now

**Comment by learncodingforweb** [comment]
not working, frame is undefined here, after i change it into ``audio_bytes = audio_frames.to_ndarray().tobytes()``
**[Errno -9988] Stream closed**

**Comment by manoj-thamizhan** [comment]
can you attach screenshots

**Comment by manoj-thamizhan** [comment]
try changing framebuffer to 1024

**Comment by andreaswatch** [comment]
@learncodingforweb, looks like we are on the same page...Yesterday I got the mic to work, today the speaker :)
In my case, most of your class worked okay. The problem for me was that I have a audio and a video track. I moved track to an argument of play and it started to work.
Hope this helps.

`class AudioPlayerTrack():
    kind = "audio"

    def __init__(self, audio):
        super().__init__()
        self.track = None
        self.audio = pyaudio.PyAudio()
        self.INDEX        = 0
        device_info       = self.audio.get_device_info_by_index(self.INDEX)
        print(device_info['name'])
        self.kind         = "audio"
        self.RATE         = int(device_info['defaultSampleRate']) #44100
        self.AUDIO_PTIME  = 0.020                                    # 20ms audio packetization
        self.SAMPLES      = int(self.AUDIO_PTIME * self.RATE)
        self.FORMAT       = pyaudio.paInt32
        self.CHANNELS     = int(device_info['maxOutputChannels']) #2
        self.CHUNK        = int(self.RATE*self.AUDIO_PTIME)
        self.FORMATAF     = 's32_le'   #'s32'                           # s32_le
        self.LAYOUT       = 'stereo'
        self.sampleCount  = 0

        self.stream       = self.audio.open(format=self.FORMAT, 
                                            channels=self.CHANNELS,
                                            rate=self.RATE,
                                            output=True, 
                                            input_device_index=self.INDEX,
                                            frames_per_buffer=self.CHUNK)

    async def play(self, track):
        try:
            while True:
                frame = await track.recv()
                if frame:
                    data = frame.to_ndarray()
                    data = data.astype('int32') << 16
                    self.stream.write(data.tobytes())
        except Exception as e:
            print(f"Error while receiving frames: {e}")

    def stop(self):
        try:
            self.stream.stop_stream()
        except:
            pass
        try:
            self.stream.close()
        except:
            pass
        try:
            self.audio.terminate()
        except:
            pass
`

in def offer:
`    speaker = AudioPlayerTrack(audio)

    @pc.on("track")
    async def on_track(track):
        if track.kind == "audio":
            await speaker.play(track)
            print("end")
                    
            @track.on("ended")
            async def on_ended():
                stop_script(None, None) #stops the mic
        else:
            print("got a track of kind: " + str(track.kind))`

**Comment by learncodingforweb** [comment]
I am getting
```
ALSA lib pcm.c:8568:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8568:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8568:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8568:(snd_pcm_recover) underrun occurred
```
**after that webrtc get disconnected**

Even i tried using ``self.stream.write(data.tobytes(), exception_on_underflow=False)``

if i disable audio play on speaker, then webrtc working fine, without any disconnect problem. Can you help me, how to avoid this issue?

**Comment by andreaswatch** [comment]
Not sure about the reason for the underrun.
Obviously, I am not an expert and in python/audio/webrtc and I am not sure if I can help any further.
However, I would check the device `self.INDEX` and the device settings. Also not sure if the conversion in def play(..) is okay for you're environment.
I've uploaded my project to https://github.com/andreaswatch/pyInterkom, you can test if the full package works for you. As I am still learning, I am interested in your findings.

**Comment by yottachi** [comment]
> 

MediaRecorder isnt really working for me, options like these arent sent `recorder = MediaRecorder('pulse', format='alsa',options={'sample_rate': '44000', 'thread_queue_size':'1024','buffer_size':'4096'})`

So i tried to implement something similar to yours but im stuck gettting "underrun occurred" same as you, have you got any solutions yet?

**Comment by learncodingforweb** [comment]
@andreaswatch , Please check bug reported
