### ISSUE TITLE
Generated offer contains multiple different `ice-ufrag` records

### ISSUE THREAD

**Issue by magniff** [aiortc/aiortc#910]
## Setup
- aiortc: `1.5.0`
- python: `3.11.2`

## Code:
```pythoh3
media_player = MediaPlayer("./assets/video.mp4")
connection = aiortc.RTCPeerConnection()
connection.addTrack(media_player.video)
connection.createDataChannel("some_channel")
offer = await connection.createOffer()
```

## Expected
Generated `offer` contains multiple identical `ice-ufrag` records.

## Found
Generated `offer` contains multiple different `ice-ufrag` records.

**Comment by mglettig** [comment]
Interesting point. 👍 I'm also stumbling across this as I try to send an aiortc offer to a libdatachannel client. This currently fails. I noticed that aiortc is adding ice-ufrags per media-level and not on the session-level. However I found that according to RFC8839 what aiortc does should be valid:
`The "ice-pwd" and "ice-ufrag" attributes can appear at either the session-level or media-level.`

**Comment by jlaine** [comment]
@mglettig Yes it's valid behaviour :)
