### ISSUE TITLE
`audioop` deprecated and slated for removal in Python 3.13

### ISSUE THREAD

**Issue by ekalosak** [aiortc/aiortc#917]
It's a warning provided in the code, that `audioop` is going to be EOL'd as a stdlib: https://peps.python.org/pep-0594/#audioop

**Comment by jlaine** [comment]
This is a valid point and it's quite sad `audioop` is being dropped. One way forward might be to leverage `PyAV` even for these simple codecs.

**Comment by jlaine** [comment]
Work in progress PR #1075

**Comment by jlaine** [comment]
Fixed in #1075
