### ISSUE TITLE
Stream video or audio without the frontend client having to stream their devices

### ISSUE THREAD

**Issue by JesusZerpa** [aiortc/aiortc#924]
Hello everyone, I am currently working on a project where I need to stream video via webrtc, I already provided the iortc library in your example https://github.com/jlaine/aiortc/tree/master/examples/server and I think it's great, it's close to what I need, only as far as I can try for the server to send the signal, the track must first be sent from the frontend so that it can then be transformed on the server by python, in my case I don't want to work With the browser's camera or microphone, I just want to send the video signal from the server to the frontend, but I can't find how to set up the logic to do it, if you could guide me I would appreciate your help.

**Comment by alaa-i** [comment]
Did you check the webcam.py example ?

**Comment by JesusZerpa** [comment]
Thank you, I already saw the example that you tell me and it works as I want. I just have some doubts, trying to compare a bit the way the offer method has been coded in both examples, I am adapting the code that I had at the beginning based on the server example now with the webcam example and although I see things logically the same I don't see that the first one is returning the responses as the webcam example does, as I understand it the track is sent to the frontend in the pc.addTrack method but I don't understand why it can do it in one example and not in the other. Here I share the codes to see if they manage to see something that I don't.

my code:
```

async def offer(request):
    print("NEGOCIANDO")
    params = await request.json()

    offer = RTCSessionDescription(sdp=params["sdp"], type=params["type"])

    pc = RTCPeerConnection()

    pcs.add(pc)
    """
    @pc.on("datachannel")
    def on_datachannel(channel):
  
        @channel.on("message")
        def on_message(message):
            if isinstance(message, str) and message.startswith("ping"):
                channel.send("pong" + message[4:])
    """
    @pc.on("connectionstatechange")
    async def on_connectionstatechange():
        #log_info("Connection state is %s", pc.connectionState)
        print("Connection state is %s", pc.connectionState)
        if pc.connectionState == "failed":
            await pc.close()
            pcs.discard(pc)
   
    # open media source
    audio, video = create_local_tracks(
    )

    pc.addTrack(video)
    await pc.setRemoteDescription(offer)

    # send answer
    answer = await pc.createAnswer()
    await pc.setLocalDescription(answer)
    
  
    return web.Response(
        content_type="application/json",
        text=json.dumps(
            {"sdp": pc.localDescription.sdp, "type": pc.localDescription.type}
        ),
    )

```
webcam example code:

```
async def offer(request):
    params = await request.json()
    offer = RTCSessionDescription(sdp=params["sdp"], type=params["type"])

    pc = RTCPeerConnection()
    pcs.add(pc)

    @pc.on("connectionstatechange")
    async def on_connectionstatechange():
        print("Connection state is %s" % pc.connectionState)
        if pc.connectionState == "failed":
            await pc.close()
            pcs.discard(pc)

    # open media source
    audio, video = create_local_tracks(
        args.play_from, decode=not args.play_without_decoding
    )

    if audio:
        audio_sender = pc.addTrack(audio)
        if args.audio_codec:
            force_codec(pc, audio_sender, args.audio_codec)
        elif args.play_without_decoding:
            raise Exception("You must specify the audio codec using --audio-codec")

    if video:
        video_sender = pc.addTrack(video)
        """
        if args.video_codec:
            force_codec(pc, video_sender, args.video_codec)
        elif args.play_without_decoding:
            raise Exception("You must specify the video codec using --video-codec")
        """

    await pc.setRemoteDescription(offer)

    answer = await pc.createAnswer()
    await pc.setLocalDescription(answer)

    return web.Response(
        content_type="application/json",
        text=json.dumps(
            {"sdp": pc.localDescription.sdp, "type": pc.localDescription.type}
        ),
    )
```

From the webcam example I have been commenting on some things to try to identify the functional differences between webcam.py and my code, but still it works on webcam and on mine it doesn't
