### ISSUE TITLE
Memory Handling in aiortc

### ISSUE THREAD

**Issue by david-goldb** [aiortc/aiortc#925]
Hello,

Our system uses aiortc to relay audio and video tracks to other peers. We have a "media provider" peer, which is a viewer peer. The master peer recognizes it and then takes its media tracks and relays them (using the `MediaRelay` object) to all other peers connected to the session. We also use `MediaBlackhole` to discard this media when no other peer is there to consume it.

When a certain viewer peer connects via WebRTC to the master peer, the RAM usage ramps up, but when the peer disconnects from the session, the RAM is not released. We discard the object of the peer connection and other references to it, yet the RAM always increases.

Any ideas?
Thank you!

**Comment by david-goldb** [comment]
@jlaine, in which object does the RAM accumulate when a peer connects, and from where is it supposed to be released?
Thanks.

**Comment by alaa-i** [comment]
I am facing the same issue here. It would be very helpful if someone has an idea about this problem

**Comment by alaa-i** [comment]
@david-goldb any news ?

**Comment by lgrahl** [comment]
I would suggest to investigate it with a memory profiler.

**Comment by david-goldb** [comment]
I was hoping to get an answer from @jlaine to narrow down my possibilities and perhaps resolve it without a memory profiler investigation. Anyway, over the next few days, I'll try a few memory profilers.

**Comment by alaa-i** [comment]
I will also be working on it. I will report any new findings.

**Comment by david-goldb** [comment]
Thank you @alaa-i and @lgrahl.

By the way, @lgrahl, Do you have any recommendations for a suitable profiler in this case? 

I've heard that [memray](https://github.com/bloomberg/memray) might do the work.

**Comment by david-goldb** [comment]
@alaa-i, any updates?

**Comment by issa-ai** [comment]
I used memray to investigate the issue, it shows that the memory usage is caused by new threads.
from memray: (run at /usr/lib/python3.10/threading.py)

Each time the MediaPlayer class is called it creates a new thread and for some reason resources are not properly released at stop(). I will check this class and see what might be the problem.

**Comment by david-goldb** [comment]
I've noticed an increase in memory usage by the encoders. Every time a peer connects, there's a spike in memory that is never released:
![image](https://github.com/aiortc/aiortc/assets/53686829/75340ab0-8c48-4d77-aff4-869f0cdadd58)

**Comment by david-goldb** [comment]
I wanted to update that I addressed the issue I had. The problem was with the encoders that were never deleted. For every peer connection, a new encoder is created ([here](https://github.com/aiortc/aiortc/blob/9f14474c0953b90139c8697a216e4c2cd8ee5504/src/aiortc/rtcrtpsender.py#L274)), but it's never removed. 

After I explicitly deleted the encoder that belongs to a closed connection, the memory graph decreased: 
![Screenshot 2023-09-20 at 15 28 30](https://github.com/aiortc/aiortc/assets/53686829/0d0ba254-b89c-4f95-b1bb-0a53fdab6cdf)

**Comment by huynhkimvi1410** [comment]
> I wanted to update that I addressed the issue I had. The problem was with the encoders that were never deleted. For every peer connection, a new encoder is created ([here](https://github.com/aiortc/aiortc/blob/9f14474c0953b90139c8697a216e4c2cd8ee5504/src/aiortc/rtcrtpsender.py#L274)), but it's never removed.
> 
> After I explicitly deleted the encoder that belongs to a closed connection, the memory graph decreased: ![Screenshot 2023-09-20 at 15 28 30](https://user-images.githubusercontent.com/53686829/269282158-0d0ba254-b89c-4f95-b1bb-0a53fdab6cdf.png)

what you mean ? we comment that line and continue the code !

**Comment by jlaine** [comment]
I would expect the decoder to get cleaned up as soon as the RTCRtpSender gets cleaned up. Do you hold references to the RTCRtpPeerConnection in your code? Is this observable in any of the unmodified examples?

We might be able to alleviate the problem by dropping the reference to the encoder as soon as it is stopped.

**Comment by david-goldb** [comment]
Hi, 
@alaa-i As a said, I just explicitly deleted the sender's encoder after disconnection:

`      for sender in self._peer_connection.getSenders():
            if sender._RTCRtpSender__encoder:
                try:
                    self._logger.info(f"Deleting encoder for {sender.kind} RTP sender ...")
                    del sender._RTCRtpSender__encoder
                    self._logger.info(f"Encoder for {sender.kind} RTP sender has been deleted.")
                ...
`
And it solved the memory jumps.

@jlaine Also when I removed the reference to the peer connection the problem persisted for some reason (Maybe due to a reference cycle or something). Anyway, I see now that you've added a fix to the source code. Thanks.
