### ISSUE TITLE
[URGENT HELP] I can't get a client working in Python

### ISSUE THREAD

**Issue by firish** [aiortc/aiortc#928]
I want to send an image through a server and receive it in a Python client. I only see examples of .js clients. Can someone please give me an example of a working Python client file?

**Comment by lgrahl** [comment]
https://github.com/aiortc/aiortc/tree/main/examples/videostream-cli

**Comment by stevin-hong** [comment]
> I want to send an image through a server and receive it in a Python client. I only see examples of .js clients. Can someone please give me an example of a working Python client file?

Has this issue been resolved? I encountered the same problem where the client written in Python cannot connect successfully, but it works with JavaScript. Could you please post the complete code of the Python client? Thank you very much!
