### ISSUE TITLE
Can already encoded audio/video be sent (without having to encode it)?

### ISSUE THREAD

**Issue by ibc** [aiortc/aiortc#939]
Sorry for asking here (docs say it's not that bad if purely related to aiortc). This could be a feature request as well.

Imagine I have an already VP8 encoded video in a file. Is it possible to create a `MediaPlayer` with it so later, when passing its `MediaStreamTrack` to `pc.addTrack()`, the media encoding is bypassed? The idea here is to avoid encoding, which is CPU intensive and makes it hard to use aiortc for massive testing purposes.

**Comment by rprata** [comment]
@ibc , please, check if [this](https://github.com/aiortc/aiortc/blob/main/examples/webcam/README.rst#pre-encoded-vp8-video) help you.

You can run aiortc only make demux (without transcoding). It will reduce CPU processing

**Comment by ibc** [comment]
Thanks a lot, @rprata. I'm closing this feature request since, indeed, it's already possible by passing proper command line options.

**Comment by ibc** [comment]
After reading all the docs and internals and tracking the "decode" option in `MediaPlayers` class (which BTW is not documented at all), it's still not clear whether encoding will happens or not. 

- So I create a `MediaPlayer` by reading a local `video.ts` file with `decode=False`). So I assume that, for it to work, `video.ts` must be already encoded in the expected codec (VP8 or H264).
- Then I get the video `MediaStreamTrack` of the `MediaPlayer` and pass it `pc.addTransceiver(track)`.
- The question is: will the RTP engine **encode** the given `track` into the SDP negotiated codec or not?
