### ISSUE TITLE
profile-level-id : aiortc.exceptions.OperationError: Failed to set remote video description send parameters

### ISSUE THREAD

**Issue by FabienDanieau** [aiortc/aiortc#944]
Hi,

I am wondering what kind of profile-level-id for the H264 codec are accepted by a aiortc webrtc client.
In *aiortc/codecs/__init__.py* , there is 

```
    add_video_codec("video/VP8")
    for profile_level_id in ("42001f", "42e01f"):
        add_video_codec(
            "video/H264",
            {
                "level-asymmetry-allowed": "1",
                "packetization-mode": "1",
                "profile-level-id": profile_level_id,
            },
        )
```
If the other peer sends a H264 stream with a BASELINE profile it is fine, but if I use a MAIN profile there is the following error

```
  File ".../src/example/videostream-cli/cli.py", line 111, in run
    await pc.setRemoteDescription(obj)
  File "/python3.10/site-packages/aiortc/rtcpeerconnection.py", line 854, in setRemoteDescription
    raise OperationError(
aiortc.exceptions.OperationError: Failed to set remote video description send parameters
```

I can fix this by adding the profile "4d0033" to the above list. 
Why only two profiles are provided? Does it make sens to add more?

Thanks

**Comment by jlaine** [comment]
Simply adding more profiles won't be enough, this means also tuning the H.264 codec parameters to match the profile

**Comment by FabienDanieau** [comment]
Thanks for the answer. Ok I understand that this info needs to be propagated to the encoder. `create_encoder_context` I suppose. 
What about the decoder? Does it have to be specified somewhere in `class H264Decoder(Decoder):` ?

I am a bit confused since I see many profiles in sdp.py, but I am not quite sure how they are used.
