### ISSUE TITLE
pylibsrtp.Error: couldn't initialize

### ISSUE THREAD

**Issue by bernardolansing** [aiortc/aiortc#967]
I am trying to run a unidirectional video-only transmission from a Raspberry PI (Zero 2 W) to an Android app. This has worked before, but now I am receiving this error:

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-17' coro=<RTCPeerConnection.__connect() done, defined at /home/proto003/.pyenv/versions/3.9.16/lib/python3.9/site-packages/aiortc/rtcpeerconnection.py:1000> exception=Error("couldn't initialize")>
Traceback (most recent call last):
  File "/home/proto003/.pyenv/versions/3.9.16/lib/python3.9/site-packages/aiortc/rtcpeerconnection.py", line 1010, in __connect
    await dtlsTransport.start(self.__remoteDtls[transceiver])
  File "/home/proto003/.pyenv/versions/3.9.16/lib/python3.9/site-packages/aiortc/rtcdtlstransport.py", line 413, in start
    self._rx_srtp = Session(rx_policy)
  File "/home/proto003/.pyenv/versions/3.9.16/lib/python3.9/site-packages/pylibsrtp/__init__.py", line 202, in __init__
    _srtp_assert(lib.srtp_create(srtp, _policy))
  File "/home/proto003/.pyenv/versions/3.9.16/lib/python3.9/site-packages/pylibsrtp/__init__.py", line 55, in _srtp_assert
    raise Error(ERRORS[rc])
pylibsrtp.Error: couldn't initialize
```

This error is actually thrown from the [webcam](https://github.com/aiortc/aiortc/tree/main/examples/webcam) example, so it couldn't be an error in my code. Everything works fine when I'm running the same code on my Linux PC. Since the same code used to work properly before, I believe that this is being caused by a system update or something like that. I don't believe that this is a camera hardware/software issue since I can record camera frames even with the `contrib` libraries.

Some information on the system:
Raspbian OS Bullseye
CPython 3.9.16
aiortc 1.5.0 (pre-built)
System date and time are correct

This issue is probably not related with the library itself. Even though, I'd appreciate if someone more experienced could share any suggestion.

**Comment by jlaine** [comment]
Wrong repo, can you please post a minimal reproduction to https://github.com/aiortc/pylibsrtp repo, including how you built `pylibsrtp`?

**Comment by bernardolansing** [comment]
[Posted](https://github.com/aiortc/pylibsrtp/issues/29).
