### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fredyshox** [aiortc/aiortc#988]
It would be really nice if a new release, for example, 1.5.1, was published with the fix for header extension IDs (https://github.com/aiortc/aiortc/commit/6a2a5e97a1274c6f1847bd0616d0c9c6d4fe4bbf) which is already on main.

**Comment by jlaine** [comment]
I'm working on it, I'd also like to provide wheels for Python 3.12.

**Comment by jlaine** [comment]
Done, aiortc 1.6.0 is available on PyPI!
