### ISSUE TITLE
Readme command missing role on Additional options for running videostream-cli

### ISSUE THREAD

**Issue by SGA-pranamika-pandey** [aiortc/aiortc#990]
In the "Additional options" section on the Readme for videostream-cli, the command for playing a media file doesn't include "offer" role for the offer instance of "cli.py":

`$ python cli.py --play-from video.mp4`

which gives following error:

> -usage: cli.py [-h] [--play-from PLAY_FROM] [--record-to RECORD_TO] [--verbose]
              [--signaling {copy-and-paste,tcp-socket,unix-socket}] [--signaling-host SIGNALING_HOST]
              [--signaling-port SIGNALING_PORT] [--signaling-path SIGNALING_PATH]
              {offer,answer}
cli.py: error: the following arguments are required: role

Verified below: 
* Check whether there is already an existing issue for the same topic.
* Ensure you are actually reporting an issue related to ``aiortc``. The goal
  of the issue tracker is not to provide general guidance about WebRTC or free
  debugging of your code.
* Clearly state whether the issue you are reporting can be reproduced with one
  of the examples provided with ``aiortc`` *without any changes*.

**Comment by jlaine** [comment]
Quite right, thanks for noticing!
